### ISSUE TITLE
add Windows Power Plan as action

### ISSUE THREAD

**Issue by rickygjun** [BartoszCichecki/LenovoLegionToolkit#1001]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

I'm using all custom power mode preset, hence would like to switch to the associated Windows Power Plan in actions as well.

The Power Plans in settings can only allow a specific power plan for custom mode, but cannot support switching between presets.

Use Case:
Switching Custom Power Mode preset to "Game" Preset, activate "Legion Performance Mode" Power Plan
Switching Custom Power Mode preset to "Quiet" Preset, activate "Legion Quiet Mode" Power Plan

### How would you like the problem to be solved?

Add Windows Power Plan selection as action

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment]
Power plans are linked to power modes and that is not going to change.
