### ISSUE TITLE
Actions improvement: import, export, reorder

### ISSUE THREAD

**Issue by rickygjun** [BartoszCichecki/LenovoLegionToolkit#1003]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

I now have quite a few actions been defined, due to the powerful features LLT provided.

It will be a lot of effort if I re-install LLT.

Hence import, export become my next question.

In addition, been able to re-order those actions would also be handy.

### How would you like the problem to be solved?

Support import, export, re-order in actions

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment]
Settings are stored in `%LOCALAPPDATA%\LenovoLegionToolkit` you can back them up. Reordering can be done using right click menu.
