### ISSUE TITLE
Battery info problem

### ISSUE THREAD

**Issue by Autobiography59** [BartoszCichecki/LenovoLegionToolkit#1006]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2, OS build 22621.2428

### Device

Legion pro 7 16IRX8H

### BIOS version

KWCN38WW

### What's wrong?

I don't see these values:
1) battery discharge
2) battery temp
3) battery mode(trey)
4) discharge rate(trey)
5)on battery since

### How to reproduce the bug?

1) trey
2) battery menu

### What is the behavior that you expected?

Tweaked cpu in the trottlestop.

### Logs

I don't think I can reproduce the problem, I don't know what it came from.

**Comment by BartoszCichecki** [comment]
Please create issues when you have all relevant information.
