### ISSUE TITLE
Power mode visible in sys tray, but not available (neither visible nor configurable)

### ISSUE THREAD

**Issue by bcutter** [BartoszCichecki/LenovoLegionToolkit#1008]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Win 11 22H2 Build 22621.2428

### Device

Yoga Pro 9 14IRP8 - Type 83BU

### BIOS version

MBCN26WW (2023-07-25)

### What's wrong?

This software works just PERFECT. Totally happy. I only discovered, even in sys tray this is shown...
![grafik](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/13799156/0387190f-ae12-4e33-97bc-bd7f00d1efc8)
...

it does not give the actual power mode. It also can not be set, here's the full power section:
![grafik](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/13799156/08478811-4884-4a25-acdf-bd0e4556ea08)

This is not a Legion device which I am aware of of course. Does this mean (as Vantage allows to control it using the battery widget:
![grafik](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/13799156/7fb34b71-4d44-4c97-ae3d-f9718cd3aa5c)
) it would have to be "reverse engineered" first to make it consistently available in LLT?

This is **not an issue asking for compatibility** as I'm very sure the maintainer has neither time nor device to do so. Just because the sys tray pop-up showing up the **power mode** while at the same time it can't be read or configured at the moment seems to me inconsistent why I deciced to flag this as _bug_.

### How to reproduce the bug?

1. Install LLT
2. Check sys tray icon where power mode is shown (empty)
3. Check LLT and discover power mode is not available at all

### What is the behavior that you expected?

- **At best: power mode is fully available (visible and configurable).**
- 2nd best solution: power mode is partly available (visible).
- 3rd best solution: power mode is not visible in sys tray pop-up if the device does not support it currently.

### Logs

[log_2023_10_27_16_03_57.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13191101/log_2023_10_27_16_03_57.txt)

**Comment by BartoszCichecki** [comment]
You are running LLT on an incompatible device.

**Comment by bcutter** [comment]
...and it runs great. Thank you very much sir closing the issue which took me 30 minutes of creating within few seconds. Keep up the good work.

By the way: if all issues are closed that restrictively, there'll probably never step up others to help reverse engineer and contribute to LLT. Just my 2 cents man.
