### ISSUE TITLE
Add windows 11 lighting support

### ISSUE THREAD

**Issue by Lampadina17** [BartoszCichecki/LenovoLegionToolkit#1009]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

22621

### Device

15ARH05H

### Is your feature request related to a problem?

add support for new lighting api https://learn.microsoft.com/en-us/windows-hardware/design/component-guidelines/dynamic-lighting-devices

### How would you like the problem to be solved?

.

### What alternatives have you considered?

.

**Comment by BartoszCichecki** [comment]
Please check existing issues and discussions before creating issues.
