### ISSUE TITLE
[Compatibility Request] Legion Y740-15IR

### ISSUE THREAD

**Issue by sudiir12345** [BartoszCichecki/LenovoLegionToolkit#101]
The new Vantages updates are really bloated and this app seems to serve all my needs. Really appreciate the work. 
My laptop model seems to be unsupported and I am here to request model support. 

The requested Information are:
1. Model: LENOVO LEGION Y740-15IR

2. Hybrid mode works fine. 
Always on USB settings also works fine. 
The refresh rate change works well as I had added custom refresh rate using cru. The app only showed the panels refresh rate by default.
On the miscellaneous tab, Flip to start and overdrive are not part of the feature set of this laptop. Fn and Touchpad lock work as intended.

3. Battery mode seems to work for changing from normal to conservation and vice versa, but I have to power cycle the charger for the setting to take effect. Rapid charge doesn't seem to work (I am not sure if my testing methods were good as the charging time I observed between rapid and normal was negligible).
Power Mode doesn't change the modes. I can confirm this as I can access the debug bios where those options are not changed.
Discrete GPU tab doesn't work properly, Haven't been able to figure out what its doing as task manager shows no apps are running but toolkit is showing 1 app is running.
I haven't got around to testing the power plans, will update once i get around to it.

4. I haven't faced any crashes until now , will update if I encounter any.

**Comment by BartoszCichecki** [comment]
Hey!

Thanks for great description! I will add this model to the list so that you can "just run it". However, Y-models are quite different from the 5 Pro that I am using and I can't properly add support for the device, so unfortunately so options may not work correctly.

**Comment by sudiir12345** [comment]
That's really unfortunate. Thank you for the work you have put into this.
