### ISSUE TITLE
CPU and GPU graphs not shown on certains model included 15ARH05H

### ISSUE THREAD

**Issue by Lampadina17** [BartoszCichecki/LenovoLegionToolkit#1010]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22621

### Device

15ARH05H

### BIOS version

FSCN14WW

### What's wrong?

cpu and gpu graph not appear on this model

### How to reproduce the bug?

just open ltt

### What is the behavior that you expected?

cpu and gpu graphs should be showed on every model

### Logs

none

**Comment by BartoszCichecki** [comment]
Please check existing issues and discussions before creating issues.
