### ISSUE TITLE
CPU at 0.38 GHz after CMOS reset

### ISSUE THREAD

**Issue by FatTonyKS** [BartoszCichecki/LenovoLegionToolkit#1011]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.0 and 2.17.0 BETA 4

### OS

Win 11 Pro 22H2 22621.2428

### Device

Legion Slim 7 16IRH8

### BIOS version

M0CN33WW

### What's wrong?

I had to do a CMOS reset because my keyboard backlight would not turn on (happens from time to time). Since then LTK freezes my CPU clock at 0.38 GHz, regardless of the selected mode. Only when I close LTK and then change the profile again with Fn+Q, the CPU clock becomes dynamic again. This happens after every CMOS reset and only a reinstallation of LTK helps. I tested both the last stable and the latest beta.

### How to reproduce the bug?

1. Do CMOS reset
2. Start LTK
3. Change power mode

### What is the behavior that you expected?

CPU clock not freezing

### Logs

[log_2023_10_29_04_29_00.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13197195/log_2023_10_29_04_29_00.txt)

**Comment by BartoszCichecki** [comment]
LLT doesn't control CPU speed. You need to look somewhere else.

**Comment by FatTonyKS** [comment]
If the error only occurs when LTK is running, and goes away immediately as soon as LTK is closed - then how can it not be related to LTK? And after reinstalling LTK everything works normally again.
