### ISSUE TITLE
power plans error

### ISSUE THREAD

**Issue by Autobiography59** [BartoszCichecki/LenovoLegionToolkit#1012]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 Home 22H2 build 22621.2506

### Device

Legion Pro 7 16IRX8H

### BIOS version

KWCN38WW

### What's wrong?

When entering Settings-Power plans an error is displayed
<img width="309" alt="2023-10-30 23_01_10-Application Error" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/145613827/666accc2-d1a7-4743-bd6c-5494be2fc945">
[error_2023_10_30_17_11_57.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13207917/error_2023_10_30_17_11_57.txt)

### How to reproduce the bug?

1. Go to "Settings"
2. Click on "power plans"

### What is the behavior that you expected?

1) Deleted edge browser
2) imported custom battery power plan from Legion Series discord
<img width="526" alt="2023-10-30 23_08_35-#knowledge-base _ Legion Series - Discord" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/145613827/b16795ed-caee-46f5-b988-5996927bf5f3">

### Logs

[log_2023_10_30_17_11_35.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13207915/log_2023_10_30_17_11_35.txt)

**Comment by BartoszCichecki** [comment]
I patched the error so it doesn't crash LLT, however the root issue can't be fixed in LLT as it's a Windows error - for some reason it fails when reading one of the power plan names.

Also, you are missing some drivers, so please go through the README on the main project page and read through it.
