### ISSUE TITLE
 single display brightness

### ISSUE THREAD

**Issue by jojo2massol** [BartoszCichecki/LenovoLegionToolkit#1016]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2 build 22621.2506

### Device

Legion 5 15ACH6A

### BIOS version

G9CN33WW

### What's wrong?

Single display brightness feature isn't working. While switching to quiet mode, brightness reduces.

It seems like this issue does not appear while switching through the interface, but only with `Fn` + `Q`.

### How to reproduce the bug?

1. In Lenovo Legion Toolkit settings, switch Single Display Brightness on.
2. With `Fn` + `Q`, switch to quiet mode
3. Brightness is reduced.

### What is the behavior that you expected?

No brightness change

### Logs

[log_2023_11_01_14_50_58.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13228336/log_2023_11_01_14_50_58.txt)

**Comment by BartoszCichecki** [comment]
Hey, I can't reproduce the issue. I can also see from your log that brightness level was applied to all 7 power plans that you have. That might be an issue with some setting in Windows (in power plans?) to reduce brightness when power saving plans. I can also see that you have Vantage running in the background so I am not even sure if this works as expected.

**Comment by jojo2massol** [comment]
I finally found the way to reproduce : 
When Windows energy saving is enabled, power plans are working different. LLT custom profiles are not any more applied (default Lenovo profiles are applied), and brightness reduces systematically, even switching from quiet to balanced.
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/54369031/1f833ac5-769e-4e5b-96b0-015b29168cf6)

**Comment by BartoszCichecki** [comment]
Good find! I did some improvements to this feature in afae68e1ec257732b3d017cab3f18973c99b7ab3, so that brightness is also applied to "overlays", however power saver isn't an overlay and Microsoft didn't expose an API for it, so it cannot be properly fixed unfortunately :(

**Comment by jojo2massol** [comment]
The issue is that I have a single brighness when LLT is off ...
When LLt is on, the brightness is quite ... erratic

https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/54369031/e68c1778-29fb-470b-9c6f-cdc670a2ee70

BTW I'm using version 2.21.0 BETA 2

**Comment by jojo2massol** [comment]
Hi ! 
Is this issue still unplanned, since the issue only exists when LLT is running? Or maybe I didn't quite understand what you meant?  
I see a Windows API for power saver : <https://learn.microsoft.com/en-us/uwp/api/windows.system.power.powermanager.energysaverstatus?view=winrt-22621>
I don't know how your code really works, but I presume it changes the brightness when I'm changing mode (that's the only explanation I have to explain the fact that the brightness changes when I change the power mode, only when the application is running.)
Isn't it possible to prevent these brightness changes when the energy saver is on ?

**Comment by BartoszCichecki** [comment]
Yes, it is still not planned, because there isn't anything I can do.

The "Single brightness" option synchronizes brightness across Power Plans. The battery saver and the new "Power Mode" option in Windows settings app does not use power plans, but in fact are "power plan overlays" that are applied on top of a power plan. 

Microsoft is phasing out the old-school power plans, so there are basically two ways to go: use only stock Balanced power plan and the new settings like "Power Mode" and Battery saver - in which case you don't even need the "Single brightness" because there is only one power plan. The other option is to use power plans and refrain from using the new options like Battery saver and Power Modes in Settings app.
