### ISSUE TITLE
LenovoLegionToolkit sometimes keeps the GPU active

### ISSUE THREAD

**Issue by Xerionius** [BartoszCichecki/LenovoLegionToolkit#102]
**Describe the bug**
LenovoLegionToolkit sometimes keeps the GPU active. Pressing "Deactivate" or restarting LenovoLegionToolkit fixes this temporarily.

**To Reproduce**
1. Open LenovoLegionToolkit
2. Use your Laptop while LenovoLegionToolkit is open in the background

**Expected behavior**
LenovoLegionToolkit should not keep the GPU active when there are no other programs using the GPU.

**Screenshots**
![Screenshot 2022-05-18 144850](https://user-images.githubusercontent.com/11562061/169044666-9f311486-0c7f-47d3-8253-da21525b5c9f.png)

**Environment (please complete the following information):**
 - LenovoLegionToolkit Version: 1.7.1
 - OS: Windows 11 21H2 build 22000.675
 - Laptop model: Legion 5 Pro 16ACH6H
 - .NET version: 5.0.3.29722
 - Do you have Vantage installed? Yes

**Logs**

**Comment by BartoszCichecki** [comment]
Please check if you have this problem with the 2.0 BETA :)
