### ISSUE TITLE
The warranty information isn't displayed

### ISSUE THREAD

**Issue by Glimspe** [BartoszCichecki/LenovoLegionToolkit#1020]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 10  22H2

### Device

Legion 5 ACH6A

### BIOS version

G(CN33WW

### What's wrong?

As you see,the  warrranty time didn't displayed.
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/100057577/8ec3fecf-2110-4f91-a221-73dc09f61473)

### How to reproduce the bug?

click my device information

### What is the behavior that you expected?

Make it work correctly.

### Logs

[log_2023_11_07_03_20_42.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13275358/log_2023_11_07_03_20_42.txt)

**Comment by BartoszCichecki** [comment]
I need a serial number to be able to reproduce this issue.

**Comment by Glimspe** [comment]
[cid:f6d84482-e239-4cf9-9324-03b35f44008e]
________________________________
发件人: Bartosz Cichecki ***@***.***>
发送时间: 2023年11月8日 4:01
收件人: BartoszCichecki/LenovoLegionToolkit ***@***.***>
抄送: Glimspe ***@***.***>; Author ***@***.***>
主题: Re: [BartoszCichecki/LenovoLegionToolkit] The warranty information isn't displayed (Issue #1020)


I need a serial number to be able to reproduce this issue.

―

**Comment by Glimspe** [comment]
My serial number is PF398L7R,
________________________________
发件人: Glimspe Aurora ***@***.***>
发送时间: 2023年11月8日 10:49
收件人: BartoszCichecki/LenovoLegionToolkit ***@***.***>
主题: 回复: [BartoszCichecki/LenovoLegionToolkit] The warranty information isn't displayed (Issue #1020)

[cid:f6d84482-e239-4cf9-9324-03b35f44008e]
________________________________
发件人: Bartosz Cichecki ***@***.***>
发送时间: 2023年11月8日 4:01
收件人: BartoszCichecki/LenovoLegionToolkit ***@***.***>
抄送: Glimspe ***@***.***>; Author ***@***.***>
主题: Re: [BartoszCichecki/LenovoLegionToolkit] The warranty information isn't displayed (Issue #1020)


I need a serial number to be able to reproduce this issue.

―

**Comment by BartoszCichecki** [comment]
Hey, thanks. I noted the serial # and removed it from here so that it isn't too public.

**Comment by BartoszCichecki** [comment]
@Glimspe from what I can see the API on lenovo.com.cn is not responding, and timing out - that's why warranty information isn't displayed. So either I need another data source that I can use or maybe it's a temporary outage. I can't do much at the moment, if you have another data source I can use, please leave a comment. Otherwise we can only wait for that service to start responding again. Either way I am closing this ticket for now. Feel free to reopen if you know where to get warranty information for CN serial numbers in a different way.

**Comment by BartoszCichecki** [comment]
Oh wait, actually I think I found another way.

**Comment by BartoszCichecki** [comment]
Fixed, will be available in next release.
