### ISSUE TITLE
Issue with Incorrect Display of PL1 Value in Custom Mode Presets

### ISSUE THREAD

**Issue by xxhhlk** [BartoszCichecki/LenovoLegionToolkit#1023]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 10 Pro 22H2 19045.3636

### Device

Legion Y9000P IAH7H

### BIOS version

J2CN54WW

### What's wrong?

I found a bug similar to issue #947, but this time the bug has a smaller impact and appears to only affect PL1 values.

### How to reproduce the bug?

1. Create two custom mode presets, one with the defaults and the other with the maximum offset set to 21 and the PL1 value adjusted to the maximum, then save.
2. When selecting a different preset in the preset modification window, the PL1 value of the preset with the larger offset will incorrectly become 80.
3. If you create another preset with the same offset as the preset with the larger value, and switch between the two, you will see that the PL1 value is displayed correctly.
4. This bug can also be reproduced by other combinations, such as a maximum offset of 100 and the largest PL1 value, an offset of 79 and any PL1 value.

### What is the behavior that you expected?

In the above cases, the PL1 value should be displayed correctly when switching any preset.

### Logs

When trying to reproduce, the software generated one error and two error logs. When trying again, no errors were reported. The logs are attached.
The names of my presets are
- 111
- Cooler
- Limted Power
- Max Fan
- Unlimited Power

[log_LTT_xxhhlk_2023_11_07_13_32_33.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13282614/log_LTT_xxhhlk_2023_11_07_13_32_33.zip)

**Comment by BartoszCichecki** [comment]
Can you upload a video of the bug? I have troubles reproducing it.

**Comment by xxhhlk** [comment]
I did some more testing and found that if I wanted to reproduce the bug, I would also need to change the PL2 value of the default preset.
 [Here's the video](https://drive.google.com/file/d/1a1DReiHr9Mviovw5g1yXJbYH6vo6yYls/view)

**Comment by BartoszCichecki** [comment]
OK, so _works on my machine_, so I don't have a clue why that is happening. Can you try this build?

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13300807/LenovoLegionToolkitSetup.zip)

**Comment by xxhhlk** [comment]
I'm happy to tell you that after testing, this fix successfully resolved the issue. Thanks!
