### ISSUE TITLE
Keyboard Backlight setting showing for an incompatible model

### ISSUE THREAD

**Issue by zwresn453** [BartoszCichecki/LenovoLegionToolkit#1026]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Legion 7 16ACHg6

### BIOS version

Newest (GKCN60WW)

### What's wrong?

The Readme file does not mention support for Per-Key RGB lighting on Gen 6, so I assume that LLT is not compatible with these.

However, LTT's dashboard shows Keyboard Backlight setting. The setting tile responds to user input, but doesn't actually do anything. Also, the tooltip says "change brightness with Fn+Space", which is inaccurate on gen 6.

I am assuming that this is simply a bug in LLT's decision on whether to show the settings tile.

(Note that the setting tile itself is showing, not just in the "Customize Dashboard" menu.

Panel Logo Backlight is working correctly - it shows as an option in Customize but doesn't appear in the actual Dashboard. (please don't remove the ability to see incompatible settings in Customize; it is interesting to know what features other devices have.))

Also note that this problem appeared some time after the Keyboard Backlight feature was added - when it was first added it worked properly.

### How to reproduce the bug?

Only reproduceable on affected models. (ex. 16ACHg6)
1) Go to Dashboard tab
2) Scroll to "Other" section, or wherever the Keyboard Backlight option has been configured to be.

### What is the behavior that you expected?

The Keyboard Backlight option should appear in Customize Dashboard, but should not appear in the actual Dashboard (because incompatible)

### Logs

[log_2023_11_08_03_38_08.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13291847/log_2023_11_08_03_38_08.txt)

**Comment by BartoszCichecki** [comment]
GKCN BIOSes are known to report backlight options that do not exist an a laptop. In fact the Legion 7 gen 6 is the odd one here, because the interface for white keyboard backlight is reported as supported by BIOS, even though it actually uses iCue for keyboard backlight.

I didn't want to introduce complex white/blacklisting logic to LLT for just this model, so my best recommendation is to just remove the control from Dashboard and ignore it. I will update the readme, and thanks for staying vigilant!
