### ISSUE TITLE
No sensors showing up

### ISSUE THREAD

**Issue by ItzPeto** [BartoszCichecki/LenovoLegionToolkit#1031]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 Insider Preview Build 23585

### Device

IdeaPad Gaming 3 15ACH6

### BIOS version

H3CN39WW(V2.09)

### What's wrong?

The sensors that are supposed to show the CPU and GPU utilization, fans, temps, etc. are not showing up at all. I'm not getting any compatibility errors on startup.

### How to reproduce the bug?

1. Open LLT
2. Look at the dashboard

### What is the behavior that you expected?

I was expecting to see my CPU and GPU sensor stats

### Logs

[log_2023_11_10_13_20_04.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13319648/log_2023_11_10_13_20_04.txt)

**Comment by BartoszCichecki** [comment]
If it doesn't show up, then it isn't supported. Gen 6 IdeaPad Gaming is more similar to gen 5 Legion firmware wise, so this would be most likely solved by #881 so I am closing this a duplicate.
