### ISSUE TITLE
dGPU Hardware Disable (read description)

### ISSUE THREAD

**Issue by XyKER1** [BartoszCichecki/LenovoLegionToolkit#1033]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2 Build 22621

### Device

Legion 5i Slim Gen 8 (2023)

### Is your feature request related to a problem?

Lenovo Vantage has the ability to disable the discrete GPU entirely through the BIOS, removing it from task manager and preventing it from drawing power at all. However, there is no option like this in Legion Toolkit.

I know you can temporarily kill the GPU or restart, but even after this, the GPU comes back on intermittently for me. I would be great if you could add in this feature so that the dGPU is completely disabled as described above. If you need more information, like a screenshot or screen recording of how this is different from what Legion Toolkit does, I will be happy to provide it.

### How would you like the problem to be solved?

Add in the ability to permanently disable the dGPU (removing it from task manager and device manager) through the BIOS like Lenovo Vantage has. To be clear, I don't mean this option is in the BIOS menu, just that Vantage uses some method of doing this that can't be achieved simply through Windows - it must be communicating with the BIOS to fully disable the dGPU.

### What alternatives have you considered?

I'm new to Legion laptops, so the only alternative I know of is to use Vantage, but this uses more RAM and CPU, so I would much prefer to use this application.

### Additional information

I don't currently have any screenshots because I did a clean install after opening Lenovo Vantage and seeing how much bloatware was on this laptop. I've also heard Vantage is notoriously difficult to fully remove once installed. However, I can redownload Vantage and provide one if you don't think I've provided enough information.

**Comment by BartoszCichecki** [comment]
There is an option for this: it's called Hybrid Mode and it's been supported since forever. If you don't see it, install necessary drivers that you are obviously missing.

And for the love of god, this option is even visible on the screenshot on the main page. Please don't report issues that aren't issues.

**Comment by XyKER1** [comment]
@BartoszCichecki Sorry for bothering you about this. It turns out Nvidia container is always using tons of CPU in the background. If I right click on the Nvidia icon in the taskbar and click Exit, this immediately stops Nvidia container from using CPU and allows the GPU to be ejected.

The reason I was confused was because Legion Toolkit said the GPU was inactive and the option for "kill apps" was greyed out, making me think nothing was using the GPU, but clearly Nvidia container was. Before I did a clean install, this Nvidia container process wasn't an issue, so the dGPU ejected instantly with Vantage.

Maybe this is something you can implement into Legion Toolkit (to make sure Nvidia container isn't keeping the dGPU from ejecting), as it doesn't seem to recognize this process is using the dGPU? Again, sorry for bothering you with this, but I'm sure you can understand there is no way I could've known that Nvidia Container was what was keeping Legion Toolkit from doing its job!
