### ISSUE TITLE
hotkey for power mode with external keyboard

### ISSUE THREAD

**Issue by xxm101010** [BartoszCichecki/LenovoLegionToolkit#1036]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

last version

### OS

windows11 22h2

### Device

Legion R9000P ARX8

### Is your feature request related to a problem?

cant switch power mode with external keyboard

### How would you like the problem to be solved?

Custom shortcut keys for four power modes plz
Includes custom modes

### What alternatives have you considered?

Actions not support

**Comment by BartoszCichecki** [comment]
As of now, more complex hotkeys are out of scope. If anything changes I will reopen this issue.
