### ISSUE TITLE
An extra panel was shown when putting mouse on the task bar icon

### ISSUE THREAD

**Issue by Ptilopsis01** [BartoszCichecki/LenovoLegionToolkit#1043]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Win11 23H2 22631.2787

### Device

Legion Y9000X IAH7(S7 16IAH7)

### BIOS version

JYCN51WW

### What's wrong?

As I said in the title, there is an extra panel shown when putting your mouse on the icon of ltt in taskbar
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/93318731/94d98f5a-c033-4bf3-a37e-e6484909a585)

### How to reproduce the bug?

Just put your mouse on the taskbar icon

### What is the behavior that you expected?

The ltt panel is the only one shown when I put my mouse on its icon

### Logs

no logs(

### Additional information

I've noticed that for some time, and I think maybe it's a feature of windows which was ignored?

**Comment by BartoszCichecki** [comment]
It's a bug in how recent Windows 10/11 builds handle custom popups. There is no workaround at the moment. Only hope is that MS will fix it in future builds.
