### ISSUE TITLE
Switch wallpapers when switching perfomance mode

### ISSUE THREAD

**Issue by NotUrWang** [BartoszCichecki/LenovoLegionToolkit#1044]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 pro 22h2 build 22621.2283

### Device

Legion Pro 7i Gen 8 (soon)

### Is your feature request related to a problem?

No problems, just a nice feature to have.

### How would you like the problem to be solved?

When Fn+Q is pressed, not only will the setting for the performance mode change but also the wallpaper.
For example, you have a bright live wallpaper during normal/performance mode and a dark, still wallpaper on quiet mode to save battery life.
I was thinking that it would sit nicely in the action tab

### What alternatives have you considered?

My current thought process is to do it manually or to use an automation software (I haven't tried it yet)

**Comment by BartoszCichecki** [comment]
Hey,

I don't think features like this are a good fit for LLT.

However, you can pretty easily make a script like shown [here](https://stackoverflow.com/questions/46984616/how-to-set-wallpaper-from-windows-command-prompt-on-windows-10) and run the script using Run action.

**Comment by NotUrWang** [comment]
> Hey,
> 
> I don't think features like this are a good fit for LLT.
> 
> However, you can pretty easily make a script like shown [here](https://stackoverflow.com/questions/46984616/how-to-set-wallpaper-from-windows-command-prompt-on-windows-10) and run the script using Run action.

No worries, as I claimed, it is a nice to have feature.
Using your solution of a script is it possible to add it to LLT as a custom action?
