### ISSUE TITLE
After updating BIOS Version: LPCN47WW, EC Version: LPEC47WW on Lenovo R9000P 2023, the Legion Toolkit’s “lock touchpad” function becomes invalid every time the notebook is turned on or wakes up from sleep.

### ISSUE THREAD

**Issue by Wjq1024** [BartoszCichecki/LenovoLegionToolkit#1047]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 10 22H2

### Device

 Legion Pro 5 16ARX8 - Type 82WM (R9000P 2023)

### BIOS version

LPCN47WW

### What's wrong?

After updating BIOS Version: LPCN47WW, EC Version: LPEC47WW on Lenovo R9000P 2023, the Legion Toolkit’s “lock touchpad” function becomes invalid every time the notebook is turned on or wakes up from sleep.

### How to reproduce the bug?

Every time the notebook is turned on or wakes up from sleep.
This problem occurs after updating to a new BIOS.
BIOS download address:https://pcsupport.lenovo.com/hk/en/products/laptops-and-netbooks/legion-series/legion-pro-5-16arx8/82wm/downloads/driver-list/component?name=BIOS%2FUEFI&id=5AC6A815-321D-440E-8833-B07A93E0428C
or
https://newsupport.lenovo.com.cn/driveDownloads_detail.html?driveId=119650

### What is the behavior that you expected?

It is desirable to retain user control of the "Lock Touchpad" option rather than having it reset after a reboot or wake from sleep.

### Logs

.

**Comment by BartoszCichecki** [comment]
Report this bug to Lenovo.
