### ISSUE TITLE
Ability to add custom notifications to Actions

### ISSUE THREAD

**Issue by zwresn453** [BartoszCichecki/LenovoLegionToolkit#1048]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11

### Device

Legion 7 16ACHg6

### Is your feature request related to a problem?

I disable Hybrid Mode when I play games, but I need to remember to manually re-enable it every single time I am on the go and need the battery to last longer than 1.5 hours. 

I assume there is some reason that changing hybrid mode as part of an Action cannot be done (please correct me if I am wrong). Because of this, and because custom notifications would be nice to have in general, I would like to have the ability to program in a reminder for myself to enable hybrid mode when I run my "Battery Saving Mode" quick action. 

### How would you like the problem to be solved?

Option to add custom notifications to Actions. It would also be nice to set a custom timeout for each notification (including "wait for user acknowledgement").

### What alternatives have you considered?

Keep forgetting to turn on hybrid mode

### Additional information
Sorry if someone already asked this; I thought I saw someone asking this before but now I can't find it.

**Comment by BartoszCichecki** [comment]
> I assume there is some reason that changing hybrid mode as part of an Action cannot be done

How would you see this working if changing Hybrid mode requires restart?

In general, latest beta available on Discord already allows showing custom notifications when Actions run. If something is still missing, please reopen this issue after new version is released.

**Comment by zwresn453** [comment]
> How would you see this working if changing Hybrid mode requires restart? 

It would certainly need to be handled differently; LLT would probably need to prevent any other "tiles" from being added below the Hybrid Mode tile (to ensure that it is the last thing executed before the restart).

If custom notifications are in the works, then I am probably OK with just using those.
