### ISSUE TITLE
Very annoying startup banner.

### ISSUE THREAD

**Issue by archlegion** [BartoszCichecki/LenovoLegionToolkit#1049]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 Pro 23H2 OS Build 22631.2715

### Device

Legion Y545

### Is your feature request related to a problem?

![Screenshot 2023-11-29 134541](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/148542657/e31ee03e-a99a-4cee-b805-ec9fdb0c6c5e)
 Hello World! Guys, I removed Lenovo Vantage for its banners, ads, unknown services..etc...
Please remove this startup banner or make a checkbox, not to show every time I start laptop.

### How would you like the problem to be solved?

Please remove this startup banner or make a checkbox, not to show every time I start laptop.

### What alternatives have you considered?

Please remove this startup banner or make a checkbox, not to show every time I start laptop.

**Comment by BartoszCichecki** [comment]
Closing because of violation of rule "I made myself familiar with the README."
