### ISSUE TITLE
Smart Fn Lock does not work as expected

### ISSUE THREAD

**Issue by partingscientist** [BartoszCichecki/LenovoLegionToolkit#1052]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0

### OS

Windows 10 22H2 19045.3693

### Device

Lenovo Legion 5 15ARH05

### BIOS version

EUCN28WW

### What's wrong?

The functionality `Smart Fn Lock` does not work when trying to perform browser reload while bypassing cache (`Ctrl + F5`) with `FnLock` being on. Performing the aforementioned key-press with `FnLock` and `Smart Fn Lock` on will reduce the brightness on the screen instead of performing a cache-bypassing reload.

### How to reproduce the bug?

1. Ensure that `FnLock` is off and `Smart Fn Lock` is off.
2. Open `https://github.com` on any major internet browser (reproducibility has been tested in Chromium and Firefox).
3. Press `Ctrl + F5` to reload the site while bypassing cache on your browser. Observe the behaviour.
4. Turn on `FnLock` by pressing `Fn + Esc` and set `Smart Fn Lock` for `Shift, Ctrl, Alt` from LLT.
5. Press `Ctrl + F5` to reload the site while bypassing cache on your browser. Observe the behaviour.

### What is the behavior that you expected?

The browser will perform a cache-bypassing reload on step 3 and 5.

### Logs

[log_2023_12_02_02_32_14.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13533175/log_2023_12_02_02_32_14.txt)

**Comment by BartoszCichecki** [comment]
I cannot reproduce this on my Gen 7, so it might be a Gen 5 issue. As stated in the readme:

> Generations 6 (MY2021), 7 (MY2022) and 8 (MY2023) are supported, although some features also work on the 5th generation (MY2020).

so that might be one of the things that isn't working properly on Gen 5.
