### ISSUE TITLE
Notifications not appearing in active virtual desktop unless app window present or minimized to tray

### ISSUE THREAD

**Issue by e-l-i-j-a-h** [BartoszCichecki/LenovoLegionToolkit#1053]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0

### OS

Windows 11 Home 22H2 build 22621.2715

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN51WW

### What's wrong?

I have configured four virtual desktops to assist me in organizing my windows. In one of these desktops, I usually leave task manager and Lenovo Legion Toolkit open in a side-by-side view. Unfortunately, this results in notifications from Lenovo Legion Toolkit only displaying when that desktop is active (i.e. showing on my screen).

Notifications from Lenovo Legion Toolkit correctly display in the currently active desktop when the window is minimized to the tray. This issue only occurs when the window is left open in another desktop.

### How to reproduce the bug?

1. Open task view by pressing the Windows key + tab key.
2. Configure two or more virtual desktops.
3. Open the Lenovo Legion Toolkit window in one virtual desktop.
4. Enable notifications via the app's settings tab if not already enabled.
5. Confirm that notifications are correctly enabled by performing some action that would normally trigger a notification (camera switch, keyboard lighting preset, etc).
6. Navigate to another virtual desktop while leaving the app window open in its original desktop.
7. Perform the same action that would normally trigger a notification.

### What is the behavior that you expected?

I expected notifications to display on the currently active desktop regardless of which desktop the Lenovo Legion Toolkit window was left open in.

### Logs

[log_2023_12_02_06_13_12.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13533557/log_2023_12_02_06_13_12.txt)

### Additional information

![desktops](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/13988479/64403605-4569-4233-9977-d86ee8442abf)

Attached above is my current virtual desktop configuration as it appears in task view.

**Comment by BartoszCichecki** [comment]
Hey, this is a limitation of WPF unfortunately. Once #980 is done, this problem will be resolved. I will close this a duplicate.
