### ISSUE TITLE
Smart Fn Lock causing system stutter

### ISSUE THREAD

**Issue by The12thUnique** [BartoszCichecki/LenovoLegionToolkit#1058]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0

### OS

Windows 10 22H2

### Device

Legion 5 15ARH7H

### BIOS version

JUCN63WW

### What's wrong?

Turning on Smart Fn Lock, and then trying to use causes my laptop to momentarily stutter. If I am playing an audio, it will mute itself and then pick back up, watching a video the framerate will drop or playback just stops altogether. 

### How to reproduce the bug?

1. Turn Smart Fn Lock on any mode is fine
2. Try using the keys

### What is the behavior that you expected?

That it won't stutter. 

### Logs

[log_2023_12_02_23_46_51.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13537681/log_2023_12_02_23_46_51.txt)

**Comment by BartoszCichecki** [comment]
It is unfortunately a know issue on some BIOS versions. Happens also when Fn Lock is enabled or disabled. There is no solution to this except for a BIOS fix. I will update readme with this info.

Thanks for reporting though!

**Comment by The12thUnique** [comment]
Ah I see. Alright then.
