### ISSUE TITLE
Power Mode indicator only switches if triggered through Vantage/LLT.

### ISSUE THREAD

**Issue by mohitmujawdiya** [BartoszCichecki/LenovoLegionToolkit#106]
**Describe the bug**
Whenever I switch my Power Plan through Control Panel or Windows Settings, the LED indicator color does not change if Vantage is disabled. It works if Vantage is enabled.

**To Reproduce**
1. Go to LLT and disable Vantage.
2. Reboot
3. Then go to Control Panel\System and Security\Power Options
4. Switch between Legion-specific power modes. (The LED doesn't change).
5. Repeat the same switching in Windows Setting/System/Power & Battery (No LED change here either).

**Expected behavior**
The LED indicator on the power button should indicate the colors of corresponding power modes even if switched from Control Panel or Windows Settings.

**Environment (please complete the following information):**
 - OS: Windows 11 21H2 build 22000.708
 - Laptop model: Legion 5 Pro 16ACH6H
 - .NET version: 6.0.4
 - Do you have Vantage installed? Yes
 - Running the new LTT Beta, the UI is so slick! Thanks Dev!

**Comment by BartoszCichecki** [comment]
Nice! Didn't know this is what Vantage is doing, will totally add it ;)
