### ISSUE TITLE
Windows Defender detecting update as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by kleidiss** [BartoszCichecki/LenovoLegionToolkit#1061]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Ideapad Gaming 3 15ACH6

### BIOS version

H3CN45WW(V3.03)

### What's wrong?

I tried to update to  2.17.0  with the LLT updater and windows instantly  detected it as a Trojan:Win32/Wacatac.B!ml
![Screenshot 2023-12-03 142506](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/124008722/1a9724e1-7c0a-416a-99db-fab8a367e836)

### How to reproduce the bug?

1- Try and update to  2.17.0
2- Get malware prompt from Windows Defender

### What is the behavior that you expected?

Not getting detected as a severe threat 

### Logs

Not related

**Comment by BartoszCichecki** [comment]
"I made myself familiar with the README."

Please make yourself familiar before opening issues because you obviously didn't.
