### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by cdnov** [BartoszCichecki/LenovoLegionToolkit#1076]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11 22H2

### Device

Legion R9000P ARX8

### Is your feature request related to a problem?

In some regions, you can't connect to GitHub directly, so you need to use a proxy.

### How would you like the problem to be solved?

Proxy Support

### What alternatives have you considered?

Windows Proxy

**Comment by BartoszCichecki** [comment]
Added 4 new arguments that can be configured:

```
--proxyUrl=example.com
--proxyUsername=some_username
--proxyPassword=some_password
--proxyAllowAllCerts
```

That can be added to `args.txt` (details in README). Build with this change can be found here: https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/7173399635
