### ISSUE TITLE
Suggestion to make the "On Battery Since" stat more useful and smarter!

### ISSUE THREAD

**Issue by advanced03** [BartoszCichecki/LenovoLegionToolkit#1077]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0

### OS

Windows 11 22H2

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

I would like to start off by saying that I really love this app, keep up the good work!

That being said, I do have several suggestions to make the On Battery Since more useful.

1. Implement the option that resets the "on battery since" time if the device shuts down/restarts.
2. Notification/warning when the drain is higher than a set number.
3. Show the drain in percentage together with the wattages.

### How would you like the problem to be solved?

1. In the power tab, there is a option that can be toggled, if enabled, this feature resets the "On Battery Since" timer when the device shuts down or restarts.
2. Also in the power tab of the settings, there should be an option (either the user enters it or a slider bar) where the user can select a %/W for the app to give a notification/warning that says something of the line of "High drain: Your current battery drain is X"
3. In battery > discharge rate, give the % drain next to the wattage drain. so it says -8w (-10%)

### What alternatives have you considered?

N/A

### Additional information

These changes should make this stat more useful and more importantly, more accurate.

**Comment by BartoszCichecki** [comment]
> In the power tab, there is a option that can be toggled, if enabled, this feature resets the "On Battery Since" timer when the device shuts down or restarts.

This is not a bad idea.

> Also in the power tab of the settings, there should be an option (either the user enters it or a slider bar) where the user can select a %/W for the app to give a notification/warning that says something of the line of "High drain: Your current battery drain is X"

When LLT is minimized it doesn't monitor discharge rate, because of poor refresh frequency and delay in how Windows calculates this information.

> In battery > discharge rate, give the % drain next to the wattage drain. so it says -8w (-10%)

I don't understand what % should be shown, because % don't make sense here. If anything %/h would be better here, but still make little sense.

**Comment by advanced03** [comment]
Yeah sorry for not clarifying, I meant the drain percentage per hour.

**Comment by advanced03** [comment]
Oops didn't mean to mark it as closed

**Comment by getmkt** [comment]
Would also be great to add "screen on time" while on battery. The built-in screen on time per hour in Windows 11 settings does not work properly and does not show "while on battery".

**Comment by Ekscentricitet** [comment]
Well, #1171 gives you the option to reset the On battery since timer on reboot. Therefore, the Screen time on battery should be the same measurement, unless I am missing something.

**Comment by getmkt** [comment]
"On battery since" is total time on battery. You may turn screen on or off multiple times as you use the laptop. The screen on time would add up all. This will need observing screen on and off events. See https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-power?tabs=csharp
