### ISSUE TITLE
Synchronise Windows Power Mode with Legion Power Mode

### ISSUE THREAD

**Issue by BartoszCichecki** [BartoszCichecki/LenovoLegionToolkit#1078]
### Discussed in https://github.com/BartoszCichecki/LenovoLegionToolkit/discussions/1073

<div type='discussions-op-text'>

<sup>Originally posted by **ToniCui** December 10, 2023</sup>
First of all, thanks a lot for making legion toolkit, it's much better than the original legion zone.

Besides, I wanna apologize for using Chinese in my screenshot, becasue the system on this laptop is customized for China and I can only use Chinese in Windows, for the same reason, I translate some keywords by myself, they might not be accurate, so if you're cofused please ask me.

My laptop is called  legion r9000p, like the system, it's a special model for China, I'll say it's kinda like Legion 5 and I'll put a screenshot with my hardwire info beneath. Now matter I choose what power mode in legion toolkit, the power plan on Windows remain quiet model/ high-power efficiency mode, as you can see in my second screenshot. Is it just I didn't change the right option or what?
<img width="343" alt="微信截图_20231210114045" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/76056320/4e297f8b-1f2a-48db-afac-41f459264ce9">
<img width="998" alt="微信截图_20231210113651" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/76056320/9cc0f7ec-3d55-40cb-b8d4-36f40538cc77">
</div>

**Comment by pantherra** [comment]
https://github.com/tarcode-apps/BatteryMode
I think you can use code from this repository to implement control of PowerMode on Windows 11 through lenovo toolkit?

**Comment by BartoszCichecki** [comment]
>  Dashboard does nothing.
> even though the light changes

Then it's doing what it's supposed to do. The "Power Mode" in Windows settings **is not the same** as Fn+Q or Legion power modes.

**Comment by BartoszCichecki** [comment]
I would also like to point out that this is very low priority, since there isn't much point in implementing this feature.

If you **do not** use the "old" power plans which are available from Control Panel, meaning you only use default "Balanced" power plan that comes with Windows, it is enough to go intro Windows Settings app and set "Best performance" while connected to AC and then, disconnect AC and set "Better battery". Windows will remember this "Power Mode", which really is a power plan overlay, for when your on AC and when you are on battery.

If instead you have multiple power plans, for example the stock Legion power plans, you shouldn't mess with the new "Power Mode" setting in Windows.

**Comment by BartoszCichecki** [comment]
>  Dashboard does nothing.
> even though the light changes

@feralslash Then it's doing what it's supposed to do. The "Power Mode" in Windows settings **is not the same** as Fn+Q or Legion power modes.

**Comment by ThingsWhy** [comment]
Hello, I don't know if it was the version of this issue that worked, now when I use the latest version (2.21.1-2.21.2) of the toolbox, my windows power mode changes to the recommended project, better performance, best performance, and what I originally set is gone
<img width="661" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/37958754/335ca8a0-d556-4188-99e9-62b51a3025f4">
<img width="674" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/37958754/8c05c14d-ea74-4abd-ae94-2d21a089b9b1">

**Comment by feralslash** [comment]
I resolved my issue. I did not enable 'Disable Lenovo Vantage and ImController' in the settings page.
After enabling it, windows power plan will change when I change the power mode in toolkit or when i use Fn+Q.
Sorry for the confusion.
