### ISSUE TITLE
PROBLEM WITH MY RGB KEYBOARD

### ISSUE THREAD

**Issue by ZeyadAhmed003** [BartoszCichecki/LenovoLegionToolkit#1081]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

WINDOWS 11 PRO , 23H2, 22631.2792

### Device

LEGION 5 15ITH6H

### BIOS version

H1CN53WW

### What's wrong?

I have bought my laptop in July 2022 i was not familiar with the RGB thing in my laptop but the thing i found later that i can't change or close the rgb in keyboard and the Lenovo spectrum doesn't show in Lenovo vantage so after a little research i found ur application and there is a guy on Ur discord server told me to disable Lenovo vantage and some other steps  and after all this steps i can't control the rgb keyboard. 

![WhatsApp Image 2023-12-12 at 23 17 31_633f39db](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/112496754/e2571d17-4166-4e12-ad5f-eefbd555d71e)

### How to reproduce the bug?

i don't know what to write here.

### What is the behavior that you expected?

I expected that i can control the lightning of my keyboard.

### Logs

[log_2023_12_12_19_52_58.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13652895/log_2023_12_12_19_52_58.txt)
[log_2023_12_12_19_53_40.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13652896/log_2023_12_12_19_53_40.txt)

**Comment by BartoszCichecki** [comment]
Resolved on Discord.
