### ISSUE TITLE
PrintScreen key doesn't work while LLT is focused

### ISSUE THREAD

**Issue by zwresn453** [BartoszCichecki/LenovoLegionToolkit#1083]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11

### Device

Legion 7 16ACHg6

### BIOS version

Latest

### What's wrong?

When LLT is focused, Windows's "Use the PrintScreen key to launch screen snipping" feature does not trigger. LLT is probably inadvertently preventing presses of the PrintScreen key from reaching Windows. 

The dialog that is triggered is the exact same thing as when you press Win+Shift+S. 

This issue could cause friction if a user is trying to take a screenshot of a bug in LLT, and doesn't know of any way to trigger Snipping Tool other than the PrintScreen key

### How to reproduce the bug?

1) Enable the feature: Start > "prtsc" > Use the Print Screen key to launch screen snipping.
2) With LLT not focused, press PrtScn. Press Esc.
3) Launch/focus LLT
4) Press PrtScn key

The dialog triggered in Step 2 does not trigger in Step 4.

### What is the behavior that you expected?

The screen snipping dialog is triggered.

### Logs

[log_2023_12_15_06_45_24.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13682031/log_2023_12_15_06_45_24.txt)

**Comment by BartoszCichecki** [comment]
This is a limitation of Windows. When an app running with Administrator privileges is focused, PrtSc won't work.
