### ISSUE TITLE
弹出独立显卡

### ISSUE THREAD

**Issue by bobandbrony** [BartoszCichecki/LenovoLegionToolkit#1084]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18

### OS

windows11 23H2

### Device

Legion y9000x(2022)

### Is your feature request related to a problem?

弹出独立显卡（就像弹出U盘那样，设备管理器也不会显示独立显卡），而不是休眠独立显卡（程序里的休眠会使独立显卡一直挂在后台消耗电量）

### How would you like the problem to be solved?

弹出独立显卡，且程序主界面不显示独立显卡

### What alternatives have you considered?

在任务栏弹出，但这个选项已经不可用了

**Comment by BartoszCichecki** [comment]
Please report issues only in English.
