### ISSUE TITLE
 information of AMD GPU & 83/165Hz refresh rate

### ISSUE THREAD

**Issue by V3-vvv** [BartoszCichecki/LenovoLegionToolkit#1088]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.18.0

### OS

Windows11 23H2

### Device

R9000k 2022

### BIOS version

K9CN44WW

### Which features of the application did you test?

GPU information & refresh rate

### Which features of the application do not work as expected?

Unable to display the parameter information of AMD GPU normally, and the refresh rate does not have a dynamic refresh rate of 83/165Hz

**Comment by BartoszCichecki** [comment]
Duplicate #827
