### ISSUE TITLE
CPU Temperature Limit

### ISSUE THREAD

**Issue by nadimsaridar** [BartoszCichecki/LenovoLegionToolkit#1092]
### Rules

- [ ] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11 23H2 build 22631.2861

### Device

Legion 5 15ACH6A

### BIOS version

G9CN33WW

### What's wrong?

Hello, I am having a problem with the custom power plan in the toolkit. It was working perfectly, but after I updated my windows and my AMD software (from 23.9.1 to 23.12.1), the CPU section of the custom power plan is not applied, unless I save it again while playing a game (take note that my laptop is always on that custom power plan because the LED of my power button is always purple).

### How to reproduce the bug?

In my custom power plan, I have my CPU temperature limited to 90°C.
When playing any demanding game, I check the CPU temperature on the AMD software, and it is on 100°C.
After saving again the custom power plan while playing the game, the temperature drops to 90°C (sometimes after few minutes, the temperature rises again to 100°C)

### What is the behavior that you expected?

I expect that I shouldn't be saving this power plan everytime, as it used to work before the updates without any problem

### Logs

couldn't find it, as I couldn't even find any README file

**Comment by BartoszCichecki** [comment]
If you say it worked before and now it doesn't after you updated some other software, it is pretty obvious that this other software is interfering. You need to figure out how (probably) AMD software is overriding this limit and stop it from doing that. There isn't anything I can do in this case.
