### ISSUE TITLE
Signed build

### ISSUE THREAD

**Issue by xucian** [BartoszCichecki/LenovoLegionToolkit#1093]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

1.0

### OS

Windows 10

### Device

Legion 7i 

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

create a signed build so we can safely install it

### What alternatives have you considered?

none

**Comment by BartoszCichecki** [comment]
Are you willing to sponsor a certificate? If not explanation is in the readme.
