### ISSUE TITLE
Keyboard Backlight not working correct on Legion Slim 7 16APH8 with german keyboard

### ISSUE THREAD

**Issue by Venom1278** [BartoszCichecki/LenovoLegionToolkit#1095]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11

### Device

Legion Slim 7 16APH8

### BIOS version

M1CN36WW

### What's wrong?

# key and >< key are switched. # Key not working if an effect / color is applied.

### How to reproduce the bug?

Go to Keyboard Backlight.
choose e.g. Setting 4
choose Rainbow skew
# Key is not working
Default Rainbow skew from lenove on Setting1 works.

choose left half of the keyboard blue, choose right half of the keyboard pink. 
<> Key on the left side is pink, # key on the right side is blue

### What is the behavior that you expected?

# key and >< key working as expected

### Logs

[log_2023_12_26_12_41_04.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13771666/log_2023_12_26_12_41_04.txt)

### Additional information

![Unbenannt](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/154876360/da46dfad-455c-44f2-909a-a949fb972eb8)
![IMG_1221_](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/154876360/b0a18cfe-9555-449d-bde9-36831d93e149)

**Comment by BartoszCichecki** [comment]
Please see this response: https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/1090#issuecomment-1865014521

**Comment by Venom1278** [comment]
That did the trick. 
Thank you for the very fast help.
