### ISSUE TITLE
 Error opening Lenovo Legion Toolkit

### ISSUE THREAD

**Issue by CmxxdZZJ** [BartoszCichecki/LenovoLegionToolkit#1096]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11 23H2

### Device

Legion R9000P ARX8

### BIOS version

LPCN47WW

### What's wrong?

//Before the issue, I must express my gratitude. This application is wonderful.
Issue: When I click it， it cannot open.And terminates like these photos below.

<img width="698" alt="Snipaste_2023-12-30_14-42-07" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/102661691/c5adb9ab-731c-41fb-8aee-d14b9549a702">
<img width="1044" alt="Snipaste_2023-12-30_14-42-13" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/102661691/4b29ca0b-53d9-49fd-88c2-fc447591ba3d">

### How to reproduce the bug?

Just open it.

### What is the behavior that you expected?

I hope it can work nomarlly.

### Logs

[error_2023_12_30_12_21_48.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13798270/error_2023_12_30_12_21_48.txt)
[error_2023_12_30_12_21_50.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13798271/error_2023_12_30_12_21_50.txt)
[log_2023_12_30_12_21_48.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13798272/log_2023_12_30_12_21_48.txt)

### Additional information

My computer recently had its motherboard replaced after official after-sales service store. I don't know if this has any impact. Because this application works well in my computer before in old version. However，even I reinstalled the old version which worked well before. It still appeared the same error.

Also, I installed ExplprerPatcher (https://github.com/valinet/ExplorerPatcher). I don't know if it has any impact too. I havn't installed it when it works well. So far, that's all I've thought of.

Thank you for your effort again.

**Comment by BartoszCichecki** [comment]
Sorry, this is an error that comes from Windows. It might be related to ExplorerPatcher or some other modifications that were made. This isn't something that I can work around.

**Comment by CmxxdZZJ** [comment]
Thank you for your reply.
As you said, it is completely caused by Windows. // Sorry for adding to your troubles. 🙂
After I reinstalled the system, it was fine.  // The ExplorerPatcher software does not cause any impact.

Thank you again for your great contribution. This software is really convenient.
________________________________
发件人: ***@***.*** ***@***.***> 代表 Bartosz Cichecki ***@***.***>
发送时间: 2024年1月2日 17:43
收件人: BartoszCichecki/LenovoLegionToolkit ***@***.***>
抄送: CmxxdZZJ ***@***.***>; Author ***@***.***>
主题: Re: [BartoszCichecki/LenovoLegionToolkit] Error opening Lenovo Legion Toolkit (Issue #1096)


Closed #1096<https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/1096> as not planned.
