### ISSUE TITLE
Add Scoop installation support in Readme

### ISSUE THREAD

**Issue by YisusChrist** [BartoszCichecki/LenovoLegionToolkit#1099]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.0

### OS

Windows 11 23H2 Build 22631

### Device

Legion Pro 5 16ARX8

### Is your feature request related to a problem?

It is stated that the program can be installed by 2 different ways:

- Manually from [Releases page](https://github.com/BartoszCichecki/LenovoLegionToolkit/releases/latest)
- [winget](https://github.com/microsoft/winget-cli)

But there is a 3rd option already supported which is Scoop. If you take a look at the available packages, you can easily find the one corresponding with this program:

- [Basic info](https://scoop.sh/#/apps?q=lenovo&id=523e2177e59281b7987b6b0ec86c374c1a559862)
- [Full package info](https://github.com/ScoopInstaller/Extras/blob/master/bucket/lenovolegiontoolkit.json)

All the hard work is already done, so I think it must be included inside the Readme download section.

### How would you like the problem to be solved?

Including the mentioned procedure as an installation option:

```
> scoop install extras/lenovolegiontoolkit
```

### What alternatives have you considered?

Including the mentioned procedure as an installation option:

```
> scoop install extras/lenovolegiontoolkit
```

**Comment by BartoszCichecki** [comment]
Could you write up the text that I can copy paste to README? Or make a PR?
