### ISSUE TITLE
Legion S7 15ACH6 is compatible

### ISSUE THREAD

**Issue by tofaeltohin** [BartoszCichecki/LenovoLegionToolkit#11]
Legion S7 15ACH6 

(Legion Slim 7 2021 model, AMD Ryzen 7 5800H, RTX 3060, Windows 11 Pro)

Launched using `--skip-compat-check` in Powershell as administrator.

**List of features that are working as expected:**
- Power Mode
- Hybrid Mode
- Battery Mode
- Always on USB
- Flip to start
- Over Drive
- Fn Lock
- Touchpad Lock
- Tools -> Lenovo Vantage -> Enable/Disable

**List of features that seem to not work (they do nothing):**
- None

**List of features that crash the app:**
- None

**Feature request:**
- Please add a checkmark for "Tools -> Lenovo Vantage -> Enable/Disable".
- Dark mode (sorry, if I'm asking too much)

**Comment by BartoszCichecki** [comment]
Thanks for support! Compatibility will be added in 1.2.

Dark mode, might be comming later, but no plans at the moment. I will add a separate issue for that.
