### ISSUE TITLE
2.0.0 becoming bloated

### ISSUE THREAD

**Issue by mergen3107** [BartoszCichecki/LenovoLegionToolkit#110]
Hi!

Thank you for the app, but I think it is that time when Lenovo Legion Toolkit is becoming more like Vantage already.

1) Interface requires more clicks. In 1.7.2. every setting option is in plain sight. So it is easy to set all within 4-5 clicks. In 2.0.0 each setting is hidden in the drop-down menu. I think this is UX regression.

2) It becomes less lightweight. 2.0.0 is around 35 MB, 1.7.2 is around 1.7.2 for the same functionality.

This isn't a rant, but rather my input as from a regular user. I'd stay on 1.7.2 for a little longer.

Thank you anyway!

**Comment by mergen3107** [comment]
By bloated I mean “looking fancier than its functionality needs” :D 
As for the drop downs: radio button are much accessible than drop downs. You just need to open the app, click once per setting (instead of two in drop downs), and close the app. This is all what the app is intended for, right? 

Again, this isn’t blaming, just my thoughts about the UX and why I think so. 

I appreciate the other parts you explained about optimization!

Thank you very much for your hard work and open communication! 

P.S. the old flip about Fn lock is still present on 2.0.0 #77

**Comment by BartoszCichecki** [comment]
I see what you mean. I have a cool thing coming soon and it needed more space on the UI, so hopefully it will make more sense soon 😉

**Comment by versedwildcat** [comment]
Leaving my two cents in, I think the new UI looks tremendously better than the old one. All settings remain accessible within 3 clicks, apart from the advanced ones which require an extra 2.

An intuitive and user-friendly UI can help people migrate over from Vantage and is definitely not bloat.

**Comment by tofaeltohin** [comment]
I just wanted to say THAAANK YOU!!! I love the UI. Matches Windows 11 perfectly. I loved it so much that I donated instantly after installing the app. I requested dark mode in the past & I'm so happy for it.

***Feature request: Fan control (no pressure, no rush) 😁
