### ISSUE TITLE
Suggestion to add power display in CPU and GPU dashboards

### ISSUE THREAD

**Issue by unikevin** [BartoszCichecki/LenovoLegionToolkit#1100]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows11 22H2 build 22621

### Device

Legion R9000P ARX8

### Is your feature request related to a problem?

-

### How would you like the problem to be solved?

-

### What alternatives have you considered?

You can use AIDA64/HWiNFO to check, but they are too complicated ,If LLT adds power display, you can throw them in the trash (joke

I mean, if you want to simply monitor the status of the computer, especially "whether its performance release is OK", CPU utilization, frequency, temperature, fan speed, power, they are very common indicators, and the power display seems to be The last piece of the puzzle. Then, you no longer need to open AIDA64/HWiNFO unless you have more specialized needs.

I haven't read the source code and don't know if the current sensor data in the dashboard comes from Lenovo's hardware API or something else, if it doesn't provide power data it might give you a hard time, but I do hope this feature comes out At LLT, thank you for your work!
The progress bar can be: current power/power litmit wall or design maximum power value

**Comment by BartoszCichecki** [comment]
While this isn't a bad idea, it won't be possible to add it. CPU temperature isn't something that is possible to read without ring0 driver and there isn't one that is readily available. You can check LibreHardwareMonitor if you are looking for something simple.
