### ISSUE TITLE
I want to be able to customize some functions in the system tray.

### ISSUE THREAD

**Issue by RinSky123** [BartoszCichecki/LenovoLegionToolkit#1105]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11  23H2 22635.2915

### Device

Legion r70002021

### Is your feature request related to a problem?

I hope to be able to adjust the microphone, camera, charging mode and other switches at any time like the "Lenovo Vantage" tray toolbar.

### How would you like the problem to be solved?

At present, several functions in the right-click tray are actually not used very much.
My idea is that you can customize which functions are placed in the right button tray in the Settings, such as the switch of microphone and camera, the switch of charging mode, etc., can be placed directly in the tray, so that you can switch and switch without opening the application.

### What alternatives have you considered?

My current solution is to share Lenovo Vantage and Toolkit.

### Additional information

This allows you to switch on and modify certain functions directly.
![PixPin_2024-01-04_01-11-37](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/121341108/17cf9a65-8c81-4479-9e13-ba603fa0ee9d)

**Comment by BartoszCichecki** [comment]
Right click tray menu? You could always customize it. Quick Actions defined in Actions tab appear in the tray right click menu. 

Please explore the app before creating issues next time.
