### ISSUE TITLE
Show error message when failing to set boot logo

### ISSUE THREAD

**Issue by Ace-Radom** [BartoszCichecki/LenovoLegionToolkit#1106]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11 22H2 Build 22621.2861

### Device

Legion R9000p 2021H

### Is your feature request related to a problem?

I found that the customize boot logo feature will not show the reason why this file is not set as the boot logo, when exceptions are thrown in `BootLogo.cs`. For example, when I'm using a png photo with the size 1024*768, exception will be thrown at:

https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/27bf3d3401eaa9bff43dde852bc8941edf7b5004/LenovoLegionToolkit.Lib/System/BootLogo.cs#L325-L331

and it will be caught at:

https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/27bf3d3401eaa9bff43dde852bc8941edf7b5004/LenovoLegionToolkit.WPF/Windows/Settings/BootLogoWindow.xaml.cs#L82-L86

But according to the codes here: this group of exceptions will only be recorded in log (if enabled), no message will be shown in frontend.

Although the tips (`Custom boot logo must be excatly 2560 x 1600 pixels large. Supported formats are: BMP, JPEG, PNG.`) is actually clear enough to show what may happen, I still think something should be produced to users: more like a warning than an information.

### How would you like the problem to be solved?

I'm considering showing a warn message box to users, or adding a warn message (in red) to the set-boot-logo window will also be nice.

### What alternatives have you considered?

I forked this repo and trying to add this feature on my own. Please tell me if you think this feature request is accecptable.

And same, please tell me if this is not necessary.

**Comment by BartoszCichecki** [comment]
Yup, sounds like a good idea! Remember that these errors will need to be translate'able so make sure to create appropriate resources.

**Comment by Ace-Radom** [comment]
> Yup, sounds like a good idea! Remember that these errors will need to be translate'able so make sure to create appropriate resources.

Okay I'll work on it when I finish my jobs in hand.

**Comment by Ace-Radom** [comment]
I created a PR and linked to this issue just now.
