### ISSUE TITLE
Discrete GPU Option Disappearing on Autorun

### ISSUE THREAD

**Issue by Hagenth** [BartoszCichecki/LenovoLegionToolkit#111]
**Describe the bug**
Greetings!
First of all, thanks for this amazing app that makes the life of so many Legion users so easier! It is a really amazing app and we'll never thank you enough for it!
Now, I have noticed a tiny bug that have been seen by other members (2 so far on the Laptop Wiki Discord) of the community as well, which is that when the app starts with Windows, it seems that the "Discrete GPU" option disappears, and we cannot disable the dGPU anymore. However, after restarting the app as an admin, it seems to come back.
Hopefully, that'll be an easy fix for you,
Again thank you and have a great day,
Hagenth

**To Reproduce**
- Autorun (Start minimized to tray when you log in to Windows)
- To fix it, simply close the app on the task bar and restart it as an administrator

**Expected behavior**

**Screenshots**
[https://cdn.discordapp.com/attachments/900732420955983903/983729177024937984/unknown.png](url)
[https://cdn.discordapp.com/attachments/900732420955983903/983730193791332392/unknown.png](url)

**Environment (please complete the following information):**
 - OS: Windows 11 21H2 build 22000.675
 - Laptop model: Legion 5 Pro-16ITH6H Laptop (Lenovo) - Type 82JD
 - .NET version: 5.0.408
 - Do you have Vantage installed? Yes but the service is disabled ([https://cdn.discordapp.com/attachments/668432254472552448/985094898476802108/unknown.png](url))

**Comment by filius-martis** [comment]
Same her, Legion 5 Pro 16ACH6H on Windows 11.

As a side note, having an indication for dGPU activity right on the tray icon would be very helpful, let`s say the green dot from the Discrete GPU section.

**Comment by BartoszCichecki** [comment]
Great catch guys, fix will be in next release. Thanks!

**Comment by BartoszCichecki** [comment]
@filius-martis regarding the indicator, you can enable the GPU activity icon in nVidia Control Panel: 
![image](https://user-images.githubusercontent.com/7916915/173243780-e0e1fb6d-7374-4399-bedf-fcd5a90ecc96.png)
