### ISSUE TITLE
LLT with a Custom Power Mode reboots a Legion 7 Pro Gen8 with AMD 7945HX and NVidia RTX 4080

### ISSUE THREAD

**Issue by RNarayan73** [BartoszCichecki/LenovoLegionToolkit#1111]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11 23H2 build 22631.2861

### Device

Legion Pro 7 16ARX8H (82WS)

### BIOS version

LPCN47WW

### What's wrong?

When LLT is running with "Disable Lenovo Vantage and ImController" activated and in a Custom Power Mode, the laptop reboots intermittently and spontaneously. The issue is particularly pronounced after the laptop has been woken up from hibernation.
When LLT is run without the above setting active or in one of the built-in power modes e.g. Quiet, Balance, Performance, then the issue doesn't occur.
This however, effectively disables the functionality to manage Custom Power Mode and switch between multiple Presets along with the ability to tune the fan speeds to override the atrociously loud defaults.

### How to reproduce the bug?

1. Set up a custom power mode with power and fan settings
2. Activate the "Disable Lenovo Vantage and ImController"
3. Hibernate the laptop and then re-awaken (optional)
4. Use the laptop for a little while before it restarts spontaneously

### What is the behavior that you expected?

The laptop shouldn't restart spontaneously when in custom power mode with the "Lenovo Vantage and ImController" setting disabled in LLT

### Logs

[log_2024_01_09_11_25_35.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13873842/log_2024_01_09_11_25_35.txt)
[log_2024_01_09_11_28_02.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13873846/log_2024_01_09_11_28_02.txt)

### Additional information

On further investigation, I noticed that the available settings for Custom Power Mode in LLT and Vantage are not the same. 

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/82275999/144d6edd-fb7d-43ee-930a-9a8fcf9fe56e)

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/82275999/433a3978-9007-406c-8fb3-a62de706f384)

In particular, the CPU to GPU Dynamic Boost values in Vantage has a range from 0-25W in steps as shown above, whereas in LLT it has a continuous range from 15-25W. Note, the lower limits are different.
Furthermore, whereas the GPU cTGP ranges in both Vantage and LLT are the same, between 80-160W, in Vantage has a stepped range while LLT has a continuous range.

I wonder if this discrepancy is the cause of the issue.

**Comment by BartoszCichecki** [comment]
Please attach a log that includes opening of custom mode settings.

**Comment by RNarayan73** [comment]
Log with custom power mode opening included:
[log_2024_01_10_14_14_41.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13889401/log_2024_01_10_14_14_41.txt)

I also encountered the error with the default Balance Power mode. Either or both the logs below:
[log_2024_01_10_14_24_33.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13889487/log_2024_01_10_14_24_33.txt)
[log_2024_01_10_14_51_53.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/13889488/log_2024_01_10_14_51_53.txt)

**Comment by BartoszCichecki** [comment]
> I also encountered the error with the default Balance Power mode. Either or both the logs below:

What error?

**Comment by RNarayan73** [comment]
> What error?

Same as above. Laptop with LLT with the "Disable Lenovo Vantage and ImController" active in Balance mode also spontaneously reboots.

**Comment by BartoszCichecki** [comment]
Oh yeah, the spontaneous reboot isn't due to this disabled or LLT or whatever. I am more interested in fixing the value pickers in custom mode settings.

**Comment by RNarayan73** [comment]
> Oh yeah, the spontaneous reboot isn't due to this disabled or LLT or whatever. I am more interested in fixing the value pickers in custom mode settings.

So, how does one explain the fact that the error occurs only when the "Lenovo Vantage and ImController" is disabled? 
Does the log show anything that suggests how I can avoid the error?

**Comment by BartoszCichecki** [comment]
Correlation does not equal causation. The long won't show anything because it's not LLT that causes the crash. Vantage and ImController don't do anything that could cause a reboot if they aren't running.

**Comment by BartoszCichecki** [comment]
@RNarayan73 you can download a test build from [here](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/7477602350/artifacts/1159981761) to see if the settings show drop downs properly now.

**Comment by RNarayan73** [comment]
> @RNarayan73 you can download a test build from [here](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/7477602350/artifacts/1159981761) to see if the settings show drop downs properly now.

@BartoszCichecki yes, they do show as discrete values in a dropdown

**Comment by BartoszCichecki** [comment]
Thanks for checking. Regarding the reboots, they most likely aren't caused by ImController not running or LLT. You will need to find the issue on your own.

**Comment by netwolf1** [comment]
In my install the item is called "GPU to CPU Dynamic Boost" (versus CPU to GPU...).
I guess that's a type, correct? (LT 2.18.0)
