### ISSUE TITLE
Battery Mode changes to conservation after restart

### ISSUE THREAD

**Issue by ObamaLotion** [BartoszCichecki/LenovoLegionToolkit#112]
**Describe the bug**
Battery Mode settings don't apply after restart

**To Reproduce**
1. Change battery mode to something other than conservation
2. restart
3. Go into the toolkit and check battery mode

**Expected behavior**
Battery mode stays as the option that I set it to before restarting

**Environment (please complete the following information):**
 - OS: Windows 11 21H2 build 22000.675
 - Laptop model: Legion 5 Pro 16ACH6
 - .NET version: 6.0.300
 - Do you have Vantage installed? no

**Comment by BartoszCichecki** [comment]
I dont have this issue on my L5P. Something similar was reported before in #82 and it was a BIOS version that had a bug. I am running latest 54 BIOS, so maybe check this first?

**Comment by younyokel** [comment]
I am experiencing a parallel problem, but with the Power Mode set to Quiet instead of the Battery Mode set to Conservation. I will try rebooting a few more times and see what the problem might be.

**Comment by BartoszCichecki** [comment]
Since LLT is not "remembering" any of these settings between runs, I am curious to see what might be the issue, because every time LLT starts, it first reads the current settings from the machine.

If you manage to reproduce this, enable logging and attach the logs.

**Comment by RawHere** [comment]
This problem is what i am facing too, battery mode changing to normal, it is a bios issues for actual fix you need t roll back your bios.
I tried to fix it by turning On Bluetooth > rebooting , it works at least for now. Turning off Bluetooth afterwards works sometimes as fix sometimes it does not, at least for me.
