### ISSUE TITLE
Add changing lid close behaviour to actions

### ISSUE THREAD

**Issue by enoversum** [BartoszCichecki/LenovoLegionToolkit#1121]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.19.0B1

### OS

Windows 11

### Device

Legion Pro 7 Gen 8

### Is your feature request related to a problem?

Normally, I have my laptop set to go to sleep mode when closing the lid. Under certain circumstances (e.g. I'm at work) that I can define with rules in LLT, I'd love to change the lid close settings changed to 'do nothing', because I use external screens. 

### How would you like the problem to be solved?

Have an action in LLT to be able to change the lid close behaviour. 

### What alternatives have you considered?

Using LLT to execute a .bat script to perform the change, which doesn't work reliably.

**Comment by BartoszCichecki** [comment]
🤔

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/7916915/be401936-b2ed-4c23-bcfd-975b01e12033)

**Comment by enoversum** [comment]
Hey @BartoszCichecki, that's a possible trigger for an action in LLT, not an action itself that can be performed. As in: when lo-wattage charger is connected, change lid close behaviour to 'do nothing'. Right 😉?

**Comment by BartoszCichecki** [comment]
My bad, I miss understood. However, lid close action is a property of a power plan. I really don't want to deal with power plan options as the API is an absolute pain to work with. What I suggest as a solution is to make a bat script and use the run step, which I can see you considered, but that is the exact same API that LLT would use, so result would be similar.

**Comment by enoversum** [comment]
> My bad, I miss understood. However, lid close action is a property of a power plan. I really don't want to deal with power plan options as the API is an absolute pain to work with. What I suggest as a solution is to make a bat script and use the run step, which I can see you considered, but that is the exact same API that LLT would use, so result would be similar.

Ah, understood. I understand it's probably not too easy to work with. I tried to change lid-close settings via command line, but it doesn't seem to apply reliably. So probably very vulnerable to failure after all, especially with different Windows versions requiring different commands. I thought you might have an ace up your sleeves that I don't know about 😁!
