### ISSUE TITLE
Connected (Wifi) network as action trigger

### ISSUE THREAD

**Issue by enoversum** [BartoszCichecki/LenovoLegionToolkit#1122]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.19.0B1

### OS

Windows 11

### Device

Legion Pro 7 Gen 8

### Is your feature request related to a problem?

I cannot choose 'When connected to a specific network' as a trigger for actions in LLT :) .

### How would you like the problem to be solved?

An option added.

### What alternatives have you considered?

Using other triggers.

**Comment by BartoszCichecki** [comment]
Test build available [here](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/7547444376).
