### ISSUE TITLE
Logo "Y" / RGB light customization

### ISSUE THREAD

**Issue by TimmyTurner51** [BartoszCichecki/LenovoLegionToolkit#1125]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

Build 20240112230550 BETA

### OS

Windows 11 21h2

### Device

Legion 7i 16ITHG6

### Is your feature request related to a problem?

No problem for the toolkit itself.

### How would you like the problem to be solved?

Hello, as the feature request title states, I see the Y logo when the lid is closed glows blue for idle, and opening the lid it goes to RGB or a pre-set color in ICUE. My feature request is, can we get the Y logo customization options? For example, I'd like it to "breathe" say, green, when a notification comes in when the laptop lid is closed. To further the request, maybe even full RGB customization in this fashion. The toolkit is a favorite for me as it's an all-in-one solution, beating Vantage by a long shot. But to further it's capabilities, small features like this can surely make it worthwhile, saving people the ICUE installation and possibly even the battery drain from it.

### What alternatives have you considered?

Alternative is ICUE or other third-party software which either is the cause of heavy battery drain or depends on icue's components to function, making no better experience.

**Comment by BartoszCichecki** [comment]
From what I know it isn't possible to change logo color while sleeping.

Regarding iCUE, it isn't supported as stated in the readme.
