### ISSUE TITLE
Lenovo Vantage custom fan control in custom mode sucks.

### ISSUE THREAD

**Issue by Vortex3008** [BartoszCichecki/LenovoLegionToolkit#1126]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11 22h2

### Device

Legion slim 5 

### Is your feature request related to a problem?

I use LLT because it allows me to tweak the fan speed in custom mode. I would rather use Lenovo Vantage, but it only allows setting the fans to a higher rpm not lower. 

### How would you like the problem to be solved?

I think the Lenovo Vantage software could be modified to allow the sliders from custom fan control to go lower. I successfully modified the gigabyte control center which is the software for gigabyte laptops to allow lower fan speeds by opening a dll file with dnspy and moddifieng some assembly code.

### What alternatives have you considered?

I could keep using LLT but when i disable lenovo vantage services and the gpu spikes to 84C game stutters hard and it is distracting and in general LLT is not ideal for me. 

### Additional information

I am asking here because Lenovo Vantage seems very complicated software to mod, and I thought someone here could tell me if it is possible and where to start. I would like to know at least what files correspond to the custom mode.

**Comment by BartoszCichecki** [comment]
Ok sorry, but what is this about?
