### ISSUE TITLE
Empty refresh rate

### ISSUE THREAD

**Issue by younyokel** [BartoszCichecki/LenovoLegionToolkit#113]
Hi! Issue or not, the refresh rate doesn't show up. I don't have multiple refresh rate values configured, so I don't expect to see them there, but the emptiness looks a bit odd.
![image](https://user-images.githubusercontent.com/53343081/173245717-a5c608a2-c4e9-4513-a017-40ab340044ee.png)
The refresh rate of my screen (according to Windows settings) is 60.61 Hz.

**Comment by BartoszCichecki** [comment]
Fair point, I will change the behavior to hide the control if there is only a single refresh rate available!
