### ISSUE TITLE
15ARP8 incompatible, DESPITE being "supported" already

### ISSUE THREAD

**Issue by preindex** [BartoszCichecki/LenovoLegionToolkit#1136]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.19.0

### OS

Windows 10 22H2 19045.2965

### Device

Legion 5 15ARP8

### BIOS version

NDCN09WW

### Which features of the application did you test?

All features work as intended, which is also evidenced by issue [#1134](https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/1134)

### Which features of the application do not work as expected?

All features work as intended, which is also evidenced by issue [#1134](https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/1134)

<img width="863" alt="Capture2" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/48609126/e02094fb-7dd7-4e79-9d7e-11dd50aad92f">
<img width="1279" alt="Capture" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/48609126/f059ed0d-4e84-4e09-a99d-dab68807d07e">

**Comment by preindex** [comment]
<img width="863" alt="Capture2" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/48609126/095cf019-935e-4cc6-8fc6-9cd6c4223386">
<img width="1279" alt="Capture" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/48609126/b7f11e18-adcc-4496-8677-4b081fba89d6">

**Comment by BartoszCichecki** [comment]
The ticket you linked was merged after 2.19 was released. There was a mixup and 15ARP8 want added to the list of compatible devices in 2.19.
