### ISSUE TITLE
LLT的GPU超频开关有点问题

### ISSUE THREAD

**Issue by YR710** [BartoszCichecki/LenovoLegionToolkit#1137]
### Rules

- [ ] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.19.0

### OS

Win11

### Device

Legion R9000P ARX8

### BIOS version

LPCN47WW

### What's wrong?

LLT工具箱的显卡超频开关功能在每次重新启动电脑后会失效，电脑将会是处于超频开启状态。需要在控制台重新开关才会起效。

### How to reproduce the bug?

控制台关闭超频独立显卡，重启电脑后也显示的关闭，但实际上电脑显卡此时是出于开启GPU超频的状态。

### What is the behavior that you expected?

修复此项功能

### Logs

[1_2052.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14033340/1_2052.zip)

**Comment by BartoszCichecki** [comment]
English please

**Comment by YR710** [comment]
The LLT toolkit graphics overclocking switch will not work after each reboot. The software turns off the overclocking but the graphics card will be on when using the computer. It needs to be turned on again in the console.

**Comment by YR710** [comment]
![Uploading 屏幕截图 2024-01-24 205338.png…]()
1
