### ISSUE TITLE
The GPU overclocking control switch is not working

### ISSUE THREAD

**Issue by YR710** [BartoszCichecki/LenovoLegionToolkit#1140]
### Rules

- [ ] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.19.0

### OS

Windows11 22H2. 22621.2861

### Device

Legion R9000P ARX8

### BIOS version

LPCN47WW

### What's wrong?

The GPU overclocking function control switch fails

### How to reproduce the bug?

Every time the computer restarts.

### What is the behavior that you expected?

fix bug
<img width="1181" alt="屏幕截图 2024-01-24 205338" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/157562289/097f5866-33f9-4b53-be43-4b60c0ce6f96">

### Logs

[1_1033.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14053211/1_1033.zip)

**Comment by BartoszCichecki** [comment]
Not sure if we understand each other correctly. Do you mean you need to enabled "Overclock GPU" every time after restart? Because if that is the case, I can't reproduce the issue you have. Please attach logs from LLT to help resolve the issue. Instruction is in the readme.

**Comment by YR710** [comment]
Each restart requires a switch off to turn off GPU overclocking，If you do not do this, GPU overclocking will be enabled by default.4060GPU default frequency should be 2500MHZE.  Each time the GPU is restarted, the frequency is 2775MHZ, and the overclocking function is not turned on

**Comment by YR710** [comment]
> 不确定我们是否正确理解了对方。您的意思是每次重启后都需要启用“超频GPU”吗？因为如果是这种情况，我无法重现您遇到的问题。请附上 LLT 的日志以帮助解决问题。说明在自述文件中。

Each restart requires a switch off to turn off GPU overclocking，If you do not do this, GPU overclocking will be enabled by default.4060GPU default frequency should be 2500MHZE. Each time the GPU is restarted, the frequency is 2775MHZ, and the overclocking function is not turned on

**Comment by YR710** [comment]
> Not sure if we understand each other correctly. Do you mean you need to enabled "Overclock GPU" every time after restart? Because if that is the case, I can't reproduce the issue you have. Please attach logs from LLT to help resolve the issue. Instruction is in the readme.

I don't know what's going on, but the LOG folder is empty
<img width="780" alt="屏幕截图 2024-01-26 104900" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/157562289/52b3980c-5f7b-4ac5-93d6-76a191151216">

**Comment by YR710** [comment]
> > 不确定我们是否正确理解了对方。您的意思是每次重启后都需要启用“超频GPU”吗？因为如果是这种情况，我无法重现您遇到的问题。请附上 LLT 的日志以帮助解决问题。说明在自述文件中。
> 
> Each restart requires a switch off to turn off GPU overclocking，If you do not do this, GPU overclocking will be enabled by default.4060GPU default frequency should be 2500MHZE. Each time the GPU is restarted, the frequency is 2775MHZ, and the overclocking function is not turned on

GPU overclocking is not turned on but the frequency is 2775MHZ
<img width="1181" alt="屏幕截图 2024-01-24 205339" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/157562289/ccc15681-5974-439f-a211-f0ea48f58dca">

**Comment by BartoszCichecki** [comment]
If the OC is not on, then it isn't on. Educate yourself on how GPU clocks work, especially the boost part before reporting "issues" next time.
