### ISSUE TITLE
New Actions Trigger to detect IO devices

### ISSUE THREAD

**Issue by Pretentiousness** [BartoszCichecki/LenovoLegionToolkit#1143]
### Rules

- [x] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.19.0

### OS

Windows 11 22h2

### Device

Legion 7 16ITHg6

### Is your feature request related to a problem?

a trigger whenever a new IO device is connected like a flash drive, Bluetooth or wired speaker, headphones can be very helpful.

### How would you like the problem to be solved?

If there is a trigger then i can set actions to close certain app and restart it, some apps like openRGB dont detect new speakers etc without a proper restart so it will help there.

### What alternatives have you considered?

use python scripts but its janky

### Additional information

i use my laptop with multiple Bluetooth headsets, keyboards and having stuff run or close when you connect them is very helpful.

**Comment by BartoszCichecki** [comment]
You want these to trigger when a specific device is connected? How to filter them? By type? Name?

**Comment by Pretentiousness** [comment]
> You want these to trigger when a specific device is connected? How to filter them? By type? Name?

For my use - case detection by "type" would be more beneficial. type as in speakers, keyboards, mouse, headsets, monitors, controllers etc etc. by name can also work but then I will have to create multiple actions for every single one of them.  I am fine with either of them you can do whatever is easier to implement.

**Comment by Ekscentricitet** [comment]
That can be cool! My use case would be to set a predefined Game Mode when I connect a controller. Would it be possible to actually detect if you connected more than 1 devices of the same type? For my particular example, if I connect one controller it means I am playing single player games but if I connect multiple it means I am probably playing with somebody else. This is not the most exciting use case and might not be worth the implementation effort, but just throwing it out there as an idea.

**Comment by Pretentiousness** [comment]
> You want these to trigger when a specific device is connected? How to filter them? By type? Name?

Also to trigger when they get disconnected. a minor thing but important to mention.
