### ISSUE TITLE
cpu/gpu performance panel when game is on

### ISSUE THREAD

**Issue by vanthq** [BartoszCichecki/LenovoLegionToolkit#1144]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows10 

### Device

Legion5 Pro

### Is your feature request related to a problem?

only if not confilict with the game

### How would you like the problem to be solved?

when game is on ,the performance is always on the top

### What alternatives have you considered?

no

**Comment by BartoszCichecki** [comment]
Please update the issue with more detailed description. Otherwise, the issue will be closed.

**Comment by vanthq** [comment]
add a switch when turned  on,the cpu/gpu performance information could be displayed on the top of all the game on,locating upper left corner,including cpu/gpu tempurture, frequency，usage percentage etc.It was first found in the legion zone.A little trick but once the llt owned the function,the legion zone can be uninstalled.

**Comment by BartoszCichecki** [comment]
It seems like most people would use RTSS for more advanced overlays like this or Xbox game bar for more basic ones. 

I fail to see why would I duplicate such functionality, especially that I wouldn't be better in any way.

**Comment by vanthq** [comment]
we all know there exists too many Lenovo manager apps so i wish to have all-in-one app.Anyway，thanks for your replying
