### ISSUE TITLE
[Gen 9] Hotkeys like Fn+F4 don't work

### ISSUE THREAD

**Issue by nathanlcl** [BartoszCichecki/LenovoLegionToolkit#1158]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.0

### OS

Windows 11 23H2 22631.2861

### Device

Legion Y7000P IRX9 (2024)	MP2MLMDJ

### BIOS version

NMCN19WW

### What's wrong?

After letting the LLT take over the function keys, that is, after disabling Lenovo Hotkeys, the Fn+F4 key cannot control the microphone switch, but it can be controlled normally and there is a pop-up prompt before taking over.

### How to reproduce the bug?

Appears immediately after the takeover.

### What is the behavior that you expected?

Turn the microphone on and off normally

### Logs

[log_2024_02_06_02_04_07.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14173858/log_2024_02_06_02_04_07.txt)

### Additional information

Those Lenovo software installed: Legion Zone, Lenovo Hotkeys
Those Lenovo software are disabled: Legion Zone, Lenovo Hotkeys

**Comment by BartoszCichecki** [comment]
Can you also check Fn+F8, Fn+F10 and Fn+Space? If they don't work please also upload logs, just name the files in a way that I can tell them apart.

**Comment by nathanlcl** [comment]
Fn+F8 don't work, Fn+Space don't have notification （I've turned on this feature） and Fn+F10 work.
[log_2024_02_06_02_54_59.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14174134/log_2024_02_06_02_54_59.txt)

**Comment by BartoszCichecki** [comment]
Could you upload separate logs for each of the Fn keys and give them pretty names so I know which one is which one?

**Comment by nathanlcl** [comment]
[Fn+Esc.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14174241/Fn%2BEsc.txt)
[Fn+F4.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14174242/Fn%2BF4.txt)
[Fn+F8.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14174243/Fn%2BF8.txt)
[Fn+F10.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14174244/Fn%2BF10.txt)
[Fn+Space.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14174246/Fn%2BSpace.txt)
[NumLock.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14174247/NumLock.txt)

I hope I didn't misunderstand what you meant.

**Comment by BartoszCichecki** [comment]
You can download a test build from [here](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/7803822992/artifacts/1224499504) and see if this build handles Fn+F4, Fn+F8 and Fn+Space correctly. Let me know the results.

**Comment by nathanlcl** [comment]
The Fn+F4 and Fn+Space are work, but the Fn+F8 only opens the settings, it does not turn airplane mode on or off.
[Fn+F8-2.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14188346/Fn%2BF8-2.txt)

**Comment by BartoszCichecki** [comment]
I am glad it works. Currently there is no public API to turn on/off Airplane Mode in Windows, so opening settings is the only reliable way. What Lenovo did in their Hotkeys app is a flaky hack.
