### ISSUE TITLE
Custom Fan Control

### ISSUE THREAD

**Issue by QuanKLA** [BartoszCichecki/LenovoLegionToolkit#1160]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.0

### OS

Windows 11 22H2 22621.3007

### Device

15aph8 LOQ

### BIOS version

LYCN40WW

### What's wrong?

In the Fan Control in custom settings.

If you move the second slider down to lowest(same position as first) and leave all sliders in defauly spots. The fan RPM drops to 0 when saved (fans visibily stopped too) and they never increase in RPM until the second fan slider is put back up. I thought about using it as a 0rpm feature on the laptop and discovered it.

I quickly used CPUz benchmark to raise cpu temps up to 75degrees before manually stopping and fans never turned on until changing that second slider.

### How to reproduce the bug?

Set first custom fan slider to lowest. Set second fan slider to lowest. Rest of sliders as default. Save. Fan RPM goes to 0/Fans stop spinning.

### What is the behavior that you expected?

Execpected fans to stop for a 0rpm mode. But possibly they may only run at lowest rpm (1400)

### Logs

[log_2024_02_06_17_40_09.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14184246/log_2024_02_06_17_40_09.txt)

**Comment by BartoszCichecki** [comment]
Unfortunately this isn't something I can fix. Looking at logs, fan table is set correctly, but if EC doesn't spin up the fans as needed it's Lenovo's bug.
