### ISSUE TITLE
Dynamic gpu switch feature(to switch gpus without needing to restart)

### ISSUE THREAD

**Issue by GH-NNG** [BartoszCichecki/LenovoLegionToolkit#1166]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.1

### OS

Windows 11 23H2 build 22631.3085

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

Advanced optimus / Smart Access Graphics / or the feature to dynamically switch gpus without needing to restart has been available in all intel variants and amd non pro variants since 2020 or 2021.
Can it be possible to allow to dynamically switch between the gpus, since mux is available anyways.
It is really a hassle to always restart for a game, i do want best performance and less heat in every game scenario which the direct dgpu conenction provides.

### How would you like the problem to be solved?

There are many requests of 2021 to 2023 users in lenovo forums etc.
But they give the most dissappointing answers,
I wont feel sad if this feature cannot be made to work here.
Thanks for the app legion toolkit app anyways.
Will forcing gpu switch cause any problems if that can be implemented, however the display will turn black or flicker during the switch. So..

### What alternatives have you considered?

no alternatives i can think of as of now

**Comment by BartoszCichecki** [comment]
If your laptop doesn't have Advanced Optimus, you need to restart. There is no way around it.
