### ISSUE TITLE
The notice "dGPU Connected" continuously pop up when AC adapter connected.

### ISSUE THREAD

**Issue by ma0shu** [BartoszCichecki/LenovoLegionToolkit#1172]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 22H2（22621.3085)

### Device

Legion Pro 5 Gen 8 (R9000P in China)

### BIOS version

LPCN47WW

### What's wrong?

The notice "dGPU Connected"("独立显卡已连接") continuously pop up when at dGPU mode (HybridModeState_Off) and AC adapter connected.
![screencapture2](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/61415309/0c639868-dbe9-4235-bb2e-8e9701340ce3)
When I use battery it won't show this.

### How to reproduce the bug?

Plug in AC adapter and wait for about an hour, then open the main window.

### What is the behavior that you expected?

won't show the notice that frequently

### Logs

[log.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14317742/log.txt)
I guess the problem is in line 350?
`[17/02/2024 04:36:30.771] [27] [PowerStateListener.cs#83:SystemEvents_PowerModeChanged] Event received: StatusChange
`

### Additional information

1> When I open Winndows Settings App > System > Power & battery, the Settings App will crash immediately. I don't know why and I can't find solution anywhere. Is it related to this?
2> The background CPU usage is somehow high. Maybe it's also related to this.

**Comment by BartoszCichecki** [comment]
This popup appears when Windows reports that dGPU was connected to the system. So if it happens like in your gif something is wrong with either your windows or your laptop.
