### ISSUE TITLE
Turn off screem sends the computer to hibernation instead of working with the screen off

### ISSUE THREAD

**Issue by Wittusus** [BartoszCichecki/LenovoLegionToolkit#1174]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 Home 10.0.22631 build 22631

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN59WW

### What's wrong?

When I click the "turn off displays" option, it sends the computer to sleep/hibernation, turning off all fans and not doing any work in that time. Sorry if it's the intended use, I thought it was just for turning off the screen so the computer can do it's work while not in use.

### How to reproduce the bug?

1. Go to the home tab
2. Click "turn off" button in the "Turn off displays" panel

### What is the behavior that you expected?

I expected the laptop to work as earlier, just with the screen being black instead.

### Logs

[log_2024_02_18_11_09_29.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14322220/log_2024_02_18_11_09_29.txt)

**Comment by BartoszCichecki** [comment]
It is a standard Windows message that is used to turn of screens called 'SC_MONITORPOWER' as per [documentation](https://learn.microsoft.com/en-us/windows/win32/menurc/wm-syscommand) it just turns off the screen and nothing more. 

It might be down to your setting in Windows to hibernate or sleep when monitor is off, but that is something you need to figure out.
