### ISSUE TITLE
As shown in the figure

### ISSUE THREAD

**Issue by jad686** [BartoszCichecki/LenovoLegionToolkit#1175]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 10 企业版 LTSC 21H2

### Device

R9000P 2021

### BIOS version

无

### What's wrong?

<img width="810" alt="屏幕截图 2024-02-22 165753" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/55620918/b388670f-c839-4f29-8a77-50ccc94296e8">
<img width="773" alt="屏幕截图 2024-02-22 165912" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/55620918/ecc1fb0b-0ac1-4dcf-94d2-82279da2c6d8">

### How to reproduce the bug?

每次打开都这样

### What is the behavior that you expected?

帮我提供一下解决的办法

### Logs

无

### Additional information

无

**Comment by BartoszCichecki** [comment]
Issues should be reported in English.
