### ISSUE TITLE
Hybrid-Auto Mode turning off dGPU even when AC is connected, even when using experimental method

### ISSUE THREAD

**Issue by agustinrojo** [BartoszCichecki/LenovoLegionToolkit#1179]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11

### Device

Legion 5 Pro 16ARX8

### BIOS version

LPCN47WW

### What's wrong?

Hybrid-Auto Mode is supposed to give the user's exactly what I want right now, which is to always use dGPU whenever my laptop is connected, right now it's connected and the dGPU is powered off.

### How to reproduce the bug?

Open LLT, Select Hybrid-Auto mode, connect charger, dGPU get's powered on for a bit, and gets powered off again (right now I'm on 77% charge, which is the max it gets)

### What is the behavior that you expected?

I expected the dGPU to always be running when I have my laptop connected to the AC

### Logs

[log_2024_02_23_20_50_29.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14389985/log_2024_02_23_20_50_29.txt)

### Additional information

Thanks for your work!

**Comment by Ekscentricitet** [comment]
Isn't this the expected behaviour if you are not utilizing the GPU? [Reference](https://download.lenovo.com/pccbbs/pubs/legion_s7_16_7/html/en-us/explore_GPUMode.html).

**Comment by BartoszCichecki** [comment]
Yes that is correct. Powered off state is normal even on AC. When on battery Hybrid-Auto will completely disconnect gpu from system so it isn't even visible. Of course assuming it wasn't in use when AC was unplugged.
