### ISSUE TITLE
[FEAT] Random message from a list when an action is triggered

### ISSUE THREAD

**Issue by Ekscentricitet** [BartoszCichecki/LenovoLegionToolkit#1181]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

Latest

### OS

Windows 10

### Device

Legion 5 Pro

### Is your feature request related to a problem?

No.

### How would you like the problem to be solved?

This is quirky but if https://github.com/BartoszCichecki/LenovoLegionToolkit/pull/1178 gets accepted I realized it could be used to trick the brain into learning new stuff with random notifications. For example, you could set an action every 5 minutes to trigger your keyboard backlight and display a message with some word in a language you are trying to learn or a new shortcut you forget to use. You could also put random messages to not get bored by the same notification. The WiFi Connected trigger already implements a list of strings. There can be a new "Random notification" step that uses the same configuration. I can implement it if the configuration for triggers can be used in steps and you think it is not going too far. If it is not so straightforward - leave it. Would it also be possible to customize the amount of time the dialog is displayed?

### What alternatives have you considered?

You can also simply change the message yourself when you learn what you were trying to learn.

**Comment by BartoszCichecki** [comment]
I get the idea, however I think it might be a little bit too specific (and therefore out of scope of this project).

However, since it is already possible to run scripts and show custom notifications, what could be added is saving the output of a whatever is ran in the Run step (like a script returning a random string) into a variable and then this variable could be used inside a custom notification.

What do you think?

**Comment by Ekscentricitet** [comment]
That should work. It can also be useful for other purposes (you can use it to check if your custom script worked as expected). Good idea.
