### ISSUE TITLE
 Request to add BIOS support，y9000p 2023 test machine

### ISSUE THREAD

**Issue by leeleekee** [BartoszCichecki/LenovoLegionToolkit#1183]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.20.2

### OS

Windows 11 	23H2  22631.3155

### Device

Legion Pro 5 16IRX8

### BIOS version

KWCN12WW

### Which features of the application did you test?

Unable to use custom functions，can't control fan speed

### Which features of the application do not work as expected?

BIOS version is not support

### Additional information

This is an test machine，not an official version

**Comment by BartoszCichecki** [comment]
Logs are missing

**Comment by leeleekee** [comment]
[log_2024_02_25_16_05_04.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14396941/log_2024_02_25_16_05_04.txt)
is this ok？

**Comment by BartoszCichecki** [comment]
Ok so what is not working? Custom mode is supported on your laptop.

**Comment by leeleekee** [comment]
> 好的，那么什么不起作用呢？您的笔记本电脑支持自定义模式。

I guess it's because of the BIOS version？it like some kind of customized version，I can’t upgrade to the latest version，

**Comment by BartoszCichecki** [comment]
I don't understand what you are saying. What isn't working?

**Comment by leeleekee** [comment]
> I don't understand what you are saying. What isn't working?

legion zone can use custom mode，but the minimum fan speed is 2000 rpm，can't adjust it lower，it's a bit noisy
<img width="594" alt="屏幕截图 2024-02-26 002641" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/161231747/5e74e6d9-8bbc-492d-a5d6-f90d8cb6c1d2">

**Comment by BartoszCichecki** [comment]
I can see that LLT can't load custom mode info that is needed. The only option is to update to a more recent version of BIOS. But if you say it's a "test machine" which I understand is some sort of pre-release engineering sample, and you can update BIOS, I can't fix it.

Also, you probably won't be able to set fans lower than ~2000RPM anyway.

**Comment by leeleekee** [comment]
> I can see that LLT can't load custom mode info that is needed. The only option is to update to a more recent version of BIOS. But if you say it's a "test machine" which I understand is some sort of pre-release engineering sample, and you can update BIOS, I can't fix it.
> 
> Also, you probably won't be able to set fans lower than ~2000RPM anyway.

got it，thank you
