### ISSUE TITLE
Touchpad Lock won't stay disabled after resuming PC from hibernation

### ISSUE THREAD

**Issue by marslu87** [BartoszCichecki/LenovoLegionToolkit#1190]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 Home 22621.3155

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN51WW

### What's wrong?

Whenever I disable the Touchpad Lock, it resets to enabled when I wake my PC from hibernation. Windows Settings for the touchpad are currently set to leave touchpad on with a mouse connected:
<img width="770" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/161613824/646daf67-3b47-484d-9886-3dc1078dfc5b">

### How to reproduce the bug?

1. Go to Lenovo Legion Toolkit dashboard
2. Disable Touchpad Lock
3. Close out of Lenovo Legion Toolkit
4. Put PC in hibernation
5. Turn PC on
6. Open Lenovo Legion Toolkit
7. Have to manually disable Touchpad Lock since it doesn't remember previous setting

### What is the behavior that you expected?

I expect Lenovo Legion Toolkit to remember the previous Touchpad Lock settings with each session.

### Logs

[log_2024_02_28_15_04_09.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14435900/log_2024_02_28_15_04_09.txt)

**Comment by BartoszCichecki** [comment]
> I expect Lenovo Legion Toolkit to remember

That is a fair expectation, but these settings are actually stored in EC/BIOS, so that is up to Lenovo to fix them - I can't "fix it". But you just gave me an idea to investigate if "resume form sleep/hibernate" could be added to Actions, which would effectively give you an option to create a workaround - I will investigate this separately.

FYI: the "Windows settings" touchpad lock is completely separate from Lenovo's implementation.

**Comment by marslu87** [comment]
Thanks. I figured it was a separate setting but wanted to include just in case it affected the toolkit settings somehow. I like that workaround idea! Thank you for investigating.
