### ISSUE TITLE
快捷按钮不能一键开启飞行模式

### ISSUE THREAD

**Issue by mzxwt** [BartoszCichecki/LenovoLegionToolkit#1198]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 23H2

### Device

拯救者R9000X 2023 （AMD 7840H）

### BIOS version

M1CN37WW

### What's wrong?

使用Legion tool kits替代原来Hotkeys后，按Fn+F8后不能直接开启飞行模式，而是跳转到设置界面
![屏幕截图 2024-03-02 162910](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/26818282/2b14d30c-7c31-42e7-b62b-a959a73610b3)

### How to reproduce the bug?

See error

### What is the behavior that you expected?

点按快捷键后直接开启飞行模式

### Logs

No logs

**Comment by BartoszCichecki** [comment]
English please.
