### ISSUE TITLE
Smart fn lock interfering with games

### ISSUE THREAD

**Issue by rp1231** [BartoszCichecki/LenovoLegionToolkit#1199]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 Home 23H2

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN63WW

### What's wrong?

When playing the Dead Cells game, the Smart Fn lock interferes with the game.

### How to reproduce the bug?

1. Set smartfn lock to the `Shift, Ctrl, Alt` option.
2. Play the Dead Cells game and press Shift to roll
3. The game will lag when pressing either Shift or Ctrl (Both of which are default for the rolling action in the game)

### What is the behavior that you expected?

The game should not lag

### Logs

Let me know if a log is required for this problem.
Also on a side note , the Readme is not linked in the bug report form.

**Comment by BartoszCichecki** [comment]
Read the FAQ. If you encounter stuttering when Fn Lock is toggled, disable it while in games

**Comment by BartoszCichecki** [comment]
> Would save people troubleshooting a lot of time.

People would save a lot of time troubleshooting, if they read the readme.

> After turning that off, the problems with the stuttering in games vanished even with smart fn on.

Will add this to readme.
