### ISSUE TITLE
Battery mode changes from conservation to normal after restart

### ISSUE THREAD

**Issue by user2852** [BartoszCichecki/LenovoLegionToolkit#120]
**Describe the bug**
Hello, this is similar to issue #112 I was keeping an eye on that because I have noticed the same kind of thing on occasion whereby the battery mode will change from Conservation Mode to Normal Mode after a restart. 

I pretty much always use Conservation Mode so it's very clear when it has happened since the battery fills up. It's pretty rare, and I've only noticed it when restarting after disabling Hybrid Mode.

I see you've closed that now, but I didn't comment because in that thread you asked for logs, and since it doesn't happen often I couldn't add anything. However, I _think_ I may have some logs and hoping they may help solve it, maybe?

**To Reproduce**
1. Open LegionToolkit
2. Disable Hybrid Mode (may also happen when enabling Hybrid, but I don't recall that happening to me)
3. Restart
4. Check LegionToolkit, Battery Mode has changed to "Normal"

**Expected behavior**

Selected Battery Mode should persist after restarting

**Environment (please complete the following information):**
 - OS: Windows 10 21H1 19043.1766
 - Laptop model: Legion 5 15ARH05H Type 82B1
 - BIOS: FSCN18WW
 - .NET version: 4.8.4084.0
 - Do you have Vantage installed? Yes, but disabled

**Logs**
Log 1: This is the log when changing the settings **before** restarting i.e. disabling Hybrid, enabling Overdrive:

[log_2022_06_23_13_08_00.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/8967360/log_2022_06_23_13_08_00.txt)

Log 2: This is the log **after** restarting, checking LegionToolkit and seeing battery mode had indeed changed from Conservation Mode to Normal Mode:

[log_2022_06_23_13_10_03.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/8967393/log_2022_06_23_13_10_03.txt)

Also, if it matters, before changing the settings I was using Quiet Mode and balanced power plan. Battery was about 25-30% charged? That's a guesstimate though.

Sorry if all that is a bit long. Hope it helps.

Thanks for the great tool!

Regards.

**Comment by BartoszCichecki** [comment]
Thanks for detailed description!

Unfortunately these perks are at Lenovo's fault unfortunately. Sometimes BIOS settings change on their own, so there is nothing I can do about it to properly fix it.

However, in the next release you will be able to configure "Actions". For example you will be able to set, that whenever laptop is connected/on AC power, set the Battery mode to "Conservation".

I hope this will help - that's the only thing I can do.
