### ISSUE TITLE
Not minimizing to tray after boot-up

### ISSUE THREAD

**Issue by Yooupi** [BartoszCichecki/LenovoLegionToolkit#1202]
Rules
 I made myself familiar with the README.
 I checked closed issues for similar ones and did not find a similar problem mentioned before.
 I understand that, if insufficient information was provided, my issue will be closed without an answer.
Version
2.20.2

OS
Windows 11 23H2 22631.3235

Device
Legion Y9000P IAH7H

BIOS version
J2CN56WW

What's wrong?
It doesn't minimize to the tray after booting up, but it's working in the task manager, and it just doesn't show up in the tray. This bug occurred after I updated to the latest Windows 11 system. And Restarting Windows Explorer doesn't work.
Note: It will be fine after uninstalling the latest Windows 11 update KB5034848.

How to reproduce the bug?
This happens after booting up

What is the behavior that you expected?
I wish it would show up in the system tray, so it would be easier to use.

Logs
no log, because it isn't a mistake, it just doesn't show in the tray.

Additional information
No response

**Comment by BartoszCichecki** [comment]
22631 is an insider preview build. Please do not report issues with beta builds of Windows here, but to MS.
