### ISSUE TITLE
Unexpected Exception Occurred and Crashed

### ISSUE THREAD

**Issue by PeaceFull05** [BartoszCichecki/LenovoLegionToolkit#1203]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 23H2

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN63WW

### What's wrong?

Out of nowhere, LLT gave me two warning saying something unexpected happened, and then it proceeded to crash.
<img width="674" alt="LLT Error 2" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/162044617/e75528c8-09ee-482e-948e-a0ac3bbb8fc7">
<img width="310" alt="LLT Error why" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/162044617/68f2129d-cd85-4bf1-9612-b5f3ca0c646c">

### How to reproduce the bug?

I am not sure as it happened out of nowhere.

### What is the behavior that you expected?

After seeing those errors I figured it would crash as well, and I had to restart it.

### Logs

I am not able to reproduce the bug, as it came out of nowhere, as previously stated.

### Additional information

<img width="674" alt="LLT Error 2" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/162044617/5d4182a0-7609-4e72-a724-b917f37582f8">
<img width="310" alt="LLT Error why" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/162044617/08d37ed1-9dfe-4b20-9a37-4e37ec632d73">

Not familiar with github and not sure if screenshots were uploaded so I pasted them here again. I only see text.

**Comment by PeaceFull05** [comment]
Also I am worried this error caused issues or corrupted files with LLT so is it preferable to reinstall it fully?

**Comment by BartoszCichecki** [comment]
> I am not sure as it happened out of nowhere.

Thanks for reporting, however if it can't be reproduced, I can only classify it as "shit happens" sometimes. If there are steps to reproduce it, I can revisit the issue.

> this error caused issues or corrupted files

Unlikely.
