### ISSUE TITLE
it not work well on legion y9000p 2024 14900hx

### ISSUE THREAD

**Issue by tamakiramimy** [BartoszCichecki/LenovoLegionToolkit#1205]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.20.2

### OS

win11 22h2

### Device

legion y9000p 2024 14900hx

### BIOS version

N0CN17WW

### Which features of the application did you test?

custom mode all cpu and gpu function
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/29190190/dbf7c71f-e17a-416f-8bca-ee11beb38431)
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/29190190/96daea72-7571-409a-bd17-9eb1e832be5b)
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/29190190/3b23e2bc-1ad9-42bd-96f1-3ef6803d0a5e)

### Which features of the application do not work as expected?

None of the above functions work

**Comment by BartoszCichecki** [comment]
1. Logs are missing
2. Description is missing
