### ISSUE TITLE
Fan reversing for dust cleaning

### ISSUE THREAD

**Issue by ZHQ-R6Qc** [BartoszCichecki/LenovoLegionToolkit#1211]
### Rules

- [X] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.1

### OS

Windows 10 22H2 19045.4046

### Device

Legion R9000P ARX8

### Is your feature request related to a problem?

I hope I can clean my cooling fans without disassembling.

### How would you like the problem to be solved?

Would you add a feature to make fans rotating in reverse so that they can blow away dust sticking on the inlet?

### What alternatives have you considered?

Or should I just buy a vacuum cleaner?

**Comment by BartoszCichecki** [comment]
Not possible
