### ISSUE TITLE
Notification popups flash white when darkmode is enabled

### ISSUE THREAD

**Issue by TinyTerra** [BartoszCichecki/LenovoLegionToolkit#1212]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 Home 23H2 build 22631

### Device

Legion Pro 7 16IRX8H

### BIOS version

KWCN42WW

### What's wrong?

Notification popups flash white when darkmode is enabled

### How to reproduce the bug?

1. Go to Settings
2. Set theme to Dark
3. Go to Notifications
4. Enable Caps/Num lock notifications
5. Press Caps Lock or Num Lock

### What is the behavior that you expected?

The notification pops up and has a persistent dark colour

### Logs

[log_2024_03_05_10_19_47.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14493827/log_2024_03_05_10_19_47.txt)

**Comment by BartoszCichecki** [comment]
I can't reproduce this on my laptop, but if someone can and wants to have a shot at this, be my guest.

**Comment by BartoszCichecki** [comment]
I don't see any other comments after a month since this issue is reported. Because of this, and because I can't reproduce it on my laptop, there isn't anything I can do.
