### ISSUE TITLE
Conservation Mode set in app but not taking effect

### ISSUE THREAD

**Issue by melterx12** [BartoszCichecki/LenovoLegionToolkit#1213]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 23H2 Build 22631

### Device

Legion Slim 5 14APH8

### BIOS version

MACN24WW

### What's wrong?

Conservation mode is set in the legion toolkit app, but battery is being charged to 100%. When I had vantage installed this setting capped the charge level at 80%.

### How to reproduce the bug?

Set conservation mode to on in the app. Toggling on and off seems to have no effect either.

### What is the behavior that you expected?

Conservation mode should prevent the battery from charging beyond 80%

### Logs

[log_2024_03_06_12_56_36.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14510183/log_2024_03_06_12_56_36.txt)

**Comment by BartoszCichecki** [comment]
If you turn on conservation mode below 80% and it still charges to full, perform EC reset. Instructions can be found on Discord linked in the readme.
