### ISSUE TITLE
 Toolkit is suitable for the Thinkbook series, please cancel the “not suitable for your devices” message dialog at the start up.

### ISSUE THREAD

**Issue by EcstasyGu** [BartoszCichecki/LenovoLegionToolkit#1218]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 22H2 22621.3235

### Device

Thinkbook14+ 2024 ultra7 with RTX4060 (ThinkBook 14 G6+ IMH)

### Is your feature request related to a problem?

Thanks for providing the Toolkit！
I ve tried it on my Thinkbook14+ 2024 ultra7 with RTX4060 laptop，and find it is fine and function well，
The only problem is that the prompt message at the start up，could this be canceled？and the log button is always on.
I know that this Toolkit is not develop for the thinkbook series，but it is good at my device，so the Toolkit suitable for the Thinkbook series. 

### How would you like the problem to be solved?

please cancel the “not suitable for your devices” message dialog at the start up.

### What alternatives have you considered?

the toolkit is make for the legion series，but also suitable for the thinkbook series，that is really good for the Lenovo laptop user

**Comment by BartoszCichecki** [comment]
If it works that's good for you but as readme states, other devices aren't officially supported.
