### ISSUE TITLE
Can't fetch drivers

### ISSUE THREAD

**Issue by jxipaul** [BartoszCichecki/LenovoLegionToolkit#1225]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 23H2 build 22631.3296

### Device

Legion 5 15ACH6H

### BIOS version

GKCN60WW

### What's wrong?

Like the title suggests, clicking on refresh in the downloads section of the app results in this error:
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/80208139/09824b16-c0cc-4d7d-8a18-c743b9569134)
Hasn't been working for some versions now for me.

### How to reproduce the bug?

1. Go to Downloads
2. Click on Refresh

### What is the behavior that you expected?

It fetches updates to the drivers

### Logs

[log_2024_03_14_15_30_55.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14604538/log_2024_03_14_15_30_55.txt)

**Comment by BartoszCichecki** [comment]
Reinstall .NET. For some reason it broke on your laptop.

**Comment by jxipaul** [comment]
Welp, I can't reinstall .NET, because it says that it is already installed on my computer even though I uninstalled it from control panel.
