### ISSUE TITLE
Add a menu with all setting without having to add them to dashboard

### ISSUE THREAD

**Issue by Quenom** [BartoszCichecki/LenovoLegionToolkit#1227]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11

### Device

16ACH6H

### Is your feature request related to a problem?

There are setting that i dont change often but sometimes there is a need to, i also want a clean dashboard without having to scroll.

### How would you like the problem to be solved?

A button on the left under downloads with all setting from dashboard accessible
Alternatively hide that inside existing settings menu

### What alternatives have you considered?

manually adding setting to dashboard, setting it, and immediately removing it from dashboard

**Comment by BartoszCichecki** [comment]
I don't really see how it would be useful to have a list with 20 items. If you use these items, just put them on the Dashboard.
