### ISSUE TITLE
Lack of Manual Fan Control in Legion 9

### ISSUE THREAD

**Issue by Rintarou227** [BartoszCichecki/LenovoLegionToolkit#1235]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 22H2

### Device

Legion 9 

### BIOS version

MHCN33WW

### What's wrong?

Lack of Legion 9 Fan Control within Custom Mode

### How to reproduce the bug?

1: Go to Power Mode
2: Click on cog to access additional custom options
3: Scroll Down to the Fan Menu 
4: Only Max Fans are present

### What is the behavior that you expected?

When I scroll down to the Fans Menu, only Max Fans are present

### Logs

[log_2024_04_05_05_24_20.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14880247/log_2024_04_05_05_24_20.txt)

### Additional information

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/166098267/f4b44740-198b-4036-b631-570181a807cb)

**Comment by BartoszCichecki** [comment]
Thanks!

It looks like LLT discards the fan table, because there is an extra, 4th sensor, in the fan table that is currently unknown:

```
Type: CPU, FanId: 1, SensorId: 4, FanSpeeds: [1900, 2000, 2400, 2600, 2900, 3400, 3600, 4000, 4500, 5400], Temps: [52, 55, 58, 61, 65, 72, 76, 80, 84, 86]
Type: CPUSensor, FanId: 1, SensorId: 1, FanSpeeds: [1900, 2000, 2400, 2600, 2900, 3400, 3600, 4000, 4500, 5400], Temps: [46, 49, 127, 127, 127, 127, 127, 127, 127, 127]
Type: GPU, FanId: 2, SensorId: 5, FanSpeeds: [1900, 2000, 2200, 2500, 2900, 3400, 3700, 4100, 4500, 5400], Temps: [55, 58, 62, 64, 67, 73, 75, 78, 81, 83]
Type: Unknown, FanId: 3, SensorId: 5, FanSpeeds: [0, 3000, 2500, 2900, 0, 3600, 3800, 4100, 5200, 9000], Temps: [55, 58, 62, 64, 67, 73, 75, 78, 81, 83]
```

I need to do some digging, to check what is it for, but otherwise it should be a quick and easy fix to add it.

**Comment by BartoszCichecki** [comment]
Here is a test build: [installer](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/8575083115/artifacts/1389580475) let me know if you can now adjust fan speeds.
