### ISSUE TITLE
Extremely high CPU usage on "Services and Controller App" in Keyboard tab + not decreasing if switched quickly

### ISSUE THREAD

**Issue by RegorForgot** [BartoszCichecki/LenovoLegionToolkit#1239]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.0 Beta 3 (but present on 2.20.0 and perhaps prior)

### OS

W11H 23H2 22631.3296

### Device

Legion Slim 7i Gen 8 (82Y3)

### BIOS version

M0CN33WW

### What's wrong?

When the program is switched to the Keyboards tab (my unit has a Spectrum keyboard), the fans spin up rapidly, and services.exe uses a very high amount of CPU (10%+ on a 13700H). Doing actions such as changing the backlight or mode increases this value even further. Rapidly switching modes, I got this value up to 50% (!!!). Changing the tab or closing the app takes the cpu usage down to 0% again.

Moreover, if the keyboard tab is opened, and the user changes the tab just as it loads, the application does not detect this and it keeps querying services.exe even if the app window is closed. This is only paused if the user switches back into the keyboard tab, the user waits, and then closes the window.

It does this even with a clean reconfiguration (removing files in the Data redirectory and resetting the user data).

From a glance at the trace file recorded below it seems to be calling AbstractSoftwareDisabler.GetStatusAsync() constantly causing the issue

### How to reproduce the bug?

See above

### What is the behavior that you expected?

Reduced number of calls to services.exe, and program to detect when user switches out of tab to stop the querying of services.exe rather than continuing.

### Logs

No error log, but a trace log from running TRACE mode within IDE:
[log_2024_04_06_13_05_56.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14893631/log_2024_04_06_13_05_56.txt)

I turned on the app, quickly switched the keyboard tab in and out, closed the window (all the while services.exe is under constant load), and it only reduced after i reopened the window and switched back into the keyboards tab, and out again.

### Additional information

I realise this is an edge case, but it caused me issues a while ago due to the immense battery drain because of it (something like -15W on top) from all the calls, and I only found the cause now.

**Comment by RegorForgot** [comment]
![rider64_ngubikognq](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/55347112/68d2f183-7454-4ad9-9146-9d6d67c6ae48)

**Comment by BartoszCichecki** [comment]
Nice catch! Not sure why the CPU is spiking so much (can't reproduce that part), but I did some optimizations. Check out [the build](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/8582855536/artifacts/1390954930) and let me know if that helped.

**Comment by RegorForgot** [comment]
Awesome! That seems to have fixed the issue with the high idle power usage, as well as the tab change. To replicate the cpu spiking try moving the brightness slider back and forth quickly. I've found that to get up to 100% cpu usage (completely max my laptop's CPU), so might be worth investigating. Even the tab is a little bit more responsive to open now! Though when I originally opened it it did take a few seconds for the actual keyboard lights to show up on screen.

**Comment by RegorForgot** [comment]
Further observations about the lights not showing up on startup :
- using spacebar to change the mode is not enough to get the lights to show up
- neither is adjusting the brightness using the arrow keys
- adjusting the mode, or the brightness down to 0 then back up *through the app* did work to get the lights on the application to show up

**Comment by BartoszCichecki** [comment]
Yeah, just noticed that too. Will fix it and post new beta on discord.
