### ISSUE TITLE
Legion 7 16ACHG6 Device Not Supported Error

### ISSUE THREAD

**Issue by amohanty03** [BartoszCichecki/LenovoLegionToolkit#1241]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11 Home 22H2 Build 22621.3296

### Device

Legion 7 16ACHG6

### BIOS version

GKCN59WW

### What's wrong?

This device is not supported by Legion Toolkit error, it occurred on one random day and has stopped working ever since. Re-install did not fix it. I have not uninstalled anything in particular nor have I updated the BIOS recently. Only updates that have taken place are the Windows updates.

### How to reproduce the bug?

1. Launch Legion Toolkit and the error message pops up.

### What is the behavior that you expected?

The Legion Toolkit service to run as it was working previously.

### Logs

[error_2024_04_07_19_52_22.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14898754/error_2024_04_07_19_52_22.txt)
[error_2024_04_07_19_55_46.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14898755/error_2024_04_07_19_55_46.txt)

**Comment by BartoszCichecki** [comment]
The error indicates issue with WMI services on you laptop - that's the problem.
