### ISSUE TITLE
Backlight enabling after user became active feature stopped working in latest build 2.21.0

### ISSUE THREAD

**Issue by sumitbhowmick** [BartoszCichecki/LenovoLegionToolkit#1245]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.0

### OS

Windows 11 Home Single Language Version 23H2 OS Build 22631.3296

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN59WW

### What's wrong?

The user becomes active state action doesn't get triggered after installation of latest build 2.21.0.

### How to reproduce the bug?

1. Configure LLT Action as follows:
A. When user becomes active - select keyboard backlight profile1 
B. When user becomes inactive for 10 sec - turn off keyboard backlight

2. Do not touch Laptop for 10 sec to become inactive. Observe keyboard backlight turns off
3. Move mouse, but keyboard light doesn't turns back on.

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/25614243/b319ecd5-b886-42a8-8d09-7405ad957bc0)

### What is the behavior that you expected?

The Keyboard backlight should turn back on, as per configuration when mouse is moved/key pressed.

### Logs

[log_2024_04_10_05_50_17.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14927954/log_2024_04_10_05_50_17.txt)

### Additional information

My understanding from Log File:
Logline 380: User inactive state triggered.
Line 397: Keyboard turns off successfully.
Line 403: User active state detected
Line 418: Preset off <--- wrong info, probably because of exception in Line 298

Please note that, the white backlight enablement action works fine when power is restored (same action configured), but doesn't work for user became active scenario.

**Comment by BartoszCichecki** [comment]
Resolved in d7302cc6e92ad75515b69afb28e8685e81e97e31
