### ISSUE TITLE
Scoop installer is not working for dotnet-sdk

### ISSUE THREAD

**Issue by rchoc** [BartoszCichecki/LenovoLegionToolkit#1247]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.0

### OS

Windows 10 Home 22H2 build 19045

### Device

Legion 5 Pro

### BIOS version

Latest

### What's wrong?

Installation instruction in Readme for `scoop` does not work correctly.
First, latest version requires dotnet 8 SDK, which is available from `main`, so `version` bucket is not required.
Second, even after installing dotnet-sdk with scoop, LLT does not find that and prompt to install again.

### How to reproduce the bug?

1. Ensure dotnet-sdk (any version) is not installed to start with.
2. Copy [lenovolegiontoolkit.json](https://github.com/ScoopInstaller/Extras/blob/051ed65b721e0954c5a0839112000050968107ee/bucket/lenovolegiontoolkit.json) file locally and modify `"depends": "versions/dotnet6-sdk",` line to `"depends": "dotnet-sdk",`
3. Follow readme steps to install with scoop from this local copy
   - scoop bucket add extras
   - scoop install LLT.json
4. Check installation has finished correctly with dependency install
5. Start LLT, it will find no dotnet-sdk and ask to install it from MS website.

### What is the behavior that you expected?

Installation instruction should work if provided. If not, just instruct on high level and not provide specific commands.
The problem is probably with [dotnet-sdk installer via scoop](https://github.com/ScoopInstaller/Main/issues/874), so at least dependency should be corrected in manifest.
As winget instruction does not include dotnet-sdk, maybe it can be skipped for now.

### Logs

```
Installing 'dotnet-sdk' (8.0.204) [64bit] from main bucket
Loading dotnet-sdk-8.0.204-win-x64.zip from cache
Checking hash of dotnet-sdk-8.0.204-win-x64.zip ... ok.
Extracting dotnet-sdk-8.0.204-win-x64.zip ... done.
Linking ~\scoop\apps\dotnet-sdk\current => ~\scoop\apps\dotnet-sdk\8.0.204
'dotnet-sdk' (8.0.204) was installed successfully!
Installing 'LLT' (2.21.0) [64bit]
Loading LenovoLegionToolkitSetup.exe from cache
Checking hash of LenovoLegionToolkitSetup.exe ... ok.
Extracting LenovoLegionToolkitSetup.exe ... done.
Linking ~\scoop\apps\ll\current => ~\scoop\apps\ll\2.21.0
Creating shortcut for Lenovo Legion Toolkit (Lenovo Legion Toolkit.exe)
'LLT' (2.21.0) was installed successfully!
'dotnet-sdk' suggests installing 'extras/vcredist2022'.
```

### Additional information

After deciding what to update in the instruction, manifest file in scoop `extras` bucket has to be updated with correct dependency.

**Comment by BartoszCichecki** [comment]
@YisusChrist can you take a look at this?

**Comment by YisusChrist** [comment]
Hello @rchoc,

I tried to reproduce your issue but it was not possible in my machine (Windows 11 Home 23H2 Build 22631.2861 - Legion Pro 5 16ARX8). I followed your steps and now in pc and I end up having the following information:

```
> dotnet --list-sdks
8.0.204 [C:\ProgramData\Scoop\apps\dotnet-sdk\current\sdk]
```
```
> dotnet --info
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\ProgramData\Scoop\apps\dotnet-sdk\current\sdk\8.0.204\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [C:\ProgramData\Scoop\apps\dotnet-sdk\current\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [C:\ProgramData\Scoop\apps\dotnet-sdk\current\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\ProgramData\Scoop\apps\dotnet-sdk\current\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\ProgramData\Scoop\apps\dotnet-sdk\current\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_ROOT       [C:\ProgramData\Scoop\apps\dotnet-sdk\current]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
```
> scoop list | grep sdk
dotnet-sdk                     | 8.0.204                 | main                           | 2024-04-14 22:00:35 +02:00    |         |
```
```
> scoop list | grep lenovo
lenovolegiontoolkit            | 2.21.0                  | D:\Downloads\lenovolegionto... | 2024-04-14 22:00:37 +02:00    |         |
```

With all of this my LLT installation works flawlessly and the program opens without any issue. I suggest you to take verify that the installation path of dotnet is in your system PATH and try again.

I would also like to ask you about the dotnet 8 SDK requirement that you mentioned. It has always worked for me with both SDK 6 and SDK 8, but I don't find now where it is mentioned that the minimum version is now the SDK 8. Could you provide more information about this?

**Comment by BartoszCichecki** [comment]
> I would also like to ask you about the dotnet 8 SDK requirement that you mentioned. It has always worked for me with both SDK 6 and SDK 8, but I don't find now where it is mentioned that the minimum version is now the SDK 8. Could you provide more information about this?

It is the latest release 2.21.0 that now uses .NET 8. Wasn't aware that scoop will need updates, but will keep it in mind in the future!

**Comment by rchoc** [comment]
Thanks @aliesbelik for updating scoop manifest with dotnet8.

For @BartoszCichecki, if seemed to me like a scoop issue too. Installing dotnet with scoop did not make it available to processes, there were other commands needed to run first to "activate" dotnete. When installing LLT with winget, the installer tries to detect existing dotnet and if needed, it'll run the dotnet downloader+installer, so is a much much better installation experience.

Now after winget install, I am unable to uninstall dotnet (cannot believe there is no uninstaller for dotnet8, someone please correct me) and try with scoop installs. As @YisusChrist could not replicate, I guess for the same uninstall reason, it's probably not worth the trouble any more. Maybe update the readme installation part to remove scoop versions bucket or better, just highlight winget as recommended and scoop as a user preference thing. Your call Bartoz and Yisus.

Thanks for this project though, I am yet to play with it, but it looks way better than Lenovo vantage and free of garbage. Really appreciate you building this. 🙇
