### ISSUE TITLE
 Speaker Mute/Unmute Action 

### ISSUE THREAD

**Issue by SonNguyen75** [BartoszCichecki/LenovoLegionToolkit#1250]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.2

### OS

Windows 11, Version 23H2

### Device

Legion 515ACH6H

### Is your feature request related to a problem?

I have a problem where I want to add an action to connect and disconnect my charger so that I don't accidentally blast open a tab of YouTube I currently have open or any media for that matter. 

### How would you like the problem to be solved?

I want to add a step where you can mute and unmute your speaker when a trigger happened

### What alternatives have you considered?

I have tried some hacky ways with scripts but it didn't work

**Comment by Ace-Radom** [comment]
I'm working on this feature cuz it can also be useful to me. If no progress on this feature's implementation has already been done and the feature itself is accepted ~~(and if I would be able to impement this)~~, I'm happy to open one new PR.

**Comment by Ace-Radom** [comment]
@SonNguyen75 You can check the progress in #1255. If you want, you can also get the test-version installer in the [latest gh action run](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/8724550147) yourself.

There's only one thing I need to know: do you only want to mute/unmute the "system default sound output", or all sound output devices? I only made steps for muting/unmuting the system default sound output, which you can check it here:

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/104905842/f1e10a59-e45f-4f14-9145-d9c6b94dfca4)

Normally it should do its work, but if you have sth using a force-sound-output to another sound output device (another speaker), it won't be muted. Please tell me if you also want to mute all devices: I can add a check-box to the steps.

**Comment by SonNguyen75** [comment]
I just want to mute the default sound output for now but I've installed it and it doesn't seem to work. Maybe we can try all sound output devices then?
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/72625429/678db1ff-10cb-4bc8-8c7c-cfc818278482)

**Comment by Ace-Radom** [comment]
> @Ace-Radom  I just want to mute the default sound output for now but I've installed it and it doesn't seem to work. Maybe we can try all sound output devices then?
> 
> ![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/72625429/678db1ff-10cb-4bc8-8c7c-cfc818278482)

Yes this is an known issue I noticed hours ago. I misunderstood sth yesterday and these two steps actually mute/unmute the first active sound output device, but it's not always the "default" one, depends on personal choice. Some fixes and the step for muting/unmuting all devices are now in progress. I'll try to finish it this night or tomorrow. If there's anything new for you to test I'll let you know.

**Comment by Ace-Radom** [comment]
@SonNguyen75 Status update: could you please test [this build](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/8750035381/artifacts/1428672700) created by the latest gh action run? It's a rework on this feature, so please remove `Mute Speaker` and `Unmute Speaker` from your Action settings before installing the new test build.

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/104905842/adb08030-201f-4809-83b4-83749b2ebd3e)

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/104905842/c9dfcc79-65fd-4220-8963-85be0cfb1457)

You may try both of them: if I haven't misunderstood sth again, they should both work well.

**Comment by SonNguyen75** [comment]
@Ace-Radom Everything seems to be working perfectly right now
