### ISSUE TITLE
Startup Actions for automatic steps in specific stats on LLT startup

### ISSUE THREAD

**Issue by Ace-Radom** [BartoszCichecki/LenovoLegionToolkit#1251]
### Rules

- [X] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.1

### OS

Windows 11 23H2

### Device

Legion R9000p 2021H

### Is your feature request related to a problem?

I bought myself in the past few days a new monitor, and I managed to use Actions to change wallpapers (provided by WallpaperEngine) whenever the external display is connected or disconnected. It works, pretty fine, but it leads to a small problem that these actions won't be triggered if I disconnect the external display when the laptop has already been shutdown. When my open my laptop on the second day in my school, it starts with a "wrong" wallpaper which should be for a dual-screen situation.

Surely I can simply open WallpaperEngine and change the wallpaper by hand, but I think it would be way better if we can do it automatically.

### How would you like the problem to be solved?

It will be cool when we add a new Action period (`Startup Actions`, maybe?) into the LLT automation functions.

In my vision, the Startup Actions is similar to the original Actions, but instead of waiting for signals, it will automatically ask the system the states of selected units of the computer (e.g. is external monitor connected? is power adapter connected?). Briefly, the Startup Actions run automatically on LLT startup, ask for the *physical* states of AC power supply, external monitor, time, dGPU/hybried mode, etc. If the states match the settings in the Startup Actions, LLT runs simply the steps.

I don't think the *software* states such as power mode, resolution, should be added into the Startup Steps, because the states are actually unchangeable during computer shutdown: I'm requesting this feature actually for computer startup. How much triggers should be added into the Startup Actions is questionable and need to be discussed, but I think external monitor, power supply and time should be in any case there.

### What alternatives have you considered?

I tried to write a script and add it into Windows Startup Processes, but...I mean, I'm able to but that's for real too complex as it should be.

### Additional information

If this feature is accepted to add into LLT, I may start to work on it in a few days when I finish my exams in school.

**Comment by BartoszCichecki** [comment]
From what I understand, you could configure 4 actions:

- When external monitor disconnected
- When external monitor connected
- When external monitor disconnected and Startup (using Multiple triggers option)
- When external monitor connected and Startup (using Multiple triggers option)

which would do what you need to do.

**Comment by Ace-Radom** [comment]
Just tested, it works. I didn't consider multiple triggers...sry for this issue and thanks for the suggestions
