### ISSUE TITLE
periodic action with if (another action) or rework the multiple trigger to be either 1 || 2|| 3  or  1&&2&&3 or if(1||2) then 3

### ISSUE THREAD

**Issue by ABdelrahmanAlaa1** [BartoszCichecki/LenovoLegionToolkit#1252]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.1

### OS

win 11 23h2 build 22631.3447

### Device

loq 15irh8

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

it is a feature request, not a problem

### What alternatives have you considered?

creating a batch that runs periodically(task scheduler) and adding a run command in an action which is triggered by the wanted trigger (app/etc) and when the app closes terminates it. 

limitations: 
-triggers cannot be limited to an application
-The task does not end after the trigger ends( app closes, etc..)

**Comment by BartoszCichecki** [comment]
Without some example use cases or reasoning behind this request, I can't really evaluate feasibility of something like this.

**Comment by ABdelrahmanAlaa1** [comment]
well many games have useless garbage collection systems and keep filling page lists so I used a per game tailored page list cleaner to avoid stutters however in only periodic actions it will keep running every chosen interval without any start/stop conditions(other actions like app start /terminate)
