### ISSUE TITLE
The software will flash back and not work properly.

### ISSUE THREAD

**Issue by LiliZeng778** [BartoszCichecki/LenovoLegionToolkit#1253]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.0

### OS

win 11 21h2

### Device

legion R9000P 2021H

### BIOS version

GKCN50WW

### What's wrong?

When I open the software, three seconds later, the software will flash back and will not work properly.  
log's last two lines shows:
[13/04/2024 12:50:49.620] [26] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[13/04/2024 12:50:49.623] [26] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
And then the software crashed.

### How to reproduce the bug?

just open the toolkit.every time.

### What is the behavior that you expected?

i can Normal use this toolkit.

### Logs

[log_2024_04_13_12_50_44.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14973928/log_2024_04_13_12_50_44.txt)

**Comment by BartoszCichecki** [comment]
I don't know what "flash back" means, but the log does not include any information about the issue an without this information, I cannot do much. You are also not on latest LLT version, so try to update and see if it still happens.

**Comment by LiliZeng778** [comment]
sorry,"flash back" means "crash".When I open the software, it crashes in three seconds. Even if I update to the latest version, it crashes.

**Comment by BartoszCichecki** [comment]
Do you have any logs starting with "error" in the logs folder? When did it start happening?

**Comment by LiliZeng778** [comment]
Here's how I used the software. 
As a first step, I download the latest toolkit.exe from github release interface. 
Second, I open the exe file to install the toolkit. 
Third, after the installation is complete, I click on the toolkit shortcut on the computer desktop to open the toolkit. 
Fourth, the software crashes after running for a few seconds. 
I mean I can't use the software. I don't know why my computer has compatibility problems. 
I found no record of error in the log.

**Comment by LiliZeng778** [comment]
Here's how I used the software. 
As a first step, I download the latest toolkit.exe from github release interface. 
Second, I open the exe file to install the toolkit. 
Third, after the installation is complete, I click on the toolkit shortcut on the computer desktop to open the toolkit. 
Fourth, the software crashes after running for a few seconds. 
I mean I can't use the software. I don't know why my computer has compatibility problems. 
I found no record of error in the log.

**Comment by BartoszCichecki** [comment]
So, it never worked for you properly? Giving that there are no errors in the log you sent, there is no way for me to figure out what happens. You might have some luck looking in Event Viewer, but in a case like this I would say there is some other issue that causes this, but it's impossible for me to say what exactly.

If you find more information, feel free to leave a comment here.
