### ISSUE TITLE
Smart FN Lock tends to fail to register Alt key release event, when toggling HDR on/off quickly using Win+Alt+B shortcut, if LLT Dashboard page is being displayed.

### ISSUE THREAD

**Issue by ZZZXXX0110** [BartoszCichecki/LenovoLegionToolkit#1254]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.1

### OS

Windows 23H2 build 22631.3447

### Device

Legion 7i 16IAX7 (7th gen)

### BIOS version

BIOS Version/Date	LENOVO K1CN44WW, 8/17/2023

### What's wrong?

When using the Windows's built-in keyboard shortcut for toggling HDR on and off, Win+Alt+B, and when doing so very quickly (for example, releasing Win, Alt, and B keys faster than the screen blackout that's part of the HDR toggling process), the Smart FN Lock feature would fail to register the Alt key release event, and FN lock would remain disabled despite Alt key having already become released. 

Tapping Alt key again normally after toggling HDR allows Alt key release event to properly register, and Smart FN Lock functions correctly once again.

Note that this only happens, if the Dashboard page of LLT is the current selected page in LLT, regardless of whether LLT window is actually being displayed (including if LLT window is closed). Having or not having the HDR toggle button enabled in LLT Dashboard page also has no effect on the occurrence of this bug. Whether Smart FN Lock is configured to only respond to Alt key, or is configured to respond to all of Shift, Ctrl and Alt key, also has no effect on the occurrence of this bug. 

For example, if I select the Dashboard page in LLT, then change focus to another window, or close LLT by clicking on the "X" on LLT window's title bar, this bug would still occur. However, if I instead select any page other than Dashboard (Battery, Keyboard, Settings, Donate page, etc.) in LLT, then this bug would not happen.

If the conditions are met and LLT's Dashboard is the current page in LLT, the only way to avoid this bug is to keep Alt key held down considerably longer than the duration of HDR toggling, like 2 seconds for example, instead of simply tapping the keyboard shortcut.

### How to reproduce the bug?

1. Go to LLT main window, select Dashboard page in LLT.
2. Engage FN Lock.
3. Quickly tapping the Win+Alt+B shortcut. As in, release the keys immediately after they are pressed. Verify that screen goes black and back on, as one would expect when toggling HDR on or off.
4. Notice how FN Lock remains disengage, despite of Alt key being already released.

### What is the behavior that you expected?

Smart FN Lock functions as expected, with FN Lock disengaging when the selected modifier key is held down, and re-engage when the modifier key is released. 

### Logs

[log_2024_04_16_11_32_11.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14996103/log_2024_04_16_11_32_11.txt)

**Comment by BartoszCichecki** [comment]
I couldn't make it happen on my laptop, so I will mark it as "help wanted".

**Comment by ZZZXXX0110** [comment]
> I couldn't make it happen on my laptop, so I will mark it as "help wanted".

Oooo would it help to make a video recording of what I do on the keyboard when I replicate this bug?

**Comment by Weresk** [comment]
When smart fn unlock is active, lagging and stuck freeze when alt+tab is pressed

**Comment by BartoszCichecki** [comment]
Closing. It doesn't seem it can be easily reproduced and other users are not confirming the issue.
