### ISSUE TITLE
Would be nice to have Actions triggered by enabling/disabling HDR. 

### ISSUE THREAD

**Issue by ZZZXXX0110** [BartoszCichecki/LenovoLegionToolkit#1257]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.1

### OS

Windows 23H2 build 22631.3447

### Device

Legion 7i 16IAX7 (7th gen)

### Is your feature request related to a problem?

No, this is feature suggestion, merely a nice thing to have.

### How would you like the problem to be solved?

I would like to have an Actions trigger for enabling/disabling HDR. I was hoping to have an Actions configured so that screen brightness is automatically increased to 100%.

This is beneficial because HDR10 tone mapping scheme is mathematically designed for when display is operating at maximal brightness, and when it is not the tonemapping would be completely incorrect, making colors all wrong on top of incorrect brightness for different parts of the image. And this is by design as peak brightness is mathematically a prerequisite of dynamic range, so using HDR tonemapping when the display is not at its maximal designed brightness wouldn't be meaningful in the first place. This is also why typically when HDR is enabled on a dedicated external monitor, the monitor would automatically lock brightness to maximal brightness and disable brightness control. However Lenovo decided not to implement this on the Legion laptops that are capable of impressive 570nit of peak brightness for some seriously good HDR performance for a HDR400 rated screen, since after all this is a laptop and not a desktop-only external monitor. But it would still be really nice to have the option to have such a feature implemented when someone wants to.

### What alternatives have you considered?

Alternatively, instead of an Actions trigger for a user to implement this on their own using other Actions, this could also be provided as an option (like a toggle) for the existing HDR toggle on Dashboard page, although I'm not sure how well that would work if one toggles HDR using the Windows built-in Win+Alt+B shortcut. Assuming the shortcut works perfectly this does make sense, as there is simply no situation where it makes sense to have HDR enabled without also setting brightness to max, as long as this is provided as an option.

Currently we also have the alternative of using the "When game is running" trigger in Actions, however this is not a substitute, because HDR has uses outside gaming too, such as watching HDR encoded movies, doing professional photography/artistic/scientific work that requires an HDR display, etc., for which a trigger based on whether a game is running would be inadequate.

**Comment by BartoszCichecki** [comment]
I like the idea, but as far as I can tell, Windows doesn't have an public API for subscribing to a notification when HDR is enabled. I will keep this open for now in case I am wrong, but it doesn't seem possible.

**Comment by Ace-Radom** [comment]
The only thing I know is: it's possible. Some Legion models have a pre-installed X-Rite Color Assistant, and it shows notifications when enabling HDR (cuz it cannot apply color calibration files under HDR mode), but I don't know how to do it either. I'll keep an eye on it in my spare time.

**Comment by Ace-Radom** [comment]
@BartoszCichecki I have two sources but I don't know if they could be useful.

https://stackoverflow.com/questions/66155083/windows-api-to-get-whether-hdrhigh-dynamic-range-is-active

Here's one from stackoverflow with C# code but I cannot reproduce it on my device.

[Ace-Radom/HDRStatusGet](https://github.com/Ace-Radom/HDRStatusGet)

This is a tiny C++ demo I wrote just now, and tested.

But none of them "subscribes" a notification, but ask if HDR is enabled. I'm not sure if it would help or we can find a way to plug it into the current architecture.

**Comment by BartoszCichecki** [comment]
Getting or setting the HDR state, isn't an issue - the issue is to have a notification callback. Getting/setting is already done here: https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/master/LenovoLegionToolkit.Lib/Extensions/DisplayExtensions.cs.

**Comment by Ace-Radom** [comment]
Seems that changing HDR state will also trigger `SystemEvents.DisplaySettingsChanged`. Will do some experiments.

**Comment by Ace-Radom** [comment]
@BartoszCichecki achieved, will open a pull request later if you didn't start a progress on it.

**Comment by ZZZXXX0110** [comment]
To add in what others have already mentioned so far, Windows display color profiles are indeed separate for HDR and SDR, and as a result switching between HDR and SDR will always change display color profile, so if there is indeed a Windows notification for changing display profile, perhaps it could also be used to indirectly let LLT know that display was changed between HDR/SDR.
