### ISSUE TITLE
Windows 11 Power Mode for Best Energy Efficiency is missing

### ISSUE THREAD

**Issue by YR710** [BartoszCichecki/LenovoLegionToolkit#1259]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 22H2

### Device

Legion R9000P ARX8 (2023)

### BIOS version

LPCN42WW,

### What's wrong?

![JCCSW1{AQV_G}LG92MQPX$I](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/157562289/78989204-33f0-497f-8ba1-8b6751b0755d)
Windows 11 Power Mode for Best Energy Efficiency is missing.Without the best energy efficient power mode, the CPU 7945HX will have high frequency and high temperature when idle. The previous standby temperature of 51 degrees and 2.5GHZ frequency is now maintained at more than 70 degrees and 5GHZ frequency. The fan speed will not drop below 3000.

### How to reproduce the bug?

It cannot be restored after updating to the new LLT version in April.

### What is the behavior that you expected?

We hope to restore the optimal energy efficiency mode。

### Logs

[](url)

**Comment by YR710** [comment]
![3E0NT@KY $Y)8)IGI3PL77](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/157562289/5da3756b-5d51-482b-9926-659cfe0139b1)

**Comment by BartoszCichecki** [comment]
> Windows 11 Power Mode for Best Energy Efficiency is missing.

That is not related to LLT.

**Comment by YR710** [comment]
> > Windows 11 Power Mode for Best Energy Efficiency is missing.
> 
> That is not related to LLT.

This problem arose only after the LLT was updated. I had already turned off the system update using the lenovo Quick Fix tool. I did not update the BIOS. And through communication with others, I found that many of them also have this problem in the power mode after the recent update of LLT.

**Comment by YR710** [comment]
> > Windows 11 Power Mode for Best Energy Efficiency is missing.
> 
> That is not related to LLT.

I have found the reason why LLT's power plan overcovers OEM's power plan

**Comment by MinionAttack** [comment]
> > > Windows 11 Power Mode for Best Energy Efficiency is missing.
> > 
> > 
> > That is not related to LLT.
> 
> I have found the reason why LLT's power plan overcovers OEM's power plan

Hi, can you tell us what was the reason? Thanks.
