### ISSUE TITLE
[REQUEST] Automatically restart on hybrid mode toggle

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#126]
When switching hybrid mode on/off it prompts user for restart but it doesn't do it, it would be better if it restarts automatically on clicking yes.
Also, the discharge rate should be measured in 'W' (Watts) not in Wh (Watt-hours).
Otherwise, the program is perfect; thanks!

**Comment by BartoszCichecki** [comment]
100% on the discharge rate units. Lack of reboot is a bug, which is already fixed and will be released with version 2.2.
