### ISSUE TITLE
External monitor connect/disconnect Actions are triggered accidentally when Lid opened/closed

### ISSUE THREAD

**Issue by Ace-Radom** [BartoszCichecki/LenovoLegionToolkit#1261]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 23H2

### Device

Legion R9000p 2021H

### BIOS version

GKCN53WW

### What's wrong?

I have two action pipelines which should be triggered when external monitor being connected / disconnected. But I noticed when I close the Lid (with no external monitor connected), LLT receives a `monitor disconnected` message and trigger the `external monitor disconnected` pipeline. Same thing happens when I open the Lid, a `monitor connected` message is received, and the other pipeline will be accidentally triggered.

### How to reproduce the bug?

1. Create two pipelines triggered by `external monitor connected / disconnected`, and make sure no external display is pluged in.
2. Close the Lid.
3. Open the Lid.
4. Both pipelines are triggered, but they shouldn't.

### What is the behavior that you expected?

Opening / Closing the Lid shouldn't trigger external monitor actions.

### Logs

[log_2024_04_26_07_52_03.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15127589/log_2024_04_26_07_52_03.txt)

**Comment by BartoszCichecki** [comment]
This seems to be a tricky one, here is a workaround for this: [installer](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/9054388379/artifacts/1495259088) 

It's hard for me to test it though, since it seems that this behavior isn't present on my machine. Let me know if this works better.

**Comment by Ace-Radom** [comment]
It's also really tricky to me. This bug happened all the time two weeks ago, but I cannot reproduce it any more. Logs are checked, pipelines aren't triggered (monitor connected msg isn't received). 

[log_2024_05_13_06_08_17.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15290347/log_2024_05_13_06_08_17.txt)

I wondered if it's a bug from ms and was fixed in the past two weeks, but my laptop didn't install any updates except ms defender antivirus. I'll still try the new test build and tell u what's going on anyway.

**Comment by BartoszCichecki** [comment]
It might have been a fluke, to be honest. Internal display is technically never disconnected, so it is a bit odd.

**Comment by Ace-Radom** [comment]
[log_2024_05_13_19_13_22.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15299074/log_2024_05_13_19_13_22.txt)

It seems that both connecting and disconnecting external monitor trigger the `external monitor connected` automation pipe. I compiled a build from branch `bug/external-screen-action` myself since new commit was made, this bug remains. 

[log_2024_05_13_19_24_27.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15299152/log_2024_05_13_19_24_27.txt)

Lid opening and closing look fine.

And btw, as the second log file shows, `external monitor disconnected on startup` works pretty fine, the bug which is described above only appears after startup.

**Comment by BartoszCichecki** [comment]
After giving this a thought, I think I will just go ahead and merge the PR. It doesn't really break anything and might increase some more safety that won't hurt.
