### ISSUE TITLE
Legion Slim 5 16AHP9

### ISSUE THREAD

**Issue by AfroHorse** [BartoszCichecki/LenovoLegionToolkit#1263]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.21.2

### OS

Windows 11 Pro 10.0.22631 Build 22631

### Device

Legion Slim 5 16AHP9

### BIOS version

NRCN15WW

### Which features of the application did you test?

Battery mode/overnight charging - all fine
Power mode - all fine
Keyboard RGB - all fine
FN Lock - all fine
Flip to start - all fine
Other display options - all fine

### Which features of the application do not work as expected?

Refresh rate - changing the option does not appear to actually change the refresh rate. Usually a logo with refresh will appear if it does change which is not happening

### Logs

[log_2024_04_29_22_12_10.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15155585/log_2024_04_29_22_12_10.txt)

**Comment by BartoszCichecki** [comment]
16AHP9 is not a Legion laptop.

**Comment by Miademora** [comment]
Not this one?
https://psref.lenovo.com/Product/Legion/Legion_Slim_5_16AHP9

**Comment by BartoszCichecki** [comment]
Oh, my bad 😅

**Comment by AfroHorse** [comment]
@BartoszCichecki just as a heads up, updated to 2.21.3 which based on PR looks like it should contain this but im still getting the incompatibility prompt at start up. Is this expected?

**Comment by BartoszCichecki** [comment]
Yes, 2.21.3 was just a hotfix release. This will be released with 2.22.0 which will come probably end of this week.
