### ISSUE TITLE
Pop up priority needs to be increased. 

### ISSUE THREAD

**Issue by ArtificialAngels** [BartoszCichecki/LenovoLegionToolkit#1264]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.0

### OS

Windows11 23H2 22631.3527

### Device

Legion 5 pro

### Is your feature request related to a problem?

In full screen PUBG, the prompt pop-up cannot be displayed at all.

### How would you like the problem to be solved?

Pop up priority needs to be increased. 

### What alternatives have you considered?

Pop up priority needs to be increased. 

### Additional information

non

**Comment by BartoszCichecki** [comment]
Duplicate #980
