### ISSUE TITLE
The Flip To Start option has no effect whatever value you set (Sleep mode)

### ISSUE THREAD

**Issue by MinionAttack** [BartoszCichecki/LenovoLegionToolkit#1265]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 Pro 23H2 Build 22631.3527

### Device

Lenovo Legion 7 16ARHA7 - 82UH

### BIOS version

K9CN45WW

### What's wrong?

The Flip To Start option has no effect whatever value you set. It doesn't matter whether you have the option on or off, it always behaves as if it is on when you use sleep mode.

I've tried resetting the BIOS settings, enabling the feature, saving, re-entering the BIOS, disabling the feature, saving again... but it has no effect. I've also tried disabling Lenovo Toolkit, reinstalling Lenovo Vantage and the associated service, logging into the application and checking that the functionality is disabled, enabling it, rebooting, disabling it, rebooting again and still no effect. 

If you suspend the device, when you open the lid it reactivates from the suspended state. If the laptop is switched off, it does not reactivate. 

The question I have is whether this functionality is only for when the laptop is off, or should it also work in sleep mode.

### How to reproduce the bug?

1. Go to the Lenovo Legion Toolkit application.
2. Disable the Flip to start option.
3. Activate sleep mode.
4. Open the lid.
5. The notebook exits sleep mode.

### What is the behavior that you expected?

If the notebook is in sleep mode, opening the lid should not reactivate the notebook and bring it out of sleep mode.

### Logs

[log_2024_04_30_17_55_47.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15169158/log_2024_04_30_17_55_47.txt)

Looking at the content, I have seen that there are some exceptions or errors. But they are beyond the scope of my knowledge.

### Additional information

If I am misunderstanding the functionality and it is only for when the laptop is off and has nothing to do with sleep mode, I apologise and this issue can be closed.

**Comment by BartoszCichecki** [comment]
> If I am misunderstanding the functionality and it is only for when the laptop is off and has nothing to do with sleep mode.

Exactly this ☝️
