### ISSUE TITLE
dGPU shows disconnected but stays connected after hibernation/sleep/shutdown - Legion 7 16IRX9

### ISSUE THREAD

**Issue by sohrabhamza** [BartoszCichecki/LenovoLegionToolkit#1267]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 23H2 22631.3527

### Device

Legion 7 16IRX9

### BIOS version

NSCN23WW

### What's wrong?

After shutdown/sleep/hibernation, dGPU stays connected (shows disconnected). It is not visible in the task manager but power draw is detected. 

30-36W total discharge rate is shown. 

After moving to Hybrid Mode, then back to Hybrid IGPU mode (here dGPU connects), then back to Hybrid, then again back to Hybdrid IGPU (dGPU disconnects finally)

After this total battery discharge rate drops to 18-20W 

### How to reproduce the bug?

1. Be on Hybrid IGPU mode
2. Shutdown/Hibernate/Sleep your laptop
3. Start it again on battery
4. Observe total battery discharge rate
5. Change to hybrid mode
6. Change to hybrid IGPU mode
7. Observe dGPU connects 
8. Change to hybrid mode
9. Change to hybrid IGPU mode 
10. Observe total battery discharge rate

### What is the behavior that you expected?

Starting laptop after hibrernation/shutdown/sleep, total battery discharge rate while doing nothing should be 17-20W and not 30-35W

### Logs

[log_2024_05_01_13_25_34.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15177483/log_2024_05_01_13_25_34.txt)

-Not sure how useful they are as I hibernated the device in the middle 

### Additional information

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/66321101/bc61f869-b336-4fab-8626-149ffbb60427)
-Correct Battery Usage - Note: Not ideal as chrome was running 
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/66321101/2ecc4698-76f5-4c78-aac3-e6437c8b5412)
-Wrong Battery Usage - Right after booting up (Waited a few minutes for the usage to settle)

**Comment by BartoszCichecki** [comment]
As stated in the README:

> All above settings are using built in functions of the EC and how well they work relies on Lenovo's firmware implementation.

LLT only tells EC what is the settings, but the process of connecting disconnecting is handled by firmware. I suggest resetting EC - instruction can be found in the Discord server: https://discord.com/invite/legionseries
