### ISSUE TITLE
Toolkit on WinPE

### ISSUE THREAD

**Issue by mihajlo001** [BartoszCichecki/LenovoLegionToolkit#1268]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.21.2

### OS

Windows 10 Version 2004 build 19041.1 WinPE 10 Sergei Strelec x64

### Device

Legion 5 pro 16iah7h

### BIOS version

J2CN40WW

### Which features of the application did you test?

The application itself.

### Which features of the application do not work as expected?

The application wont start.

### Additional information

I want to use the Legion Toolkit on a WinPE 10 Sergei Strelec which is a live windows environment running from usb stick.

Im using Linux and wanted and easy access to Toolkit without having to dual boot.

I installed Legion Toolkit on WinPE, the .net is also installed, and i installed both needed drivers, but the application wont start. When i click on executable the loading icon appears for a split second on the cursor and after that nothing happens.

**Comment by BartoszCichecki** [comment]
I am sorry, but I don't support custom Windows distros. On the other hand, if required components are there, there is no reason for LLT to not work, so that it is up to you to make sure that all needed components are installed on the PE environment.
