### ISSUE TITLE
Error while trying the enter the Actions tab

### ISSUE THREAD

**Issue by akshay9944** [BartoszCichecki/LenovoLegionToolkit#127]
Describe the bug
I receive the following error messages when i try to enter the Actions tab

1. Go to 'Desktop'
2. Click on 'Lenovo Vantage Toolkit'
3. Click on  'Actions Tab'
4. See errors
5. Application crashes

![Screenshot 2022-06-27 132351](https://user-images.githubusercontent.com/28150328/175889982-ba8d6656-43e8-4c28-8f24-7ef9dfe8b251.png)

 - OS: Windows 10 Home 21H2 build 19044.1766
 - Laptop model: Legion 5 Pro 15ACH6A
 - Do you have Vantage installed? - Yes

**Comment by BartoszCichecki** [comment]
You have an AMD GPU right? If yes, this is fixed and a new version is coming most likely tomorrow.

**Comment by akshay9944** [comment]
Yes mine is an all AMD laptop. Thank you!!!
I absolutely love the Toolkit!!

**Comment by BartoszCichecki** [comment]
In the meanwhile follow you can check [discord.gg/legionseries](https://discord.com/invite/legionseries) and in the #community-made channel there is a link to 2.2 beta4 that should have this issue resolved (and also adds RGB keyboard support).

**Comment by akshay9944** [comment]
Thank you i will!!
