### ISSUE TITLE
add Japanese

### ISSUE THREAD

**Issue by anmoti** [BartoszCichecki/LenovoLegionToolkit#1271]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 Home Build 22621.ni_release.220506-1250

### Device

Legion 5 15IAH7H

### Is your feature request related to a problem?

I thought this project was great, but it would be even better if it supported Japanese.
I would like Japanese to be added to the translation.

### How would you like the problem to be solved?

If you add Japanese, I will translate it using DeepL etc.
Of course, I will make adjustments to make it easier to understand Japanese.

### What alternatives have you considered?

English is fine, but it takes time for Japanese people who don't know English to use this software.

**Comment by BartoszCichecki** [comment]
Hej @anmoti you can do the translations on crowdin as described in Contribution section: https://github.com/BartoszCichecki/LenovoLegionToolkit?tab=readme-ov-file#translation
