### ISSUE TITLE
[FEAT] Support the Fn+N hotkey

### ISSUE THREAD

**Issue by shockdude** [BartoszCichecki/LenovoLegionToolkit#1273]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 23H2 build 22631

### Device

Legion 5 Slim 16APH8

### Is your feature request related to a problem?

Fn+N is a key combination that is supported by Legions, but which LLT currently doesn't use.
According to the laptop's User Guide, pressing the Fn+N key combination should "Show Device Information".
If I enable Lenovo Hotkeys, Fn+N directs me to install Vantage from the MS Store (since I don't have Vantage installed).

### How would you like the problem to be solved?

Have Fn+N be configurable, with the same features as the existing Smart Key Action & Smart Key Secondary Action.

### What alternatives have you considered?

Have Fn+N simply open LLT

**Comment by BartoszCichecki** [comment]
Fn+N is not supported on my laptop, so if you could capture a log output where you have LLT open and you press Fn+N a couple of times, then we can find a key code for it.

**Comment by Miademora** [comment]
im not the op but here is a log from mine.
i pressed fn+n 3 times and it opened microsoft store with the vantage app preselected then i closed the store each time.
[log_2024_05_10_16_02_44.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15277351/log_2024_05_10_16_02_44.txt)

**Comment by shockdude** [comment]
Collected my own log as well, using a fresh LLT config for cleanliness.
I did Fn+N 5 times, and I see 5 `SpecialKeyListener` events & handlers, so I think the log worked?
(log edited to redact my IP address from an unrelated auto-update error).
[log_2024_05_11_04_10_47.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15281608/log_2024_05_11_04_10_47.txt)

**Comment by BartoszCichecki** [comment]
I know this isn't ideal, but for now I bound Fn+N to bringing LLT to foreground. I don't have any way of checking, if device supports this shortcut, so bring to foreground seems to be the best option. It would be pretty confusing to expose it in settings for people who can't really use it.
