### ISSUE TITLE
Add Linux support native for app

### ISSUE THREAD

**Issue by RaulKong898** [BartoszCichecki/LenovoLegionToolkit#1276]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

Linux

### OS

linux

### Device

Lenovo Legion 5 15ACH6H

### Is your feature request related to a problem?

Add Linux support native for app

### How would you like the problem to be solved?

Add Linux support native for app

### What alternatives have you considered?

Add Linux support native for app

### Additional information

Add Linux support native for app

**Comment by BartoszCichecki** [comment]
There is alternative project mentioned in the readme that works on Linux.
