### ISSUE TITLE
Remap FN Keys

### ISSUE THREAD

**Issue by dcsilva0** [BartoszCichecki/LenovoLegionToolkit#128]
It would be really useful to be able to remap some fn keys for example:

fn + f4 - mutes the microphone, but doesn't work with vantage and lenovo fn keys service disabled

fn + f9 - opens the toolkit but it would be great to have it launch other apps (since the toolkit can be launched from the system tray) or run quick actions - maybe even run different actions when double pressing it.

fn + prtsc - I'm not sure if this one is possible, but one thing that always annoyed me is that, when fn lock is enabled I can't take quick screenshots, or open Windows "new" screenshot UI. It always launched the app instead. I have to press fn + prtsc (or disable fnlock)

fn + 8 - airplane mode - doesn't work without lenovo fn keys service, but honestly I don't think people use their gaming laptops on the plane that often they need to have a shortcut to enable it. Being able to remap it would probably be more useful than "fixing" it.

[Edit: Being able to add custom FN shortcuts would be super useful too, it would be basically like having an extra keyboard for custom shortcuts. I don't know if that is actually possible though.]

Btw, these are the shortcuts on my 2021 Legion 5, I'm not sure if they're different on other Legions laptops.

And most important, thanks for making this app! It is amazing and has fixed most of the things I find annoying on my laptop.

**Comment by BartoszCichecki** [comment]
Regarding Fn+F4 and Fn+F9, support for this is on the way.
Regarding custom shortcuts, unfortunately it's not possible with the way Lenovo implemented them.

Finally, regarding remapping I'll keep this on the roadmap ;)
