### ISSUE TITLE
Custom Mode on Gen 9 laptops using FN+Q

### ISSUE THREAD

**Issue by SpectreDev1** [BartoszCichecki/LenovoLegionToolkit#1282]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

Latest

### OS

W11

### Device

Legion 5i Gen 9

### Is your feature request related to a problem?

No it is not

### How would you like the problem to be solved?

To add the feature which has to be manually enabled in vantage to cycle through the power modes including custom mode

<img width="952" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/93622611/a8515ff4-1707-42dd-9221-e70edef13c92">

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment]
I need some more description:
1. After checking "enable extreme mode", is there any configuration for it?
2. Does the power LED turn purple like with standard custom mode?
3. Does cycling with Fn+Q work only when extreme mode is checked?
4. Please include a log from LLT (instruction in readme) when cycling with Fn+Q with both this option enabled and disabled.

**Comment by SpectreDev1** [comment]
1. After enabling Extreme mode you cant adjust anything 
2. Yes it does go purple like the Gen 7 laptops
3. No it doesn't require extreme mode to be enabled for Fn+Q cycling 
4. Will do

**Comment by SpectreDev1** [comment]
[disabled.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15294631/disabled.txt)
[enabled.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15294632/enabled.txt)
[both.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15294633/both.txt)

**Comment by SpectreDev1** [comment]
theres the log

**Comment by BartoszCichecki** [comment]
Please also paste the output out these commands from PowerShell:

`Get-WmiObject -namespace root\WMI -class LENOVO_CAPABILITY_DATA_00`
`Get-WmiObject -namespace root\WMI -class LENOVO_CAPABILITY_DATA_01`
`Get-WmiObject -namespace root\WMI -class LENOVO_CAPABILITY_DATA_02`

**Comment by SpectreDev1** [comment]
> Get-WmiObject -namespace root\WMI -class LENOVO_CAPABILITY_DATA_02

https://pastebin.com/NWNXyVfq

**Comment by BartoszCichecki** [comment]
Great, so now, you can check the output of this:

`(Get-WmiObject -namespace root\WMI -class LENOVO_OTHER_METHOD).GetFeatureValue(1048576).value`

If I am not wrong, it should return `0` when Fn+Q thing is off and `1` if it's on.

**Comment by BartoszCichecki** [comment]
Great stuff. I need to do some coding and will post a new beta. Thanks for help.

**Comment by SpectreDev1** [comment]
no problem
