### ISSUE TITLE
4 Keyboard RGB profiles for Gen 9 Legions

### ISSUE THREAD

**Issue by SpectreDev1** [BartoszCichecki/LenovoLegionToolkit#1283]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

Latest Beta

### OS

Win 11 Latest

### Device

Legion 5 Gen 9

### Is your feature request related to a problem?

No not really 

### How would you like the problem to be solved?

Just add profile 4 for the Gen 9 laptops as Lenovo Vantage has 4 profiles too 

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment]
Please put more effort into issues. 

What do you see now?

**Comment by SpectreDev1** [comment]
well currently LLT only supports 3 different RGB profiles for the keyboard where as vantage supports 4 different profiles

<img width="258" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/93622611/7969549b-106c-4ba5-8763-9d985aaa2823">

**Comment by BartoszCichecki** [comment]
What type of keyboard is this, what device (machine type)?

**Comment by SpectreDev1** [comment]
its a Legion 5 16IRX9, with a 4 Zone RGB keyboard

**Comment by BartoszCichecki** [comment]
Here is a test build: [installer](https://github.com/BartoszCichecki/LenovoLegionToolkit/actions/runs/9084354203/artifacts/1502295773), let me know if it works properly.

**Comment by SpectreDev1** [comment]
100% Working
