### ISSUE TITLE
Dynamic Response Time aka Overdrive missing

### ISSUE THREAD

**Issue by SpectreDev1** [BartoszCichecki/LenovoLegionToolkit#1291]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

Latest Beta

### OS

Win 11 Latest

### Device

Legion 5 Gen 9

### BIOS version

NMCN22WW

### What's wrong?

well lenovo renamed the overdrive mode to dynamic response time, overdrive mode doesnt show up in LLT at all for Legion 5 Gen 9

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/93622611/1458b49e-fc36-462c-a33b-db0bf9edd5a7)

### How to reproduce the bug?

Its missing entirely

### What is the behavior that you expected?

Expect Overdrive/Dynamic Response Time to be there

### Logs

dont think its possible to log

**Comment by BartoszCichecki** [comment]
Attach log plz.

**Comment by BartoszCichecki** [comment]
Hmmmm that is a tricky... what was the default value for it? Was it off by default?

**Comment by BartoszCichecki** [comment]
Anyway, let's start with a WMI dump from Gen 9, because I don't have it yet. Please post the output of this powershell script:

```
$wmi_classes = Get-WmiObject -Namespace 'ROOT/WMI' -List -Class "*LENOVO*"
foreach ($wmi_class in $wmi_classes){
  Write-Host "########################################"
  Write-Host "########################################"
  Write-Host "########################################"
  Write-Host "Name:" $wmi_class.Name
  Write-Host "Class Name:" $wmi_class.Name
  Write-Host "Class GUID:" $wmi_class.Qualifiers["guid"].Value
  Write-Host "Description:" $wmi_class.Methods.Count
  Write-Host "Methods:"
  foreach ($method in $wmi_class.Methods){
    Write-Host "Name:" $method.Name
    Write-Host "WmiMethodId:" $method.Qualifiers["WmiMethodId"].Value
    Write-Host "Class Name:" $wmi_class.Name
    Write-Host "Class GUID:" $wmi_class.Qualifiers["guid"].Value
    Write-Host "Description:" $method.Qualifiers["Description"].Value
    Write-Host "Implemented:" $method.Qualifiers["Implemented"].Value
    Write-Host ""
  }
  Write-Host ""
}
```

**Comment by SpectreDev1** [comment]
> Hmmmm that is a tricky... what was the default value for it? Was it off by default?

Yep it's off by default

**Comment by SpectreDev1** [comment]
> Anyway, let's start with a WMI dump from Gen 9, because I don't have it yet. Please post the output of this powershell script:
> 
> ```
> $wmi_classes = Get-WmiObject -Namespace 'ROOT/WMI' -List -Class "*LENOVO*"
> foreach ($wmi_class in $wmi_classes){
>   Write-Host "########################################"
>   Write-Host "########################################"
>   Write-Host "########################################"
>   Write-Host "Name:" $wmi_class.Name
>   Write-Host "Class Name:" $wmi_class.Name
>   Write-Host "Class GUID:" $wmi_class.Qualifiers["guid"].Value
>   Write-Host "Description:" $wmi_class.Methods.Count
>   Write-Host "Methods:"
>   foreach ($method in $wmi_class.Methods){
>     Write-Host "Name:" $method.Name
>     Write-Host "WmiMethodId:" $method.Qualifiers["WmiMethodId"].Value
>     Write-Host "Class Name:" $wmi_class.Name
>     Write-Host "Class GUID:" $wmi_class.Qualifiers["guid"].Value
>     Write-Host "Description:" $method.Qualifiers["Description"].Value
>     Write-Host "Implemented:" $method.Qualifiers["Implemented"].Value
>     Write-Host ""
>   }
>   Write-Host ""
> }
> ```

I'll do this tomorrow for you

**Comment by SpectreDev1** [comment]
https://pastebin.com/ECyw0hKU here is the dump

**Comment by SpectreDev1** [comment]
btw i have the 240hz panel, not sure if that makes any difference for you

**Comment by BartoszCichecki** [comment]
Hmmm... ok let's try something...

Check if this returns different values depending on what you select in the dropdown. Make sure that you click "Done" after each change:

`(Get-WmiObject -namespace root\WMI -class LENOVO_OTHER_METHOD).GetFeatureValue(1703936).value`

If it works, write down the values it returns for each of the options from the dropdown, so I can map them correctly.

**Comment by SpectreDev1** [comment]
> Hmmm... ok let's try something...
> 
> Check if this returns different values depending on what you select in the dropdown. Make sure that you click "Done" after each change:
> 
> `(Get-WmiObject -namespace root\WMI -class LENOVO_OTHER_METHOD).GetFeatureValue(1703936).value`
> 
> If it works, write down the values it returns for each of the options from the dropdown, so I can map them correctly.

1 for enabled 0 for disabled

**Comment by BartoszCichecki** [comment]
Great, we have a jackpot 😎 thanks for testing!

**Comment by SpectreDev1** [comment]
no problem

**Comment by BartoszCichecki** [comment]
I think you had another instance running because log is broken.

**Comment by SpectreDev1** [comment]
yep my bad, heres another log 
[log_2024_05_19_11_27_36.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15369142/log_2024_05_19_11_27_36.txt)

**Comment by SpectreDev1** [comment]
yep it shows up now
[log_2024_05_19_11_40_45.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15369185/log_2024_05_19_11_40_45.txt)
