### ISSUE TITLE
Incorrect GPU power limit enforced in Custom Mode

### ISSUE THREAD

**Issue by mesaprotector** [BartoszCichecki/LenovoLegionToolkit#1293]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.3

### OS

Windows 11

### Device

LOQ 15IRH8

### BIOS version

LZCN23WW

### What's wrong?

As a workaround for a bug with another program, I have been forced to use Custom Mode instead of Performance Mode while gaming. Lenovo Legion Toolkit seems to treat Custom Mode as an offshoot of Balanced Mode, and the GPU power limit is set to the same as it is in Balanced Mode (75W) instead of the higher Performance Mode power limit. In Lenovo Vantage, this does not occur and the GPU can use 95W when in custom mode.

Note that I cannot manually set the TGP in either Vantage or LLT, and I do not expect to be able to.

I made sure Vantage was disabled and rebooted before testing the issue again in LLT.

### How to reproduce the bug?

1. Start HWInfo64 (or similar monitoring software), and open a window showing the total GPU power.
2. Open Lenovo Legion Toolkit and apply custom mode.
3. Run a GPU-heavy game or benchmark (I used Superposition).
4. Check the HWInfo64 to see how much power the GPU is drawing.

### What is the behavior that you expected?

GPU power limit is set to 95W, the same as in Performance Mode (and when using Custom Mode on Lenovo Vantage).

### Logs

See attachment. I ran the GPU for over a minute in Custom Mode, then switched to Balance and then Performance with Fn+Q, in case that would show anything useful.
[log_2024_05_18_01_59_23.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15356790/log_2024_05_18_01_59_23.txt)

### Additional information

I'd like to try resetting my embedded controller, but the listed method didn't work for me. Neither did disabling the battery in BIOS. I know where my CMOS battery is and could open the laptop to unplug it, but I'd rather not if there's an easier way.

**Comment by BartoszCichecki** [comment]
Interesting case. Please try this build and let me know if it fixes the issue: 
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15357865/LenovoLegionToolkitSetup.zip)

**Comment by mesaprotector** [comment]
It does indeed seem to work now, thank you. Apologies for the rather long log this time, but I wanted to switch between Custom and other modes to see if that affected anything.

[log_2024_05_18_03_54_17.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15358167/log_2024_05_18_03_54_17.txt)

**Comment by BartoszCichecki** [comment]
Great. You can keep using this version until next stable version is released. Thanks for the bug report!
