### ISSUE TITLE
[Feature Request] Run an Action at specific time

### ISSUE THREAD

**Issue by revanmj** [BartoszCichecki/LenovoLegionToolkit#130]
**Describe the solution you'd like**
Ability to set specific time as an Action initiator instead of just events like app open/close, charger connect/disconnect.

If possible, options like "at sunset/sunrise" would also be nice if that wouldn't be too much of a problem.

**Additional context**
I would like to use it for things like automatically enabling keyboard backlight at night and disabling it during the day.

**Comment by BartoszCichecki** [comment]
Good idea 👍

**Comment by BartoszCichecki** [comment]
@revanmj I have troubles finding a good (free) API that would allow for IP based geolocation for sunrise sunset. Do you know any?

**Comment by revanmj** [comment]
I often saw http://ip-api.com/ being used for getting location data and https://sunrise-sunset.org/ for getting actual times
