### ISSUE TITLE
请求添加一个[自动化]的功能-[时间段]

### ISSUE THREAD

**Issue by MrLinXD** [BartoszCichecki/LenovoLegionToolkit#1303]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.3

### OS

Windows 10 LTSC 2021  Build 19044

### Device

Y9000x 2020 

### Is your feature request related to a problem?

我希望在中午午睡的时候, "当用户重新操作电脑后"亮度能调到10%. 平时办公的时候,  "当用户重新操作电脑后"亮度能调到50% . 

### How would you like the problem to be solved?

我希望能添加这个功能.

### What alternatives have you considered?

无

**Comment by BartoszCichecki** [comment]
Please use English for issue reporting.

**Comment by Ace-Radom** [comment]
> Brief translation & summary: add a automation trigger that combines `in specific time range` and `when user becomes (in)active`

@MrLinXD This is discussed in #1219. The thing is, current `AutomationProcessor` is stateless, which means that this function you requested is real hard to achieve, and may lead to a couple of huge ’consistency‘ issues (for details plz check the explanation in the original issue). Therefore this feature is considered, but there may be no push on that in a short time.

And btw, as the repo owner said & what's explaned in both [contributing guide](https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/master/CONTRIBUTING.md) & [chinese readme](https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/master/README_zh-hans.md#%E8%B4%A1%E7%8C%AE%E6%AD%A4%E9%A1%B9%E7%9B%AE), please report issues only in English, thx for your understanding.

@BartoszCichecki Duplicate of #1219.
