### ISSUE TITLE
windows power modes seems don't have power best power efficiency

### ISSUE THREAD

**Issue by kaniamutan14** [BartoszCichecki/LenovoLegionToolkit#1309]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.0

### OS

windows 11 23h2 build 22631

### Device

legion 5 15IMH05

### BIOS version

EFCN45WW

### What's wrong?

In the new update have introduced that changing legion power mode changes windows power mode, there is option to choose power efficiency, balance, best performance but in windows settings there is recommended, better performance, best performance, so if i set to better efficiency and go to settings the power mode shows blank, balance displayed as recommended in windows settings and better performance option is not there in llt 
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/75250134/2da57839-db0a-42bc-a036-a44555978564)
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/75250134/970c5d58-c23d-4008-96f2-3c8333736ee4)
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/75250134/d9d1235e-1734-4694-91a8-d23eb2442e1c) this is how windows settings show when set to power efficiency 

### How to reproduce the bug?

1. set power mode to best efficiency for any mode in llt 
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/75250134/b3193cf3-73a1-48d8-b681-116e9e356340)
2. open settings then power and battery
3. power mode shows blank bar
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/75250134/d890c0d2-f789-42c5-9596-de8d2f50f8da)

### What is the behavior that you expected?

naming is not correct and better performance option in windows setting power mode is not utilized

### Logs

[log_2024_05_29_17_46_13.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15488761/log_2024_05_29_17_46_13.txt)

**Comment by BartoszCichecki** [comment]
Options presented in LLT are correct. As [stated in the readme](https://github.com/BartoszCichecki/LenovoLegionToolkit#windows-power-plans--windows-power-mode), if you are experiencing problems the solution is to reset Windows' power settings.

**Comment by BartoszCichecki** [comment]
It's not - those keys store values for which power mode is used on battery and on AC adapter.

**Comment by MLuukkonen** [comment]
After some experimenting, I was able to replicate how to make this happen in Windows 11 23H2.

----------------------------------------------------

If you have any power setting subkeys in

HKLM\CurrentControlSet\Control\Power\User\PowerSchemes\3af9b8d9-7c97-431d-ad78-34a8bfea439f

which is the "High Performance Overlay", Windows renames the power mode options to "Recommended", "Better performance", "Best performance."

Deleting or renaming the "3af9b8d9-7c97-431d-ad78-34a8bfea439f" subkey renames the power mode options back to "Best power efficiency", "Balanced", "Best performance."

----------------------------------------------------

Furthermore, it changes which overlay values the first two power mode options set.

Normally, "Best power efficiency" sets your active overlay to "961cc777-2547-4f9d-8174-7d86181b8a7a", and "Balanced" sets your active overlay to "00000000-0000-0000-0000-000000000000".

If the subkey exists, "Recommended" changes the active overlay to "00000000-0000-0000-0000-000000000000", and "Better performance" changes the active overlay to "3af9b8d9-7c97-431d-ad78-34a8bfea439f".

I assume it is this change in the behavior of which active overlay is set that makes the selection box appear blank.

**Comment by kaniamutan14** [comment]
Wow you have dived deep into this, you found the cause, really grateful for you,
now I remember once I saw some video and enabled ultimate high-performance plan but later switcher back to balanced power mode maybe that's the cause. After I reset the power mode using the cmd it became normal.
Really thank you for finding it
