### ISSUE TITLE
[REQUEST] RGB Customization

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#131]
I'm really grateful you added keyboard customization on the application! But I think it could have a little more features for it to be perfect.
Feature requests regarding keyboard RGB customization:
1. Allow precise RGB color selection like Vantage (R, G, B) values.
2. Add custom profiles like 4JX's ["Smooth Wave"](https://cdn.discordapp.com/attachments/879885895044575304/879885965026541628/YouCut_20210825_022814067.mp4) profile which is much better than normal Lenovo wave profile and add wider range of speed control [4JX's "L5P-Keyboard-RGB" GitHub](https://github.com/4JX/L5P-Keyboard-RGB)
3. Profile Switching using FN+Space (I don't know if this is a bug or not but when I try to switch profiles using FN+Space it reverts to Vantage's profile config)
4. Ability to export/import profiles and have more than 3 profiles if possible

I know I'm asking a lot and if this will take a huge chunk of your time I won't be sad if you never did it; otherwise, thanks for rescuing us from Vantage!

**Comment by BartoszCichecki** [comment]
1. Added to the list.
2. Custom profiles are most likely not coming, speed control I will look at.
3. Fn+Space should work. Vantage must be disabled and restart is recommended, then Fn+Space should work correctly.
4. More profiles is also doable, I'll see if it's requested more.

**Comment by BartoszCichecki** [comment]
If you still have problems with Fn+Space please try this possible hotifx:
[LenovoLegionToolkitSetup_possible_hotfix.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9008102/LenovoLegionToolkitSetup_possible_hotfix.zip)

**Comment by alantoblooddy** [comment]
Hey,

_In addition to the RGB._ The Lenovo legion 7 series (both 2020 & 2021) uses the iCue software to control the lightning (which is a pain in the back even with some background services disabled). Would it be possible to add customization for them?

I thought creating a separate request was unnecessary, that's why I'm leaving a comment here.

**Comment by BartoszCichecki** [comment]
Replacing iCue is an absolutely massive task, so I don't plan on doing that any time soon.

On the upside I've heard that openRGB works with 7s.

**Comment by alantoblooddy** [comment]
I thought maybe borrowing the stuff from the openRGB if that's possible and incorporating it in the LLT. Then it would be really the ultimate app :D. In any case, thanks for the great app!

_To be honest, still I'm unable to understand how to setup everything, but maybe I'm blind_

**Comment by RickyTVs** [comment]
> 1. Added to the list.
> 2. Custom profiles are most likely not coming, speed control I will look at.
> 3. Fn+Space should work. Vantage must be disabled and restart is recommended, then Fn+Space should work correctly.
> 4. More profiles is also doable, I'll see if it's requested more.

I think being able to customize the number of profiles you have is a great idea!

**Comment by BartoszCichecki** [comment]
Changing RGB values will be avaialble in 2.3.0.

**Comment by RickyTVs** [comment]
> Changing RGB values will be avaialble in 2.3.0.

Would you add the profile customization feature?

**Comment by BartoszCichecki** [comment]
If you mean number of profiles, I will make a separate issue for that. If you mean customization like L5P-Keyboard-RGB, then this is not planned. The author is most welcome to integrate it into LLT if he wants to though.

**Comment by RickyTVs** [comment]
> If you mean number of profiles, I will make a separate issue for that. If you mean customization like L5P-Keyboard-RGB, then this is not planned. The author is most welcome to integrate it into LLT if he wants to though.

Yes, I mean the number of profile and import/exporting them.
Thanks!

**Comment by BartoszCichecki** [comment]
If you want to "export" them you can just copy `rgb_keyboard.json` file from `%LOCALAPPDATA%\LenovoLegionToolkit` and keep it somewhere ;)

**Comment by Oblivious02** [comment]
> If you want to "export" them you can just copy `rgb_keyboard.json` file from `%LOCALAPPDATA%\LenovoLegionToolkit` and keep it somewhere ;)

I had no idea that's where RGB settings are saved, I can change the RGB values precise values like I've requested there lol, thank you

**Comment by DJPillu** [comment]
was this issue created for the four-zone keyboard laptops?
