### ISSUE TITLE
Crash on Settings

### ISSUE THREAD

**Issue by BartoszCichecki** [BartoszCichecki/LenovoLegionToolkit#1311]
### Discussed in https://github.com/BartoszCichecki/LenovoLegionToolkit/discussions/1310

<div type='discussions-op-text'>

<sup>Originally posted by **DaPetra** May 29, 2024</sup>
After updating to the latest version, an error message now appears on my Legion Pro 7 (Gen9) when I click on settings. After clicking OK, the program closes completely.

<img width="305" alt="2024-05-29 20_01_16-Error_LLT" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/92589051/d4b1c9c9-cb3c-453a-aae3-a377c36174f7">
</div>

**Comment by BartoszCichecki** [comment]
Hotfix 2.22.1 is now released.

FYI @DaPetra @jonathanAB214

**Comment by jonathanAB214** [comment]
Thank you!
