### ISSUE TITLE
Add support for Lenovo LOQ AMD Gen 9 15AHP9

### ISSUE THREAD

**Issue by AyushSehrawat** [BartoszCichecki/LenovoLegionToolkit#1314]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.22.1

### OS

Windows 11 Home Single Language 23H2 22631.3593

### Device

Lenovo LOQ AMD Gen 9 15AHP9

### BIOS version

NZCN20WW

### Which features of the application did you test?

Things i have tested

- Working CPU and GPU graph shown on home tab
- Working power and graphics settings shown on home tab (power mode, battery mode, gpu working mode, custom mode)
- Working display and other section on home tab (resolution, dpi, refresh rate, microphone, keyboard backlight)
- Battery section is displayed perfectly
- Downloads section displays the bios and other driver updates correctly
- Settings work fine (autorun, minimize to tray, minimize on close, disable lenovo services, power settings)

### Which features of the application do not work as expected?

All the stuff i tested works fine.

### Additional information

Since this model was not in the compatibility, it always used to pop up a message after boot saying compatibility issue. I had to disable it with args.txt. Some kind of option or making it one time only would be good.

**Comment by pratyush-1327** [comment]
I have the exact same device but still get the pop up of compatibility
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/78858764/c9c9528f-7a66-40f1-8f42-7235b3ffae4c)

**Comment by AyushSehrawat** [comment]
Issue is that it's not been pushed to release. For now go to legion toolkit data folder and make an args.txt file. Add two flags in it, one for log and another for no compat check

@BartoszCichecki Can you push it to the next release?

**Comment by BartoszCichecki** [comment]
Yes it will be included in next release.
