### ISSUE TITLE
Cpu useage and frequece dont shows correct

### ISSUE THREAD

**Issue by yancj9ya** [BartoszCichecki/LenovoLegionToolkit#1316]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.1

### OS

Windows 11 专业教育版23H22023/6/1622631.3672

### Device

Legion R9000P ARX8

### BIOS version

LPCN47WW

### What's wrong?

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/86911331/fb501969-f6cb-4841-848f-516dc7acbc2d)

the up two line dont show

### How to reproduce the bug?

when pc start it shows maybe,but after a while it cant shows,i dont know what cause this happen

### What is the behavior that you expected?

i dont know what this for

### Logs

[error_2024_04_12_11_28_12.txt](https://github.com/user-attachments/files/15521349/error_2024_04_12_11_28_12.txt)
[error_2024_04_11_13_54_38.txt](https://github.com/user-attachments/files/15521350/error_2024_04_11_13_54_38.txt)
[error_2024_02_16_04_57_12.txt](https://github.com/user-attachments/files/15521351/error_2024_02_16_04_57_12.txt)

**Comment by BartoszCichecki** [comment]
CPU usage and frequency isn't shown because LLT can't access Windows performance counters.

I don't know if you are using some sort of modified Windows or something is broken in your install but this isn't an issue on my side.
