### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by Amalmei** [BartoszCichecki/LenovoLegionToolkit#1317]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.1

### OS

Windows 11

### Device

Lenovo Legion 5 Slim

### BIOS version

95.06.1e.00.51

### What's wrong?

Error when trying to open.
![Error](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/106670152/9adc71d8-540c-4aed-b232-f379e05bf1ee)
![error 2](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/106670152/37818fbb-6530-4964-8e03-85b1d0214e29)

### How to reproduce the bug?

App will not open

### What is the behavior that you expected?

for the app to work as normal, 

### Logs

![Error](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/106670152/9c144aaa-1f1d-403e-890a-5c484471f667)
![error 2](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/106670152/a3b8b7ed-0cbc-49ca-b46c-861b03769727)

**Comment by BartoszCichecki** [comment]
Please attach logs as stated in the readme.

**Comment by vasubawa** [comment]
Hi, I'm also getting Application error. I have attached my log files. 


[AppDomain_UnhandledException.txt](https://github.com/user-attachments/files/15567921/AppDomain_UnhandledException.txt)
[Application_DispatcherUnhandledException.txt](https://github.com/user-attachments/files/15567922/Application_DispatcherUnhandledException.txt)

**Comment by BartoszCichecki** [comment]
Thanks @vasubawa. Your issue is different from the one reported in this ticket originally. However, hotfix will soon be released for the issue you are having.

**Comment by Amalmei** [comment]
It just started working again.
