### ISSUE TITLE
RGB keyboard bugs

### ISSUE THREAD

**Issue by goldmastersims** [BartoszCichecki/LenovoLegionToolkit#132]
In this video, you can notice a couple issues:

1. If the backlight is off, it doesn't reflect in Legion Toolkit.
2. The default keyboard profiles, baked into firmware, are not overwritten by Legion Toolkit when pressing Fn + Space. This is true even if the keyboard presets in the app are different from those baked into firmware.

Even if Lenovo Vantage is not installed and coming from a clean Windows install, the second bug is still an issue.

https://youtu.be/w3TpK7EXQ44

**Comment by BartoszCichecki** [comment]
Please attach logs.

**Comment by BartoszCichecki** [comment]
In the meanwhile you can check this possible hotfix to see if it fixes the issue.

[LenovoLegionToolkitSetup_possible_hotfix.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9008095/LenovoLegionToolkitSetup_possible_hotfix.zip)

**Comment by goldmastersims** [comment]
> In the meanwhile you can check this possible hotfix to see if it fixes the issue.
> 
> [LenovoLegionToolkitSetup_possible_hotfix.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9008095/LenovoLegionToolkitSetup_possible_hotfix.zip)

This fixes bugs 1 and 2.
