### ISSUE TITLE
Extend GPU overclock range

### ISSUE THREAD

**Issue by gsture** [BartoszCichecki/LenovoLegionToolkit#1320]
### Rules

- [x] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.1

### OS

Windows 11 Enterprise LTSC

### Device

16APH8

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

I would like the GPU overclocking feature to have a bigger range.

### What alternatives have you considered?

I tried gpu_oc.json but that didn't work. I now overclock with afterburner because my stable overclocks are higher then the overclock range this tool supports at the moment. I would rather use 1 application for both cpu settings and gpu overclock.

### Additional information

Thanks for offering a clean alternative to vantage adware!

**Comment by BartoszCichecki** [comment]
Increased to what values?

**Comment by gsture** [comment]
> Increased to what values?

After reconsidering I think would leave the sliders like they are as a fail save option for someone less tech savvy and have an advanced option where one can type in the values manually.

**Comment by gsture** [comment]
Thank you. That was ultra fast :D
