### ISSUE TITLE
IdeaPad Gaming 3i 15IMH05 has two KB backlight levels, but LLT only turns on/off in low.

### ISSUE THREAD

**Issue by mvildosolae** [BartoszCichecki/LenovoLegionToolkit#1329]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.2

### OS

Windows 10 21H2 build 19044

### Device

IdeaPad Gaming 3i 15IMH05

### BIOS version

EGCN34WW

### What's wrong?

This device has a backlit keyboard (blue light only), with two brightness levels. This is controlled via Fn + Spacebar, in the following order:

Off -> Low brightness -> High brightness

However, LenovoLegionToolkit treats this model as a one-level backlit keyboard, so it only shows a single toggle (ON/OFF), with the low brightness mode.

### How to reproduce the bug?

Use LenovoLegionToolkit to turn the keyboard backlight off and on. When it turns on, it's in the low brightness mode, with no choice to use the high brightness other than pressing Fn + Spacebar.

### What is the behavior that you expected?

LenovoLegionToolkit should expose both brightness levels in the UI for the keyboard backlight.

### Logs

[log_2024_06_10_04_03_11.txt](https://github.com/user-attachments/files/15755176/log_2024_06_10_04_03_11.txt)

### Additional information

[WMI dump](https://pastebin.com/mQwvLWMf)

I can provide any other log or command output you need about this model (I'm not sure if it's been reported before).

**Comment by BartoszCichecki** [comment]
This is a Gen 5 laptop and as stated in the readme: _"Issues related to devices older than Gen 6 or that are not Legions are out of scope of this project."_
