### ISSUE TITLE
Add screen brightness to actions

### ISSUE THREAD

**Issue by NoScore4U** [BartoszCichecki/LenovoLegionToolkit#135]
Would love to have an action for screen brightness. This would us to automatically set the screen brightness to 50% when on battery and say 90% when plugged in.

Great job on the app!

**Comment by BartoszCichecki** [comment]
Unfortunately giving that a lot of people have multiple power plans, it's almost impossible to get a nice experience without annoying brightness spikes.

Also, this can be configured directly in Windows Power Plans.

**Comment by BartoszCichecki** [comment]
Related: #63
