### ISSUE TITLE
Power Plan changes to custom when toolkit is launched

### ISSUE THREAD

**Issue by andredalmolin** [BartoszCichecki/LenovoLegionToolkit#1353]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 Pro 23H2 22631.3810

### Device

Legion Pro 5 16IRX8

### BIOS version

KWCN44WW

### What's wrong?

I always use my Legion in performance mode, but sometimes when I open the toolkit, the program changes the power plan to custom.

### How to reproduce the bug?

Open the toolkit

### What is the behavior that you expected?

Keep the power mode without changing.

### Logs

[log_2024_07_01_13_49_41.txt](https://github.com/user-attachments/files/16053856/log_2024_07_01_13_49_41.txt)

**Comment by BartoszCichecki** [comment]
There is nothing in the log that would indicate that your laptop switched to Custom mode.

Another thing is that you have Vantage services running. Please make familiarize yourself with the readme.
