### ISSUE TITLE
Bug: cannot install via scoop

### ISSUE THREAD

**Issue by WenSimEHRP** [BartoszCichecki/LenovoLegionToolkit#1355]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Microsoft Windows 11 Home China (x64) Build 22631.3737 (23H2)

### Device

Legion Y9000P IRX8

### BIOS version

KWCN36WW

### What's wrong?

Cannot install via scoop

### How to reproduce the bug?

run the following command in terminal:
```
scoop install lenovolegiontoolkit@2.23.0
# or
scoop install lenovolegiontoolkit
```

### What is the behavior that you expected?

Software is installable using scoop

### Logs

Here is the log generated by scoop:
```
❯ scoop install lenovolegiontoolkit
Installing 'lenovolegiontoolkit' (2.23.0) [64bit] from 'extras' bucket
Loading LenovoLegionToolkitSetup.exe from cache.
Checking hash of LenovoLegionToolkitSetup.exe ... ok.
Extracting LenovoLegionToolkitSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\jerry\scoop\apps\lenovolegiontoolkit\2.23.0\LenovoLegionToolkitSetup.exe.
Log file:
  ~\scoop\apps\lenovolegiontoolkit\2.23.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Extras/issues/new?title=lenovolegiontoolkit%402.23.0%3a+decompress+error
```
~\scoop\apps\lenovolegiontoolkit\2.23.0\innounp.log
```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```
Is the setup file corrupted?

### Additional information

The older version can be installed regularly
```
❯ scoop install lenovolegiontoolkit@2.22.2
WARN  Given version (2.22.2) does not match manifest (2.23.0)
WARN  Attempting to generate manifest for 'lenovolegiontoolkit' (2.22.2)
Autoupdating lenovolegiontoolkit
Downloading LenovoLegionToolkitSetup.exe to compute hashes!
Loading LenovoLegionToolkitSetup.exe from cache
Computed hash: c8e431d793a1a5e7b39891f2740c59796e2740566dd00de1f40f423a176387b2
Writing updated lenovolegiontoolkit manifest
WARN  Purging previous failed installation of lenovolegiontoolkit.
ERROR 'lenovolegiontoolkit' isn't installed correctly.
Removing older version (2.23.0).
'lenovolegiontoolkit' was uninstalled.
Installing 'lenovolegiontoolkit' (2.22.2) [64bit] from 'C:\Users\jerry\scoop\workspace\lenovolegiontoolkit.json'
Loading LenovoLegionToolkitSetup.exe from cache.
Checking hash of LenovoLegionToolkitSetup.exe ... ok.
Extracting LenovoLegionToolkitSetup.exe ... done.
Linking ~\scoop\apps\lenovolegiontoolkit\current => ~\scoop\apps\lenovolegiontoolkit\2.22.2
Creating shortcut for Lenovo Legion Toolkit (Lenovo Legion Toolkit.exe)
'lenovolegiontoolkit' (2.22.2) was installed successfully!
```

**Comment by BartoszCichecki** [comment]
@YisusChrist can you take a look at this?

**Comment by WenSimEHRP** [comment]
Installer file downloaded by scoop, if needed.
[application.zip](https://github.com/user-attachments/files/16059273/application.zip)

**Comment by YisusChrist** [comment]
It does not seem to be an error related to 'llt' but rather a problem with [Inno Setup](https://jrsoftware.org/isinfo.php).

This has been referenced [here](https://github.com/ScoopInstaller/Extras/issues/13547) and [here](https://github.com/ScoopInstaller/Extras/issues/13444) on the Scoop Extras repository.

**Comment by cscnk52** [comment]
can fixed by install another version of innounp
```
scoop uninstall innounp
scoop bucket add versions
scoop install versions/innounp-unicode
```

**Comment by BartoszCichecki** [comment]
Closing as it seems that related issues were resolved.
