### ISSUE TITLE
Screen Refresh Rate Action is sometimes blank

### ISSUE THREAD

**Issue by NoScore4U** [BartoszCichecki/LenovoLegionToolkit#136]
I added an action for 60hz when on battery and another for 165hz when plugged in. After I saved these I noticed the option that matched the current screen refresh rate was blanked out. 

Legion 7i 16ITHg6

**Comment by BartoszCichecki** [comment]
Were you running with an external screen? Or maybe Advanced Optimus? Settings for refresh rate will not be fully visible if LLT can't locate the internal display - that doesn't mean that they won't run correctly, if the built in display can be located when action runs.
