### ISSUE TITLE
No ability to turn off fans in custom power mode

### ISSUE THREAD

**Issue by Pjooo** [BartoszCichecki/LenovoLegionToolkit#1361]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 23H2 build 22631.3810

### Device

Lenovo Legion Slim 5-14 Ryzen 7-7840HS/32GB/1TB/Win11 RTX4060

### BIOS version

MACN23WW

### What's wrong?

I cannot set fan speed to 0RPM in custom power mode. The lowest it allows me to set is 2100RPM CPU, and 2200RPM GPU. Temps are really low (40-50C while browsing web etc.), quiet power mode has ability to turn off fans. But custom mode can't.

### How to reproduce the bug?

1. Set power mode to custom
2. Click configure button
3. Go to fan profile
4. Try setting fan lower than 2100RPM -> You can't.

### What is the behavior that you expected?

I want ability to set fans to 0RPM with lower temperatures.

### Logs

no logs for this issue

**Comment by BartoszCichecki** [comment]
Fan speeds are ultimately are controlled by the embedded controller (EC). You can set any curve with LLT, but if EC deems that the speed is too low it will be overridden. Nothing I can do about that.
