### ISSUE TITLE
[FEAT] Turn off Laptop Display Using Keyboard Shortcut

### ISSUE THREAD

**Issue by tysonrd** [BartoszCichecki/LenovoLegionToolkit#1364]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.22.2

### OS

Windows 11 23H2

### Device

Legion Slim 5 14APH8

### Is your feature request related to a problem?

On older Windows 10 Laptops there was a feature to be able to turn off the screen quickly by pressing the power button. Now with windows 11, this feature is unavailable on most laptops, including many Legions. 

It's nice to be able to quickly turn off the screen, while keeping everything running and not locking it for when you return. I know in LLT there is currently a feature that allows you to turn off the laptop display by clicking a button on the screen. Would there be a way to map this function to a keyboard shortcut and/or the power button?

I'm sure many users would find this feature useful. It would also be a nice OLED protection feature for those who have them or will in the future. 

### How would you like the problem to be solved?

N/A

### What alternatives have you considered?

N/A

**Comment by BartoszCichecki** [comment]
You can create a quick action that turns off the screen and assign it to Fn+F9 in LLT settings. This should accomplish what you want to do.

**Comment by tysonrd** [comment]
Should have clarified further, yes this turns off the laptop's screen, but it also puts it into sleep mode. I want to be able to turn the screen off while having the laptop remain unlocked and all systems running with the push of a key or two.

**Comment by BartoszCichecki** [comment]
That it is up to your windows power settings.
