### ISSUE TITLE
The font is blurry

### ISSUE THREAD

**Issue by wbmins** [BartoszCichecki/LenovoLegionToolkit#1367]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 家庭中文版 23H2 22631.3880

### Device

Legion R9000P ARX8

### BIOS version

LPCN51WW

### What's wrong?

![image](https://github.com/user-attachments/assets/8fe781c6-a0af-46f4-be54-b40789187dfa)

### How to reproduce the bug?

Click Settings, then About. You can see that the font gradually changes from blur to clear``

### What is the behavior that you expected?

font  clear

### Logs

/

**Comment by BartoszCichecki** [comment]
Cannot reproduce
