### ISSUE TITLE
CLI PATH environment variable does not follow custom installation location 

### ISSUE THREAD

**Issue by Snake-babu** [BartoszCichecki/LenovoLegionToolkit#1368]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 10 Home 22H2 build:19045.4651

### Device

Legion 5 Pro 16ACH6H

### BIOS version

GKCN65WW

### What's wrong?

- Switching on "Add CLI to PATH" option in settings results in the PATH variable being set to (what I assume to be) default installation location of LLT  (C:\Users\<user_name>\AppData\Local\Programs\LenovoLegionToolkit)

- But my LLT is installed in a custom location, so CLI doesn't work. 

### How to reproduce the bug?

1. Go settings
2. Enable "CLI" and "Add path to CLI"
3. Search in windows for "edit the system environment properties" and go to it
4. in the bottom right of the system properties dialog click for environment variables
5. Under user variables, edit the PATH variable
6. The new path variable tab points to "C:\Users\<user_name>\AppData\Local\Programs\LenovoLegionToolkit"
7. Also when using "llt" in cmd, it doesn't work (unless cmd is opened in the same directory as the llt.exe ofc)
9. After changing the PATH variable to match my custom installation location, LLT CLI works wonderfully 

### What is the behavior that you expected?

- Since I have my LLT installed in a different location, I would assume the PATH variables to match the same. 

### Logs

I believe my logs are irrelevant (also my last log file is from 2023) but I will still attach them. 
[error_2023_07_23_08_43_59.txt](https://github.com/user-attachments/files/16247902/error_2023_07_23_08_43_59.txt)

### Additional information

<img width="1261" alt="Screenshot (347)" src="https://github.com/user-attachments/assets/cc1d8dc6-97e2-405d-a4a5-5ce1a1ec7478">
<img width="1255" alt="Screenshot (348)" src="https://github.com/user-attachments/assets/b7a982e7-7b21-497d-a518-3ae76b9d53ee">

**Comment by Ace-Radom** [comment]
Nah log isn't needed I think... It should be a simple one, PR with the fix is on the way.
