### ISSUE TITLE
Batch Force Close Background Apps

### ISSUE THREAD

**Issue by NoScore4U** [BartoszCichecki/LenovoLegionToolkit#137]
I'm wondering if it is possible to have another tab added to the toolkit for app control. In the tab, there would be a shortcut to windows startup apps (to control which start with the computer) and an app that lets you select which apps that are currently running for force kill command. This selection would be saved and could be run with an action (e.g. when the power is unplugged).

This can be done now via batch files [YouTube Link](https://youtu.be/xFb_8-4Uaak), but I wonder if it's possible to do via the toolkit. Having an option like this would allow us to stop the battery drain from background apps while still keeping them installed for when plugged in. Cheers! :)

**Comment by BartoszCichecki** [comment]
Technically you can already run scripts from Actions, so you can automate it. If it will get a separate nice UI, I don't know. Let's see if it's requested more.
