### ISSUE TITLE
[FEAT] Battery Charge Threshold

### ISSUE THREAD

**Issue by jonshipman** [BartoszCichecki/LenovoLegionToolkit#1371]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Win 11 Home; Version 10.0.22631 Build 22631

### Device

Legion Go

### Is your feature request related to a problem?

Feature Request:

![image](https://github.com/user-attachments/assets/d15eab5d-e555-4ca4-bc73-b438ec715ff8)

Feature as seen on Legion Space

### How would you like the problem to be solved?

https://forums.lenovo.com/t5/Lenovo-Vantage-Knowledge-Base/Q-amp-A-setting-a-ThinkPad-battery-charge-threshold-by-script/ta-p/4345631

https://support.lenovo.com/us/en/downloads/ds541411

^ Just reference links. ChargeThreshold.exe does not work on the Go (the go does not use the Lenovo Power and Battery driver) but probably uses a similar method built into Legion Space.

### What alternatives have you considered?

I mean, I could just use the Legion Software

**Comment by BartoszCichecki** [comment]
Legion Go isn't supported.
