### ISSUE TITLE
need Windows Power Mode and Windows Power Plan mixed mode

### ISSUE THREAD

**Issue by xxm101010** [BartoszCichecki/LenovoLegionToolkit#1378]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

last version

### OS

23h2

### Device

Legion R9000P ARX8

### Is your feature request related to a problem?

R9000P has 4  Windows Power Plan
when the game using Balanced Windows Power Mode work better than  Windows Power Plan in Custom mode
but in Quite mode Windows Power Mod not usefull
it doesn’t know how to limit 7945hx  the CPU too hot
so this kind of scene want to use Windows Power Plan

### How would you like the problem to be solved?

more flexible settings with Power Mode Synchronization thx

### What alternatives have you considered?

no

**Comment by BartoszCichecki** [comment]
Windows Power Plans and Power Modes shouldn't be mixed. You need to use one or the other.
