### ISSUE TITLE
Displaying Incorrect Discharge Rate

### ISSUE THREAD

**Issue by Yeeepheee** [BartoszCichecki/LenovoLegionToolkit#1380]
### Rules

- [X] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 23H2 build 22631

### Device

15ACH6H

### BIOS version

GKCN65WW

### What's wrong?

Displays the incorrect battery discharge when using the usb-c
![Screenshot 2024-08-05 171931](https://github.com/user-attachments/assets/f5b42b15-c35b-4814-a680-64e43be92e27)

### How to reproduce the bug?

Charging my laptop with a usb-c cable. I havent checked using ac adapter since im currently away from home. 

Also im not sure if it this version issue or is it because i flashed my vbios.

### What is the behavior that you expected?

I expected something in the postive as i have a 100w usb-c cable

### Logs

[log_2024_08_05_16_41_14.txt](https://github.com/user-attachments/files/16500406/log_2024_08_05_16_41_14.txt)

**Comment by BartoszCichecki** [comment]
Discharge rate is provided by Windows via ACPI functions. If it is incorrect, report it to Lenovo or Microsoft.
