### ISSUE TITLE
Crash only on download menu.

### ISSUE THREAD

**Issue by ryuXmetsu** [BartoszCichecki/LenovoLegionToolkit#1381]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 23H2 (OS BUILD 22631.3958)

### Device

Legion 5

### BIOS version

NMCN22WW

### What's wrong?

Downloads page does not open shows the error attached below. It used to open on factory windows install i reformatted recently and it stopped working.
![Screenshot (1)](https://github.com/user-attachments/assets/8c42e2e3-8fe2-4c88-b660-33f27588d5f2)
About page works as it should but when i exit it from the about page gives a crash message as well. 

### How to reproduce the bug?

1. Open legion toolkit and go to downloads for the first eror
2. Open legion toolkit and go to about page then exit the program 

### What is the behavior that you expected?

It used to work like days ago but after reformatting windows it started throwing errors.

### Logs

[error_2024_08_05_17_08_02.txt](https://github.com/user-attachments/files/16505214/error_2024_08_05_17_08_02.txt)
[error_2024_08_05_17_08_47.txt](https://github.com/user-attachments/files/16505215/error_2024_08_05_17_08_47.txt)

### Additional information

![Screenshot (1)](https://github.com/user-attachments/assets/0ee69728-c0ea-429f-9b41-441fe88036bc)
![Screenshot (2)](https://github.com/user-attachments/assets/6db43455-b8e5-4825-9747-33606148b55e)
![Screenshot (3)](https://github.com/user-attachments/assets/97b4c0e2-3a8a-41b9-ad11-984f19aca2c5)

**Comment by BartoszCichecki** [comment]
Errors indicate that LLT cannot access it's folder where all settings are stored, because permissions are messed up. Fix permissions on that folder and it will work again.

**Comment by ryuXmetsu** [comment]
Thank you for the quick reply. Was able to get it fixed after reinstalling from WingetUI using admin privileges.
