### ISSUE TITLE
加入CPU等温度显示

### ISSUE THREAD

**Issue by luckyandfine** [BartoszCichecki/LenovoLegionToolkit#1383]
### Rules

- [ ] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 10  22H2  19045.4651 

### Device

Legion Y7000 2019 PG0

### Is your feature request related to a problem?

Add CPU and other temperature display

### How would you like the problem to be solved?

Add relevant temperature display to the function page

### What alternatives have you considered?

none

**Comment by BartoszCichecki** [comment]
This is already available on compatible models.
