### ISSUE TITLE
Legion Slim 7 Gen 8 Change Boot Logo Feature Not Showing In Toolkit

### ISSUE THREAD

**Issue by EdwardYaeger** [BartoszCichecki/LenovoLegionToolkit#1384]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 

### Device

Legion Slim 7 16IRH8

### Is your feature request related to a problem?

Whenever I look at posts online that show how to change the boot logo of their Legion's using Toolkit, they are always shown in Gen 6 and 7. I have yet to see a guide for Gen 8 laptops.

### How would you like the problem to be solved?

It would be nice to have this feature on Gen 8 Legion models as well.

### What alternatives have you considered?

There's some tutorials online that show a different method but they look kinda sketchy to be honest and I feel more comfortable to do this  method instead.

### Additional information

![Screenshot 2024-08-07 160020](https://github.com/user-attachments/assets/459109e2-57f3-4d4a-9a8f-ee7b2801abdf)
![Screenshot 2024-08-07 155754](https://github.com/user-attachments/assets/0ccff4c1-dbb6-41ac-87f6-af5cbb25c927)

**Comment by BartoszCichecki** [comment]
Read the readme - this is not available on Gen 8.

**Comment by EdwardYaeger** [comment]
Ah i see.  Thank you very much for the reply!
