### ISSUE TITLE
[FEAT]: Add dependabot.yml to automatically detect and update dependencies

### ISSUE THREAD

**Issue by YisusChrist** [BartoszCichecki/LenovoLegionToolkit#1387]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows 11 23H2 Build 22631.2861

### Device

Legion 5 Pro 16ARX8

### Is your feature request related to a problem?

No problems to be reported, just a mere suggestion for automatism and to improve the project maintainability

### How would you like the problem to be solved?

DotNet dependencies (declared in the csproj file) used by the application can become outdated very easily. Same happens to the dependencies used in the repository actions. Using a dependabot.yml, which is completely supported by Github, will help to effortlesly detect the new versions and update them with automatic pull requests.

Additionally, with some little tweaks and another Github action, it is possible to automatically merge those pull requests to keep the project always updated.

### What alternatives have you considered?

Just the dependabot file, nothing else

### Additional information

I will open a pull requests with the changes suggested.

**Comment by BartoszCichecki** [comment]
Closing, comment in the PR.
