### ISSUE TITLE
Lenovo Ideapad 3 14ITL05 Not compatible with legion toolkit

### ISSUE THREAD

**Issue by pbk123461** [BartoszCichecki/LenovoLegionToolkit#1390]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.23.1

### OS

Windows 11 23H2 22631.3880

### Device

Lenovo Ideapad 3 14ITL05

### BIOS version

LENOVO GCCN32WW, 11/18/2022

### Which features of the application did you test?

It said device not compatible, i couldn't even get in the application

### Which features of the application do not work as expected?

everything

**Comment by BartoszCichecki** [comment]
"I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups." 🤨
