### ISSUE TITLE
PUA found during winget installation

### ISSUE THREAD

**Issue by amzon-ex** [BartoszCichecki/LenovoLegionToolkit#1391]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

Windows 11 build 26120.1350

### Device

Legion 5 15ACH6H

### BIOS version

HHCN37WW

### What's wrong?

PUA warning is thrown when trying to install update to LLT (2.23.0 -> 2.23.1) via winget. Screenshot of warning attached.
![image](https://github.com/user-attachments/assets/24df6bf3-f350-4cc2-a1eb-b92a305386e0)

Update fails, presumably because the temporary file is isolated by Windows Defender.

### How to reproduce the bug?

Try to install update to version 2.23.1 using winget.

### What is the behavior that you expected?

Update installs and no PUA warning is raised.

### Logs

Don't see how to log this issue using the standard method. Let me know if there is another way I can use.

**Comment by BartoszCichecki** [comment]
This is the same case as false positives from Windows Defender. Explanation here: https://github.com/BartoszCichecki/LenovoLegionToolkit?tab=readme-ov-file#why-is-my-antivirus-reporting-that-the-installer-contains-a-virustrojanmalware
