### ISSUE TITLE
GPU Configurable TGP does not go into the negative

### ISSUE THREAD

**Issue by TheIndiv** [BartoszCichecki/LenovoLegionToolkit#1392]
### Rules

- [x] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows 11 Home 22631.3880

### Device

Legion 5 15ITH6H

### Is your feature request related to a problem?

GPU Configurable TGP does not go into the negative

### How would you like the problem to be solved?

GPU Configurable TGP should be allowed to go into the negative

### What alternatives have you considered?

I tried MSI Afterburner to reduce the power limit of the GPU but I can't find a way to enable the sliders. I think Lenovo is just being a dick?

**Comment by BartoszCichecki** [comment]
If it doesn't go into negative, then it isn't allowed by Lenovo. So your conclusion is kinda correct...
