### ISSUE TITLE
Legion Y540 15IRH-PGO - Compatible

### ISSUE THREAD

**Issue by DarkVader-cell** [BartoszCichecki/LenovoLegionToolkit#1393]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.23.1

### OS

Windows 10 Pro 22H2

### Device

Legion Y540 15IRH-PGO

### BIOS version

BHCN45WW

### Which features of the application did you test?

- The Power Mode changes and shortcuts work fine, I was able to switch Performance modes accordingly
- Battery Mode was set to "Conservation", I can confirm that the battery charging was limited to 60%.
- Hybrid/Discrete GPU works fine, I could disable by dGPU and see what was running on it as well.
- All other misc features such as Disable Microphone, Keyboard shortcuts etc work as intended.
- The battery statistics are also provided accurately. 

### Which features of the application do not work as expected?

Everything works fine as intended. The only features missing are the ones not supported by the Legion Y540 firmware and hardware.

**Comment by BartoszCichecki** [comment]
Log is missing, additionally 15IRH is [already whitelisted](https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/c1b4b373e3aa4100b63f71fbf4d0159760e6954c/LenovoLegionToolkit.Lib/Utils/Compatibility.cs#L55).

**Comment by BartoszCichecki** [comment]
I can't do anything without a log.
