### ISSUE TITLE
Keyboard backlight resets on Legion 5 Pro 16ARH7H 

### ISSUE THREAD

**Issue by FrozenAlex** [BartoszCichecki/LenovoLegionToolkit#1395]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Microsoft Windows 11 Pro 10.0.22631 Build 22631

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN66WW

### What's wrong?

After the LLT starts, after some time the keyboard backlight gets reset to a default rolling rgb effect and switching the mode does not work. All of the lenovo services seem to be disabled

### How to reproduce the bug?

1. Boot the system, LLT starts up.
2. After some time the keyboard resets to default lighting profile.
3. Go to LLT and try to change the backlight and it crashes it.
4. After the app restart, backlight works again.

### What is the behavior that you expected?

I expected the backlight to not be reset to default

### Logs

[error_2024_08_16_03_40_04.txt](https://github.com/user-attachments/files/16632650/error_2024_08_16_03_40_04.txt)
[error_2024_08_16_03_36_54.txt](https://github.com/user-attachments/files/16632651/error_2024_08_16_03_36_54.txt)
[error_2024_08_15_18_18_58.txt](https://github.com/user-attachments/files/16632652/error_2024_08_15_18_18_58.txt)
[error_2024_08_15_18_18_55.txt](https://github.com/user-attachments/files/16632653/error_2024_08_15_18_18_55.txt)

### Additional information

![image](https://github.com/user-attachments/assets/e0ac20c5-08c2-4afe-aacc-1f2dabb0a61c)
![image](https://github.com/user-attachments/assets/15149b89-45df-402f-b577-e08c39d4e61b)

**Comment by FrozenAlex** [comment]
It seems to reliably happen when going out of sleep mode

**Comment by GH-NNG** [comment]
i am a user of legion 5 pro 16 arh7h
ig same bios, issue never happens to me, rarely or with an improper shutdown or restart, until the device bootsup, the keyboard lighting profiles cycle in the default lenovo ones, but once it boots up or after sign-in (not sure which), the keyboard lighting is controlled by the profiles in LLT

**Comment by GH-NNG** [comment]
> i am a user of legion 5 pro 16 arh7h ig same bios, issue never happens to me, rarely or with an improper shutdown or restart, until the device bootsup, the keyboard lighting profiles cycle in the default lenovo ones, but once it boots up or after sign-in (not sure which), the keyboard lighting is controlled by the profiles in LLT

this is not an issue for me, and i personally dont call it a bug, but what u have mentioned was something different, i am just mentioning it has never happened to me, the way it did for u

**Comment by FrozenAlex** [comment]
Well for me it dies after some time running. It works fine for a bit and then dies

**Comment by BartoszCichecki** [comment]
This isn't something that is "fixable". Communication with RGB keyboard is pretty low-level - it doesn't require any drivers, but instead utilizes USB HID messages. If keyboard resets and you encounter this type of error, it basically means that LLT tried to send a command, but keyboard didn't respond.

It _usually_ indicates hardware issue, especially if it happens all the time. Additionally, as stated in the README, some anti-cheats hinder communication with RGB controller.

This issue was already reported in other tickets like #862, #703.
