### ISSUE TITLE
Incorrect temperature reading

### ISSUE THREAD

**Issue by Fortex365** [BartoszCichecki/LenovoLegionToolkit#1396]
### Rules

- [X] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.0

### OS

23H2

### Device

Legion 5 Pro 16ACH6H

### BIOS version

GKCN60WW

### What's wrong?

When launching application the temperature spike is showing incorrect unreal data. Usually around 10°C higher. Comparison with Ryzen Controller

### How to reproduce the bug?

-

### What is the behavior that you expected?

-

### Logs

-

**Comment by BartoszCichecki** [comment]
Temperatures are exposed by Lenovo APIs, so they aren't incorrect. They are used by EC to adjust fan speeds among other things.
