### ISSUE TITLE
Conservative (80%) Battery option missing after updating BIOS to KWCN46WW

### ISSUE THREAD

**Issue by DiegcD** [BartoszCichecki/LenovoLegionToolkit#1401]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows 11 23h2 22631.4037

### Device

Legion 5 Pro 16IRX8

### BIOS version

KWCN46WW

### What's wrong?

After updating BIOS my laptop charged to 100% when before I selected to 80%. I opened LLT to check if the option was changed. Then I noticed the option was missing after updating the BIOS.

Hopefully you can restore the option again in an update.

### How to reproduce the bug?

1. Update to BIOS KWCN46WW
2. Option to limit charge to 80% is missing in LLT

### What is the behavior that you expected?

The option to appear in LLT and it to work correctly.

### Logs

Sorry, using GitHub from mobile.

**Comment by BartoszCichecki** [comment]
Nothing to do without logs.
