### ISSUE TITLE
LenovoLegionToolkit did not detect the status of the logo light toggled using Fn+L.

### ISSUE THREAD

**Issue by bj114514** [BartoszCichecki/LenovoLegionToolkit#1402]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows 11 23H2 (22631.3958)

### Device

R900P(2023) ARX8

### Is your feature request related to a problem?

I enabled all the disabled options in Lenovo Legion Toolkit. When I use Fn+L to turn the logo backlight on or off, the switch in Lenovo Legion Toolkit does not change, and there is no option for the logo light in the pop-up prompt. However, this problem does not occur in Lenovo Hotkeys.

### How would you like the problem to be solved?

Real-time detection of the status of the logo light and add a logo light option in the pop-up prompt options.

### What alternatives have you considered?

I can use Lenovo Hotkeys, but they are too ugly and cannot be customized. Therefore, I hope LenovoLegionToolkit can add this feature.

**Comment by BartoszCichecki** [comment]
I don't see his is this a feature request? I guess you wanted to report a bug? In this case attach logs.

**Comment by BartoszCichecki** [comment]
Closing due to lack of response from the author.
