### ISSUE TITLE
Can Legion 7 16IAX7 support Custom Mode

### ISSUE THREAD

**Issue by A10Nec37** [BartoszCichecki/LenovoLegionToolkit#1404]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.23.1

### OS

Windows 11 22H2 build 22621

### Device

Legion 7 16IAX7

### BIOS version

K1CN48WW

### Which features of the application did you test?

I'd like to use Custom Mode to control my fans curve

### Which features of the application do not work as expected?

Custom Mode

**Comment by BartoszCichecki** [comment]
It does. Also, this isn't place for questions.
