### ISSUE TITLE
Turn off RGB when charger is disconnected

### ISSUE THREAD

**Issue by calyrex-s** [BartoszCichecki/LenovoLegionToolkit#1406]
### Rules

- [x] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows 11 24H2

### Device

Legion Pro 5 16ARX8

### Is your feature request related to a problem?

Some laptops have the option to reduce the refresh rate to 60hz and to turn off RGB when the charger is disconnected.

### How would you like the problem to be solved?

It would be nice if you add an option to switch resolution to 60HZ and and another option to turn off RBG backlight automatically when the charger is disconnected.

### What alternatives have you considered?

Idk.

**Comment by BartoszCichecki** [comment]
It's already there. It's called actions.
