### ISSUE TITLE
Choose a custom colour for the power modes and a shortcut to turn off the LED

### ISSUE THREAD

**Issue by Ashokaas** [BartoszCichecki/LenovoLegionToolkit#1408]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.23.1

### OS

Windows 23H2 build 22631.4037

### Device

Legion Pro 5 16IRX8

### Is your feature request related to a problem?

When I use my PC at night to watch films, for example, I always have this very bright LED on the power button. What's more, it's impossible to choose a power option with FN+Q, you have to go through LLT.

### How would you like the problem to be solved?

I would like a way of turning the LED on/off with a shortcut like (FN+L) or similar. I would also like to be able to switch to a personalised power mode with FN+Q and even several personalised modes with the option of choosing the colour of each mode. 

### What alternatives have you considered?

None

### Additional information

None

**Comment by BartoszCichecki** [comment]
Changing brightness or color of power LED isn't possible.
