### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by DeanRelax** [BartoszCichecki/LenovoLegionToolkit#141]
**Describe the bug**
Upon starting Lenovo Legion Toolkit, an error pops up. LLT works as intended as long as I don't close the error message. If the error message is closed (by clicking OK on the pop-up) LLT also closes after a few seconds.

I have tried LLT versions 2.2.0 and 2.2.1, and the issue is reproducible on both versions. Earlier I've been using versions 1.7.2 and lower, which worked fine and did not give any error messages.

**To Reproduce**
Steps to reproduce the behavior:  Start LLT from the shortcut on the desktop.

**Expected behavior**

LLT to start without any error messages poping up.

**Screenshots**

![image](https://user-images.githubusercontent.com/1932135/177006806-0b4a6ecc-7f9c-432f-bb42-c0c47a3347c1.png)

**Environment**
 - OS: Microsoft Windows 10 Home 10.0.19044 Build 19044
 - Laptop model: LENOVO_MT_82JQ_BU_idea_FM_Legion 5 Pro 16ACH6H
 - .NET version: 5.0.402
 - Do you have Vantage installed?: Yes

**Logs**

[error_2022_07_02_17_17_18.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9033209/error_2022_07_02_17_17_18.txt)
[log_2022_07_02_17_17_17.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9033210/log_2022_07_02_17_17_17.txt)

**Comment by BartoszCichecki** [comment]
Yup looks like a bug. What power plans do you have on your system?

**Comment by BartoszCichecki** [comment]
Hey @DeanRelax,

I have troubles reproducing your issue. Can you please try this early build of 2.3.0 and paste logs that it creates?

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9095149/LenovoLegionToolkitSetup.zip)

**Comment by DeanRelax** [comment]
I have 4 power plans listed:

Balanced
Legion Balance Mode
Legion Performance Mode
Legion Quiet Mode

The issue can replicated while using each power plan.

I might gave been changing the settings for plans in the past. Is there any setting in particular that you think could interfere with LLT?

I downloaded the beta-version of LLT from your comment, but it doesn't seem to change anything in regards to the issue.
[log_2022_07_31_17_44_02.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9229214/log_2022_07_31_17_44_02.txt)

**Comment by BartoszCichecki** [comment]
I have a real hard time reproducing the issue and figuring out what is wrong, so please try this version too:
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9229231/LenovoLegionToolkitSetup.zip)

It will also crash, but maybe it will give a hint about what's going to.

**Comment by DeanRelax** [comment]
Ran it and here's the logs:
[log_2022_08_02_18_17_26.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9243985/log_2022_08_02_18_17_26.txt)
[error_2022_08_02_18_17_27.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9243989/error_2022_08_02_18_17_27.txt)

**Comment by BartoszCichecki** [comment]
Thanks a lot! I think this build might fix the issue, but even if it works please attach logs, because I need to figure out the root cause.

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9244310/LenovoLegionToolkitSetup.zip)

**Comment by BartoszCichecki** [comment]
Also do you have Vantage installed?

**Comment by BartoszCichecki** [comment]
OK, so I am kind of loosing my mind here :D

So here is the plan:
1. Try this build: [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9245221/LenovoLegionToolkitSetup.zip)
 2. Paste logs here.
 3. If it doesn't work uninstall LLT completely from your system. Make sure that `%LocalAppData%\LenovoLegionToolkit` does not exist, `%LocalAppData%\Programs\LenovoLegionToolkit` folders are gone.
 4. Try the build from step 1 again.

It seem like no one else reported or has this issue and looking at the latest logs, the thing that happens for you should never happen, but let's see where this takes us. I am really curious about the reason.

**Comment by BartoszCichecki** [comment]
OK, so I am kind of loosing my mind here :D

So here is the plan:
1. Try this build: [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9245349/LenovoLegionToolkitSetup.zip)
 2. Paste logs here.
 3. If it doesn't work uninstall LLT completely from your system. Make sure that `%LocalAppData%\LenovoLegionToolkit` does not exist, `%LocalAppData%\Programs\LenovoLegionToolkit` folders are gone.
 4. Try the build from step 1 again.

It seem like no one else reported or has this issue and looking at the latest logs, the thing that happens for you should never happen, but let's see where this takes us. I am really curious about the reason.

**Comment by BartoszCichecki** [comment]
Try 2.3.0 once it's released. If issue is not resolved there, reopen this ticket.

**Comment by DeanRelax** [comment]
Hi again. Just wanted to drop by and inform you that I've just tried version 2.3.1, and the error message no longer pops up. Everything works as intended. Thank you for your great support, and thank you for developing this great application!

Btw. have you considered adding functionality to disable/enable Nvidia Ampere dynamic boost and CPU boost? If so, I could stop using LegionFanControl and solely rely on LLT.

**Comment by BartoszCichecki** [comment]
For some BIOSes (GKCN and HHCN) there will be feature added called "Custom Power Mode" which is available in Legion Zone. It turns power button pink/purple and allows you to adjust CPU and GPU power limits.

Looking that you also have a Legion 5 Pro, you will be able to use it in 2.4.0 :)
