### ISSUE TITLE
Group of improvements on LLT update checker

### ISSUE THREAD

**Issue by Ace-Radom** [BartoszCichecki/LenovoLegionToolkit#1410]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.0

### OS

Windows 11 23H2

### Device

Legion R9000p 2021H

### Is your feature request related to a problem?

Current update checker of LLT is kinda inconvenient. LLT only checks new vesion on startup & reopening LLT window & opening tray menu with an interval of 3 hours. There's no other way to trigger an update check manually & intuitively. This is a bit unfriendly for users in regions where don't have a stable connection to github api.

### How would you like the problem to be solved?

A `Check Updates` button in settings page should be added, I think. Btw I'm also planning to do a group of small improvements to this feature, such as allow user to change the update check interval & disable update check in settings. Plz let me know if those functions are considered. I'm working on this for now, and it will be finished in days.

### What alternatives have you considered?

/

**Comment by BartoszCichecki** [comment]
The check for updates button is a good idea. 


Regarding setting for disabling updates I am against. There is already an argument for turning updates off (which should also hide the check for updates button) for those who really want to do it. 

Regarding frequency setting. We can have that as long as the minimum is 3 hours. GitHub has some rate limiting so checking shouldn't be happening too often.
