### ISSUE TITLE
Fn+Q hotkey notification pop up 

### ISSUE THREAD

**Issue by baraakh30** [BartoszCichecki/LenovoLegionToolkit#1414]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.0

### OS

Windows 11 pro build 26100

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

Yes , when pressing Fn + Q the power plan does change but no pop up apears as when we close the microphone for example

### How would you like the problem to be solved?

When Fn+Q is pressed show a pop up indicates which plan is currently on 

### What alternatives have you considered?

I didnt

**Comment by BartoszCichecki** [comment]
Notifications are configureable in settings. Please pay more attention next time to what can you configure before making new issues.
