### ISSUE TITLE
Application domain error

### ISSUE THREAD

**Issue by Alpen1** [BartoszCichecki/LenovoLegionToolkit#1418]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.0

### OS

Windows 11 Home 22621

### Device

Legion Pro 5 16ARX8

### BIOS version

LPCN44WW

### What's wrong?

Decided to update the program after few months. While disconnecting a xbox controller, the Toolkit froze with nothing but an empty box being shown. Then it showed me 3 errors. I was only able to screenshot 2/3 errors. This is the first time this program has crashed on me in the past year. 
![Screenshot 2024-08-31 005111](https://github.com/user-attachments/assets/0f9f23cd-662f-4ad5-9f51-30c42b7e0842)
![Screenshot 2024-08-31 005130](https://github.com/user-attachments/assets/ee942ecd-087c-42fd-869d-3d356cfb162f)

### How to reproduce the bug?

Haven't tried reproducing

### What is the behavior that you expected?

Expected nothing to happen while disconnecting the controller.

### Logs

[error_2024_08_31_05_51_18.txt](https://github.com/user-attachments/files/16823594/error_2024_08_31_05_51_18.txt)
[error_2024_08_31_05_51_19.txt](https://github.com/user-attachments/files/16823595/error_2024_08_31_05_51_19.txt)
[error_2024_08_31_05_50_55.txt](https://github.com/user-attachments/files/16823596/error_2024_08_31_05_50_55.txt)

**Comment by BartoszCichecki** [comment]
Hey, thanks for the report.

Unfortunately I can't do anything about it. Render thread failure indicates a low level crash, usually cause by one of the display drivers. The best I can recommend here is to update your drivers and keep fingers crossed.
