### ISSUE TITLE
Display blank when switching automatically from 165hz to 60hz when being unplugged

### ISSUE THREAD

**Issue by FallibleElf2988** [BartoszCichecki/LenovoLegionToolkit#142]
My Legion 5 82JU0191IN(5800H,3060)'s display goes blank when i kept an action to switch from 165hz to 60hz when the laptop is on battery. Suprisingly, it works the other way around and it was perfectly working fine yesterday. I'm on windows 11 and i have done two windows cumulative update(currently on June 23, 2022—KB5014668 (OS Build 22000.778) Preview Build)

**To Reproduce**
1. Unplug the battery
2. Kaboom display goes blank
3. Brings up some billion errors and it goes haywire and increases the zoom of the display and proceeds to freeze. I have to boot into bios and select "Dynamic Graphics"

**Expected behavior**
Simply switching from 165hz to 60hz on battery mode. Nothing too complicated lmao.

**Screenshots**
![image](https://user-images.githubusercontent.com/108755835/177384259-430f34f9-6f4c-4559-91bb-442dde8f4282.png)

**Environment (please complete the following information):**
 - OS: Win11 OS Build 22000.778
 - Laptop model: Legion 5 82JU0191IN
 - .NET version: [e.g. 5.0.408] idk what u mean by this
 - Do you have Vantage installed? [Yes/No] No

**Logs**
You might consider running with `--trace` parameter and attaching the log files. See README for details. idk what to fill in here lol im such a boomer

EDIT: This issue doesn't happen in Hybrid mode on(dgpu disabled, igpu enabled)

**Comment by BartoszCichecki** [comment]
![image](https://user-images.githubusercontent.com/7916915/177385265-3a30861d-e7a3-41eb-8fa7-471cd1cf5c1a.jpeg)

**Comment by FallibleElf2988** [comment]
> ![image](https://user-images.githubusercontent.com/7916915/177385265-3a30861d-e7a3-41eb-8fa7-471cd1cf5c1a.jpeg)

yeah i edited the message
and light mode 💀

**Comment by DJPillu** [comment]
Legion 7-16ITHg6
Oh, I wasn't sure what was producing the error. I believe something else is causing this as well. 
Without trying to change the refresh rate while plugged in, I received the same error message after the app crashed. This is seemingly randomly happened to me a couple of times.
![Screenshot 2022-07-07 000114](https://user-images.githubusercontent.com/44135684/178079279-ea678581-6d50-4f4a-8f0c-44a2d966fe97.png)

**Comment by BartoszCichecki** [comment]
Hmmm, both your errors indicate problems originating from Desktop Windows Manager (dwm.exe). It will be tricky to diagnose properly because these usually indicate that dem does and is restarted - usually because of graphics driver.

What GPUs and GPU drivers do you have?

**Comment by DJPillu** [comment]
> Hmmm, both your errors indicate problems originating from Desktop Windows Manager (dwm.exe). It will be tricky to diagnose properly because these usually indicate that dem does and is restarted - usually because of graphics driver.
> 
> What GPUs and GPU drivers do you have?

I have an Nvidia RTX 3080 - driver version 516.59
and i7 11800H integrated intel graphics - driver version 30.0.101.1003
