### ISSUE TITLE
LLT doesnt check App Paths

### ISSUE THREAD

**Issue by Pretentiousness** [BartoszCichecki/LenovoLegionToolkit#1420]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.0

### OS

Windows 11 23h2

### Device

Legion 7 16ITHg6

### BIOS version

H1CN58WW

### What's wrong?

LLT doesnt check `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths` and `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\App Paths` for application paths when using the "Run" action feature.

### How to reproduce the bug?

just try to run any application by using application's executable file name which is already mapped in "App Paths" registry but it throws errors.

### What is the behavior that you expected?

it correctly finds the mapped path value from registry

### Logs

[log_2024_09_01_18_50_01.txt](https://github.com/user-attachments/files/16830152/log_2024_09_01_18_50_01.txt)
[log_2024_09_01_18_46_19.txt](https://github.com/user-attachments/files/16830153/log_2024_09_01_18_46_19.txt)

**Comment by BartoszCichecki** [comment]
Hey, thanks for the report.

LLT relies on .NET framework to start apps, so checking of all PATHs is something the .NET team is responsible for. If that really is that case that not all PATHs are checked, you might want to report it to the .NET team: https://github.com/dotnet/runtime
