### ISSUE TITLE
BUG] Legion R9000P ARX8, Lenovo Legion Toolkit 2.24.0 is switched to quiet mode, the CPU frequency will stabilize and trigger the BUG of locking 🔒0.5GHz. The power plan is switched to balanced mode, which is invalid.

### ISSUE THREAD

**Issue by n1ko61** [BartoszCichecki/LenovoLegionToolkit#1422]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.0

### OS

Windows 11 Professional Workstation Edition 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)

### Device

Legion R9000P ARX8

### BIOS version

LPCN52WW

### What's wrong?

**BUG] Legion R9000P ARX8, Lenovo Legion Toolkit 2.24.0 is switched to quiet mode, the CPU frequency will stabilize and trigger the BUG of locking 🔒0.5GHz. The power plan is switched to balanced mode, which is invalid.**
![Clip_2024-09-03_09-50-14](https://github.com/user-attachments/assets/fa222140-5cad-4c2b-a618-0ee29e327b8d)
**I collected some comments on related issues in Bilibili, which mentioned that it might be related to the USB motherboard. Replugging or replacing a new USB motherboard might solve the problem. I decided to try this method another day.**
![image](https://github.com/user-attachments/assets/8b80da5c-aec8-474d-a3e4-4229ac63452e)

### How to reproduce the bug?

Switching to quiet mode by pressing Fn+Q, or manually switching to quiet mode on Lenovo Legion Toolkit or Legion Zone, will trigger the CPU frequency lock to 0.5GHz BUG

### What is the behavior that you expected?

I would like to confirm the cause of this BUG, ​​whether it is caused by Lenovo Legion Toolkit or a failure of the UBS motherboard.

### Logs

[log_2024_09_03_03_07_47.txt](https://github.com/user-attachments/files/16842991/log_2024_09_03_03_07_47.txt)

### Additional information

![Clip_2024-09-03_09-50-14](https://github.com/user-attachments/assets/e96d18a8-c588-4e16-b32e-31feee90d9a7)

**Comment by n1ko61** [comment]
OS：Windows 11 Professional Workstation Edition 64-bit  23H2

**Comment by BartoszCichecki** [comment]
I don't know what are you asking. I don't know what causes this behaviour. Switching to Quiet mode shouldn't lock your CPU to 0.5GHz and LLT does not control CPU clocks, so the issue is somewhere else. I have no clue about whether the USB board has anything to do with it.

If this is just a question, then next time, start a Discussion - DO NOT report "bugs" if you are not sure that this is a bug in LLT.

**Comment by n1ko61** [comment]
thanks for your reply
