### ISSUE TITLE
User mode problem

### ISSUE THREAD

**Issue by IZOBILIE777** [BartoszCichecki/LenovoLegionToolkit#1426]
### Rules

- [X] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.0.0

### OS

windows 10 20h2

### Device

legion 5 17ITH6H

### BIOS version

H1CN45WW

### What's wrong?

I created a custom mode and configured specific values ​​for CPU power consumption in LenovoLegionToolkit. But when using this mode, the long-term power limit parameter automatically changes its value. Indicated in the screenshot. Help me solve this problem and write down the values.
The Total Stop program cannot influence the power consumption of the processor because I did not make any changes to it, and I only use it to track power consumption values.

![image_2024-09-04_17-43-52](https://github.com/user-attachments/assets/9d87527a-4a44-41fb-aee0-6a075e7e4483)

### How to reproduce the bug?

.

### What is the behavior that you expected?

.

### Logs

.

**Comment by BartoszCichecki** [comment]
1. You didn't attach logs
2. You didn't write down how to reproduce the bug
3. I can see you use ThrottleStop which (depending on it's settings) might override Custom mode preset

**Comment by IZOBILIE777** [comment]
> 1. You didn't attach logs
> 2. You didn't write down how to reproduce the bug
> 3. I can see you use ThrottleStop which (depending on it's settings) might override Custom mode preset

The Total Stop program cannot influence the power consumption of the processor because I did not make any changes to it, and I only use it to track power consumption values.

**Comment by BartoszCichecki** [comment]
If you keep ignoring questions that I ask, we are not going to get anywhere.

**Comment by BartoszCichecki** [comment]
1. All instructions are in the readme
2. When making an issue, fill out all form fields and provide as much info as possible
3. Stick to english

**Comment by IZOBILIE777** [comment]
Please tell me which models support changing the power mode to custom
using the FN + Q key combination


чт, 5 сент. 2024 г. в 10:46, Bartosz Cichecki ***@***.***>:

**Comment by IZOBILIE777** [comment]
Hello, please tell me which models support changing the power mode to
custom using the FN + Q key combination?

чт, 5 сент. 2024 г. в 10:46, Bartosz Cichecki ***@***.***>:

**Comment by BartoszCichecki** [comment]
I don't keep track of things like that. If it's supported, you will see an option in settings.
