### ISSUE TITLE
Working GPU Mode/Hybrid Mode is not showing for 16ARP9

### ISSUE THREAD

**Issue by tqvu** [BartoszCichecki/LenovoLegionToolkit#1430]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Windows 11 Home

### Device

Legion Slim 5 16ARP9

### BIOS version

NUCN09WW

### What's wrong?

Working GPU Mode option is not displaying under Graphics in the LLT home screen. Manually adding in GPU Working Mode in Dashboard Customization does not add it.

### How to reproduce the bug?

1. Open LLT
2. Working GPU Mode is not showing in home screen.

### What is the behavior that you expected?

Working GPU Mode displays in home screen.

### Logs

NA

**Comment by BartoszCichecki** [comment]
There is nothing I can do without a log.
