### ISSUE TITLE
"Hybrid Auto Mode" misjudges the power status

### ISSUE THREAD

**Issue by Dawn5ky** [BartoszCichecki/LenovoLegionToolkit#1434]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Windows 11 23H2 build 22631

### Device

Legion Y7000P IRX9 (83DG)

### BIOS version

NMCN21WW

### What's wrong?

When I adjust the battery mode to “Conservation” and adjust the working mode of the graphics card to “Hybrid Auto Mode”, the graphics card (RTX4070Laptop) will frequently go offline from the off state and reboot to hibernate state when it's idle, and the problem can be solved when I manually switch to “Hybrid Mode” or “Hybrid iGPU Mode”. I think there is a problem with “Hybrid Auto Mode” determining the power state in “Conservation” mode.

### How to reproduce the bug?

1. Go to dashboard page
2. Switch the battery mode to "Conservation"
3. Switch the GPU working mode to "Hybrid Auto Mode"

### What is the behavior that you expected?

The graphics card should remain “Powered Off” and not go offline, i.e. “Hybrid Mode” behavior (since I have the charger plugged in but the battery remains at 80%).

### Logs

[log_2024_09_10_07_03_30.txt](https://github.com/user-attachments/files/16940828/log_2024_09_10_07_03_30.txt)

### Additional information

![3925BD782596C950A1372E98E2948B1F](https://github.com/user-attachments/assets/1ad9968a-ce5b-41c3-a851-706f70a80013)

**Comment by BartoszCichecki** [comment]
Battery mode and Hybrid modes have nothing in common.

> The graphics card should remain “Powered Off” and not go offline, i.e. “Hybrid Mode” behavior (since I have the charger plugged in but the battery remains at 80%).

I agree, but this isn't something that LLT controls.

**Comment by Dawn5ky** [comment]
I think the problem can be solved by detecting if Windows “smart charging” is on, for example when smart charging is on Hybrid Auto Mode will simply assume that it is connected to the power supply and follow the logic of Hybrid Mode.

**Comment by Dawn5ky** [comment]
> Battery mode and Hybrid modes have nothing in common.
> 
> > The graphics card should remain “Powered Off” and not go offline, i.e. “Hybrid Mode” behavior (since I have the charger plugged in but the battery remains at 80%).
> 
> I agree, but this isn't something that LLT controls.

I think the problem can be solved by detecting if Windows “smart charging” is on, for example when smart charging is on Hybrid Auto Mode will simply assume that it is connected to the power supply and follow the logic of Hybrid Mode.

**Comment by BartoszCichecki** [comment]
It can't, because connecting disconnecting is controlled by EC, not by LLT.

**Comment by Dawn5ky** [comment]
But I think just switching to Hybrid Mode solved the problem, which makes me confused

**Comment by Dawn5ky** [comment]
That's ok, nevermind :)
