### ISSUE TITLE
Disable Windows Key not working correctly?

### ISSUE THREAD

**Issue by dank-tagg** [BartoszCichecki/LenovoLegionToolkit#1438]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Edition	Windows 11 Home Version	23H2 Installed on	‎8/‎18/‎2024 OS build	22631.4169 Experience	Windows Feature Experience Pack 1000.22700.1034.0

### Device

Legion Y9000P IRX9

### BIOS version

N0CN24WW

### What's wrong?

The disable Windows Key isn't working correctly. No response at all.

### How to reproduce the bug?

Toolkit -> Actions -> Add new -> When game is running, disable windows key -> test manually with game open + run now -> no response at all, windows key still works.

BUT, the manual button still works, in the main tab

### What is the behavior that you expected?

Windows key gets disabled.

### Logs

[log_2024_09_16_19_46_52.txt](https://github.com/user-attachments/files/17019055/log_2024_09_16_19_46_52.txt)

### Additional information

https://github.com/user-attachments/assets/de92bf1b-1042-47dd-9211-ec93ed1badb4

https://github.com/user-attachments/assets/3b9bb5dd-fa58-4da2-b21b-8e45b3325782

**Comment by Ace-Radom** [comment]
Hmm...I would rather say the description is not correct. If you switch to `On` Win-key is disabled at least on my device. Maybe we can just change the description to `Disable Windows key on built-in keyboard`.
