### ISSUE TITLE
Legion 5 Pro 16IAH7H Compatability

### ISSUE THREAD

**Issue by dipaktapase** [BartoszCichecki/LenovoLegionToolkit#1446]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.24.1

### OS

Windows 11 22H2 Build 22621

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN57WW

### Which features of the application did you test?

All features seem to be functional.

### Which features of the application do not work as expected?

No features found to not work.

**Comment by BartoszCichecki** [comment]
This model is supported for years now. You also didn't include any logs, so nothing I can do here.

**Comment by dipaktapase** [comment]
I'm getting this when I start the LLT
![Screenshot 2024-09-27 154807](https://github.com/user-attachments/assets/1c9938e1-4a23-405c-b3ff-57f247036035)
[log_2024_09_27_02_36_09.txt](https://github.com/user-attachments/files/17162743/log_2024_09_27_02_36_09.txt)


If you could add this in next release so It can stop giving unsupported device pop up at the beginning
If you could do that, I would greatly appreciate it.

**Comment by BartoszCichecki** [comment]
You probably had your motherboard replaced which is why your model name is not set properly. It will not be added, but you can disable this warning. Instructions are in the readme.
