### ISSUE TITLE
Software quits unexpectedly after running automation

### ISSUE THREAD

**Issue by zzhzero** [BartoszCichecki/LenovoLegionToolkit#1448]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Microsoft Windows 11 10.0.22631 Build 22631

### Device

Legion Y9000P IAH7H

### BIOS version

J2CN57WW

### What's wrong?

Software exit

### How to reproduce the bug?

![image](https://github.com/user-attachments/assets/6b62c360-c1e0-4e5f-a41a-07f2973957a2)
When I set it to RED and open hdr, there is a probability that the software will exit in the background and exit hdr mode at the same time.

### What is the behavior that you expected?

Software runs normally

### Logs

[log_2024_09_27_10_41_36.txt](https://github.com/user-attachments/files/17162968/log_2024_09_27_10_41_36.txt)

**Comment by Ace-Radom** [comment]
@zzhzero the log you uploaded reports nothing, make sure that you've already closed the running LLT before starting catching the log. Please catch a new one and upload it here / replace the wrong one in your issue, otherwise we could find nothing.

**Comment by BartoszCichecki** [comment]
Closing due to lack of response from author.
