### ISSUE TITLE
Intergrated Camera doesn't work when LLT is handling 

### ISSUE THREAD

**Issue by SleepDaemon** [BartoszCichecki/LenovoLegionToolkit#1449]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.1

### OS

Windows 11 23H2 (Build 22631.4169)

### Device

Legion Y540-15IRH Type 81SX

### BIOS version

BHCN45WW

### What's wrong?

The camera is showing it is disabled via the Fn hotkey by lenovo, and when I try doing it doesnt enable.
![image](https://github.com/user-attachments/assets/e721d691-4317-4abc-978e-e161ffbd143d)

### How to reproduce the bug?

Just use camera in general

### What is the behavior that you expected?

Camera should show a video feed instead of greyed background with camera disabled icon

### Logs

[log_2024_10_01_07_39_03.txt](https://github.com/user-attachments/files/17201229/log_2024_10_01_07_39_03.txt)

**Comment by BartoszCichecki** [comment]
As written in the readme laptops older than Gen 5, might be able to use LLT, but it is provided as-is and no development is done for these devices. Your laptop is Gen 5.
