### ISSUE TITLE
Suddenly the automatic action to restart the dGPU when disconnecting AC stopped working

### ISSUE THREAD

**Issue by Dampfinchen** [BartoszCichecki/LenovoLegionToolkit#145]
**Describe the bug**
Yesterday it did work perfectly on the same version, but now for some strange reason, my automatic action isn't working anymore. But only when I disconnect my external monitor as well, it still works when just disconnecting the AC. The function itself also works when clicking it manually just fine. It's possible it has something to do with starting the laptop with AC and external monitor attached.

Automatic actions are enabled, LLT runs at autostart and the function is set to restart the dGPU. 

**To Reproduce**
1. Start the laptop with AC and external monitor attached in second screen only mode (battery was around 91%, maybe that has something to do with it too)
2. Log in and wait for LLT and Windows to fully load
3. Disconnect the external monitor and wait a couple of secs for the image to appear on the internal screen
4. Disonnect AC, the dGPU stays active.

**Expected behavior**
Restart the dGPU like before so it gets disabled when switching from external monitor to internal screen.

**Environment (please complete the following information):**
 - OS:  Windows 11 21H2 build 22000
 - Laptop model: Y540 15IRH
 - .NET version: 6.0.2/6.0.6
 - Do you have Vantage installed? No

**Logs**
[log_2022_07_10_13_33_30.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9078971/log_2022_07_10_13_33_30.txt)

**Comment by Dampfinchen** [comment]
I might add, the killing app function for deactivating the dGPU never worked for me automatically. It does work when when selecting it manually though.

**Comment by BartoszCichecki** [comment]
Hey, as I am currently on vacations I can't take a proper look at this, but looking at the code I am surprised that it worked. It seems that it's a bug in last version. 

I'll get it fixed when I am back 😅

**Comment by BartoszCichecki** [comment]
Fix will be part of 2.3.0.
