### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Acckion** [BartoszCichecki/LenovoLegionToolkit#1450]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Windows11 23H2

### Device

Legion R900P 2023 (82WM)

### Is your feature request related to a problem?

In some devices, such as the Legion Y7000P 2024, there is an option that allows you to press Fn+Q to switch between performance modes, including a custom mode. This feature is really convenient for me to switch modes. However, my device does not have such an option.

### How would you like the problem to be solved?

Add an option in some devices allowing me to press Fn+Q to switch between performance modes, including a custom mode.

### What alternatives have you considered?

None.

**Comment by Acckion** [comment]
> It is not possible to add this to older devices.

Why？ But  I think this function seems easy to implement......

**Comment by BartoszCichecki** [comment]
You are welcome to have a shot at it yourself then.

**Comment by Acckion** [comment]
Thanks anyway. I am a freshman at the School of Computer Science and Technology, Huazhong University of Science and Technology. hope I can solve this problem in the future.

**Comment by Acckion** [comment]
> You are welcome to have a shot at it yourself then.
Thanks anyway. I am a freshman at the School of Computer Science and Technology, Huazhong University of Science and Technology. hope I can solve this problem in the future.
