### ISSUE TITLE
The part of the light that is synchronized with the screen effect is not lit.

### ISSUE THREAD

**Issue by huangyuzhe** [BartoszCichecki/LenovoLegionToolkit#1451]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Windows 11 23H2 22631.4112

### Device

Legion R9000K ARHA7

### BIOS version

LENOVO K9CN46WW, 2024/4/17

### What's wrong?

The light at the bottom of the front of the laptop is incoherent, and there will be a lamp bead between each section of light that will not light up, which is no problem with using the official control center.

### How to reproduce the bug?

Go to Keyboard Controls and use the Screen Sync lighting effect to reproduce.

### What is the behavior that you expected?

I hope to turn on the lights that are not on.

### Logs

[log_2024_10_02_20_16_54.txt](https://github.com/user-attachments/files/17235536/log_2024_10_02_20_16_54.txt)

### Additional information

![image](https://github.com/user-attachments/assets/e4dd338a-9753-4b56-bc4e-c1c84d6ed04f)
![P20241003-042025](https://github.com/user-attachments/assets/394bc830-8c4c-42be-bc36-e10e668d3a52)

**Comment by BartoszCichecki** [comment]
The RGB effect is different in LLT and in Legion Zone / Vantage. The "bead" you are seeing is because, the LEDs are glowing very dim. It is not a bug - if you want the effect to be exactly like in Vantage/Legion Zone you have to use those apps.
