### ISSUE TITLE
Support Custom Boot Logo for LOQ 15IRX9

### ISSUE THREAD

**Issue by Senophyx** [BartoszCichecki/LenovoLegionToolkit#1454]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.24.1

### OS

Windows 11 24H2 Build 26100.1742

### Device

LOQ 15IRX9

### BIOS version

NECN38WW

### Which features of the application did you test?

Almost all the features is available and supported. The only feature that i need and missing is changing the boot logo.

### Which features of the application do not work as expected?

I tried to change the boot logo using LLT which should be available. but that feature is not in my LLT app (which should be in the settings menu).

**Comment by BartoszCichecki** [comment]
Not logo change is gen 6/7 only.

**Comment by Senophyx** [comment]
> Boot logo change is gen 6/7 only.

Do you mean gen 6 and 7 are lenovo laptops released in 2021 and 2022? Sorry i'm new on Lenovo laptops :)

**Comment by Ace-Radom** [comment]
> > Boot logo change is gen 6/7 only.
> 
> Do you mean gen 6 and 7 are lenovo laptops released in 2021 and 2022? Sorry i'm new on Lenovo laptops :)

@Senophyx You may have a quick look on the [compatibility](https://github.com/BartoszCichecki/LenovoLegionToolkit?tab=readme-ov-file#compatibility) section in the README. Gen 6 is for MY 2021, and Gen 7 for 2022.
