### ISSUE TITLE
LLT crash upon opening

### ISSUE THREAD

**Issue by SharnavM** [BartoszCichecki/LenovoLegionToolkit#1456]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Windows 11 Version 23H2 (OS Build 22631.4317)

### Device

Lenovo Legion Slim 7 16IAH7

### BIOS version

JYCN55WW

### What's wrong?

Whenever I open the application, I am greeted by an error "Unexpected exception occurred:
System.lO.FileNotFoundException: Could not load file or assembly 'System.Private.Xml'". I am attaching the screenshots of error boxes below. 
I've set LLT to open on startup, so everytime I start my laptop, this error pops up. LLT was working fine until yesterday, and I believe it stopped after a .NET update. I am attaching my update history as well, as I am not sure if it's the culprit or not. 

### How to reproduce the bug?

Open the LLT application, by clicking its icon.

### What is the behavior that you expected?

The app should open up just fine. 

### Logs

[log_2024_10_10_13_09_40.txt](https://github.com/user-attachments/files/17328672/log_2024_10_10_13_09_40.txt)

### Additional information

![Screenshot 2024-10-10 181355](https://github.com/user-attachments/assets/85a1869e-68d2-44ac-93c2-2da328c76051)
![Screenshot 2024-10-10 181410](https://github.com/user-attachments/assets/dd86d4e5-fb2a-47e3-94c3-252b22bff566)
![Screenshot 2024-10-10 183427](https://github.com/user-attachments/assets/9c47d3a9-5017-4b46-9b50-f5e6c9311fcf)

**Comment by BartoszCichecki** [comment]
> LLT was working fine until yesterday, and I believe it stopped after a .NET update.

If it was working before, then it isn't an issue with LLT. You need to figure out what changed in your system.

**Comment by SharnavM** [comment]
Fixed it by uninstalling and reinstalling LLT and .NET Runtime

**Comment by SharnavM** [comment]
@BartoszCichecki Is there an option for importing/exporting actions in LLT?

**Comment by BartoszCichecki** [comment]
In the About tab there is a link for app data folder. You can back up it's contents. Actions are stored in 'automation.json' file.
