### ISSUE TITLE
Keyboard backlight intensity setting

### ISSUE THREAD

**Issue by younyokel** [BartoszCichecki/LenovoLegionToolkit#1458]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Windows 10

### Device

Legion 5-Y540 (2020)

### Is your feature request related to a problem?

My keyboard two backlight intensity modes--low and high, but Toolkit always showed a On/Off switch as long as I remember. The keyboard always lights up in high intensity.

### How would you like the problem to be solved?

Maybe it's a limitation of my now unsupported Legion model (bought 2020). Any workaround? 

### What alternatives have you considered?

-

**Comment by BartoszCichecki** [comment]
As written in the readme laptops older than Gen 5, might be able to use LLT, but it is provided as-is and no development is done for these devices.
