### ISSUE TITLE
It is not possible to set the software to start automatically at boot or delay to start at power

### ISSUE THREAD

**Issue by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [BartoszCichecki/LenovoLegionToolkit#1459]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

Windows10 22H2

### Device

LegionR9000K 2021H

### BIOS version

GKCN65WW

### What's wrong?

It is not possible to set any auto-start mode via the auto-boot option within the software, including boot auto-start or delayed auto-start

### How to reproduce the bug?

1. Open the software
2. Find the "Settings" option
3. Find the "Power on Auto-Start" option
4. Change any of the values in this option
5. Crashes occur

### What is the behavior that you expected?

The software automatically terminates the operation after prompting an error code recorded in the Log file

### Logs

[log_2024_10_12_03_15_22.txt](https://github.com/user-attachments/files/17348633/log_2024_10_12_03_15_22.txt)

**Comment by BartoszCichecki** [comment]
There seems to be an issue with Task Scheduler on your Windows install. I am not able to troubleshoot issues with your Windows.

If you used any debloating scripts or custom Windows ISO that might be a source of issues.

Make sure that Task Scheduler is working properly on your machine.
