### ISSUE TITLE
Revo Uninstaller opens up when "When AC power adapter is connected" action runs

### ISSUE THREAD

**Issue by GR8623** [BartoszCichecki/LenovoLegionToolkit#1466]
### Version

2.24.1

### OS

Windows 10 Home 22H2

### Device

Legion 7 16ITHg6

### BIOS version

H1CN58WW

### What is wrong?

when "When AC power adapter is connected" and  "When AC power adapter is disconnected" action runs Revo Uninstaller app opens up. 

![image](https://github.com/user-attachments/assets/8edc679d-add0-4ce5-a4d3-e1a66f31a1e5)
These are the only actions and steps I have set up. 

I had revo uninstaller 2 years before getting LLT. As soon as I installed LLT and made the steps, this issue began. 

### What did you try already?

nothing

### How to reproduce the bug?

unplug ac power or plug it back in, and sometimes it opens. Not all the time, only sometimes. 

### What is the behavior that you expected?

I expect nothing to open

### Logs

[log_2024_10_22_00_50_20.txt](https://github.com/user-attachments/files/17468443/log_2024_10_22_00_50_20.txt)

### Additional information

after running the log, apparently this only happens when I start the laptop (powered off, not on sleep) and I disconnect or connect ac power after I login.

**Comment by BartoszCichecki** [comment]
Closing: Point 5 of Contribution guide.
