### ISSUE TITLE
Actions: Enable/Disable Night Light, also if possible add a time based Limitation

### ISSUE THREAD

**Issue by CyberBonk** [BartoszCichecki/LenovoLegionToolkit#1467]
### Version

2.24.1

### OS

windows 11 23H2

### Device

Legion slim 7i gen 8 (16IRH8)

### Is your feature request related to a problem?

it is not an "issue", just thought of a way to automate a feature, like i set my laptop to enable and disable Night Light from sunrise to sunset, but when i want to enter a game i want the laptop to disable Night Light when i enter a game and Re-enable it when i exit the game, 

_**if possible** _ add a time based limitation, where if Iam Before sunset (between 6am to 6pm, or Location Based like the option built-in the Night Light feature), that doesn't turn Night Light back on

### How would you like the problem to be solved?

- Add a New "Step" to Enable/Disable Night Light 
- Add a Time Based Limitation (Manual Time Set or Location based time)

### What alternatives have you considered?

N/A

### Additional information

i consider this a low Priority Feature Request

**Comment by BartoszCichecki** [comment]
Hey, there is no official API to control Night Light in Windows, so there is no way for LLT to control it.

**Comment by Ace-Radom** [comment]
@BartoszCichecki it doesn't seem so *impossible* at least I've already found the reg key for controlling night light & a similar impl here: https://github.com/Maclay74/tiny-screen/blob/main/TinyScreen/Src/Services/NightLight.cs.

I haven't tested it yet but may do it today, and the thing I can check without running the code seems to be fine. Would it be considered & reopened if this impl works?

**Comment by BartoszCichecki** [comment]
@Ace-Radom yes, but this is not documented anywhere, ergo might change at any point. For such a small thing, it doesn't make sense to introduce potentially breaking code.

**Comment by Ace-Radom** [comment]
Tested & worked on:

- Win11 23H2 22631.4317
- Win10 22H2 19045.5011

But I agree that it is an undocumented feature & I cannot test other windows versions since I don't have other windows devices in hand, so it's up to you.
