### ISSUE TITLE
Add "--allow-all-power-modes-on-low-wattage-ac" argument

### ISSUE THREAD

**Issue by gammeflamme** [BartoszCichecki/LenovoLegionToolkit#1470]
### Version

 2.24.1

### OS

Windows 11 Home 23H2 22635.4371

### Device

Legion Slim 5 16APH8

### Is your feature request related to a problem?

I don't want to accidentally use a high power profile on battery but I do want to be able to use them when using a usb pd charger.

### How would you like the problem to be solved?

add the argument --allow-all-power-modes-on-low-wattage-ac that uses the same criteria as the "When low wattage AC power adapter is connected" to determine if it is allowed to use all power modes. 

### What alternatives have you considered?

Another solution could be to add an "allow performance power modes" action so that users could customize how they want it to work.

**Comment by cuizhao-hlp** [comment]
I would also like to be able to switch to custom mode when using a 140w pd charger to limit cpu power distribution and fan speed!!!!!!

**Comment by cuizhao-hlp** [comment]
The custom mode can only be switched on the original power supply, which is too unfriendly for a model like the r9000p whose adapter weight is up to 1kg

**Comment by gammeflamme** [comment]
> The custom mode can only be switched on the original power supply, which is too unfriendly for a model like the r9000p whose adapter weight is up to 1kg

You can use the --allow-all-power-modes-on-battery to use performance and custom modes when using usb pd and on battery.
https://github.com/BartoszCichecki/LenovoLegionToolkit?tab=readme-ov-file#why-cant-i-switch-to-performance-or-custom-power-mode-on-battery
This feature request is to add another arg to enable perf and custom mode when using low wattage adapters but not when on battery.

**Comment by BartoszCichecki** [comment]
There isn't any code in LLT that will prevent you from settings Performance or Custom modes while a low power AC adapter is connected, so this option isn't needed. Your EC might refuse to switch to Performance mode in such case, but there is no workaround for that.
