### ISSUE TITLE
Clearify AMD CPU OC/UV in readme

### ISSUE THREAD

**Issue by gammeflamme** [BartoszCichecki/LenovoLegionToolkit#1471]
### Version

2.24.1

### OS

Windows 11 Home 23H2 22635.4371

### Device

Legion Slim 5 16APH8

### Is your feature request related to a problem?

in the readme both throttlestop Intel XTU are mentioned but both intel exclusive so there is no clear "compatible" software for AMD oc/uv.

### How would you like the problem to be solved?

Adding oc/uv software that is compatible with both llt and AMD or adding why oc/uv is a bad idea on AMD to the read me.

### What alternatives have you considered?

I have tried using Universal x86 tuning utility but because its quite expansive I'm unsure if everything works properly when using it with llt or if they are fighting for control so clarifying that in the read me or offering alternatives would be great.

**Comment by BartoszCichecki** [comment]
It's just a list of examples. Compatibility isn't an issue. Regardless of what software you use, you need to remember that if you set some power limits in LLT and then you also set it in another software, it might override the setting in LLT.
