### ISSUE TITLE
Add a toggle to disable keyboard power-saving, which avoids keyboard responsiveness problems.

### ISSUE THREAD

**Issue by shockdude** [BartoszCichecki/LenovoLegionToolkit#1472]
### Version

2.24.1

### OS

Windows 11 24H2 build 26100

### Device

Legion 5 Slim 16APH8

### Is your feature request related to a problem?

On my laptop, the keyboard has a power-saving feature where it turns off after like 10-15 seconds. Pressing any key will wake the keyboard back up.
Problem is, the keyboard takes a few hundred milliseconds to wake up, long enough for keypresses to be delayed or even be ignored. This unresponsive behavior is noticeable in some games and can be annoying.

I've seen other users experience this issue on different laptops, e.g. a Legion 5 Pro.

### How would you like the problem to be solved?

An actionable toggle to enable/disable/toggle power-saving on the USB Input Device(s) representing the keyboard.
In other words, uncheck "Allow the computer to turn off this device to save power".
![image](https://github.com/user-attachments/assets/9ea2289d-e60e-47e8-bcca-635623d09be3)

The action could have a description saying how disabling keyboard power-saving improves keyboard responsiveness after idle periods, but with a warning that it breaks sleep (see additional information).

On my laptop, I can toggle power-saving with these powershell commands:
```powershell
$d = Get-CimInstance -ClassName MSPower_DeviceEnable -Namespace root\wmi | where {$_.InstanceName -like 'USB\VID_048D*PID_C9*'}
$d | ForEach-Object -Process {
    $_.Enable = !$_.Enable
    $_ | Set-CimInstance
}
```

I've set up a LLT action based on this command, but having this feature built into LLT would be even nicer.
![image](https://github.com/user-attachments/assets/45966ea3-18df-466b-a230-398f7f43f978)

### What alternatives have you considered?

Mash keys to keep the keyboard awake.
Continue using the custom LLT action I set up to toggle keyboard power-saving.

### Additional information

Unchecking "Allow the computer to turn off this device to save power" on any device breaks S0 sleep, the laptop says powered on and idle. No S0 sleep is pretty bad when the laptop is unplugged, the battery will drain way more.
I've avoided this by creating actions to re-enable keyboard power-saving when the lid is closed or the laptop is unplugged. I don't know if there's a more convenient, automatic way to do this outside of using actions.

**Comment by Ace-Radom** [comment]
Sadly, the rule you provided to match the instance name of USB Input Device (`USB\VID_048D*PID_C9*`) doesn't work on all devices. I don't know a lot how to search datas from WMI in powershell, but I did some similar things under wbemtest.

```sql
SELECT * FROM MSPower_DeviceEnable WHERE InstanceName LIKE 'USB\\VID_048D*PID_C9*'  
```

And the result is:

![image](https://github.com/user-attachments/assets/7ec6061d-ba8a-4160-906b-3765d34d74aa)

The instance name of USB Input Device on my laptop is `USB\VID_048D&PID_C101`. Although they do start with `USB\VID_048D` (seems to be) but I think a rule like `USB\VID_048D%` is not reliable, cuz nobody can tell it they would be changed in the future. WMI is a pretty low-level interface and changing values in WMI must be safe in my opinion.

Plus, I also tried the following thing to find a solution.

```powershell
Get-PnpDevice -PresentOnly | Where-Object { $_.InstanceId -like 'USB*' } | Select-Object -Property FriendlyName,InstanceId
```

But as you might already have noticed: I use a chinese Windows version which chinese is the single OS language choice, and the device's friendly-name will be translated. The output isn't sth like `USB Input Device`, but `USB 输入设备` which means the same thing in chinese. That means searching instance in this way is also not reliable.

I would say if the action you use works, then just use it. Plz let me declare that I don't think it's a bad idea, but at least it seems to me impossible to make this function works _safely_ on all laptops. Let's wait for bc and see what do he think and if he knows sth else to this feature.

**Comment by BartoszCichecki** [comment]
I am with @Ace-Radom on this one. Without doing some manual investigation it is impossible to tell automatically with VID/PID should be used as it will vary depending on the laptop.

However, thanks for posting the script - interested users will be able to look it up in closed issues.
