### ISSUE TITLE
Quick Power Mode Selection

### ISSUE THREAD

**Issue by Gmemster** [BartoszCichecki/LenovoLegionToolkit#1477]
### Version

2.24.1

### OS

Windows 11 24H2 Build 26100.2161

### Device

Lenovo LOQ 15IAX9

### Is your feature request related to a problem?

to quickly change power mode without needing to switch through it multiple times with Fn+Q

### How would you like the problem to be solved?

Add a special keybind to quickly change to specific mode or adding a quick menu in the tray when selected

### What alternatives have you considered?

-

**Comment by BartoszCichecki** [comment]
Quick Actions that you create appear in right click tray menu. Create the ones that you need.
