### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by edusardon** [BartoszCichecki/LenovoLegionToolkit#1485]
### Version

Last

### OS

W11

### Device

Legión 5

### Is your feature request related to a problem?

I would like the processor to maintain a temperature range between 65 and 95 degrees Celsius. The minimum temperature of 65 degrees is set because, at this level, the processor doesn't suffer significant wear, and it also allows the fan to run at a low speed, reducing noise, which is precisely the goal I'm aiming for.

Could you help me implement a function that meets these parameters?

Thank you in advance.

### How would you like the problem to be solved?

???

### What alternatives have you considered?

???

**Comment by BartoszCichecki** [comment]
I don't know what are you asking for. Fan control is available for supported devices in Custom Power Mode.

**Comment by BartoszCichecki** [comment]
Closing due to lack of response from author.
