### ISSUE TITLE
Choice to shut down apps not compatible with legion toolkit from inside the toolkit

### ISSUE THREAD

**Issue by Jestersky98** [BartoszCichecki/LenovoLegionToolkit#1489]
### Version

2.24.2

### OS

Windows 11 23H2 version 22631.4317 os-version

### Device

Legion Slim 5 16APH8 - Type 82Y9

### Is your feature request related to a problem?

Hi I would like a feature to shut down apps that don't work with the toolkit like lenovo vantage, imcontroller and lenovo hotkeys from inside the toolkit app since it seems very hard to make sure these programs don't open on start up even while removing them from the start up list, some program related to them open them up and disrupt the toolkit

### How would you like the problem to be solved?

To solve the problem I'd just a button right next to the yellow pop up to forcefully shut down the programs disturbing the toolkit since the current sliders for it don't work, that's why I wanted a forceful shutdown
"Disable Lenovo Vantage and ImController" and "Disable Lenovo Hotkeys" don't disable them properly

### What alternatives have you considered?

I have tried to remove the programs from start up list several times and they show as off yet they still open every time I restart the laptop and I will have to manually go into the task manager to shut them down aswell as restarting legion toolkit to try the sliders again

**Comment by BartoszCichecki** [comment]
> The current sliders for it don't work

What does it mean? What processes are left running after you toggle them "on"?

**Comment by Jestersky98** [comment]
Lenovo Vantage, ImController and Lenovo Hotkeys
Those programs show up in the legion toolkit at the bottom in yellow text saying that it needs to shutdown but the disable slider in the settings aswell as turning them off in the start up menu in task manager don't work in preventing them from starting and I have to manually turn them off in task manager after every restart

**Comment by Jestersky98** [comment]
I don't know how to attach log but so far form my testing the disable sliders work for hotkeys but not lenovo vantage and imcontroller if you manually turn off the disable and then turn it on again but still doesn't prevent the programs from starting up at restart of the laptop
How do I attach log for you?

**Comment by BartoszCichecki** [comment]
Instruction are in the readme.

**Comment by Jestersky98** [comment]
I'll get back to you tomorrow then cause I don't have the time right now to restart and send it and so on, but thank you :)

**Comment by BartoszCichecki** [comment]
Closing due to lack of response.
