### ISSUE TITLE
Compatibility request for  Lenovo Legion Y9000K 2021H

### ISSUE THREAD

**Issue by KhatibFX** [BartoszCichecki/LenovoLegionToolkit#149]
**First and foremost**
Did you read the whole README? Yes

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 21H2 build 19044.1826
 - Laptop model: Lenovo Legion Y9000K 2021H
 - .NET version: 4.8.4084.0
 - Do you have Vantage installed? Yes

**List of features that are working as expected**
Power modes, actions (only ones tested, but I checked the menus for the other features and nothing looked broken)

**List of features that seem to not work**
None so far

**List of features that crash the app**
None so far

**Additional context**
This is a Chinese variant of the Lenovo 7i Gen 6 with Mini LED and Liquid Metal.

**Comment by BartoszCichecki** [comment]
Will be added in 2.3.0.
