### ISSUE TITLE
Add "Legacy Game Compatibility Mode" support

### ISSUE THREAD

**Issue by rickygjun** [BartoszCichecki/LenovoLegionToolkit#1495]
### Version

2.24.2

### OS

Windows 11

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

I have a regular played legacy game required to park e-core while playing.
Can I suggest to add a toggle and action support in LLC for the BIOS setting "Legacy Game Compatibility Mode"

### How would you like the problem to be solved?

add a toggle and action support in LLC for the BIOS setting "Legacy Game Compatibility Mode"

### What alternatives have you considered?

Fn+F4 or scroll lock

**Comment by BartoszCichecki** [comment]
There is no UEFI interface for it. You need to stick with the keyboard shortcut.
