### ISSUE TITLE
When a 'Lenovo - System' update pushes through Windows Update; Causes Zombie process until Lenovo hotkeys disabled/killed.

### ISSUE THREAD

**Issue by dreamsyntax** [BartoszCichecki/LenovoLegionToolkit#1496]
### Version

2.24.2

### OS

Windwos 11 23H2 Build 22631.4460

### Device

Legion 7i Pro Gen 8

### BIOS version

KWCN46WW

### What is wrong?

If Windows Update pushes a `Lenovo - System` update, upon next reboot the Lenovo Fn and functions keys service is restarted, and LLT hangs as a zombie process without being in the Tray.

![image](https://github.com/user-attachments/assets/5ee440b7-e48f-40c9-9c43-4721f769054d)

### What did you try already?

N/A; Reporting Lenovo explicitly breaking your service

### How to reproduce the bug?

Have no Lenovo Services installed
Clean Install Win 23H2
Install LLT and explicitly set it to block Function Keys and IMController services

Let:
Lenovo - System - 2.0.14.17 install via Windows Update (or whatever newest pushed System), then reboot.

### What is the behavior that you expected?

LLT runs as normal, and when opened warns about the Hotkey service running again.

### Logs

Logs dir is empty

**Comment by BartoszCichecki** [comment]
This is an inconvenience, but it cannot be resolved. When update is pushed, service will restart no matter what.
