### ISSUE TITLE
Fan not always work after setting custom curve

### ISSUE THREAD

**Issue by CyayC8** [BartoszCichecki/LenovoLegionToolkit#1497]
### Version

2.24.2

### OS

Windows 11 23H2

### Device

Legion Slim 5 16IRH8

### BIOS version

M2CN32WW

### What is wrong?

After setting custom fan curve Dashboard > Power mode : Custom, the fan will not always react to the curve. My cpu temp will rise (95+C) while the fans stay off. Opening clicking the cogwheel and then Save& Close again starts the fan like they should. But then they "forget" making the temp rise again until I press the Save & Close again.

### What did you try already?

Reopen
Reinstall
Reboot

### How to reproduce the bug?

See What Is Wrong.

+ Set fan curve. Start game or use pc normally. Temps will rise. Need to click on the Save & Close button in the custom mode cogwheel - menu. Fans start until its cooled. Then temps start rising and loop begins again.

### What is the behavior that you expected?

I expect the fans to follow the curve.

### Logs

[log_2024_11_20_14_09_22.txt](https://github.com/user-attachments/files/17831888/log_2024_11_20_14_09_22.txt)

### Additional information

![Screenshot 2024-11-20 150614](https://github.com/user-attachments/assets/1a383b80-5b88-4a3b-a23b-8bd5671f0eb8)
This should makje my fans spin @2900rpm at 95C but they stay off.

**Comment by BartoszCichecki** [comment]
LLT does not directly control the fan speed. The curve is applied and EC is responsible for controlling the speed.

Log is clean - no issues applying the fan curve, so if you experience problems try resetting EC. Instructions are available on the discord server linked in the readme.
