### ISSUE TITLE
Compatibility Test: Lenovo Legion 5 15ACH6H

### ISSUE THREAD

**Issue by jasonsf** [BartoszCichecki/LenovoLegionToolkit#15]
Full model name (i.e. Legion 5 Pro 16ACH6H)
 - Lenovo Legion 5 15ACH6H
List of features that are working as expected.
 - All (Tested by toggling in Lenovo Legion Toolkit and seeing Vantage recognizing the change. Did not actually test each feature.)
List of features that seem to not work (they do nothing).
 - None
List of features that crash the app.
 - None

**Comment by BartoszCichecki** [comment]
Thanks for support! Compatibility will be added in 1.2.
