### ISSUE TITLE
Keyboard RGB, hex/rgb code option.

### ISSUE THREAD

**Issue by mohitmujawdiya** [BartoszCichecki/LenovoLegionToolkit#150]
**Is your feature request related to a problem? Please describe.**
The current color selector is fine but inaccurate if I want the same color across all four zones.

**Describe the solution you'd like**
An option to enter hex/RGB code below the color wheel.

**Describe alternatives you've considered**
Editing the config file to enter the exact color I want to use.

**Comment by BartoszCichecki** [comment]
Will be available in 2.3.0, see #131
