### ISSUE TITLE
Adding Actions Related to Battery percentage

### ISSUE THREAD

**Issue by CodeCraftPlugin** [BartoszCichecki/LenovoLegionToolkit#1504]
### Version

2.24.2

### OS

Windows 11 24H2 26100.2454

### Device

IdeaPad Gaming 3 15ACH6

### Is your feature request related to a problem?

Well, Lenovo has a rapid charge and conservative mode, but using both has disadvantages such as after 100% rapid charge starts to decrease the charge capacity of the battery, conservative mode on the other hand prevents the battery from changing to 60 + decreasing the overall use time on the battery.
starts

### How would you like the problem to be solved?

Add an Action that checks if you have that battery percentage or a range to do a task. For the above problem change the charge mode to rapid charge mode when the battery is below 30% or 30% and when it is 100% it changes it back to either normal or conservative mode 

### What alternatives have you considered?

I am so far using my own Python script to check the battery percentage and use the llt command line utility for change in charge mode

**Comment by Ace-Radom** [comment]
Please check #564. An explaination why this feature is not considered for now is there.

**Comment by CodeCraftPlugin** [comment]
Since this is not planned for now, should I close this issue?

**Comment by Ace-Radom** [comment]
> Since this is not planned for now, should I close this issue?

You can, since it will be closed anyway because of duplication.
