### ISSUE TITLE
CPU Temperature Control

### ISSUE THREAD

**Issue by Enum0** [BartoszCichecki/LenovoLegionToolkit#1507]
### Version

2.24.2

### OS

Windows 11 23H2 22631.4460

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

One of the main features I've chosen LLT for is the ability to undervolt my AMD CPU to prevent system overheating. LLT allows to limit wattage, however the temperatures may vary depending on GPU usage and environment temperature.

### How would you like the problem to be solved?

Add an option to set a limit not only by wattage, but by a temperature threshold.

### What alternatives have you considered?

I discovered that feature in UXTU tool (Universal x86 Tuning Utility) and find this a pretty conviniet method to control CPU undervolting. While the CPU temperature is below the threshold the wattage and clock are high, but when it achieves the threshold, the CPU starts throttling

**Comment by BartoszCichecki** [comment]
Only functions exposed by Lenovo are available in Custom Mode settings. If for some reason, temperature control for CPU is not available, you need to resort to using other software.
