### ISSUE TITLE
Lenovo Legion 5 15IAH7H (2022 Model Gen7) compatibility

### ISSUE THREAD

**Issue by harrisck** [BartoszCichecki/LenovoLegionToolkit#151]
**First and foremost**
Did you read the whole README? [Yes/No] YES

**Environment (please complete the following information):**
 - OS: [e.g. Windows 11 21H2 build 22000] Windows 11 21H2 build 22000.795
 - Laptop model: [e.g. Legion 5 Pro 16ACH6] Legion 5 15IAH7H (Legion 5 Gen7 2022 Type 82RB)
 - .NET version: [e.g. 5.0.408] 4.8.04161
 - Do you have Vantage installed? [Yes/No] YES

**List of features that are working as expected**
[e.g. Power Modes, Hybrid Mode etc.]
Power Modes
Battery Modes
Always On USB
Hybrid Mode
Refresh Rate
Discrete GPU
Touchpad Lock
FN Lock
Windows Key Lock
Flip to Start
Overdrive

**List of features that seem to not work**
[e.g. Power Modes, Hybrid Mode etc.]
Nothing - all seems to work

**List of features that crash the app**
[e.g. Power Modes, Hybrid Mode etc.]

**Additional context**
I'm trying the 2.3.0 beta and the downloads work for the model 82RB also

**Comment by BartoszCichecki** [comment]
Will be added in 2.3.0.
