### ISSUE TITLE
Two fan curve breakpoints don't work

### ISSUE THREAD

**Issue by omri09** [BartoszCichecki/LenovoLegionToolkit#1511]
### Version

2.24.2

### OS

Windows 11 23H2

### Device

Legion 5 16IRX9

### BIOS version

NMCN22WW

### What is wrong?

Hello,

The highlighted fan curve breakpoints are not functioning correctly.
The fan speed alternates between the 65°C sensor breakpoint and the next one at 94°C.

![image](https://github.com/user-attachments/assets/6a5c161a-580c-411d-857e-5f05fa379339)

### What did you try already?

Reinstall the software.

### How to reproduce the bug?

1. Go to custom mode
2. Set any fan curve

### What is the behavior that you expected?

When reaching the two breakpoints at 83°C and 85°C, the fan speed should be set.

### Logs

[log_2024_12_07_00_48_00.txt](https://github.com/user-attachments/files/18045380/log_2024_12_07_00_48_00.txt)

**Comment by BartoszCichecki** [comment]
Fan curve is controlled by EC. LLT only sends a preferred fan curve to the embedded controller and it's up to it to apply fan speeds properly.

If it is not functioning properly, report a bug to Lenovo.
