### ISSUE TITLE
Addition of CPU and GPU wattage metrics in the CPU/GPU dashboard

### ISSUE THREAD

**Issue by rforzachamp821** [BartoszCichecki/LenovoLegionToolkit#1513]
### Version

2.24.2

### OS

Windows 11 24H2 Build 26100

### Device

Legion Pro 5i 16IRX9

### Is your feature request related to a problem?

No, it is not related to a major problem with the application. However, it would be a major convenience upgrade, as it would allow me to view the actual power consumption of the CPU in real time without the need of external applications that I would have to run.

### How would you like the problem to be solved?

Adding a simple overall wattage metric to the CPU and GPU columns in the Home Dashboard menu. The CPU should just be an overall wattage of all the cores combined, and the GPU should be the same thing.

### What alternatives have you considered?

Just opening HWInfo instead. However it is an inconvenience to do it every single time, as HWInfo takes a little time to load, and I am impatient :)

### Additional information

The wattage metrics could be added below this table as an extra row:

![image](https://github.com/user-attachments/assets/6e9b8ee0-b3b9-498a-ac7e-1068a51110ef)

Additionally, I foresee this as a viable addition to the program as it is a useful metric that can be used to understand what has to be tuned to increase battery life, performance, etc. This definitely relates to the program's subject, and adds nicely to the CPU-GPU table specifically.

**Comment by BartoszCichecki** [comment]
All of this is true, except that to read CPU wattage ring0 driver is needed which causes the same security problems as LFC method of controlling fans. For this reason this will not be added.

So yes, use hwinfo because they have a signed secure ring0 driver.
