### ISSUE TITLE
Request to Add Instant Boot Support for Older Laptop Models

### ISSUE THREAD

**Issue by RPLUG** [BartoszCichecki/LenovoLegionToolkit#1515]
### Version

2.24.2

### OS

Windows 11 

### Device

Lenovo Legion R7000P2021H

### BIOS version

GKCN65WW

### Which features of the application did you test?

I tested the Instant Boot feature. My laptop is a relatively old model, but after updating the BIOS, it was able to support Instant Boot. In the BIOS, I could select the relevant configuration options. I found the corresponding setting button in the toolbox, but it cannot be displayed on the homepage.
![Uploading 1.jpg…]()

### Which features of the application do not work as expected?

The Toolkit does not currently provide the relevant configuration options for the Lenovo Legion R7000P 2021H. I hope this option can be added to the homepage so that users of the older version can benefit from the latest BIOS update.

**Comment by RPLUG** [comment]
![1](https://github.com/user-attachments/assets/f4865781-652c-4d64-a068-4059c61d1d63)
![2](https://github.com/user-attachments/assets/e11d8ae0-36a3-45ce-b142-b01e754037e8)

**Comment by BartoszCichecki** [comment]
Your laptop may support instant boot, but if LLT doesn't show it - it doesn't support changing the value from OS level. That is not something I can "fix".

**Comment by RPLUG** [comment]
> Your laptop may support instant boot, but if LLT doesn't show it - it doesn't support changing the value from OS level. That is not something I can "fix".

Thanks! So what you mean is that, although the BIOS provides this option, it can only be modified from the BIOS and cannot be changed from the operating system, right?

**Comment by BartoszCichecki** [comment]
Exactly. On technical level Gen 7 and later laptop have this option exposed as UEFI variable so it can be changed from OS level. Gen 6 for some reason do not have it exposes, so OS cannot access it.
