### ISSUE TITLE
Precise rgb value input and smooth transitions for backlight

### ISSUE THREAD

**Issue by selimsandal** [BartoszCichecki/LenovoLegionToolkit#152]
When using vantage we can input precise rgb values, I use that to dim the brightness to a lower value than the low brightness setting (100,0,0) for a lower brightness white keyboard for example.

I think this can be a good addition.

Also I noticed vantage smoothly transitions from backlight off state to on state but toolkit doesn't. Not an important feature but wanted to mention it to see if it can be implemented.

**Comment by BartoszCichecki** [comment]
Will be available in 2.3.0, see #131

**Comment by selimsandal** [comment]
Great! Sorry for the duplicate.
