### ISSUE TITLE
LLT No fan speed on windows startup. 

### ISSUE THREAD

**Issue by Dragosh1205** [BartoszCichecki/LenovoLegionToolkit#1524]
### Version

2.24.2

### OS

Windows 11 Pro 24H2 Build 26100.2605

### Device

Lenovo Legion 7 16IAX7

### BIOS version

LENOVO K1CN48WW

### What is wrong?

When i start up my laptop, the fan on the right side of the laptop (GPU side) goes all out while the one on the left (CPU side) stays normal, idle, or not turned on at all. 
If i leave the laptop alone, it will cycle, going all out for like 2-3 min, then taking a 1-2 min break going back to normal, then back at full again, and so on until i take actions to stop this. 
I have to mention the fans are clean and i have done so recently, however the paste is still the factory one as removing the vapour chamber would void the warranty (there's a sticker on the screw). 

### What did you try already?

Tried everything related to updates, windows update, additional updates, bios update, LLT/Vantage update. 
Tried disabling LLT and going back to Vantage. 
Tried resetting any overclock or turbo clock adjustments (have to lower the laptop turbo speeds since it wants to go all out with 5GHz and makes it go to 100 degrees celsius) from Vantage and even in BIOS - reset overclock/undervolt, everything.
Tried on plug in and on battery power to see if it works.
Tried disabling discrete GPU and killing any tasks that use it so as to be able to hit restart GPU in LLT and to see it display powered off.

### How to reproduce the bug?

1. Start system
2. Listen for the fan going wild
3. Start LLT, and check fan speed
4. Fan speed is blank or showing no speed = fans go wild
5. Fan speed is present, showing an rpm value = fans act normally and laptop is doing fine.

### What is the behavior that you expected?

LLT should show fan speed in the main window for both CPU and GPU. Sometimes it shows and all is fine, sometimes it doesn't show a balue for the GPU and the fan goes to max rpm.

### Logs

[log_2024_12_24_07_55_32.txt](https://github.com/user-attachments/files/18237306/log_2024_12_24_07_55_32.txt) This is a log after the issue is worked around and LLT is working fine. 

Will add another log when the issue appears again, and trace the workaround in a log.

### Additional information

So i have been having this issue for a while now. Not sure if it's LLT or related to my system specific settings/processes/services. I have done some adjustments to non essential services disabling them off in order to lower process count in task manager, so as to make the laptop quieter on idle. 

What i have noticed is that there is a workaround but even i don't know exactly what fixes the issue. 

If i start the laptop and it does the fan thing, i usually go to LLT, change the GPU mode from Hybrid-Auto (which i prefer and use all the time) to Hybrid. Then, i kill any process that may keep the dGPU running, and then wait for the GPU to power off, or restart it so it shows as powered off. Then i can disconnect the plug, and if the dGPU is still powered off, i can change it back to Hybrid-Auto in order for it to disconnect the dGPU, thus leaving the laptop running on iGPU only. After that, the GPU section in LLT will take the CPU fan speed since the iGPU is on the CPU. After that i can reconnect the plug, the dGPU will reconnect and show it's own rpm values, fixing the wildness and max speed, returning back to normal idle speeds.

![image](https://github.com/user-attachments/assets/522f2806-279a-425d-a4e0-3b8f9862ac4b) 
Normal, with GPU showing fine, the fan is at low or idle speed.

![image](https://github.com/user-attachments/assets/85c915b8-a53c-446c-aafb-a02d6008ab21) 
No GPU fan speed rpm shown, the fan is at max rpm.

**Comment by BartoszCichecki** [comment]
LLT does not control fans speeds - this is not a LLT bug.

**Comment by Dragosh1205** [comment]
It's not about controlling the fan speed. It's about displaying the info or communicating with the hardware? I'm not an expert. But when LLT shows no fan speed, the gpu fan goes max speed. When LLT shows the value, it's all normal. Could it be some communication error between LLT and hwinfo or something?

**Comment by BartoszCichecki** [comment]
No, fans speed is reported by EC. If EC reports 0, LLT will show 0.

I suggest you contact Lenovo for warranty - it might be a good idea based on the description of how your fans work.
