### ISSUE TITLE
Add "Energy saver" in the list of action 

### ISSUE THREAD

**Issue by CodeClimberNT** [BartoszCichecki/LenovoLegionToolkit#1527]
### Version

2.24.2

### OS

Windows 11 24h2 Build 26100.2605

### Device

LOQ 15AHP9

### Is your feature request related to a problem?

I'm trying to conceive the best possible setup to have the longest battery life with a single click

### How would you like the problem to be solved?

Having the option to select "energy saver" and then deciding to enable/disable based on the trigger may be a good approach to implement such behavior.

### What alternatives have you considered?

I didn't use yet the macro, so maybe it could have been done also in a single click with that, but right now my approach is to both run the manual trigger to set all relevant options to the lowest and then enable the energy saver option manually in the windows option/quick bar

**Comment by BartoszCichecki** [comment]
There is no API to control energy saver setting iirc so this will not be added.
