### ISSUE TITLE
Request for customization of battery conservation % 

### ISSUE THREAD

**Issue by vink2212** [BartoszCichecki/LenovoLegionToolkit#153]
Lenovo keeps it’s battery conservation mode at 60% which is quite low. You can manually spoof this by charging the battery to the desired % and then turning on conservation mode. It would be really cool if legion tool kit could implement a feature where you can increase the conservation limit in increments of 10 or so. 

Not sure if this is possible and it would have to be safe, but maybe another way is to have conservation mode start automatically when the battery is charged to a desired amount.

**Comment by BartoszCichecki** [comment]
Previously discussed here: https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/20#issuecomment-988825583
