### ISSUE TITLE
Characterset not correct for Dutch language

### ISSUE THREAD

**Issue by Miniterror** [BartoszCichecki/LenovoLegionToolkit#154]
Characterset for CPU boost modes not correct, i think it wants to state Efficiënt and the ë is causing it.
It can also be written without the dots on top the E so like Efficient.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/101180056/180846196-120aebed-d9fa-4739-93b3-ee0bb1863fa2.png">

**Comment by BartoszCichecki** [comment]
Can you paste the output from `powercfg /list` here?

**Comment by BartoszCichecki** [comment]
Can you run `chcp` in cmd.exe and let me know the result?
