### ISSUE TITLE
Package Downloads - Enhancements

### ISSUE THREAD

**Issue by sickypedia** [BartoszCichecki/LenovoLegionToolkit#155]
**Is your feature request related to a problem? Please describe.**
I see the Toolkit Beta has a feature to download stuff from Lenovo. This is very cool! My suggestion is to add the following enhancements:
1. Quick text box to filter the results which are returned upon clicking 'Refresh'. E.g.: Typing 'VGA' should filter out gpu drivers.
2. Batch select and download.
3. Append download title to the downloaded file name for easier file management.
4. Machine type code should update corresponding OS versions. I think 'Win 10' and 'Win 11' are static options currently and using 10MQ, I'm unable to download Win 7 packages, which website offers.

**Comment by BartoszCichecki** [comment]
Great suggestions!

1. Added to 2.3.0
2. I don't see it as super important since you can click download on multiple packages and they will download concurrently.
3. Added to 2.3.0
4. Added to 2.3.0

**Comment by younyokel** [comment]
I will also give some improvements on downloading. Is there no notification in Windows that the download is complete? When I used the download I didn't have any notifications other than those inside the app. Also, changing the sorting of apps by name date and category cancels the download (or changes the download icons to the default?)

**Comment by BartoszCichecki** [comment]
Hey, please create a separate issue especially when this one is closed already. It's impossible for me to follow comments on closed issues.
