### ISSUE TITLE
[Feature Request] Disabling lightning on Lenovo Legion 7 Gen6

### ISSUE THREAD

**Issue by alantoblooddy** [BartoszCichecki/LenovoLegionToolkit#156]
**Is your feature request related to a problem? Please describe.**
It's impossible to turn the lighting off while being plugged in. The only way to disable it is by lowering the lightning to 0% using FN + Arrow Down which is not ideal as FN functions and FN combinations are not lid up in this case.

**Describe the solution you'd like**
A toggle that would turn on or off keyboard lightning. The lighting is off by default when the blue mode is enabled, and the laptop runs on battery. 

**Describe alternatives you've considered**
iCue is a mess...

**Comment by BartoszCichecki** [comment]
Hey, as I said before. There is no plan for adding support for iCue lightning. Take a look at OpenRGB - it apparently supports Legions now.
