### ISSUE TITLE
Lenovo Yoga Slim 7 Pro 16" AMD (16ACH6)

### ISSUE THREAD

**Issue by v-marinkov** [BartoszCichecki/LenovoLegionToolkit#157]
**First and foremost**
Did you read the whole README? Yes

**Environment (please complete the following information):**
 - OS: Windows 11 Home 21H2 build 22000.795
 - Laptop model: Lenovo Yoga Slim 7 Pro 16" AMD (16ACH6)
 - .NET version:  4.8.04161
 - Do you have Vantage installed? No

**List of features that are working as expected**
Always On USB, Refresh rate, Fn lock, Flip to start, Discrete GPU (maybe)

**List of features that seem to not work**
- Power modes (although they work fine with the fn+Q shortcut)
- Hybrid mode complete missing
- Battery conservation: this seems to work only when Vantage has been installed and run in the last days. Afterwards the option to charge the battery to 60% disappears even from the BIOS and the only way to restore it is to install Vantage. Is this normal?

**List of features that crash the app**
Power plans under settings

**Additional context**
![Screenshot 2022-08-03 143237](https://user-images.githubusercontent.com/7135724/182625361-b634be83-c9df-4f62-84ec-282a5e4b8396.jpg)
<img width="860" alt="image" src="https://user-images.githubusercontent.com/7135724/182625413-4f4f317d-94d7-4670-a85b-5e02d658d763.png">

Logs:
[error_2022_08_03_14_32_19.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9251925/error_2022_08_03_14_32_19.txt)
[log_2022_08_03_14_32_08.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9251926/log_2022_08_03_14_32_08.txt)
[log_2022_08_03_14_35_39.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9251928/log_2022_08_03_14_35_39.txt)

**Comment by BartoszCichecki** [comment]
Yoga devices may not be fully compatible, and support for them is not planned.

**Comment by v-marinkov** [comment]
Well, that's unfortunate. Could at least advise on this:
"Battery conservation: this seems to work only when Vantage has been installed and run in the last days. Afterwards the option to charge the battery to 60% disappears even from the BIOS and the only way to restore it is to install Vantage. Is this normal?"

Is Vantage a requirement for it to work and show up in the BIOS generally?

**Comment by BartoszCichecki** [comment]
I don't know to be honest. I don't have conservation mode in BIOS at all. Lenovo is known for weird BIOSes so what you are saying is not surprising.
