### ISSUE TITLE
[REQUEST] Add Hybrid Mode ON/OFF Event Listener

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#159]
What I mean by event listener is like "When AC adapter is connected" and also like "When app is running".

My intention is for when having the Hybrid Mode OFF is to open certain apps automatically like MSI AfterBurner and RTSS and others.

I have temporarily solved this problem by using the "When app is running" event listener and added all my games so that it'll open the other apps automatically, but that's not really optimal since I have to add every single new game I download.

Also I deeply appreciate @BartoszCichecki for actually implementing my previous request "RGB customization" and doing it in such a short notice, thanks again!

**Comment by Ahsan40** [comment]
Hi, I am confused about one thing which is after changing the hybrid mode laptop needs to restart. So, either the task need to be done manually or use "When app is running" anyway. Right? Or, I am missing something?

**Comment by BartoszCichecki** [comment]
Yeah, I am also confused. I would suggest making Quick Actions for that. Would that be enough? You could make two actions to start/stop apps that are needed.
