### ISSUE TITLE
Legion 5i Pro 16ITH6H

### ISSUE THREAD

**Issue by jumanjimanji** [BartoszCichecki/LenovoLegionToolkit#16]
So far working as expected:
-Disable Lenovo Vantage services works as expected, the Star Fn key (Fn + F9) brings up the toolbar.
-Power modes
-Battery modes
-Misc: Haven't tried Flip to start.
-Hybrid Mode: Haven't tried.
-Always on USB: Haven't tried.

I've still to find any feature that doesn't work, and haven't experienced any crashes. Maybe allow a single instance running in order to avoid problems?

Thank you very much for the work!

**Comment by BartoszCichecki** [comment]
Thanks for support! Compatibility will be added in 1.2.

Single instance will be added separately :)
