### ISSUE TITLE
Lenovo Thinkbook 14p G3 ARH (21EJ)

### ISSUE THREAD

**Issue by NamesMT** [BartoszCichecki/LenovoLegionToolkit#160]
**First and foremost**
Did you read the whole README? Yes

**Environment (please complete the following information):**
 - OS: Windows 11 22H2 build 22621.169
 - Laptop model: Thinkbook 14p G3 ARH (21EJ)
 - .NET version: 4.8.09032
 - Do you have Vantage installed? Yes

**List of features that are working as expected**
Everything, except below:

**List of features that seem to not work**

**List of features that crash the app**
Power plans (Invalid class)

**Additional context**
- App Version: 2.3.1

**Comment by BartoszCichecki** [comment]
Can you start also with `--trace` parameter and paste logs? I am a little hesitant about adding ThinkPads because there are significant differences.

**Comment by NamesMT** [comment]
Here you go:
[error_2022_08_08_02_13_52.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9277334/error_2022_08_08_02_13_52.txt)
[log_2022_08_08_02_13_29.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9277332/log_2022_08_08_02_13_29.txt)

**Comment by BartoszCichecki** [comment]
Looks like there are too many differences between your ThinkPad and Legion devices and I won't be able to support it.
