### ISSUE TITLE
Lenovo Legion 5 Pro 16ARH7H (2022 Model Gen7) compatibility 

### ISSUE THREAD

**Issue by KrishivVora** [BartoszCichecki/LenovoLegionToolkit#162]
**First and foremost**
Did you read the whole README? [Yes/No] YES

**Environment (please complete the following information):**
 - OS: Windows 11 21H2 build 22000
 - Laptop model: Legion 5 Pro 16ARH7H 
 - .NET version: 4.0.30319
 - Do you have Vantage installed? Yes, but disabled it in LLT

**List of features that are working as expected**
Power Modes
Battery Modes
Always On USB
Refresh Rate
Touchpad Lock
FN Lock
Windows Key Lock
Flip to Start
Overdrive

**List of features that seem to not work**
Hybrid Mode
Discrete GPU

**List of features that crash the app**
N/A

**Additional context**
Hybrid mode / dGPU bug: when hybrid mode is on, after unplugging and replugging the laptop charger, Nvidia dGPU seems to be turned off permanently. It is not recognized in Nvidia Control Panel and games run using AMD iGPU. A restart fixes this and the dGPU does stay on until the laptop is unplugged and replugged.

Also, Fn + R shortcut doesn't work. All other Fn shortcuts work and automated task to change refresh rate on unplug/replug also works. This is with Lenovo Fn App disabled in LLT.

**Comment by BartoszCichecki** [comment]
So... pretty much no feature works as expected?

**Comment by BartoszCichecki** [comment]
Does Fn+R work with Vantage and Fn Keys enabled?

**Comment by KrishivVora** [comment]
> So... pretty much no feature works as expected?

Almost all features do work except the two I mentioned at the end.

> Does Fn+R work with Vantage and Fn Keys enabled?
No it doesn't. But Hybrid Mode does work as expected with Vantage, like when unplugging and replugging does not permanently disable the dGPU as it does with LLT.

**Comment by BartoszCichecki** [comment]
You can try this build out. It adds support for gen 7 hybrid modes.
[LenovoLegionToolkitSetup_gen7.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9354401/LenovoLegionToolkitSetup_gen7.zip)

**Comment by BartoszCichecki** [comment]
Oh and I will close this issue, let's continue discussion in #165 .
