### ISSUE TITLE
❗ANNOUNCEMENT❗ Regarding support for Gen 7 (2022) Legions.

### ISSUE THREAD

**Issue by BartoszCichecki** [BartoszCichecki/LenovoLegionToolkit#165]
7th generation Legions, so these released in 2022, are not currently fully supported by LLT.

I am planning on adding support, but there are quite a few differences compared to 6th gen. Since the laptop I have is 6th gen, it will be significant amount of work and time needed to correctly support newest models.

I am asking you to be patient and as soon 7th gen support is possible, I will definitely include it. It's top priority for LLT now.

**Comment by BartoszCichecki** [comment]
Related: #164 #162.

**Comment by BartoszCichecki** [comment]
Last note: help is needed in  figuring out how the new hybrid modes are controlled.

**Comment by trevlungul** [comment]
> Last note: help is needed in figuring out how the new hybrid modes are controlled.

I'm willing to help, just not too tech savvy on the software front. If there's anything you can talk me through, let me know

**Comment by BartoszCichecki** [comment]
You can try this build out. It adds support for Gen 7 Hybrid modes.
[LenovoLegionToolkitSetup_gen7.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9354441/LenovoLegionToolkitSetup_gen7.zip)

**Comment by trevlungul** [comment]
Quick impression, so far, looking good. Discharge rate on hybrid is now @ -6.5w  compare to over 20w before.
LLT seems like it's slower switching between panels (eg. home to battery), but it could be my imagination

**Comment by trevlungul** [comment]
Switched to dGPU without a problem. I notice there's also a hybrid-auto and hybrid-iGPU only now.
I switched to hybrid-auto and my 3060 is gone from the device manager - I'm assuming this should be the iGPU only functionality.
How is hybrid-auto different from hybrid?

**Comment by BartoszCichecki** [comment]
Here is the description provided by Vantage. It will also be included in next versions of LLT.

![image](https://user-images.githubusercontent.com/7916915/184997000-33331f4f-1c9f-4fd5-9510-6c4fbb6a036e.png)

**Comment by trevlungul** [comment]
Got it. 
TBH, I've never installed Vantage

Since I'm here, can I make a feature request? Would it be possible to hide "updates" on the download page? For my machine the only things there are Legion Arena Application and a couple dock drivers. Neither are any interest to me, so it'd be nice to hide or ignore them (sort of like how you can hide Windows updates)

**Comment by BartoszCichecki** [comment]
Make a separate issue for this so that I don't forget to look into this 😬

**Comment by KrishivVora** [comment]
> You can try this build out. It adds support for Gen 7 Hybrid modes. [LenovoLegionToolkitSetup_gen7.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9354441/LenovoLegionToolkitSetup_gen7.zip)

Hey! Is this separate from the 2.4.1 update that came out? I updated from within LLT and just wondering if I need to fully uninstall and reinstall using this link to get Gen 7 Hybrid mode support.

**Comment by trevlungul** [comment]
> Make a separate issue for this so that I don't forget to look into this 😬

Done. I'm new to this whole Github thing so I apologize if I'm not following protocol

**Comment by trevlungul** [comment]
Have you made any changes to the above beta link? I just did a clean install and my battery drain is back to ~25w again unless I eject the 3060

**Comment by BartoszCichecki** [comment]
No, there are no changes to the build above.

**Comment by trevlungul** [comment]
False alarm. I typically use NVcleaninstall on my Nvidia drivers and it doesn't install the "platform controller and framework" by default (was missing in device manager). Once I got that installed LLT was working properly again.

Already on Discord.

Cheers

**Comment by BartoszCichecki** [comment]
Beta 2.5.0 is available on the Discord server linked in Readme.
