### ISSUE TITLE
Feature Request - Enable 'Legion AI Engine' in Balanced Mode

### ISSUE THREAD

**Issue by nadtorus** [BartoszCichecki/LenovoLegionToolkit#166]
-------------------------------------------------------------------------------------------------
_REQUEST:_
**Is it possible to add option to enable 'Legion AI Engine' in Balanced Mode?** 
-------------------------------------------------------------------------------------------------
_**Background**:_
This comes from my experience, at least to me. I'm using L7i gen 6.

It's the GPU TDP that I have concern with.

In default balanced mode (without the AI Engine checked/ticked in Lenovo Vantage), the 3070 GPU TDP is maxed at 115W. And Legion ToolKit follows this default balanced mode setting. This makes the jump to Perf. Mode a little bit too far (115W to 140W).

I don't know why the vbios is set like that. Because the 3070 TDP based on NVIDIA website is 125W + 15W dynamic boost.

But with the AI Engine checked/ticked, the GPU TDP is increased to 125W. Which is, for me, feels more balanced and true to NVIDIA TDP for 3070.

Based on my understanding, this happens because all Vantage services are stopped when I checked the disable Vantage services in Legion ToolKit. Is there another way to stop all the vantage services except the one that runs the AI Engine?

I hope you understand what I'm saying since I'm not a native English speaker..

I wanna say thank you for this app because it could stop vantages services that take many resources in the background. It's been very useful to me. Thank you so much!

**Comment by BartoszCichecki** [comment]
Support for AI engine is not planned since it requires service running in the background. I suggest switching to Performance mode when gaming. Also, AI engine works only for a number of predefined games, 18 to be specific.

**Comment by BartoszCichecki** [comment]
Good news! After giving this a thought, I decided to implement it in the end.

**Comment by nadtorus** [comment]
> Good news! After giving this a thought, I decided to implement it in the end.

Thank you so much for really giving it a thought and deciding to implement it. I really appreciate it.

**Comment by BartoszCichecki** [comment]
Please try to test this build and let me know the results.

[LenovoLegionToolkitSetup_ai.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9709440/LenovoLegionToolkitSetup_ai.zip)

**Comment by nadtorus** [comment]
> Please try to test this build and let me know the results.
> 
> [LenovoLegionToolkitSetup_ai.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9709440/LenovoLegionToolkitSetup_ai.zip)

Thank you so much for the preview build. (I already replied in email with the screenshot attached. But I reply in GitHub also in case you don't see your inbox often).
I've done a quick test in 2 games I have (RDR2 and Hitman 3). Here's some notes I have:
1. Everytime I want to close the app, this warning always appears, no matter what settings I have (Screenshot attached). But I don't think it affects the performance, the app still runs the settings I set.
2. The AI works in balanced mode when Legion Vantage services disabled (GPU wattage is fluctuating between 125W-140W, which indicates the AI works). But then, (to no. 3)
3. I tried to close the Legion ToolKit app (with the warning still appeared) with Lenovo Vantages services disabled and AI enabled, the AI still ran well until I tried to cycle the Legion Thermal Modes using Fn+Q (it went like this: Balanced AI->Performance Mode->Silent Mode->Balanced AI). When it went back to Balanced AI, it seemed the AI turned off again (I saw the GPU wattage capped to 115W again). I have to open the Legion ToolKit again and then the GPU wattage fluctuating between 125-140W again, which indicates the AI turned on. I don't have this issue when the Legion ToolKit app runs in the background, the Thermal Mode cycle doesn't affect the AI services.


This is just one quick test I ran because of the limited time I have. And I only have 2 games installed to my L7i. This could be a bad test for you as a developer but I hope this could contribute to the next step of development process, even though it's only a small contribution. I hope the issues stated in no. 1 and no. 3 could be fixed. Thank you!

Note: I'm not an English native speaker. I hope you understand what I'm saying.

**Comment by BartoszCichecki** [comment]
Hey, thanks for great feedback.
Re: 1. This is already resolved :)
Re: 2. Great stuff!
Re: 3. Good point, I need to disable AI when LLT quits and of course it needs to stay running in background for this feature to work correctly.

**Comment by nadtorus** [comment]
Thank you so much for the preview build. I reply in email so I can show one screenshot.
I've done a quick test in 2 games I have (RDR2 and Hitman 3). Here's some notes I have:
1. Everytime I want to close the app, this warning always appears, no matter what settings I have (Screenshot attached). But I don't think it affects the performance, the app still runs the settings I set.
2. The AI works in balanced mode when Legion Vantage services disabled (GPU wattage is fluctuating between 125W-140W, which indicates the AI works). But then, (to no. 3)
3. I tried to close the Legion ToolKit app (with the warning still appeared) with Lenovo Vantages services disabled and AI enabled, the AI still ran well until I tried to cycle the Legion Thermal Modes using Fn+Q (it went like this: Balanced AI->Performance Mode->Silent Mode->Balanced AI). When it went back to Balanced AI, it seemed the AI turned off again (I saw the GPU wattage capped to 115W again). I have to open the Legion ToolKit again and then the GPU wattage fluctuating between 125-140W again, which indicates the AI turned on. I don't have this issue when the Legion ToolKit app runs in the background, the Thermal Mode cycle doesn't affect the AI services.


This is just one quick test I ran because of the limited time I have. And I only have 2 games installed to my L7i. This could be a bad test for you as a developer but I hope this could contribute to the next step of development process, even though it's only a small contribution. I hope the issues stated in no. 1 and no. 3 could be fixed. Thank you!
    On Wednesday, October 5, 2022 at 12:52:49 AM GMT+7, Bartosz Cichecki ***@***.***> wrote:  
 
 


Please try to test this build and let me know the results.

LenovoLegionToolkitSetup_ai.zip
