### ISSUE TITLE
Notifications Customization

### ISSUE THREAD

**Issue by abhishek3x** [BartoszCichecki/LenovoLegionToolkit#168]
**Describe the solution you'd like**
Ability to customize position and size of the notifications for microphone and touchpad.

**Additional context**
I know these all have a physical lights or switches but adding notifications for these would be great

- webcam switch
- changing Power Modes with Fn+Q or automatically via actions  
- enabling/disabling CapsLock, NumLock and FnLock.

**Comment by BartoszCichecki** [comment]
What exactly would you like to customize?

I tried keeping notifications at bare minimum, that's why there aren't really notification about things you can "see" on the laptop.
