### ISSUE TITLE
[FEATURE REQUEST] Actions features when selecting apps.

### ISSUE THREAD

**Issue by younyokel** [BartoszCichecki/LenovoLegionToolkit#169]
Hi. Having the ability to select multiple applications at once would definitely speed up the process, and having a copy/paste feature would be extremely helpful as well.

![image](https://user-images.githubusercontent.com/53343081/184694426-85e0908d-9e6d-411e-bef1-f0ddda1deeb9.png)

**Comment by BartoszCichecki** [comment]
I don't see how multiselect would work, but copy paste can be done :)

**Comment by younyokel** [comment]
> I don't see how multiselect would work, but copy paste can be done :)

Hmmm... Is there a file in the LLT folder that stores the location of these apps so that I can just add and remove them whenever I want, using notepad?

**Comment by BartoszCichecki** [comment]
They are stored in `automation.json` in `AppData\Local\LenovoLegionToolkit`. But ability to copy paste these items will be added in 2.5.0. It will also integrate with Ctrl+C and Ctrl+V and Windows clipboard, if you have a list of paths to exe files you will be able to copy paste it from/to any other app.
