### ISSUE TITLE
Feature: RGB Effect - AmbientLight/Aurora Sync

### ISSUE THREAD

**Issue by sickypedia** [BartoszCichecki/LenovoLegionToolkit#172]
**Is your feature request related to a problem? Please describe.**
This is a feature request for the RGB effect 'AmbientLight', which [this utility ](https://github.com/4JX/L5P-Keyboard-RGB#available-effects)has. I'm not sure if this is custom feature or built as a plugin into the RGB/BIOS firmware itself. 

`AmbientLight: Reacts to content on your screen.`

I believe Lenovo officially calls it Aurora sync and it would be awesome to have it activated without official bloat.

**Comment by BartoszCichecki** [comment]
Hey custom effects that are not natively supported in hardware are not planned.
