### ISSUE TITLE
Sometimes the dGPU is shown as "inactive" but still draws ~11W (L5pro)

### ISSUE THREAD

**Issue by martinderm** [BartoszCichecki/LenovoLegionToolkit#173]
Sometimes the dGPU is shown as "inactive" but still draws ~11W of power, according to HWiNFO64 sensor readouts and battery discharge. 
No process is actually using the dGPU, so there is no option to restart it.

Maybe you can monitor dGPU power usage and offer the option to reastart the dGPU if its drawing power despite being not in use.

Model: Legion 5 Pro 16ACH6H

**Comment by mind12** [comment]
> Sometimes the dGPU is shown as "inactive" but still draws ~11W of power, according to HWiNFO64 sensor readouts and battery discharge. No process is actually using the dGPU, so there is no option to restart it.
> 
> Maybe you can monitor dGPU power usage and offer the option to reastart the dGPU if its drawing power despite being not in use.
> 
> Model: Legion 5 Pro 16ACH6H

What do you use to monitor power draw, because HWinfo wakes the dgpu repeatedly. That could cause such issue.

**Comment by martinderm** [comment]
> HWinfo wakes the dgpu repeatedly. That could cause such issue.

It's visible also from the battery discharge. If the dGPU stays active there's 25-30W discharge, if not it's 15-20W when doing only light work.


After a reboot HWinfo correctly displays 0W for the dGPU power draw and battery discharge is 15-20W.

**Comment by BartoszCichecki** [comment]
But HWInfo itself is known for either keeping gpu alive or even waking it up. There is nothing I can do about that, if NVAPI reports GPU is off, then it's off. There are of course some bugs in the drivers and weird monitoring tools behaviors, but that unfortunately is how Optimus is.

**Comment by martinderm** [comment]
> ... if NVAPI reports GPU is off, then it's off. ..

Except when it's not 😂 scnr
Anyways the issue can be detected with battery drain alone, no HWinfo required. 

Apparently there is no Optimus in the AMD models btw. They are doing something else. Works most of the time, except when it's not.

Is there a way to force restart the the dGPU via commandline even when the API reports it's off? That would help testing out the issue.

**Comment by BartoszCichecki** [comment]
That's why I mentioned:
> There are of course some bugs in the drivers and weird monitoring tools behaviors, but that unfortunately is how Optimus is.

Optimus is not ideal, nothing can be done about that.


> Apparently there is no Optimus in the AMD models btw

There is if you have nVidia GPU. Heck, even some models with AMD CPUs have Advanced Optimus.

**Comment by BartoszCichecki** [comment]
> Is there a way to force restart the the dGPU via commandline even when the API reports it's off? That would help testing out the issue.

You can go to Device Managed right click nVidia GPU and Disable, then click Enable. This though is not recommended since sometimes GPU goes into P0 state almost as if the driver looses control over it. That's why preferred way is to kill processes.
