### ISSUE TITLE
Exception Handling - Quick Actions - Internal Display Off and dGPU active

### ISSUE THREAD

**Issue by sickypedia** [BartoszCichecki/LenovoLegionToolkit#175]
**Is your feature request related to a problem? Please describe.**
I have a quick action defined with multiple steps to optimize battery usage. However, I also use an external monitor from time to time, so in this case, the 'Refresh rate' and 'Deactivate GPU' options are not applicable as the internal display is off and dGpu is active.

![image](https://user-images.githubusercontent.com/73606172/185305901-dfe6e2bb-a491-407c-858e-08f0af577dda.png)

**Describe the solution you'd like**
Running this action crashes the tool with the below error. I understand this is by design, but is it possible for the toolkit to error handle this case and skip over the steps not applicable, instead of crashing?

![image](https://user-images.githubusercontent.com/73606172/185305080-bce172c8-a315-4f63-ba18-20980a10f5be.png)

**Comment by BartoszCichecki** [comment]
Of course that is totally a bug!
