### ISSUE TITLE
[BUG] The package download status is canceled/hidden, when the sorting or filter is used

### ISSUE THREAD

**Issue by younyokel** [BartoszCichecki/LenovoLegionToolkit#176]
This will cancel or hide download status.

Open Downloads tab -> Refresh to get package list -> Press download icon of any package -> While downloading, change sorting, or use Filter.

**Comment by BartoszCichecki** [comment]
2.5.0 shows a warning whenever download might be interrupted.  Fixing this "properly" is not planned ATM.
