### ISSUE TITLE
[BUG] Fn+Q Issues - No Performance Mode

### ISSUE THREAD

**Issue by JimboMahoney** [BartoszCichecki/LenovoLegionToolkit#177]
Firstly, thanks for this tool, it's really neat!

I had hoped to do away with Lenovo Vantage, but I'll have to carry on using it (and hopefully fix this issue that I'm stuck with!).

- Model = Legion 5 15ACH6H
- Machine Type = 82JU

Steps I followed:

-  Settings
- Disable Vantage & Fn Keys
- Reboot
- Test Fn+Q - only toggles between Quiet and Balanced mode
- In addition, Toggling lowers the brightness each time, so Quiet Mode ends up on minimal brightness, even if I manually increase it
- Manully selecting Performance doesn't seem to work - no red light on power button.

Steps I've tried to resolve:

- Enable Vantage and Fn Keys
- Reboot
- Run Lenovo Vantage
- Delete Power Plans
- Reboot
- Install Power Plans as per Step 3 on [Reddit](https://www.reddit.com/r/LenovoLegion/comments/se8qz0/how_to_get_lenovo_legion_fnq_power_plans_working/)
- Reboot

I'm now stuck without access to performance mode, as far as I can tell.

Any ideas welcome, I'd really rather avoid a fresh Windows install!

**Comment by JimboMahoney** [comment]
Hah, ignore! I thought my laptop was plugged in but my wife unplugged it and Performance mode is not available when not plugged in! 😮‍💨

**Comment by BartoszCichecki** [comment]
I was just typing the response :D Good that it got sorted out ;)
