### ISSUE TITLE
[FEAT]: Spectrum RGB support

### ISSUE THREAD

**Issue by poodiepie123456** [BartoszCichecki/LenovoLegionToolkit#178]
**Is your feature request related to a problem? Please describe.**
No, it is not a problem but it would be nice as a feature to Legion Toolkit. With it I don't have to use iCUE anymore 🥲 also, can you add resolution change into the action tab as well? It would be really nice for users with a 2K+ screen to roll to FHD res on battery without going into the settings app.

**Describe the solution you'd like**
My dream solution would be spectrum built into Toolkit:')) or a tool that can change the keyboard's backlight RGB and more brightness level (maybe 10 levels), plain and simple like the accent colour in the Toolkit. 

**Describe alternatives you've considered**
I think that's all for now. Thank you for listening and have fun making this 🥰

**Additional context**

**Comment by BartoszCichecki** [comment]
So you mean iCue or Spectrum RGB? Spectrum support will be comming at some point, iCue will not.

Regarding change resolution action, it is technically a possibility but you don't really save that much power by lowering resolution.

**Comment by poodiepie123456** [comment]
> So you mean iCue or Spectrum RGB? Spectrum support will be comming at some point, iCue will not.
> Yes I mean Spectrum. Really looking forward to it
> Regarding change resolution action, it is technically a possibility but you don't really save that much power by lowering the resolution.
Yes, and the resolution change is acceptable with or without. I just realised it wouldn't do much for battery life.

**Comment by RoadToDream** [comment]
I think it's definitely doable using HID reports, but implement Spectrum will be a burden from UI point of view...

**Comment by BartoszCichecki** [comment]
Yup, Spectrum is already reverse engineered https://github.com/SmokelessCPUv2/Lenovo-Spectrum-Protocol, but you're right, UI will be painful.

**Comment by RoadToDream** [comment]
> Yup, Spectrum is already reverse engineered https://github.com/SmokelessCPUv2/Lenovo-Spectrum-Protocol, but you're right, UI will be painful.

This implementation is great! Only lacks surrounding lightbar and panel logo light. I will check if I may complete it later.

**Comment by RoadToDream** [comment]
Alright I have added all keys mapping for Gen 7, including all surrounding lights and the panel logo. 
You may check pull request here just in case you need it sometime. 
https://github.com/SmokelessCPUv2/Lenovo-Spectrum-Protocol/pull/1

**Comment by RoadToDream** [comment]
[LZ.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9771824/LZ.txt)
That's a js file that will be very helpful for implementing Spectrum. Check function getKBStatusByUSB() getKBStatusByEC() setKBStatusByUSB() and many other functions.

**Comment by RoadToDream** [comment]
I was thinking Spectrum configure is stored onto keyboard controller, but it seems that's not the case. Based on a little more research, I can confirm that those configurations are stored on local storage(like Property.Settings), and cannot retrieve directly from the controller. For writing we have clearly defined formats in repo mentioned before, for reading it's a simple GET HID REPORT, detailed info will also be uploaded to Smokeless' repo later.

**Comment by Pkcarreno** [comment]
sorry for the question, but is there any hardware difference between the iCue laptop and the spectrum laptop (gen 6 and gen 7)?

**Comment by mind12** [comment]
> sorry for the question, but is there any hardware difference between the iCue laptop and the spectrum laptop (gen 6 and gen 7)?

Yes it is, different hardware. You can't use spectrum for gen6 and it might never will be backported to gen6.

**Comment by Pkcarreno** [comment]
hi @mind12, I see, and in case someone created an api to control the rgb of the gen 6 keyboard it could be integrated into the app?

**Comment by BartoszCichecki** [comment]
Maybe, but why if OpenRGB already supports it?

**Comment by Pkcarreno** [comment]
hi @BartoszCichecki, today i discovered openrgb and i've been playing with it a bit, yes i think it can replace iCue, but i don't have any other rgb device so i thought that being able to control everything related to the laptop in the same app would be great.

Anyway, today I also discovered this cool project on LenovoLegion's discord. 
Thank you very much for sharing this amazing app

no promises, but I will look for what api alternatives I can get to control the keyboard rgb, and if I get something I will update this thread or create a new issue with the details.

**Comment by Pkcarreno** [comment]
Hi @BartoszCichecki, sorry for commenting in this thread already closed, I've been thinking about it, I haven't got any api or way to control the rgb of versions previous to spectrum, however openrgb has a sdk, implementing this could allow not only gen 6 but previous generations to be compatible, it sounds like a lot of work but it could be an option.

Again, no promises, I'm just learning winui and it could be a good experiment to try this sdk, if I make some progress I'll comment again

**Comment by BartoszCichecki** [comment]
There is no such things as previous versions of spectrum. There are 4 types of backlight:
- white
- 4 zone RGB
- iCue RGB
- Per-key Spectrum RGB

All are now supported (albeit last one is not release yet) except for iCue. Including openRGB SDK in this project is a massive overkill and reimplementing the whole iCue protocol and everything makes no sense only for effectively two models: Legion 7 gen6 and Slim 7 gen6. That is why the decision was made to not support iCue at all, especially that you can use OpenRGB, so why reimplement something that is already there?

PS: This project does not use WinUI.

**Comment by Pkcarreno** [comment]
Wow, I didn't know that, I understand why now.
sorry for the inconvenience then
