### ISSUE TITLE
Battery Mode reset to "Normal" from "Conservation"

### ISSUE THREAD

**Issue by DJPillu** [BartoszCichecki/LenovoLegionToolkit#180]
**Describe the bug**
Battery mode is being reset to Normal from Conservation without my intervention causing laptop to charge to full

**To Reproduce**
1. Waking up from sleep mode
1.2 clicking X to close window
1.3 open window via taskbar icon
1.4 battery mode is reset to normal

1. When the application is started again (automatically) after a restart (not a 100 percent sure)

**Expected behavior**
The battery mode should be at conservation at all times until manually changed or by actions.
**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 11 21H2 build 22000.856
 - Laptop model: Legion 7 16ITHg6
 - Do you have Vantage installed? Yes
 - Do you have Vantage disabled with LLT? No
 - Do you have FN Keys service installed? Yes
 - Do you have FN Keys service disabled with LLT? No, disabled it myself prior to installing LLT

**Logs**
You might consider running with `--trace` parameter and attaching the log files. See README for details.
[log_2022_08_24_13_29_27.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9418619/log_2022_08_24_13_29_27.txt)

**Comment by BartoszCichecki** [comment]
As mentioned in #120, this is an issue with BIOS on some models and can't be resolved. You can try resetting EC or flashing a BIOS update if available, but chances it will help are slim. You can work around it by adding an Action in LLT that will set Conservation mode when AC adapter is connected and disconnected. That will not fix it 100% but can make it better.
