### ISSUE TITLE
Add an option to make FN+Arrow keys control brightness and volume.

### ISSUE THREAD

**Issue by VonSparq** [BartoszCichecki/LenovoLegionToolkit#181]
**Is your feature request related to a problem? Please describe.**
I have two older Lenovo Ideapad laptops and a really handy feature they have is being able to control the screen brightness with FN+up/down arrows and sound volume with FN+left/right arrows. Legion also has keyboard shortcuts for these functions but they are nowhere near as handy (FN+F1-6).

**Describe the solution you'd like**
I would love it if you could please add a toggle in LLTK that'd enable these keyboard shortcuts, I hope it is possible and not too much work for you.

**Describe alternatives you've considered**
I have looked for an option to enable these alternative hotkeys through Vantage and in BIOS but it looks like they there's no native way to do so in newer Lenovo laptops. I have also tried binding these hotkeys with a 3rd party hotkey program but it doesn't recognize the FN key.  

**Additional context**
It's just a feature I'm really used to on my laptops, I would love it if it would be possible to enable it in my Legion. Thank you for making this amazing program and I hope it's not too much to ask.

**Comment by BartoszCichecki** [comment]
This is actually a pretty good idea. However keys that do not have anything printed on them (in terms of Fn functions) are simply not sending any keycodes or events when Fn is depressed. Sadly, this can't be worked around :(
