### ISSUE TITLE
Screen stuck after waking up from sleep

### ISSUE THREAD

**Issue by DJPillu** [BartoszCichecki/LenovoLegionToolkit#182]
**Describe the bug**
Quite a fatal bug locking up my laptop and monitors screen with only the applications that were displaying on top before laptop was put to sleep (I am actually able to interact with those apps). I have also faced similar issues as mentioned [here](https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/142#issuecomment-1179413426)
The only thing I am able to do is WIN + L to move to lock screen which also doesn't show any options except to login which brings me right back to the stuck desktop. The only thing I can do as this point is to force-shutdown my laptop, I have had this happen about 3 times by now.
As @BartoszCichecki mentions in the issue I have referred above, I believe it to yet again be connected Desktop Manager.

Currently, I have reverted back to v2.3.1

**To Reproduce**
1. Put laptop into sleep mode
2. Wake it up

**Environment (please complete the following information):**

- OS: Windows 11 21H2 build 22000.856
- Laptop model: Legion 7 16ITHg6
- Do you have Vantage installed? Yes
- Do you have Vantage disabled with LLT? No
- Do you have FN Keys service installed? Yes
- Do you have FN Keys service disabled with LLT? No, disabled it myself prior to installing LLT

**Comment by BartoszCichecki** [comment]
What does it mean that "screen is stuck"?

**Comment by DJPillu** [comment]
"Screen is stuck" means 
1. none of the monitors display task-bar, 
2. no shortcuts seem to be working (like ctrl + shift + esc to open up task bar), even if they are, it doesn't show on the screen
3. The application's window itself seems to be interactable and allows to be minimized/closed
4. Even after minimization, no desktop icons display, neither does alt+f4 achieve anything.

**Comment by BartoszCichecki** [comment]
That sound like a Windows/driver issue on your machine, so I am not sure how LLT is related to this.

**Comment by mergen3107** [comment]
After returning from sleep, try Ctrl+Shift+Win+B, and if the screen flashes and comes back to normal then this is the video driver issue.
