### ISSUE TITLE
Gen 7 Custom Mode Support

### ISSUE THREAD

**Issue by KarlLee830** [BartoszCichecki/LenovoLegionToolkit#184]
**Is your feature request related to a problem? Please describe.**
The 2022 Legion has a new Power Mode in the Legion Zone software called custom mode, where you can customize the overclock and fan curve. I often use custom mode to make the fan go to maximum speed. After using Vantage and Toolkit the inability to set to custom mode makes it difficult for me to get the laptop case to cool down quickly after gaming.

**Describe the solution you'd like**
Support switching Power Mode to Custom mode.

**Describe alternatives you've considered**
Legion 2022 models sold in China are pre-installed with Legion Zone (https://legionzone.lenovo.com/), which supports setting to Custom mode in Legion Zone. However, Legion Zone has a very bad UI and takes up the dGPU, making it impossible to remove the dGPU. .

**Additional context**
I would be happy to assist you in making the legion toolkit support custom mode, even if it just adds the power mode toggle option and doesn't support customization, so I can save presets in the legion zone and just toggle with toolkit.
Here are some pictures about legion zone and custom mode.
( The translated text was added by me. )
<img width="794" alt="Snipaste_2022-08-27_04-01-07" src="https://user-images.githubusercontent.com/61072264/186982341-6d2f0b81-89ea-4a6b-a263-15039a3e0710.png">

<img width="795" alt="Snipaste_2022-08-27_04-02-40" src="https://user-images.githubusercontent.com/61072264/186982566-32d6fd43-3e7e-4805-9fa5-a6c2cfac0230.png">

When set to custom mode, the power button turns purple.

<img width="795" alt="Snipaste_2022-08-27_04-13-52" src="https://user-images.githubusercontent.com/61072264/186983930-1d49cf50-d6d9-4a4a-b9cc-dee566c9e3ad.png">

 
---

When set to custom mode, the legion toolkit can't get power mode:
<img width="863" alt="Snipaste_2022-08-27_04-04-21" src="https://user-images.githubusercontent.com/61072264/186982839-458e18fa-144a-4f7e-b4cb-c1d992727ae1.png">

**Comment by BartoszCichecki** [comment]
Custom mode for Gen 7 is the roadmap.
