### ISSUE TITLE
Deactivate GPU doesn't work after external monitor has been used with HDMI port

### ISSUE THREAD

**Issue by c1p0** [BartoszCichecki/LenovoLegionToolkit#185]
On my 2021 L5P 16ACH6H, the "Deactivate GPU" feature doesn't work after I have used an external monitor plugged into the HDMI port. 

I am on Lenovo Legion Toolkit version 2.4.1 / Windows 11 21H2 Build 22000.856

**Comment by mind12** [comment]
> On my 2021 L5P 16ACH6H, the "Deactivate GPU" feature doesn't work after I have used an external monitor plugged into the HDMI port.
> 
> I am on Lenovo Legion Toolkit version 2.4.1 / Windows 11 21H2 Build 22000.856

It's the expected behaviour because all external ports are wired to the dgpu. You need to remove the external monitor.

**Comment by BartoszCichecki** [comment]
Well if this is the case that you have external screen connected then this is not a bug. As mind12 said: external screens connect directly to dGPU so it can't be disabled.

**Comment by BartoszCichecki** [comment]
Well if you can reproduce it, then maybe you can say if LLT reports the dGPU as "Active" or as "Inactive" is the button clickable or not and finally what is shown when you hover the mouse over "Deactive".

**Comment by c1p0** [comment]
Hey, I made a screen recording because there is actually some weird behaviour with how everything is working. 

https://www.loom.com/share/bc3d390a9dc34a4386280450ef11dd56

Please let me know if there's any more info or details I can send your way.

**Comment by c1p0** [comment]
Also, another thing to mention is that my scenario for reproducing this every day is:

1. Unlug monitor (and all other USB cables)
2. Close the lid - Laptop goes into sleep
3. Drive home - Open the lid
4. Try to use LLT to deactivate dGPU

Maybe the laptop going into sleep in the meantime has something to do with it. 

When I recorded the video I posted above, I didn't close the lid, but it still happened.

**Comment by BartoszCichecki** [comment]
From what I can everything works as intended. You need to be aware that some monitoring apps will keep dGPU artificially awake. When that happens, even though nVidia APIs will report to LLT that there are no processes running and GPU should be sleeping. The general rule is that any monitoring app like HWInfo may keep GPU awake, so get rid of them if you want battery life. That is just how Optimus is.

**Comment by BartoszCichecki** [comment]
You can also verify that the driver is reporting that GPU is idle/sleeping by enabling the indicator in nVidia control panel.

**Comment by BartoszCichecki** [comment]
From what I have seen the only bullet proof way is to first check GPU state in LLT and then check battery power draw. If GPU is working, then power draw will not go below 20Wh. You can also hover mouse on the "inactive" label and the tooltip will show the performance mode at which GPU is running (or it will say smth like "Powered off"). There isn't much more that can be done here, rarely regardless of what you do, GPU will just not go to sleep and you need to reboot. But close HWInfo and other monitors. Afterburner is also messing with power states a lot. 

I will close the issue for now, but if you find something more just comment.

**Comment by BartoszCichecki** [comment]
I have also observed that sometimes GPU will be inactive but still in P8 state and only transition to Powered off after some time.
