### ISSUE TITLE
[FIXED] Memory leak after spending prolonged periods of time in another app/game

### ISSUE THREAD

**Issue by RuinDND** [BartoszCichecki/LenovoLegionToolkit#186]
**Describe the bug**

Memory leak.

The RAM usage of the app starts fluctuating up and down after spending constant time in a game/watching youtube and so on. It will start growing slowly with 5-10mb increase and for prolonged periods of time it would go to even hundreds of mb.

**Expected behavior**

I expect the RAM not to fluctuate between high and low values. It constantly grows to 400-500mb and then drops down to 50mb usage.
The problem happens only in this specific case. If computer is restarted, it will work fine until next time it goes idle.

**Screenshots**
https://imgur.com/a/4gPIUAh
https://imgur.com/a/DIkxTZy

**Environment (please complete the following information):**
 - OS: Windows 11 22H2 build 22621.457
 - Laptop model: Legion 5 Pro 16ACH6
 - Do you have Vantage installed? No
 - Do you have Vantage disabled with LLT? No
 - Do you have FN Keys service installed? Yes, but service is disabled.
 - Do you have FN Keys service disabled with LLT? [Yes/No] No
 - BIOS Version: GKCN44WW
![ancf2mA](https://user-images.githubusercontent.com/112415312/187484414-b0e7af34-ff99-4425-ad43-70d4ef007cfd.png)
![Gsb1oIx](https://user-images.githubusercontent.com/112415312/187484421-f448ba91-38dc-4b0a-a02c-6234c7039d38.png)
![1EMaCW0](https://user-images.githubusercontent.com/112415312/187485386-73fe41a8-30bd-4e2b-aa0a-093996462d40.png) 

Last pic is after restarting system.

**Logs**

You might consider running with `--trace` parameter and attaching the log files. See README for details.

**Comment by BartoszCichecki** [comment]
Hey, thanks for reporting. Do you have any actions configured? And I guess LLT is minized to tray when that happens?

**Comment by BartoszCichecki** [comment]
OK, so basically LLT starts on startup and when in background memory usage increases, right?

**Comment by BartoszCichecki** [comment]
I think I will need to ask you for a log file.

**Comment by BartoszCichecki** [comment]
Also does this high usage maintain and you need to restart, or it goes back to reasonable levels (<100MB) on it's own?

**Comment by BartoszCichecki** [comment]
OK, I would like that you enabled logging (see README) and send me a log from when it happens. Also if you can write down exact scenario where it happens consistently it will be super useful.

**Comment by BartoszCichecki** [comment]
Hey, I can't see anything strange and also I can't really reproduce the issue. That being said, I optimized a couple of things, when Actions are disabled. There was some unnecessary code running in the background. Take a look if this improves the situation.

[LenovoLegionToolkitSetup_2.5.0_b2.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9463532/LenovoLegionToolkitSetup_2.5.0_b2.zip)
