### ISSUE TITLE
action menu lock it battery charge setting and cant change it in main menue

### ISSUE THREAD

**Issue by TONEOFTEARS** [BartoszCichecki/LenovoLegionToolkit#194]
in action menu i make it when plugged automatically make battery conservation on ... but after that in main menu i cant change it to full because action menu lock it ,,, could u please modify it and give priority to the main menu after action menu done

**Comment by BartoszCichecki** [comment]
What version are you using? What about logs? What about proper description of the issue?

**Comment by TONEOFTEARS** [comment]
version 2.4.1
actually i cant know how to get the log file 
more detail description 
if i make in action menu that i want when ac  adapter is connected . make battery charge more to conservation  
then 
i connect the ac adapter  .. the action menu do all the action i did and make batter charge to conservation 
then
i go to toolkit main menu and want to change the charge mode to normal charge 
the mode still in conservation mode still 

thats it

**Comment by BartoszCichecki** [comment]
Here you can find instruction on how to collect logs:

https://github.com/BartoszCichecki/LenovoLegionToolkit#how-to-collect-logs

**Comment by TONEOFTEARS** [comment]
[Uploading log_2022_09_03_00_12_07.txt…]()

**Comment by BartoszCichecki** [comment]
It looks like you didn't upload it correctly.

**Comment by TONEOFTEARS** [comment]
[log_2022_09_03_00_12_07.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9480859/log_2022_09_03_00_12_07.txt)

**Comment by BartoszCichecki** [comment]
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9482905/LenovoLegionToolkitSetup.zip)

Hey, please try the build above and let me know if the issue is fixed :)

**Comment by TONEOFTEARS** [comment]
ok will try

**Comment by TONEOFTEARS** [comment]
workted thank you
