### ISSUE TITLE
[FEAT]: Customizable list of refresh rate options

### ISSUE THREAD

**Issue by KrishivVora** [BartoszCichecki/LenovoLegionToolkit#196]
### Version

2.5.0

### OS

Windows 11 21H2 Build 22000.918

### Device

 Legion 5 Pro 16ARH7H 82RG001MUS

### Is your feature request related to a problem?

Currently, the list of refresh rates in the refresh rate dropdown menu has a lot of extra options like 30hz, 45hz, 75hz, etc. This leads to the Fn + R shortcut going through all these options when pressing it, which makes it take longer to toggle between 60hz and 165hz using the shortcut.

### How would you like the problem to be solved?

I'd love it if the list of refresh rates was customizable (either directly in the GUI or in a config file) so that I could only keep 60hz and 165hz in that list. This would make Fn + R only toggle between those two refresh rates for me, or how many ever refresh rates someone chooses. It could be possible that certain refresh rates are not supported by the person's display, so maybe there should be a warning to only set refresh rate to one of the supported values.

### What alternatives have you considered?

If this feature wasn't there it just makes it harder to toggle between 60hz and 165hz using the shortcut (I feel like those are the two most common refresh rates most people would care about toggling between, and not really using any other ones).

**Comment by BartoszCichecki** [comment]
Hey here is the build that adds the feature you requested:
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9499325/LenovoLegionToolkitSetup.zip)

Go to Settings and Exclude refresh rates.
