### ISSUE TITLE
[FEAT]: CPU Boost modes in actions

### ISSUE THREAD

**Issue by Spoof14** [BartoszCichecki/LenovoLegionToolkit#197]
### Version

2.5.0

### OS

Windows 11

### Device

Legion 5i pro gen 7

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

Make it possible to change CPU Boost modes with actions

### What alternatives have you considered?

I guess this could be done through power modes too, but I couldn't make it work

**Comment by BartoszCichecki** [comment]
CPU Boost modes are linked to Windows Power Plans, so if you assign different power plans to each power mode you should be able to do it. It is not technically feasible to detach these settings.
