### ISSUE TITLE
[BUG]: [Legion Slim 7 16IAH7] Support battery temperature reading

### ISSUE THREAD

**Issue by ldeseta** [BartoszCichecki/LenovoLegionToolkit#198]
### Version

2.5.0

### OS

Windows 11 21H2

### Device

Legion S7 16IAH7

### What's wrong?

The battery temperature status is in negative (and very incorrect) values. Like -273,2 C / -459,7 F

![imagen](https://user-images.githubusercontent.com/3856866/188524233-3bf8dc60-62ba-48c8-beca-c1327278bbf0.png)

### How to reproduce the bug?

1. Open LLT
2. Go to Battery section

### What is the behavior that you expected?

The battery temperature should be displayed

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Hey, can you run these two commands for me in PowerShell (as adminitrator):

```
(Get-WmiObject -namespace ROOT\WMI -class BatteryTemperature)
(Get-WmiObject -namespace ROOT\WMI -class Lenovo_BatteryInformation)
```

Also, do you see battery temperature in tools like HWInfo?

**Comment by ldeseta** [comment]
The first command returns empty. 
The second command returns an error "Class not valid Lenovo_BatteryInformation"

![imagen](https://user-images.githubusercontent.com/3856866/188626777-ecffcead-28e6-4748-ab42-c92275b17d52.png)

HWInfo does not display the battery temperature (Vantage does).

**Comment by ldeseta** [comment]
Yeap, I guess Lenovo does not share any documentation about these values. Let me know if I can help you in any way (maybe there is a command that uses wildcards, like "*Battery*" or something?)

**Comment by BartoszCichecki** [comment]
Note: seems that only Slim 7 Gen7 is affected by this.

**Comment by BartoszCichecki** [comment]
@ldeseta could maybe zip all contents of "C:\ProgramData\Lenovo\ImController" and upload them somewhere?

**Comment by ldeseta** [comment]
Sure thing! Here it is:

https://drive.google.com/open?id=13kKzBlDpVaXl6joJDrdZlBW9aTesk-Xo&authuser=ldeseta%40gmail.com&usp=drive_fs

**Comment by BartoszCichecki** [comment]
OK, this seems to be a dead end unfortunately. Let's try something else.


Install this build: [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9499577/LenovoLegionToolkitSetup.zip)

Run it and go to battery page. In `%LOCALAPPDATA%\LenovoLegionToolkit\log` there will be a `battery.txt` file please upload it here.
Also post the battery temperature shown by Vantage.

I am thinking that maybe this data is just at a different offset.

**Comment by ldeseta** [comment]
The battery temp in Vantage is 24 C.
![imagen](https://user-images.githubusercontent.com/3856866/188747176-f386d81a-b5fb-424d-9034-39d1ba78b8ac.png)

Here is the battery.txt file (created at the same time the battery was at 24C):
[battery.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9501092/battery.txt)

Hope that helps!

**Comment by BartoszCichecki** [comment]
Can you send me a screenshot like this one?

![image](https://user-images.githubusercontent.com/7916915/188979883-68f7bec0-0c6c-4b5e-a0a3-807ce91ecaaa.png)

**Comment by BartoszCichecki** [comment]
Can you run these two lines in PowerShell as admin?

```
Get-WmiObject -namespace ROOT\WMI -class BatteryStatus
Get-WmiObject -namespace ROOT\WMI -class BatteryTemperature
```

It's a long shot but you never know.

**Comment by ldeseta** [comment]
Get-WmiObject -namespace ROOT\WMI -class BatteryStatus
[commands.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9521966/commands.txt)

The seconds command returns empty. 

If it helps: 
![imagen](https://user-images.githubusercontent.com/3856866/188994181-ff76772e-9748-4ac1-a807-a23264e8dc4d.png)

**Comment by BartoszCichecki** [comment]
OK, thanks a lot I have one more idea but I need more time to do it, so I'll ping you in a couple of days!

**Comment by BartoszCichecki** [comment]
Found a fix. It will be released with next update, in the meanwhile you can use build below.
Thanks for reporting this!

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9531031/LenovoLegionToolkitSetup.zip)

**Comment by ldeseta** [comment]
> Found a fix. It will be released with next update, in the meanwhile you can use build below. Thanks for reporting this!
> 
> [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9531031/LenovoLegionToolkitSetup.zip)

It works just great!!! Thanks a lot. 🤗

Also, thanks for coding and sharing this awesome tool, truly appreciated. Keep on the great work!
