### ISSUE TITLE
[COMPATIBILITY]: IdeaPad 5 Pro 14ITL6

### ISSUE THREAD

**Issue by labodj** [BartoszCichecki/LenovoLegionToolkit#206]
### Version

2.5.0

### OS

Windows 11 10.0.22000.918

### Device

IdeaPad 5 Pro 14ITL6

### Which features of the application did you test?

- Battery Mode: OK
- Always on USB: OK
- Discrete GPU: OK,
- Fn lock: inverted behaviour
- Flip To Start: OK
- Keyboard Backlight Brightness: OK
- Battery temperature: -273,2
- Battery manufacture date: no data
- Power plans: crash (Feature SmartFanMode non supported)
- Power profiles switch (Fn+Q): missing

### Which features of the application do not work as expected?

- Fn lock: inverted behaviour
- Battery temperature: -273,2
- Battery manufacture date: no data
- Power plans: crash (Feature SmartFanMode non supported)
- Power profiles switch (Fn+Q): missing

### Logs

Log with 2.5.0:
[log_2022_09_08_20_42_58.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9530620/log_2022_09_08_20_42_58.txt)

Log with the version found [here](https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/198#issuecomment-1238476822) (for battery temperature reading problem):
[battery.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9530625/battery.txt)
[log_2022_09_08_21_00_09.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9530626/log_2022_09_08_21_00_09.txt)
[commands.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9530633/commands.txt)

### Additional information

Hi, I know this laptop it's outside the goal for this project.
I use your app in my Legion and I decided to try it in my IdeaPad.
Almost all functionalities just works, it has only minor imperfections, so I hope you can support it in a future.
It's pretty cool and very light comapred to Vantage.
I can help you testing and debugging things if you want.
Thanks for your time

**Comment by labodj** [comment]
Battery stats
![battery](https://user-images.githubusercontent.com/2527836/189228348-3583faa2-7640-4fab-9179-6e6ebd88d7d0.png)
Performance profiles (Fn+Q) missing
![performance profiles](https://user-images.githubusercontent.com/2527836/189228351-55c37d19-28df-4d68-a187-a353f9a46879.png)

**Comment by BartoszCichecki** [comment]
Hey, support for devices not from Legion series is not planned.
