### ISSUE TITLE
[FEAT]: Show GPU status in tray

### ISSUE THREAD

**Issue by 0x1F9F1** [BartoszCichecki/LenovoLegionToolkit#208]
### Version

2.5.0

### OS

Windows 10

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

Although NVIDIA has a tray icon to show GPU status, it sometimes shows the GPU as being inactive when it isn't.

### How would you like the problem to be solved?

LLT's tray icon could change to show the GPU's status. For example, a green icon could indicate the GPU is active and can be deactivated, and a blue icon could indicate the GPU is active but cannot be deactivated.

### What alternatives have you considered?

The main alternative is the NVIDIA icon, but it isn't always accurate.

**Comment by BartoszCichecki** [comment]
I will need to take a look at this. Updating the GPU state might be quite expensive and there is always a risk the fetching information from NVAPI might cause GPU to wake up - that is probably the nVidia icon refreshes very very slowly.

**Comment by BartoszCichecki** [comment]
Blocked by: https://github.com/lepoco/wpfui/issues/408
