### ISSUE TITLE
[FEAT]: Allow creating actions on "when low power AC charger is plugged in"

### ISSUE THREAD

**Issue by mwskwong** [BartoszCichecki/LenovoLegionToolkit#210]
### Version

2.5.0

### OS

Windows 11

### Device

Legion 5 Pro 16IAH7H

### Is your feature request related to a problem?

I wish the system to auto-switch the thermal mode as follows:

On battery: Quiet
When low power charger plugged in: Balance
When full power charger plugged in: Performance

### How would you like the problem to be solved?

Add an extra action of "when low power AC charger is plugged in". LLT seems able to detect whether a low or high-power charger is being used already according to the battery section.

### What alternatives have you considered?

Modify the existing "when AC charger is plugged in" action, such that it will be triggered when low power AC charger is used as well.

This will also work because the max thermal mode available when low power AC charger is used is balanced. So according to the current behavior of the software, setting thermal mode to performance when unplugged will fallback to balance.

**Comment by BartoszCichecki** [comment]
Fixed in #23ef9ab
