### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by vink2212** [BartoszCichecki/LenovoLegionToolkit#211]
### Version

2.5.0

### OS

Windows 11

### Device

Legion 7 16ACHg6

### Is your feature request related to a problem?

I like to keep my battery between 80% and 20% charge. To do this I use a VBS script that gives me a notification when the battery is at 80% and then use LTK to activate conservation mode. Is there any way to automate this process?

### How would you like the problem to be solved?

Currently you can only make actions that activate when a .exe file is started, if it was possible to do the same with a script that may solve the issue.

### What alternatives have you considered?

introducing a new action that triggers at certain battery percentages (This would also be helpful for power plans as we could activate an ultra quiet mode plan when the battery falls below a certain percentage) would also solve this issue and be useful for other scenarios as well.

### Additional information

I understand that it is not possible to change the conservation amount for the battery but with the new gen 7 devices lenovo has changed this amount to 80% or so. It would be ideal to have a way that our older devices can include this as it balances battery health and screen on time when away from the wall. 

Apologies for making a ticket for this again.

**Comment by BartoszCichecki** [comment]
Sorry, support for this is not planned.
