### ISSUE TITLE
[BUG]: RGB keyboard effects don't apply automatically on startup

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#212]
### Version

2.5.0

### OS

Windows 10 Latest build

### Device

Legion 5 Pro 16ACH6H

### What's wrong?

I have to use FN + Space every time I boot up to apply my custom RGB profiles in the latest release (2.5.0).
Previous versions for example (2.4.1) automatically apply my custom profiles on application startup.

Thanks!

### How to reproduce the bug?

Explained in description

### What is the behavior that you expected?

Automatically load custom profiles

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Can you provide a log?

**Comment by Oblivious02** [comment]
> Can you provide a log?

I've downgraded to the 2.4.1 release yesterday, would the log contain info about the newer release, or is it lost?
Also, where are logs stored? I can only find logs for errors.

**Comment by BartoszCichecki** [comment]
README contains description on how to collect logs. You can also try the 2.6.0 beta version:

[LenovoLegionToolkitSetup_2.6.0_b1.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9593609/LenovoLegionToolkitSetup_2.6.0_b1.zip)

**Comment by Oblivious02** [comment]
It's fixed in this beta version, thanks!

**Comment by Oblivious02** [comment]
> README contains description on how to collect logs. You can also try the 2.6.0 beta version:
> 
> [LenovoLegionToolkitSetup_2.6.0_b1.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9593609/LenovoLegionToolkitSetup_2.6.0_b1.zip)

**Comment by Oblivious02** [comment]
> README contains description on how to collect logs. You can also try the 2.6.0 beta version:
> 
> [LenovoLegionToolkitSetup_2.6.0_b1.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9593609/LenovoLegionToolkitSetup_2.6.0_b1.zip)


I was hibernated, booted up with the wave animation and the program didn't override it automatically, I had to CTRL + Space to view my custom RGB effect
log: [hibernate keyboard bug.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9639031/hibernate.keyboard.bug.txt)

**Comment by BartoszCichecki** [comment]
Ah, so it's not on startup but on resume from hibernate?

**Comment by BartoszCichecki** [comment]
Found and fixed will be available in next release.

**Comment by Oblivious02** [comment]
> Found and fixed will be available in next release.

Excellent! Thank you mate!
