### ISSUE TITLE
[BUG]: Nvidia GPU not turning on after plugging in AC power

### ISSUE THREAD

**Issue by KrishivVora** [BartoszCichecki/LenovoLegionToolkit#213]
### Version

2.6.0 beta 1

### OS

Windows 11 21H2 Build 22000.978

### Device

Legion 5 Pro 16ARH7H 82RG001MUS

### What's wrong?

I mentioned this problem previously in #162 regarding Hybrid mode not working correctly, but I'll describe it again here since I realized today that it's still occuring.

So basically, the issue is that the Nvidia GPU is not working at all after replugging in the laptop to AC power after it has been unplugged (i.e. on battery power). It works correctly when the laptop is plugged in when powered on, but the issue happens when the laptop is plugged in again after having been unplugged.

### How to reproduce the bug?

These are the steps that lead to this error occuring (I am in **Hybrid-Auto** mode):

1. Unplug AC adapter from laptop (before unplugging, Nvidia dGPU and AMD iGPU are working the way they should, with the Nvidia GPU being off when light tasks are being performed and turning on for games)
2. After unplugging AC adapter, Nvidia dGPU disappears from places like Task Manager performance window or NVCP. AMD iGPU does everything since laptop is on battery power.
3. Upon replugging in the AC adapter, the state from 2 remains. Nvidia dGPU does not reappear in those places and does not get activated when playing games.
4. On restarting the laptop while remaining plugged in, the state from 1 resumes. Both GPUs work as expected.

### What is the behavior that you expected?

Both GPUs should maintain the proper hybrid switching regardless of whether I am plugged in when the laptop powers on, or plug in after being on battery power for some time.

### Logs

Will attach in a minute

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by KrishivVora** [comment]
[log_2022_09_18_02_54_13.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9592955/log_2022_09_18_02_54_13.txt)
Logs!

**Comment by BartoszCichecki** [comment]
Hey, the 2022 Hybrid Mode switches were tested extensively and LLT sends exactly the same commands to the hardware as Vantage and Legion Zone. If there are problems on your machine it might be due to BIOS or driver versions or some other stuff. On top of that there were no changes to that part of LLT since issue #162 and #165 were reported.
