### ISSUE TITLE
[BUG]: Prior version 2.5.0, the Keyboard tab showed the lighting configuration

### ISSUE THREAD

**Issue by akocli** [BartoszCichecki/LenovoLegionToolkit#214]
### Version

2.5.0

### OS

Windows 10 Home 21H2

### Device

Legion 5 15ACH6

### What's wrong?

Prior version 2.5.0,  the Keyboard tab showed the lighting configuration. Now it appears as [if my model has no keyboard lighting](https://i.imgur.com/CPjnsGG.png).

### How to reproduce the bug?

Go to the keyboard tab. No keyboard is shown.

### What is the behavior that you expected?

Show the RGB configuration for the keyboard.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please teach logs. Instructions are in readme.

**Comment by akocli** [comment]
Issue/bug is no longer present after restarting.

[log_2022_09_18_10_01_45.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9593669/log_2022_09_18_10_01_45.txt)

**Comment by BartoszCichecki** [comment]
Then I'll close the issue for now. When it happens next time, please collect logs and attach them.
