### ISSUE TITLE
[FEAT]: GPU Overclocking and Ryzen cpu tweaking feature request

### ISSUE THREAD

**Issue by marwan4mr** [BartoszCichecki/LenovoLegionToolkit#216]
### Version

2.5.0

### OS

Windows 10 

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

this would minimize the background programs for a lot of legion laptop users
*add gpu overclocking and gpu memory oc and dgpu temp limit change (and maybe add shortcut for Windows key + Ctrl + Shift + B)
*add ryzenadj so we can limit temp on ryzen cpu and generally tweak them

### How would you like the problem to be solved?

add some tweaking options 

### What alternatives have you considered?

run these features using different software (ryzen controller)(msi afterburner)

### Additional information

i would like to thank the developer for his effort that made my experience using my laptop better <3 .

**Comment by BartoszCichecki** [comment]
I understand where are you coming from, but for overclocking there are better tools like XTU, RyzenAdj, AATU and Afterburner.

Adding them to LLT would increase it's memory usage and complexity, and in the end LLT is meant to provide features from Vantage/LZ that are not available in other software, not to be ultimate toolkit for everything. Especially not a replacement for far better tools like mentioned above.
