### ISSUE TITLE
[BUG]: Touchpad Lock resets itself after Sleep/Restart or Shutdown

### ISSUE THREAD

**Issue by RuinDND** [BartoszCichecki/LenovoLegionToolkit#218]
### Version

2.5.0

### OS

Windows 11 Pro 22H2 (OS Build 22621.521)

### Device

Legion 5 Pro 16ACH6H

### What's wrong?

When laptop goes into sleep mode while idle or is restarted/shutdown, the Touchpad Lock resets itself. If you usually keep it turned on, it will switch itself to off.

### How to reproduce the bug?

1. Set Touchpad Lock to ON
2. Restart laptop
3. You will notice when you open LTK after the restart that it switched itself to off.

### What is the behavior that you expected?

It should maintain the setting despite restart/sleep, just like other settings such as Overdrive(which work just fine).

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

BIOS Version: GKCN44WW

**Comment by BartoszCichecki** [comment]
It's not a bug in LLT. Lenovo's firmware tends to do these things. LLT is always reading the current state from FW and does not store this information. BIOS update might help or you can mitigate this with Actions.
