### ISSUE TITLE
CLI Interface, Hotkey and Minimize to Tray Support

### ISSUE THREAD

**Issue by sickypedia** [BartoszCichecki/LenovoLegionToolkit#22]
Hello, thank you very much for the app! I have been using it daily and have a few suggestions:

1. A dedicated CLI binary for quickly toggling features or additional command line parameters which can be passed on to the main app without loading GUI.
2. Minimize to tray support, to have the app running (and possibly bring it up using a keyboard shortcut). 
3. Support for hotkeys (Fn+q for power plans, Fn+r for refresh rate) while the app stays minimized in tray. The official hotkeys app relies on Vantage services and does not seem to work hence would be great if the app can make these keys useful again :) . I am on a clean install of Windows 10 without Vantage installed due to the telemetry involved.

**Comment by younyokel** [comment]
Minimise to tray? Do you change options often?

**Comment by sickypedia** [comment]
I assumed the app would have to be kept open for the keyboard shortcuts to work - to switch between the perf profiles and refresh rate. So #2 is technically a dependency for #3 above. 

There are two issues on a clean OS without lenovo stuff installed (Vantage and Hotkeys):

1. The power profiles (Legion Performance, Balance and Quiet) have to be manually added to the windows plans through powercfg tool in windows. These plans have hardcoded GUIDs which this toolkit and the official apps use.
2. Even if plans are added, no changes occur when using Fn+q is used - only the color indicator on the power button changes but no program actually sends windows the command to change the plan. I was hoping the toolkit can do this, so official apps can be bypassed altogether. Plus the option to toggle display refresh rate from the app would be a good addition.

**Comment by BartoszCichecki** [comment]
Just to be clear, if you clean installed I would install Hotkeys anyway. They are pretty lightweight.

**Comment by sickypedia** [comment]
Thanks @BartoszCichecki, I tried that, but Fn shortcut keys did not work - I believe they rely on Vantage services to actually change the power plan.

**Comment by BartoszCichecki** [comment]
Yes, changning the power plan may not work without Vantage if you use Fn+Q. The shortcut itself as well as Fn+Y and Fn+R should work with only Hotkeys installed. BUT Vantage during installation is adding some interfaces to WMI that this app is also using, and this scenario without anything installed is completely untested. I would really suggest to install Vantage and Hotkeys and if you don't want anything in the background, disable Vantage from this Toolkit.

Regarding other suggestions:
1. CLI, not a bad idea, I'll add it to the list.
2. Minimize to tray, is already kind of on the list, but I will need to add "listening" for changes first to make it useful: if you keep Toolkit open and change a power plan, it does not refresh and it should :) This needs to be added first.
