### ISSUE TITLE
[FEAT]: Add possibility to have grey icon

### ISSUE THREAD

**Issue by kevtang** [BartoszCichecki/LenovoLegionToolkit#220]
### Version

2.5.0

### OS

Widnows 11  10.0.22000 Build 22000

### Device

Legion 7 Slim 15ACH6

### Is your feature request related to a problem?

If users are running dark theme, is it possible to have the tray icon be Gray and white instead of bright neon red and white?

### How would you like the problem to be solved?

Light theme = red and white
dark theme = black and white or grey and white

### What alternatives have you considered?

This just goes better with most users who are running dark theme, the red and white really stands out at night when running a dark wallpaper + dark theme.

**Comment by BartoszCichecki** [comment]
Currently the UI library does not allowing changing the tray icon dynamically. On top of that only the tray icon could possibly be changed.

If anything changes, I will reopen this issue, but for now I will close it.
