### ISSUE TITLE
[FEAT]: GEN 7 Custom profiles

### ISSUE THREAD

**Issue by AceAsket** [BartoszCichecki/LenovoLegionToolkit#221]
### Version

2.6.0

### OS

Windows 11

### Device

Legion Y9000X IAH7

### Is your feature request related to a problem?

In the Legion zone for the H9000X ICH7 in the user profile, you can increase the frequencies and additional options for controlling the processor and gpu

### How would you like the problem to be solved?

add an option to user profiles and the ability to create multiple custom profiles

### What alternatives have you considered?

use this in legion zone

### Additional information

in legion zone screen
<img width="683" alt="image" src="https://user-images.githubusercontent.com/12966662/192122204-e749e340-94a1-427d-9724-daae1e311822.png">

**Comment by BartoszCichecki** [comment]
Support for temperature sliders will be added, but there are no plans to add support for GPU OC - just use Afterburner for that.

If you would like to create multiple profiles, please make a separate issue.
