### ISSUE TITLE
[BUG]:  FN Lock button setting seems reversed

### ISSUE THREAD

**Issue by Leemonoid** [BartoszCichecki/LenovoLegionToolkit#222]
### Version

2.6.0

### OS

Windows 11 build 22622.601

### Device

Legion Y740-17IRHg

### What's wrong?

The FN lock button is showing "ON" in the Legion Toolkit interface but the feature is off on the laptop.  When FN Lock is turned "OFF" in Legion Toolkit, it enables FN Lock on the laptop.

### How to reproduce the bug?

Click "FN Lock" in Legion Toolkit and observe the computer is responding the opposite of what's expected.

### What is the behavior that you expected?

Function seems to be inverted

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please attach a log file.

**Comment by Leemonoid** [comment]
[log_2022_09_24_23_42_06.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9639758/log_2022_09_24_23_42_06.txt)

**Comment by BartoszCichecki** [comment]
[LenovoLegionToolkitSetup_fn_lock.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9640827/LenovoLegionToolkitSetup_fn_lock.zip)

Can you try this build and send logs from it?

**Comment by Leemonoid** [comment]
The build you sent seems to have fixed the problem.  Logs attached, and thanks!
[log_2022_09_25_13_31_24.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9640868/log_2022_09_25_13_31_24.txt)

**Comment by BartoszCichecki** [comment]
OK, I will need to verify that, because it seems that your model is correctly recognized as pre 2021 model, but for some reason it doesn't require FN lock flip.

**Comment by BartoszCichecki** [comment]
Fixed in ff7de4d89c7977f692b3f79f1f9ec030fcc5776f
