### ISSUE TITLE
[FEAT]: light usb ports

### ISSUE THREAD

**Issue by AceAsket** [BartoszCichecki/LenovoLegionToolkit#223]
### Version

2.6.0

### OS

Windows 11

### Device

Legion Y9000X IAH7

### Is your feature request related to a problem?

usb panel illumination
![image translated](https://user-images.githubusercontent.com/12966662/192122324-c7c99843-6143-47a4-9278-9df2f2274456.jpg)

### How would you like the problem to be solved?

turn it on/off

### What alternatives have you considered?

use legion zone or hotkeys

**Comment by BartoszCichecki** [comment]
I don't know which interface these controls are using, so I will be needed some help to add this toggle.

Just out of curiosity, can you use the Fn+U or Fn+L shortcut to turn these on/off?

**Comment by AceAsket** [comment]
yes FN + U worked

**Comment by AceAsket** [comment]
> I don't know which interface these controls are using, so I will be needed some help to add this toggle.
> 
> Just out of curiosity, can you use the Fn+U or Fn+L shortcut to turn these on/off?

will this be added to the plan?

**Comment by BartoszCichecki** [comment]
If someone reverse engineers, how are they set then yes.

**Comment by RoadToDream** [comment]
Hi @BartoszCichecki, you may config that by using this script. 

```powershell
function Toggle-RearUSBLightingState {
    $LenovoWMIPath=(Get-WmiObject -Namespace "root\WMI" -Query "SELECT * FROM LENOVO_LIGHTING_METHOD").__PATH
    $LenovoWMI=[WMI]$LenovoWMIPath
    $LightingID=5
    $CurrentState=$LenovoWMI.Get_Lighting_Current_Status($LightingID).Current_State_Type
    $TargetState=[int]($CurrentState -xor 1)
    $LenovoWMI.Set_Lighting_Current_Status($LightingID,$TargetState,0)
    
}
```

**Comment by BartoszCichecki** [comment]
@RoadToDream do you know if more could be done via this interface? Anything more than USB ports lightning?

**Comment by RoadToDream** [comment]
There should be more for different versions of BIOS, but for mine I guess that's all.

**Comment by BartoszCichecki** [comment]
Hey, @RoadToDream you have an idea how to check for compatibility of this feature? I can execute these commands on L5P which doesn't have backlight of ports. I need to check somehow if device supports it, so that I don't show this on device like L5P.

**Comment by RoadToDream** [comment]
> Hey, @RoadToDream you have an idea how to check for compatibility of this feature? I can execute these commands on L5P which doesn't have backlight of ports. I need to check somehow if device supports it, so that I don't show this on device like L5P.

WMI call should return a code where code 3 should be error. If that doesn't work, maybe a BIOS version whitelist is good I guess.

**Comment by BartoszCichecki** [comment]
Closing since there doesn't seem to be a consistent interface for this that would allow:
1. Checking if devices has support for this
2. How to reliably turn it on/off an a wide range of devices.

In general looks like Lenovo has a very complex/broken logic for this.

If someone comes up with a solution to this make a PR.
