### ISSUE TITLE
[COMPATIBILITY]: Apply for Legion Y9000P IAH7H (Chinese Edition of LEGION 5 Pro-16" Gen 7)

### ISSUE THREAD

**Issue by MZhao-ouo** [BartoszCichecki/LenovoLegionToolkit#224]
### Version

2.6.0

### OS

Windows 11 22H2 build 22622.601

### Device

Legion Y9000P IAH7H
![image](https://user-images.githubusercontent.com/70903329/192141050-a4321136-bf99-4af5-95ca-6c6c8995d4de.png)

### Which features of the application did you test?

**Power**
- Power Mode
- Battery Mode
- Always on USB

**Graphics**
- GPU Working Mode
- Refresh rate
- Deactivate GPU

**Other**
- Touchpad Lock
- Fn Lock
- Windows Key Lock
- Filp To Start
- Over Drive

**Keyboard**
- Brightness

### Which features of the application do not work as expected?

Most of features in LLT work well. Here's some not important features that not work.

### Fn+R shortcut
It doesn't work on Legion Zone or Lenovo Vantage too.

### Warranty
Maybe it is Chinese Edition so you can't get it.
![image](https://user-images.githubusercontent.com/70903329/192140264-328f1952-f202-4332-9ccd-456445496263.png)

### Additional information

Will quick actions support GPU working mode ?

**Comment by BartoszCichecki** [comment]
Hey,

Regarding Fn+R, can you try to enable logging and try pressing Fn+R a couple of times?

Regarding the warranty info try copying this URL:
```
https://pcsupport.lenovo.com/api/v4/upsellAggregation/vantage/warrantySummaryInfo?geo=us&language=en&sn=SERIAL_NO
```
and replace `SERIAL_NO` with your actual serial number? You can check in the browser what this URL returns, because maybe we can add support for Chinese models too. You can also try replacing the `geo=us` with `geo=cn` for example and seeing if there is any difference.

**Comment by MZhao-ouo** [comment]
Here is the log after pressing Fn+R.
[log_2022_09_25_13_16_46.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9640836/log_2022_09_25_13_16_46.txt)

Regarding the warranty, whether using `geo=us` or `geo=cn`,  the return is the same:
```
{"data":null,"code":2022,"msg":{"desc":"Unknown Warranty","value":null}}
```

**Comment by MZhao-ouo** [comment]
Here is the log after pressing Fn+R.
[log_2022_09_25_13_16_46.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9640836/log_2022_09_25_13_16_46.txt)

Regarding the warranty, whether using `geo=us` or `geo=cn`,  the return is the same:
```
{"data":null,"code":2022,"msg":{"desc":"Unknown Warranty","value":null}}
```

**Comment by BartoszCichecki** [comment]
Can you try: `https://newsupport.lenovo.com.cn/api/machine/getmachineinfo?sn=` this url? Put your S/N at the end

**Comment by MZhao-ouo** [comment]
OK. The return seems normal.
```
{"statusCode":200,"message":"success","data":{"MachineNo":"PF3KKDV1","MTM":"82RF0000CD","PackingLotNo":"PFNXB2214258","ProductDate":"2022-02-14","ScanDate":"2022-03-10","SaleArea":"CN","PurchaseDate":"2022-03-10 00:00:00","Iwsor":null,"SaleOrder":null,"Brand":"119","CheckCode":"0AATE22C4E","SN":"PF3KKDV1","ProductModel":"Legion Y9000P IAH7H","ProductSeries":"\u62ef\u6551\u8005\u7b14\u8bb0\u672c","ProductSmallClass":"Lenovo\u7cfb\u5217","ProductBigClass":"\u7b14\u8bb0\u672c","CataLogID":"-22460","ProductSeriesID":"-12815","ProductSmallClassID":"-7071","ProductBigClassID":"114","CusName":null,"ProductLineID":"2","ProductLineName":"\u7b14\u8bb0\u672c","MachineClass":null,"BrandCode":"\u6d88\u8d39","Describe":null,"SalePath":"\u6d88\u8d39","ResponsibleParty":"Lenovo","FeeMarkID":"8","FeeMarkName":"\u5929\u65ed"}}
```
Here the unicode encoding is converted from Chinese , such as :
`\u62ef\u6551\u8005\u7b14\u8bb0\u672c` converted from "拯救者笔记本" which means "Legion Laptop" ;
`Lenovo\u7cfb\u5217` converted from "Lenovo系列" which means "Lenovo Series" ;

**Comment by BartoszCichecki** [comment]
OK, thanks for help! I can see that Chinese warranties are a little bit more complex, so I can't pull exact dates, but I can fix the link to take you to your device's warranty page on Lenovo support.

Support for the device you have will be added in next release. Hope that it enough :)

**Comment by MZhao-ouo** [comment]
Of crouse that is enough!
Thanks you for bringing us such a great and hopeful tool!
