### ISSUE TITLE
[BUG]: Legion 5 Pro (16ARH7H) with JUCN51WW BIOS has no fan control.

### ISSUE THREAD

**Issue by DrippyPunk** [BartoszCichecki/LenovoLegionToolkit#225]
### Version

2.6.0

### OS

Windows 11 Education 22H2 22621.521

### Device

Legion 5 PRO 16ARH7H

### What's wrong?

Fan control is not present in the LLT app even though I have the correct model and BIOS version.

### How to reproduce the bug?

Nothing needed, just install the app and fan control is not present.

### What is the behavior that you expected?

Fan Control being present in the app

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
What is your BIOS version?

**Comment by DrippyPunk** [comment]
JUCN51WW

**Comment by BartoszCichecki** [comment]
JUCN bios wasn't tested, that's why it doesn't show up. I can send you a test build later so you can check and I'll add support.

**Comment by DrippyPunk** [comment]
Okay no worries 👍

**Comment by BartoszCichecki** [comment]
[LenovoLegionToolkitSetup_jucn.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9641189/LenovoLegionToolkitSetup_jucn.zip)

Try this build. Check if fan settings are applied correctly and you can also post a screenshot from Custom Mode settings, so we can see if everything looks ok.

**Comment by tiggidi** [comment]
I've got the same Model and same BIOS, I can confirm that with the above mentioned build the custom power mode is now available:
![image](https://user-images.githubusercontent.com/81165453/194714027-2e09b562-ee7b-4271-a691-dc2ddfadbe73.png)

**Comment by DrippyPunk** [comment]
> 

Sure let me test too
