### ISSUE TITLE
[BUG]: Minor UI bug exclude refresh rate menu dark mode

### ISSUE THREAD

**Issue by mind12** [BartoszCichecki/LenovoLegionToolkit#227]
### Version

2.6.0

### OS

Win 11 21H2

### Device

Legion S7i

### What's wrong?

If you click the exclude refresh rate menu in dark theme mode it doesnt follow the current theme's color, LLT switches to a brownish color :)
Also happens when Lenovo hotkeys are enabled and you push fn+F7 and the project screen settings popup opens.
If you open the about page it happens too.

### How to reproduce the bug?

Dark mode
Click exclude refresh rate menu

### What is the behavior that you expected?

Follow the same theme as dark.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
I will need some more description, because that does not happen for me.

![unknown](https://user-images.githubusercontent.com/7916915/192161722-40adc6db-08bf-4a87-96c3-463e88e9ea64.png)
