### ISSUE TITLE
[FEAT]: Battery - Current Session Discharge - Time Elapsed Timer

### ISSUE THREAD

**Issue by sickypedia** [BartoszCichecki/LenovoLegionToolkit#228]
### Version

2.6.0

### OS

Win 10 22H1

### Device

Legion 5 Pro 16ACH6H

### Is your feature request related to a problem?

No, see below.

### How would you like the problem to be solved?

There's no built-in way in windows to track the elapsed time on battery power, which can be useful to better understand the laptop's actual battery runtime (specific to the user's usage), in addition to the battery estimates.

Given we already have a dedicated battery page in the toolkit, it would be helpful to have a timer which shows the elapsed time in the current discharging session. 
Just 2 additional line items such as 
"Time elapsed on battery: 1hr 2mins"
"On Battery since 3:44 PM, 26 Sep 2022" would do the trick.

### What alternatives have you considered?

None, though I believe there are 3rd party apps/widgets which may incorporate this timer.

**Comment by BartoszCichecki** [comment]
I am afraid that this will not be 100% accurate, because Windows doesn't track this. So for example connecting the laptop to charge while sleeping, filling up the battery and unplugging it before waking it up again will cause weird results.

**Comment by BartoszCichecki** [comment]
I can see that you can somewhat see this data in the new Windows settings:

![image](https://user-images.githubusercontent.com/7916915/192163632-c4ffdaa8-847a-4b44-a031-9b8fcdd5e0a5.png)

However it seems there is no way for me to access this data.

**Comment by sickypedia** [comment]
Thanks @BartoszCichecki for checking this. I did not mean for the implementation to provide comprehensive stats - hence suggested that we track only the current session. I was thinking the current triggers for charger connect and disconnect which are built into the toolkit can be leveraged to implement a simple timer.

Example - I disconnect and the timer starts and ends (or starts again to track charging time) when the charger is reconnected, the toolkit does not have to track this across reboots for any accuracy.

**Comment by BartoszCichecki** [comment]
I see, but it also won't track when the laptop goes to sleep.

**Comment by sickypedia** [comment]
Got it. Can a piece of logic handle this - continue timer if resuming from sleep when charge is lower or same as before and reset if higher than before (anything which implies the laptop was charged).

**Comment by BartoszCichecki** [comment]
Yeah, I was thinking about something like this.

**Comment by BartoszCichecki** [comment]
@sickypedia so I was able to pull this information from Windows Event log. It will not be 100% since it doesn't monitor changes made during sleep or power off, but here is how it looks like:

![batt](https://user-images.githubusercontent.com/7916915/192370400-d6c49b00-2778-4a81-968b-bee3057f8aba.png)

**Comment by sickypedia** [comment]
This looks great! Thanks @BartoszCichecki for implementing this :)

**Comment by sickypedia** [comment]
Re-opening this as I've tested the feature out and see CPU cycles being used when the toolkit window is active. I presume the change to pull charge/discharge time info from event log is causing this, but can this be optimized any further? Example - pull info from event log in intervals instead of continuously.

![image](https://user-images.githubusercontent.com/73606172/192573940-74a238fc-ed01-4162-9ff3-fe2d2e27cef7.png)

**Comment by sickypedia** [comment]
@BartoszCichecki tagging for visibility.
