### ISSUE TITLE
[COMPATIBILITY]: Ideapad Gaming 3 15IMH05

### ISSUE THREAD

**Issue by human-sketch** [BartoszCichecki/LenovoLegionToolkit#229]
### Version

2.6.0

### OS

Windows 11 21H2 

### Device

Ideapad Gaming 3 15IMH05

### Which features of the application did you test?

Power Modes and Fn + Q 
Battery Modes 
Always On USB 
Touchpad Lock 
Fn Lock 
Flip To Start 
Windows Key Lock 
Discrete GPU Deactivate/Kill Apps 
Battery Stats (Temp, Discharge Rate, Current Capacity, Full Charge Capacity, Design Capacity, Cycle Count, Manufacture Date and First Used Date)
Actions and Quick Actions (chaning power modes, etc)
Downloads
Advanced Settings (CPU Boost Modes, Power plans)
About Your Device 

### Which features of the application do not work as expected?

Everything above works

### Additional information

Will there be a possibility that a feature could be added so action is triggered at a certain battery percentage?

**Comment by BartoszCichecki** [comment]
Regarding your question, the action to trigger at certain percentage could be done, but the problem is that if you put the laptop to sleep for example, it will not kick in at specific percentage. What scenario do you have in mind?

**Comment by human-sketch** [comment]
> Regarding your question, the action to trigger at certain percentage could be done, but the problem is that if you put the laptop to sleep for example, it will not kick in at specific percentage. What scenario do you have in mind?

So basically I would like my laptop to charge to 80% then turn on conservation mode. On Ideapad Gaming laptops Conservation mode will stop charging the battery but will not discharge unlike some other legion laptops.

**Comment by BartoszCichecki** [comment]
But you know that if you for example have the battery charged at 30%, you plug in the AC adapter and turn off the laptop or put it to sleep, LLT will not be able to stop it at 80%? It will charge to 100% anyway. The reason why this is still not a part of LLT is that it is basically impossible to make it reliable.

**Comment by human-sketch** [comment]
When I charge my laptop it is always powered on, so LLT is running. I understand LLT won't run when the laptop is in sleep or when I turn off the laptop. I was wondering if a feature to trigger an action at a certain battery percentage could be added.
