### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by BartoszCichecki** [BartoszCichecki/LenovoLegionToolkit#23]

**Comment by BartoszCichecki** [comment]
After investigation, I will implement this when I migrate the app to WinUI3. Currently it's using WPF and it's too much hassle.

**Comment by sickypedia** [comment]
I understand this feature here is to recognize windows dark/light theme mode automatically and adapt. However, if most users prefer the dark theme and if WinUI3 changes are not happening anytime soon, can we consider just adjusting the `background` and `foreground` flags in the app xaml code? Just sharing an example of the version I was able to tweak and come up with. However, it is best for the dev to decide the best way forward. :)

![image](https://user-images.githubusercontent.com/73606172/144428806-51c4bd36-8940-453e-b467-746ac56ac294.png)

**Comment by BartoszCichecki** [comment]
There has been a small development on this issue. I just found a nice project that brings Windows 11 feel to WPF. I will try to experiment with it, but it looks like this might be it!

https://github.com/lepoco/wpfui

**Comment by sickypedia** [comment]
This looks great, thanks! Hopefully switching to this will help with the UI glitch as well :)

**Comment by BartoszCichecki** [comment]
Check out #105 it supports dark mode 😎
