### ISSUE TITLE
[BUG]: Whenever i unplug the laptop, the backlight will be off, regardless if i set it to make it high.

### ISSUE THREAD

**Issue by Z04Notfound** [BartoszCichecki/LenovoLegionToolkit#230]
### Version

2.6

### OS

Win 11 22h2 english pro for workstation

### Device

Legion 5 17ACH6H

### BIOS version

GKCN57WW

### What's wrong?

When using the feature where u unplug the laptop and it does certain things, ive set it so that both when plugged in and unplugged the keyboard backlight will stay on highest level. Also i made it so that by unplugging it will switch to a quiet mode and plugged in it switch to performance. 

However, whenever i unplug the laptop, the backlight will be off, regardless if i set it to make it high. 

### How to reproduce the bug?

Too hard to explain, read my explanation on top.

### What is the behavior that you expected?

The keyboard backlight should stay on highest level.

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please attach logs.

**Comment by Z04Notfound** [comment]
where can i find logs, i dont see it

> Please attach logs.

**Comment by BartoszCichecki** [comment]
https://github.com/BartoszCichecki/LenovoLegionToolkit#how-to-collect-logs

**Comment by Z04Notfound** [comment]
[log_2022_09_26_20_29_36.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9649519/log_2022_09_26_20_29_36.txt)

**Comment by BartoszCichecki** [comment]
Thanks for reporting this issue was found and fixed and will be available in next release.

In the meanwhile you can use this build that has this issue fixed.
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9649624/LenovoLegionToolkitSetup.zip)
