### ISSUE TITLE
[FEAT]: Power mode - custom profiles

### ISSUE THREAD

**Issue by AceAsket** [BartoszCichecki/LenovoLegionToolkit#231]
### Version

2.6

### OS

Windows `11

### Device

Legion Y9000X IAH7

### Is your feature request related to a problem?

save various performance profiles and apply if necessary

### How would you like the problem to be solved?

make a profile save

### What alternatives have you considered?

use app - lenovo legion zone(chinese version)

**Comment by rezpower** [comment]
I really wish it would be possible to load one of the existing power profiles (ex performance) in the Legion Toolkit "Power Mode" section and then modify it to our need and save it as new custom profile. This would be a really great option.  Even better would be to be able to load a .pow file (windows power profile) and edit and modify and save it as custom profile. Please please consider adding this option if possible :)
