### ISSUE TITLE
[BUG]: power plans not changing correctly

### ISSUE THREAD

**Issue by trevlungul** [BartoszCichecki/LenovoLegionToolkit#232]
### Version

2.6

### OS

Win. 10 21H2 v19044.1288

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN51WW

### What's wrong?

The LLT actions don't seem to be selecting the proper power plans when I connect/disconnect the power supply.
For the supplied log, it starts with LLT using the performance mode - which I have set to "ultimate power" in the settings. When I disconnect the power supply, the LLT action switches to quiet mode, but the power plan it uses is "legion quiet" rather than "kira quiet" like I have selected in the settings. Opening the power plan menu in the settings does finally switch to "kira quiet"

A couple of times, when I disconnected the power supply, it switched to balanced mode rather than quiet and I had to manually run the action to get it to switch to quiet (but still using the wrong power plan)

### How to reproduce the bug?

Boot laptop on AC - correct performance mode is being used
Disconnect the power supply - power mode switches to quiet as expected, but with the wrong plan ("legion quiet instead of "kira quiet")
Open  LLT settings/advanced/power plans - power plan switches to "kira quiet" automatically (no need to change any of the settings)

### What is the behavior that you expected?

When I unplug the power supply LLT should switch to quiet mode using "kira quiet" plan

### Logs

[log_2022_09_26_17_33_43.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9648536/log_2022_09_26_17_33_43.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

I did just update my bios from 50ww to 51ww in the past 24hrs. IIRC things were working properly before that

**Comment by BartoszCichecki** [comment]
Please disable Vantage first. If that doesn't help, reopen the issue.

**Comment by trevlungul** [comment]
BTW, using the left ctrl + left shift method to launch LLT in log mode didn't work for me (wouldn't run the program period)
Lemme know if I should submit a separate bug report

**Comment by BartoszCichecki** [comment]
[LenovoLegionToolkitSetup_test.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9648912/LenovoLegionToolkitSetup_test.zip)

Could you please install this build and collect a log once again?

**Comment by BartoszCichecki** [comment]
And you really don't have Vantage installed?

**Comment by trevlungul** [comment]
Nope, I've never installed Vantage since I bought this machine.
The only other thing installed that has anything to do with switching power plans would be Legion Fan Control, but I haven't had any conflict with it before (just to double-check, I've uninstalled LFC and I'll see what happens now)

That said this machine has always been a PITA when it comes to power management. Just getting any plan other than "balanced" to even appear involves jumping through a shitload of hoops unless I want to disable "modern standby" altogether - which causes enough problems on its own. I also think Lenovo has basically been hobbling the machine unless it's running Win. 11
It also wouldn't surprise me if something internally in Windows got f-ed up. It always seems to happen after a couple of months…

**Comment by mind12** [comment]
LegionFanControl can easily interfere with power plans. Happened to me also. Exit and test again.

**Comment by BartoszCichecki** [comment]
Yup, other than checking LFC, I can't do anything here. It's basically not LLT causing problems.

**Comment by trevlungul** [comment]
Turfing LFC did seem to sort this out for me. I'm not sure why it starting acting up all of a sudden, but it is what it is…

You mind me asking what Nvidia driver you use? I'm having issues finding one that doesn't have a high power drain in hybrid mode. Tried the 511 ones reccyd on Discord, latest Nvidia. They all have a 25W+ drain unless I "eject" the video card. The Lenovo provided 512 drivers don't have the power consumption, but also don't seem to work with Gsync either
