### ISSUE TITLE
[BUG]: No fan control on Gen 7 5i Pro with BIOS J2CN43WW

### ISSUE THREAD

**Issue by TrentonBush** [BartoszCichecki/LenovoLegionToolkit#233]
### Version

2.6

### OS

Windows 11 10.0.22000 Build 22000

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN43WW

### What's wrong?

First, thanks so much for building and maintaining this! It's a great product.

My issue: If I interpret the README correctly, I think my laptop should support fan control, but I don't see it anywhere. I have a Gen 7 Legion with BIOS > J2CN40WW, 

I tried uninstalling/reinstalling Legion Toolkit with no noticeable difference.

### How to reproduce the bug?

I simply installed LLT, disabled Vantage and Hotkeys via LLT, and rebooted.

### What is the behavior that you expected?

I was hoping for fan controls!

### Logs

[log_2022_09_27_08_17_51.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9653514/log_2022_09_27_08_17_51.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

I don't think this is relevant, but just in case: I have Windows Subsystem for Linux enabled, which enables Virtualization Based Security (VBS). VBS can interfere with some WMI commands if they try to touch certain CPU hardware registers.

**Comment by mind12** [comment]
Change power mode to custom and push the cog wheel next to it. Fan control should be there.
