### ISSUE TITLE
[BUG]: System tray icon disappears when explorer.exe is restarted

### ISSUE THREAD

**Issue by dcsilva0** [BartoszCichecki/LenovoLegionToolkit#234]
### Version

2.6.0

### OS

Windows 11 21H2 22000.978

### Device

Legion 5 15ACH6H

### BIOS version

GKCN54WW

### What's wrong?

The icon the toolkit displays on the system tray disappears when explorer.exe is restarted/crashes, and does not come back until the app is closed on task manager (as there isn't an exit button on the app, other than the one in the system tray) and opened again.

The issue is probably Windows' fault, but a restart/close app button available somewhere else than on the toolkit's system tray icon would be a useful workaround as it would make it unnecessary to use the task manager and force stop the app.

### How to reproduce the bug?

open task manager
restart explorer.exe

### What is the behavior that you expected?

the icon reappears on the system tray after the taskbar loads again.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Very good point. It is Windows' fault, but the solution from MS is that "you should just register tray icons again". So, that is now done.
