### ISSUE TITLE
[BUG]: GPU Working mode can't change between Hybrid Mode and Hybrid-iGPU only Mode

### ISSUE THREAD

**Issue by RoadToDream** [BartoszCichecki/LenovoLegionToolkit#236]
### Version

2.6.0

### OS

Windows 11 22H2

### Device

Legion 7i 16IAX7

### BIOS version

K1CN31WW

### What's wrong?

When system has only iGPU enabled, choosing Hybrid Mode will not reenable dGPU. 
When system has both iGPU and dGPU enabled, choosing Hybrid-iGPU only Mode will not disable dGPU. 

### How to reproduce the bug?

1. Open LLT
2. Select between Hybrid-iGPU only Mode and Hybrid Mode. 
3. iGPU or dGPU wouldn't enable or disable as expected. 

### What is the behavior that you expected?

iGPU or dGPU would enable or disable according to GPU mode.

### Logs

[log_2022_09_28_18_16_09.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9667893/log_2022_09_28_18_16_09.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

This issue only happens when Vantage is disabled. If Vantage service is enabled, GPU states can change accordingly. May I ask if this is expected behavior?

**Comment by BartoszCichecki** [comment]
To clarify: You have set the mode to iGPU-only and the GPU is ejected from the system. Then you change back to Hybrid and dGPU doesn't get reconnected?

**Comment by RoadToDream** [comment]
> To clarify: You have set the mode to iGPU-only and the GPU is ejected from the system. Then you change back to Hybrid and dGPU doesn't get reconnected?

Hi! Thanks for the reply. 
Both operations will not work correctly when Vantage service is disabled. While change from iGPU-only to Hybrid may work occasionally. 
If Vantage service is enabled, switch between GPU mode will still probably not work. 
Control via Vantage directly can change GPU states correctly. 
I have debugged program on my laptop using Visual Studio version 2022, and no exception is thrown. 

I am willing to provide more info if required.

**Comment by BartoszCichecki** [comment]
I can see that something might be missing compared to what Vantage is doing. I made a quick patch that may or may not work - we need to do some trouble shooting.

You can try the build below, maybe it's gonna work?

[LenovoLegionToolkitSetup_potentialfix.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9679000/LenovoLegionToolkitSetup_potentialfix.zip)

**Comment by BartoszCichecki** [comment]
You can also see the changes in the branch linked to this issue.

**Comment by RoadToDream** [comment]
Thanks for the quick fix. I have just installed this beta build and it seems it doesn't fix the issue. 
Let me know if there is anything I may help :)

**Comment by BartoszCichecki** [comment]
What about this one?

[LenovoLegionToolkitSetup_fix2.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9679085/LenovoLegionToolkitSetup_fix2.zip)

**Comment by RoadToDream** [comment]
No. 
In addition, there will be a warning message shown up when first start or on exit. 
![image](https://user-images.githubusercontent.com/8088354/193158387-0e43ac38-e361-4aba-b957-815812e7331b.png)

**Comment by RoadToDream** [comment]
I think my previous guess is correct. Added **NotifyDGPUStatus ** will guarantee GPU switch. 
```powershell
function Toggle-iGPUState {
    $LenovoWMIPath=(Get-WmiObject -Namespace "root\WMI" -Query "SELECT * FROM LENOVO_GAMEZONE_DATA").__PATH
    $LenovoWMI=[WMI]$LenovoWMIPath
    $CurrentState=$LenovoWMI.GetIGPUModeStatus().Data
    $TargetState=[int]($CurrentState -xor 1)
    $LenovoWMI.SetIGPUModeStatus($TargetState)
    while ($LenovoWMI.GetIGPUModeStatus().Data -ne $TargetState) 
    {
        Start-Sleep -Milliseconds 200
    }
    $LenovoWMI.NotifyDGPUStatus($TargetState)
}
```

**Comment by RoadToDream** [comment]
Hi,
I have done a quick fix for this issue, but didn't check for cross-bios compatibility. Just consider this pull request as a success sample for model 16IAX7. 
Great thanks for bringing this useful tool!

**Comment by BartoszCichecki** [comment]
Great find. Here is a build that replicates how Lenovo notifies DGPU (check PR for details). Let's see if that is working fine:

[LenovoLegionToolkitSetup_fix3.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9690692/LenovoLegionToolkitSetup_fix3.zip)

**Comment by BartoszCichecki** [comment]
I am getting reports that Hybrid to iGPU-only works fine here, but iGPU-only to Hybrid doesn't.

**Comment by BartoszCichecki** [comment]
OK so this build was tested and other guys claim that it works: 
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691083/LenovoLegionToolkitSetup.zip)

Could you please verify?

**Comment by RoadToDream** [comment]
Hi, I have tested it and it works. Seems to be a little slow than my build but that may be due to ACPI. I think it's all good.

**Comment by BartoszCichecki** [comment]
I was trying with listening for WM_DEVICECHANGE message, because that's what Vantage seems to be doing (instead I force device refresh manually) but the msg didn't arrive for some reason, idk why.

**Comment by RoadToDream** [comment]
> I was trying with listening for WM_DEVICECHANGE message, because that's what Vantage seems to be doing (instead I force device refresh manually) but the msg didn't arrive for some reason, idk why.

I guess there might still be some dirty IPC communicate between Vantage and services, but I am happy with the current one works.

**Comment by BartoszCichecki** [comment]
Just out of curiosity, could you try this one too: 
[LenovoLegionToolkitSetup_prolly_broken.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691192/LenovoLegionToolkitSetup_prolly_broken.zip)

I would appreciate if you send a log too.

**Comment by RoadToDream** [comment]
Sure I can do it. 
May I ask what change is introduced to this build?

**Comment by BartoszCichecki** [comment]
Sure, here is the patch file: 
[patch.diff.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691204/patch.diff.txt)

**Comment by BartoszCichecki** [comment]
And also added this:

```
    internal class SystemEventInterceptor : NativeWindow
    {
        private static int WM_DEVICECHANGE = 0x0219;

        public SystemEventInterceptor(IntPtr handle)
        {
            AssignHandle(handle);
        }

        protected override void WndProc(ref Message m)
        {
            if (m.Msg == WM_DEVICECHANGE)
            {
                if (Log.Instance.IsTraceEnabled)
                    Log.Instance.Trace($"WM_DEVICECHANGE");

                NotifyDGPU();
            }

            base.WndProc(ref m);
        }

        private async void NotifyDGPU()
        {
            var feat = IoCContainer.Resolve<IGPUModeFeature>();

            var state = await feat.GetStateAsync();
            await feat.NotifyDGPUStatusAsync(state);
        }
    }
```

Stil trying to figure out the message thing

**Comment by BartoszCichecki** [comment]
Or actually, nevermind that won't work :/

**Comment by RoadToDream** [comment]
That seems working. But will have an error shown below. 
![image](https://user-images.githubusercontent.com/8088354/193428861-f96868c0-f7dd-42df-bfae-a08d5ce8ee67.png)
Here are log and error. 
[error_2022_10_01_21_30_37.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691239/error_2022_10_01_21_30_37.txt)
[log_2022_10_01_21_30_25.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691240/log_2022_10_01_21_30_25.txt)

**Comment by BartoszCichecki** [comment]
[LenovoLegionToolkitSetup_test70.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691245/LenovoLegionToolkitSetup_test70.zip)

And this one?

**Comment by RoadToDream** [comment]
This one is good. It's as fast as my original build.

**Comment by BartoszCichecki** [comment]
And the eject appears/disappears correctly?

**Comment by RoadToDream** [comment]
Yes.

**Comment by BartoszCichecki** [comment]
Could you grab a log, just to verify?

**Comment by RoadToDream** [comment]
[log_2022_10_01_21_40_33.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691250/log_2022_10_01_21_40_33.txt)
Sure. Logs looks all good.

**Comment by RoadToDream** [comment]
Let me check power consumption to verify.

**Comment by RoadToDream** [comment]
All good.

**Comment by BartoszCichecki** [comment]
That is sooo confusing, because now only `pnputil` works.... The notifydgpustate doesn't work for some reason:

```
internal class SystemEventInterceptor : NativeWindow
    {
        private static int WM_DEVICECHANGE = 0x0219;

        private static int DBT_DEVTYP_HANDLE = 5;
        private static Guid GUID_DISPLAY_DEVICE_ARRIVAL = new("1CA05180-A699-450A-9A0C-DE4FBE3DDD89");

        public SystemEventInterceptor(IntPtr handle)
        {
            AssignHandle(handle);
        }

        protected override void WndProc(ref Message m)
        {
            if (m.Msg == WM_DEVICECHANGE)
            {
                if (Log.Instance.IsTraceEnabled)
                    Log.Instance.Trace($"WM_DEVICECHANGE");

                if (m.LParam != IntPtr.Zero)
                {
                    if (Log.Instance.IsTraceEnabled)
                        Log.Instance.Trace($"m.LParam != IntPtr.Zero");

                    var devBroadcastHdr = Marshal.PtrToStructure<DevBroadcastHdr>(m.LParam);
                    if (devBroadcastHdr.DeviceType == DBT_DEVTYP_HANDLE)
                    {
                        if (Log.Instance.IsTraceEnabled)
                            Log.Instance.Trace($"devBroadcastHdr.DeviceType == DBT_DEVTYP_HANDLE");

                        var devBroadcastDeviceInterface = Marshal.PtrToStructure<DevBroadcastDeviceInterface>(m.LParam);
                        if (devBroadcastDeviceInterface.ClassGuid == GUID_DISPLAY_DEVICE_ARRIVAL)
                        {
                            if (Log.Instance.IsTraceEnabled)
                                Log.Instance.Trace($"devBroadcastDeviceInterface.ClassGuid == GUID_DISPLAY_DEVICE_ARRIVAL");

                            if (Log.Instance.IsTraceEnabled)
                                Log.Instance.Trace($"NotifyDGPU");

                            NotifyDGPU();
                        }
                    }
                }
            }

            base.WndProc(ref m);
        }

        private async void NotifyDGPU()
        {
            var feat = IoCContainer.Resolve<IGPUModeFeature>();

            if (!await feat.IsSupportedAsync())
                return;

            if (Log.Instance.IsTraceEnabled)
                Log.Instance.Trace($"Notifying...");

            var state = await feat.GetStateAsync();
            await feat.NotifyDGPUStatusAsync(state);
        }
    }
```

**Comment by BartoszCichecki** [comment]
I pushed this code to `bug/more-investigation-hybrid` you can take a look if you want.

**Comment by RoadToDream** [comment]
I have no idea here... 
I will look into the code in branch you mentioned later. 

One maybe unhelpful comment here: 
For LLT without any modifications we mentioned here, if LLT doesn't change the state successfully, then I go to Vantage to change the state. Windows will go blue screen with error code VIDEO_DXGKRNL_FATAL_ERROR.

**Comment by BartoszCichecki** [comment]
OK, one more :D This one should handle correct messages.

[LenovoLegionToolkitSetup_test71.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691290/LenovoLegionToolkitSetup_test71.zip)

**Comment by RoadToDream** [comment]
No luck for this one. It's not working. 
(I guess pnputil may work sometimes but it is not guaranteed here)
[log_2022_10_01_22_30_09.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9691299/log_2022_10_01_22_30_09.txt)

**Comment by RoadToDream** [comment]
Just curious, does any other user experienced the same issue? It seems I am the only one that can't switch graphics card successfully, if so I guess it's due to my environment and this issue is a false alert. I can continue use my patched LLT and that's totally fine.

**Comment by BartoszCichecki** [comment]
No you are not, the fix you made is tested on couple of other machines and it works better. The problem is we can't figure out the proper order of operations with `SetIGPUModeState` and `NotifyDGPUState`. There are still some problems with waking/sleeping DGPU when connecting/disconnecting screens in iGPU-only mode.

At this point I think the only thing left that we can do is either completely reverse engineer `GraphicsCardSettings.dll` from Vantage/LegionZone or set up API monitor and monitor calls that Legion Zone is making (it's easier to trace Legion Zone than to trace Vantage) to figure out what to send where. There is still the missing piece of calling `NotifyDGPUState` when `WM_DEVICECHANGE` message is delivered.

If you would like to join the dicussion, join the Legion Series discord and ping me @bc. I can loop you in all the discussions/tracing we do there.

**Comment by BartoszCichecki** [comment]
The implementation still seems to bug out after some time, so there is def something wrong or the implementation of this is just "broken-ish". This is why I think that we need to trace the WMI calls to get an idea what is sent when.

**Comment by KarlLee830** [comment]
> Just curious, does any other user experienced the same issue? It seems I am the only one that can't switch graphics card successfully, if so I guess it's due to my environment and this issue is a false alert. I can continue use my patched LLT and that's totally fine.

I had the same problem as you, but I saw that there was already the same issue, so I didn't create a new one.

**Comment by RoadToDream** [comment]
Then it still worth digging deeper. Let me first do a WMI logging and then take a look into Legion Zone. Vantage doesn't seems very easy as most of its functions are done in a DLL and looks like all functions are wrapped in a single factory call.

**Comment by DrippyPunk** [comment]
> To clarify: You have set the mode to iGPU-only and the GPU is ejected from the system. Then you change back to Hybrid and dGPU doesn't get reconnected?

I'm having the same issue, 16ARH7H JUCN Bios

**Comment by BartoszCichecki** [comment]
Done. Tested on 16IAX7, K1CN31WW bios.

**Comment by RoadToDream** [comment]
> Done. Tested on 16IAX7, K1CN31WW bios.

Can confirm the issue is fixed. Thank you for the all the work!

**Comment by DrippyPunk** [comment]
> > Done. Tested on 16IAX7, K1CN31WW bios.
> 
> Can confirm the issue is fixed. Thank you for the all the work!

How can I test if it's fixed?

**Comment by Mr-JediFox** [comment]
However when turn Hybrid -> Hybrid iGPU, the dGPU still enable(sleep) not disable completely
