### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by marwan4mr** [BartoszCichecki/LenovoLegionToolkit#239]
### Version

2.5.1

### OS

10.0.19044 Build 19044

### Device

Legion 5 15ACH6H

### BIOS version

GKCN57WW

### What's wrong?

when changing to custom mode it change to performance mode and you have to change to custom mode again to get custom mode (you have to click custom mode twice) , this also happen with actions , BUT this only happen when vantage services are running and the issue is fixed by disabling vantage services

### How to reproduce the bug?

1-enable vantage service 
2- change to custom mode either from quite or balanced mode

### What is the behavior that you expected?

maybe force disable vantage service to use custom mode or automatically do it 

### Logs

[log_2022_09_29_21_14_05.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9679147/log_2022_09_29_21_14_05.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

its not critical problem but i wanted to mention it

**Comment by BartoszCichecki** [comment]
Yes, Vantage might interfere with Custom mode. Disable it and it'll be fine.

**Comment by BartoszCichecki** [comment]
PS: Good that you mentioned it.
