### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by DubXingg** [BartoszCichecki/LenovoLegionToolkit#240]
### Version

2.6.1

### OS

Win 10

### Device

Legion 7i 16ITHG6

### BIOS version

unknown

### What's wrong?

"Unexpected expectation occurred. object reference not set to an instance of object " when closed

### How to reproduce the bug?

Close app

### What is the behavior that you expected?

Minimize

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by Sko-Induktor** [comment]
Same error after updating to 2.6.1. The error occurs on both of my devices (L7-16ACHg6 & L5P-16IAH7H).

**Comment by BartoszCichecki** [comment]
Thanks for reporting this, just pushed a hotfix 2.6.2.
