### ISSUE TITLE
Camera On/Off notification[BUG]: 

### ISSUE THREAD

**Issue by kaniamutan14** [BartoszCichecki/LenovoLegionToolkit#241]
### Version

2.6.2

### OS

windows 11 21h2

### Device

Lenovo Legion 5 15IMH05

### BIOS version

EFCN45WW

### What's wrong?

Camera on/off notification is added in the new build but it seems not working no notification is shown when i open camera app or any app that uses camera

### How to reproduce the bug?

legion toolkit is running and lenovo hotkeys is disabled via the legion toolkit, opens camera app or opens discord and joins a voice channel to trigger camera, based on the update notes a notification should appear informing the camera in use but it didn't appear.

### What is the behavior that you expected?

A notification appears informing that camera is in use

### Logs

[log_2022_09_30_17_42_37.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9686658/log_2022_09_30_17_42_37.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Camera notification is only for devices with hardware camera switch.
