### ISSUE TITLE
[FEAT]: Request support for more notification types.

### ISSUE THREAD

**Issue by KarlLee830** [BartoszCichecki/LenovoLegionToolkit#244]
### Version

2.6.2

### OS

Windows 22H2 22622.601

### Device

Legion S7 16IAH7

### Is your feature request related to a problem?

When Lenovo Hotkeys is disabled, after using LLT to take over Fn Keys, LLT will only pop up notifications for microphone and camera on and off.

### How would you like the problem to be solved?

Add more types of notifications. For example, Caps & Num Lock, Touchpad lock, keyboard backlight, Fn Lock, etc.

### What alternatives have you considered?

Use Lenovo Hotkeys. but the Lenovo Hotkeys pop-ups look too ugly.

### Additional information

I hope LLT can take over the original Lenovo Hotkeys popup with the microphone and camera notification style, LLT's notification style looks much better.

**Comment by KarlLee830** [comment]
And can notifications for inserted charger types be added?

**Comment by RancidTuna** [comment]
If you add this, please make it so they can be turned off. This is the best part about LLT, not having the hotkey pop-ups.

**Comment by BartoszCichecki** [comment]
FYI: notifications for Spectrum keyboard will be added with spectrum support.
