### ISSUE TITLE
[BUG]: When the graphics card is ejected and re-enabled, LLT does not show the Discrete GPU option.

### ISSUE THREAD

**Issue by KarlLee830** [BartoszCichecki/LenovoLegionToolkit#245]
### Version

2.6.2

### OS

Windows 22H2 

### Device

Legion S7 16IAH7

### BIOS version

JYCN39WW

### What's wrong?

When the graphics card is ejected and re-enabled, LLT does not show the Discrete GPU option.

### How to reproduce the bug?

1. Eject the discrete graphics card.
2. Change the GPU Working Mode option in LLT.
3. The GPU is re-enabled after the change.
4. The Discrete GPU option will not be displayed in LLT.

### What is the behavior that you expected?

When the discrete graphics card is popped up and re-enabled, LLT does not need to be re-opened to Discrete GPU.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Related to #236
