### ISSUE TITLE
[BUG]: App close action doesn't work for valorant

### ISSUE THREAD

**Issue by Ahsan40** [BartoszCichecki/LenovoLegionToolkit#247]
### Version

2.6.2

### OS

Windows 10 21H1

### Device

Legion 5 15ACH6H

### BIOS version

GKCN54WW

### What's wrong?

![image](https://user-images.githubusercontent.com/30434801/193878136-d0dc3e8f-e8ba-48ac-8d03-2cc11cc07744.png)
These are the  actions I've set for my games. Open/Running action works for both game but the close action doesn't works for Valorant. It stopped working from 2.4 maybe. I was hopping it will be fixed. I've reinstalled the app as well but didn't work.

### How to reproduce the bug?

1. Create action for open and close for valorant
2. open valorant
3. close valorant

### What is the behavior that you expected?

When I close valorant, the close action should've been triggered but it doesn't.

### Logs

[log_2022_10_04_16_39_30.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9709012/log_2022_10_04_16_39_30.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
What other actions do you have configured?

**Comment by Ahsan40** [comment]
![image](https://user-images.githubusercontent.com/30434801/193882098-81a28f62-b24c-4d88-b28d-bb65d8575c46.png)
These are the other action I've been setup so far. Even if  I  don't set these 2, the issue still remains.

**Comment by BartoszCichecki** [comment]
Could you also upload the `automation.json` file from `%localappdata%\LenovoLegionToolkit`?

**Comment by Ahsan40** [comment]
[automation.json.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9709161/automation.json.txt)

**Comment by BartoszCichecki** [comment]
Please try this and let me know.
[LenovoLegionToolkitSetup_actions.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9709429/LenovoLegionToolkitSetup_actions.zip)

**Comment by BartoszCichecki** [comment]
Can you try with different exe like `notepad.exe` for example?

**Comment by Ahsan40** [comment]
Just now tried with notepad didn't work.

**Comment by Ahsan40** [comment]
However, it  works with Genshin.

**Comment by Ahsan40** [comment]
[log_2022_10_04_18_09_17.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9709548/log_2022_10_04_18_09_17.txt)

Here's the log.
- Tried notepad (not worked)
- Tried Genshin (Worked)
- Tried Valorant (not worked)

**Comment by BartoszCichecki** [comment]
I have added more logging because I can't reproduce the issue. Could yo

[LenovoLegionToolkitSetup_actions2.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9709726/LenovoLegionToolkitSetup_actions2.zip)
u get logs one more time from the build below?

**Comment by Ahsan40** [comment]
I use better discord that why it's a bit heavy here. But turned off Discord and removed from auto start. Then restart the PC and test again. Same result.
Here's the log again.
[log_2022_10_04_18_52_57.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9709794/log_2022_10_04_18_52_57.txt)

**Comment by BartoszCichecki** [comment]
OK, this makes little sense. I am getting Valorant now to test :D

**Comment by Ahsan40** [comment]
hahaha.. That would take quite some time. In the mean time try fixing for notepad. Action didn.t work for notepad as well.

**Comment by BartoszCichecki** [comment]
OK, now it's clear. Valorant uses some crazy DRMs and this is why LLT can't monitor it's process. This explains why Genshin works and I can't reproduce this with other processes like notepad etc.

I guess this will just not work for applications like this.

**Comment by Ahsan40** [comment]
I see. I think that might just be the case. Because it stop working after an game update. However the open app action still works with the stable (2.6.2) version.

**Comment by BartoszCichecki** [comment]
Anyway, I added more logs to faster track issues like this one in the future. Thanks for helping!

**Comment by Ahsan40** [comment]
### **_I am leaving this comment for the person who come here for the same issue in the  future._** 

I've found the solution.  The solution is, just add **RiotClientServices.exe** instead of **Valorant.exe**. See the screenshot below.

![image](https://user-images.githubusercontent.com/30434801/196089478-e19b847f-bbb4-44ab-b5ce-461830cecef3.png)
