### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Z4ndyz** [BartoszCichecki/LenovoLegionToolkit#251]
### Version

20220926212100, beta version, 2.6.1 i think , a version that you gave me when fixing Actions with while 

### OS

Windows 10 21H2 10.0.19044 Build 19044

### Device

Legion 5Pro Amd Gen6

### BIOS version

GKCN57WW

### What's wrong?

While changing the hybrid/dgpu mode directly by going in bios instead of switching using the button in Legion Tookit the button won't update on the next restart. It is just a visual 
![image](https://user-images.githubusercontent.com/43518302/194673286-4cc1542d-f802-4d63-9624-47dca8113b19.png)
bug, the functionality of the mode and the mode switching doesn't get affected.
![image](https://user-images.githubusercontent.com/43518302/194673363-eb066690-10c1-480e-b8d6-855b252a0eb3.png)

As seen above it can be seen that LLT shows that i'm in hybrid mode but i'm in dGPU mode(switched to dGPU last time by going in bios). (g-sync is not available in hybrid mode)

### How to reproduce the bug?

Check hybrid toggle status in LLT, be it either off or on, instead of using the button to switch mode from hybrid to gpu and vice-versa if you switch it from in-bios the button won't change accordingly, just a visual bug

### What is the behavior that you expected?

The button/slider to properly showcase the current mode. All other functionalities seem to be fine

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
The on/off state is read directly from WMI, so apparently the switch was flipped. The problem is that you can toggle it on/off but it will only take effect after reboot, there is no way to check what is the "current" state.
