### ISSUE TITLE
[FEAT]: hope support of special features.

### ISSUE THREAD

**Issue by pxxcjp** [BartoszCichecki/LenovoLegionToolkit#254]
### Version

2.6.2

### OS

windows 10

### Device

xiaoxing provides 2021

### Is your feature request related to a problem?

Change boot logo
Automatically adjust the brightness through the camera
Leave the computer automatic lock screen.
Automatically wake up in front of the computer
Automatically pause media/resume when you leave the computer.

### How would you like the problem to be solved?

I can use the above functions through this tool.

### What alternatives have you considered?

More third-party tools, but I don't want my computer to have so many self-starting projects.

**Comment by BartoszCichecki** [comment]
There are no plans to add these features.
