### ISSUE TITLE
[COMPATIBILITY]: Apply for YOGA 14s ACH 2021 82NJ

### ISSUE THREAD

**Issue by CharlesHim** [BartoszCichecki/LenovoLegionToolkit#258]
### Version

2.6.2

### OS

Windows 11 22h2 22623.730

### Device

YOGA 14s ACH 2021 82NJ

## Dashboard
- Battery Mode
- Refesh Rate
- Always on USB
- Discrete GPU
- Fn Lock
- Flip 2 Start

## Battery
- ALL

## Actions
- auto action
- Quick action

## Download
- NONE

## Settings
- ALL

### Which features of the application do not work as expected?

- "Power plan" isnt shown in the list "Add step".
- LLT crashes upon clicking "power plans" in Settings.
- Can't disable legion zone.
- When trying to run any of these two default auto actions (which includes power plan changes), LLT does nothing with the tip "completed with errors".

### Logs

[error_2022_10_10_11_32_47.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745773/error_2022_10_10_11_32_47.txt)
[error_2022_10_10_11_42_31.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745774/error_2022_10_10_11_42_31.txt)
[error_2022_10_10_11_45_06.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745775/error_2022_10_10_11_45_06.txt)
[log_2022_10_10_11_31_17.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745776/log_2022_10_10_11_31_17.txt)
[log_2022_10_10_11_33_09.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745777/log_2022_10_10_11_33_09.txt)
[log_2022_10_10_11_42_53.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745778/log_2022_10_10_11_42_53.txt)
[log_2022_10_10_11_44_28.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745779/log_2022_10_10_11_44_28.txt)
[log_2022_10_10_11_50_09.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745780/log_2022_10_10_11_50_09.txt)
[log_2022_10_10_11_50_49.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9745781/log_2022_10_10_11_50_49.txt)

### Additional information

The following is what i tried to make LLT work as expected (but failed):  
- run as admin
- uninstall lenovo hotkeys
- Kill Lenovo PC Manager (Chinese version of Lenovo Vantage or Legion Zone) in Windows task Manager

**Comment by BartoszCichecki** [comment]
As stated in readme:

"If your laptop is not part of Legion or Ideapad Gaming lines, this software is not for you."
