### ISSUE TITLE
[BUG]: PL1 and PL2

### ISSUE THREAD

**Issue by Godl1nk** [BartoszCichecki/LenovoLegionToolkit#259]
### Version

2.6.2

### OS

Windows 11 Pro 22H2

### Device

Legion 5

### BIOS version

GKCN57WW

### What's wrong?

PL1 and PL2 in custom mode is not working properly, I mentioned this previously that its rly limiting the wattage but the author told me that the correct command is sent but was ignored, I thought so until I used Universal Tuning Utility/AATU https://github.com/JamesCJ60/Universal-x86-Tuning-Utility. Their PL1 and PL2 works for me.

If theirs work than why not just use theirs ? There will be conflict if I turn both software together, since they did it, there is definitely a solution or something is not done right.

### How to reproduce the bug?

Just set power limit higher than tdp, hard to say how to reproduce but it just dont work

### What is the behavior that you expected?

Power should be limited as set

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
If it doesn't work correctly, it's a problem on Lenovo's side. Values are written to WMI correctly.
