### ISSUE TITLE
[FEAT]: Customize Fn Hotkeys

### ISSUE THREAD

**Issue by CharlesHim** [BartoszCichecki/LenovoLegionToolkit#260]
### Version

2.6.2

### OS

Windows 11 22h2 22623.730

### Device

YOGA 14s ACH 2021 82NJ

### Is your feature request related to a problem?

No. Some of those default fn hotkeys are not frequently used. It would be nice if LLT could customize the function of them.

### How would you like the problem to be solved?

Add a feature that allow users to disable the unused hotkeys (or change the functions of them).

### What alternatives have you considered?

I have not found such an app that allow me to change or disable fn hotkeys. So I just left them unused.

**Comment by BartoszCichecki** [comment]
Please do not report issues related to non legion devices.
