### ISSUE TITLE
[COMPATIBILITY]: Apply for China Edition of ZHAOYANG E40-70 - Type 80EQ

### ISSUE THREAD

**Issue by TUSITU123** [BartoszCichecki/LenovoLegionToolkit#262]
### Version

2.6.2

### OS

Windows11 22H2 build 22621.521

### Device

China Edition of ZHAOYANG E40-70

### Which features of the application did you test?

Battery Mode
Fn Lock
About your device
Battery

### Which features of the application do not work as expected?

Geaphics
Fn keys display
Power Plans
Warranty
Desable Legion Zone
Serial Number

### Logs

[error_2022_10_10_14_17_14.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9746685/error_2022_10_10_14_17_14.txt)
[log_2022_10_10_13_52_59.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9746686/log_2022_10_10_13_52_59.txt)
[log_2022_10_10_14_17_42.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9746689/log_2022_10_10_14_17_42.txt)

### Additional information

I think the functionality that only works on the Legion model can be hidden on other models.
My laptop is obviously the Chinese version, and I can check the warranty period on the official website of China, but I can't find it in the program, and the Serial Number found in the program is also wrong.
I'd also like to add a language switch, but a Russian is working on it..

The above are all machine-translated, please forgive me if there are any grammatical errors!

**Comment by BartoszCichecki** [comment]
As stated in the README and when creating issue:

"If your laptop is not part of Legion or Ideapad Gaming lines, this software is not for you. Please do NOT open compatibility requests for other devices. Issues will be closed and not looked at!"
