### ISSUE TITLE
[COMPATIBILITY]: 

### ISSUE THREAD

**Issue by freetbash** [BartoszCichecki/LenovoLegionToolkit#263]
### Version

2.6

### OS

Win11 21H2

### Device

Legion Y9000X IAH7

### Which features of the application did you test?

My laptop can't change the display mode and the trackpad display is not there but the camera and microphone can show the prompt. My machine is Legion Y9000X IAH7

### Which features of the application do not work as expected?

My laptop can't change the display mode and the trackpad display is not there but the camera and microphone can show the prompt. My machine is Legion Y9000X IAH7

### Logs

no log

### Additional information

My laptop can't change the display mode and the trackpad display is not there but the camera and microphone can show the prompt. My machine is Legion Y9000X IAH7

**Comment by BartoszCichecki** [comment]
Already added in 2.6.2
