### ISSUE TITLE
[BUG]: Performance Mode not available, the power indicator light is red however the power plan is still "Balance"

### ISSUE THREAD

**Issue by sepcnt** [BartoszCichecki/LenovoLegionToolkit#266]
### Version

BETA https://github.com/BartoszCichecki/LenovoLegionToolkit/commit/47707a3bcde2731e21cbdc0f772cb45da6124782

### OS

Windows 11 22623.730

### Device

Legion Y9000X IAH7

### BIOS version

JYCN41WW

### What's wrong?

Performance Mode not available, the power indicator light is red however the power plan is still "Balance"

### How to reproduce the bug?

Just press Fn+Q, it cannot switch power mode correctly.

### What is the behavior that you expected?

Switch to "High Performance Mode"

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Unfortunately, it seemed that Lenovo made some hack to this model.
Ultimate Mode / High Performance Mode / Low Power Mode are not visible to user and could only be enabled by Vantage # memory leaker :(
However, I can manually switch to those mode above via "powercfg /S {GUID}" ( Get the GUID via import or duplicate at first 
So maybe it will be helpful if the Toolkit could enable some specific mode even if it is invisible, allowing user to enter a certain GUID

**Comment by BartoszCichecki** [comment]
If the power plans are not switching and you don't have Vantage installed, try this: go to LLT settings, at the bottom you have an option "Windows Power Plans", open it and assign the power profiles you want to each power mode. After that try switching power modes.

If this doesn't work, please upload a log, so I can take a look.

**Comment by qwertyue** [comment]
I have the same problem, and if I try to set up Windows Power Plans, I will get an error:

System.NotSupportedException: Feature SmartFanMode is not supported.

**Comment by BartoszCichecki** [comment]
> I have the same problem, and if I try to set up Windows Power Plans, I will get an error:
> 
> System.NotSupportedException: Feature SmartFanMode is not supported.

What device?

**Comment by qwertyue** [comment]
> > I have the same problem, and if I try to set up Windows Power Plans, I will get an error:
> > System.NotSupportedException: Feature SmartFanMode is not supported.
> 
> What device?

Same as [sepcnt]

**Comment by DrippyPunk** [comment]
> If the power plans are not switching and you don't have Vantage installed, try this: go to LLT settings, at the bottom you have an option "Windows Power Plans", open it and assign the power profiles you want to each power mode. After that try switching power modes.
> 
> If this doesn't work, please upload a log, so I can take a look.

I have the same issue but my problem is that the legion performance mode straight up refuses to install.

**Comment by BartoszCichecki** [comment]
> legion performance mode straight up refuses to install

What does this mean?

**Comment by DrippyPunk** [comment]
> > legion performance mode straight up refuses to install
> 
> What does this mean?

When I install the power plans performance mode is missing, tried almost anything. Apparently it only works for gen 7 if you disable sleep entirely, which i'm not willing to do tbh

**Comment by DrippyPunk** [comment]
He is obviously having similar issues, although I haven't tested if vantage does let me use performance mode.

**Comment by BartoszCichecki** [comment]
After investigating. It seems like you are using a chinese variant of Legion Slim 7. These laptops have something called Modern Standby enabled (S0 power state). When this is enabled, you can't import other power plans than balanced, meaning LLT will not be able to switch power plans. If you somehow manage to import Legion power plans, you can configure how to switch them in LLT.
