### ISSUE TITLE
[FEAT]: we need Gpu overclocking

### ISSUE THREAD

**Issue by lym1932002643** [BartoszCichecki/LenovoLegionToolkit#268]
### Version

2.6.2

### OS

Windows 11 22h2 22623.741

### Device

y9000p 2022

### Is your feature request related to a problem?

We hope to open the same GPU overclocking function as that in the legion zone and vantage

### How would you like the problem to be solved?

We hope to open the same GPU overclocking function as that in the legion zone and vantage

### What alternatives have you considered?

no

**Comment by BartoszCichecki** [comment]
There is no plans for adding GPU over clocking. Use something like MSI afterburner.

Duplicate of #216
