### ISSUE TITLE
[BUG]: GPU Working Mode Switch issue

### ISSUE THREAD

**Issue by Airy-Tian** [BartoszCichecki/LenovoLegionToolkit#269]
### Version

2.6.2

### OS

Windows 11 Pro 22H2 Build 22621.525

### Device

Legion Y9000P IAH7H 2022 CHINA

### BIOS version

J2CN40WW

### What's wrong?

The discrete GPU is not connected and activated after switching from "Hybrid-iGPU Only Mode" mode to "Hybrid Mode" untill reboot.

### How to reproduce the bug?

1.Switch GPU Working Mode to "Hybrid-iGPU Only Mode" from "Hybrid Mode" (or other modes, only "Hybrid Mode" is tested ) and deactive GPU via LenovoLegionToolkit if there are apps running on discrete GPU.
2.Wait untill the discrete GPU is disconnected automaticly and disappears form devices manager. 
3.Switch GPU Working Mode back to ”Hybrid Mode“.
4.The Discrete GPU Widget disappeared after relaunch Lenovo Legion Toolkit and the discrete GPU kept disconnected. The NVIDIA control panel shows ‘The NVIDIA graphics card is not detected in your system.“ 

### What is the behavior that you expected?

The discrete GPU is connected soon and become available without rebooting.

### Logs

[log_2022_10_13_03_41_35.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9770317/log_2022_10_13_03_41_35.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

I frist found this issues when i installed the toolkit at "C:/Program files/LenovoLegionToolkit".
Then I tested and writed this with the toolkit installed at default location.
Only "Lenovo Fn and Function Keys" driver is installed.

**Comment by BartoszCichecki** [comment]
Duplicate #236
