### ISSUE TITLE
[FEAT]: Request for a new trigger: At specified battery percent.

### ISSUE THREAD

**Issue by MZhao-ouo** [BartoszCichecki/LenovoLegionToolkit#270]
### Version

2.6.2

### OS

Windows 11 22H2 build 22622.601

### Device

Legion Y9000P IAH7H

### Is your feature request related to a problem?

I would like to change power mode or do something when battery percent is 30% to save power. 
Or changing Battery Mode from rapid mode to Conservation when battery is charged to 80%.

### How would you like the problem to be solved?

Add `At specified battery percent` trigger to Actions.

### What alternatives have you considered?

Sorry I have no idea.

**Comment by BartoszCichecki** [comment]
Duplicate of #20.
