### ISSUE TITLE
[FEAT]: Configurable Startup Autorun Delay

### ISSUE THREAD

**Issue by ThatOtherAndrew** [BartoszCichecki/LenovoLegionToolkit#271]
### Version

2.6.2

### OS

Windows 11 Pro 22H2 Build 22621.674

### Device

Legion 7i 16IAX7

### Is your feature request related to a problem?

Since startup of LLT is delayed by 30 seconds after logon for compatibility reasons, my configured actions run 30 seconds after I reach my desktop, usually at exactly the time I've launched an app and am typing. The result is that the screen can go black for a few seconds when settings are changed, which is a minor annoyance.

### How would you like the problem to be solved?

Making the hard-coded 30 second delay into an adjustable value would be very useful, and could be disabled altogether by the end user if compatibility is not a concern in their case.

### What alternatives have you considered?

None, it is only a minor annoyance and doesn't bother me too much.

**Comment by Godl1nk** [comment]
probably not, pretty sure LLT requires some vantage services to start first (if any)

**Comment by ThatOtherAndrew** [comment]
Even if you have all Vantage services disabled? And assuming that there is a wait required, would it not be a smarter move to poll for when the service has started?
