### ISSUE TITLE
[BUG]: Keyboard backlight blue color after turn on machine even set keyboard preset to Off.

### ISSUE THREAD

**Issue by ahweisync** [BartoszCichecki/LenovoLegionToolkit#275]
### Version

2.6.2

### OS

Windows 11 Pro

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN43WW

### What's wrong?

Keyboard blue backlight issue during booting up windows after shutdown the laptop.

### How to reproduce the bug?

Laptop is shutdown
Turn on laptop
Keyboard blue backlight is turn on itself
Login to windows
LLT is running and show taskbar
Keyboard blue backlight is turn off itself because my preset for keyboard backlight is set to Off

### What is the behavior that you expected?

Laptop is shutdown
Turn on laptop

### Logs

No Logs

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Tested lenovo vantage don't have this issue and behavior

_No response_

**Comment by BartoszCichecki** [comment]
So let me understand this right. You keyboard light's up blue when you turn on your laptop and then when Windows and LLT loads up it turns off, because your profile in LLT is set to off. Right? If yes, I don't think it's a bug in LLT, because LLT controls backlight when it's running, ergo, it has no control when your laptop is starting.

**Comment by ahweisync** [comment]
but this behaviour not happen to lenovo vantage. i set keyboard light off in vantage then turn on my laptop keyboard light is turn off all the times

**Comment by BartoszCichecki** [comment]
I see, maybe the "off" state is not completely correct.

Just to be sure, you have a 4 zone RGB keyboard right?

**Comment by BartoszCichecki** [comment]
Try to install the buid and see if there is any improvement:

[LenovoLegionToolkitSetup_rgb.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9794356/LenovoLegionToolkitSetup_rgb.zip)

**Comment by ahweisync** [comment]
yes rgb but i need to test first

**Comment by BartoszCichecki** [comment]
@ahweisync any news?

**Comment by ahweisync** [comment]
new version 2.6.3 still same issue

**Comment by ahweisync** [comment]
i will test this version [LenovoLegionToolkitSetup_rgb.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9794356/LenovoLegionToolkitSetup_rgb.zip) and let you know by tomorrow after 1 night power off state

**Comment by mariobalanica** [comment]
I was able to repo this and the build above fixes it.

**Comment by ahweisync** [comment]
May i know this version [LenovoLegionToolkitSetup_rgb.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9794356/LenovoLegionToolkitSetup_rgb.zip) included Stability improvements for Hybrid Mode on gen 7 Legions?
