### ISSUE TITLE
[FEAT]: CPU Frequency tweaks

### ISSUE THREAD

**Issue by Godl1nk** [BartoszCichecki/LenovoLegionToolkit#276]
### Version

2.6.2

### OS

Windows 11 22H@

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

-

### What alternatives have you considered?

-

### Additional information

This might not be relevant for Intel CPUS because they have Throttlestop. Why am I asking this here instead of on something like AATU/UXTU ? Legion Custom mode will cause incompatibility either this features can be implemented or a way to stop the interfere

**Comment by BartoszCichecki** [comment]
The purpose of LLT is to provide most functionality available in Vantage and LegionZone. If you want to customize how the CPU works beyond what Lenovo provides use other software. And if this software conflicts with custom mode, don't use it.
