### ISSUE TITLE
[COMPATIBILITY]: SmartFanMode not supported for Lenovo Xiaoxin Pro-13API 2019

### ISSUE THREAD

**Issue by TayLin99** [BartoszCichecki/LenovoLegionToolkit#278]
### Version

2.6.2

### OS

Windows 10 22H2 build 19045.2075

### Device

Lenovo Xiaoxin Pro-13API 2019  81XD

### Which features of the application did you test?

Toolkit shows my device only support Battery Mode\Always on USB\Fn Lock\Flip To Start,
and the Battery Information runs well.

![image](https://user-images.githubusercontent.com/19733963/195984298-473ea398-a052-4c1b-9ef8-defb78dc2b69.png)
![image](https://user-images.githubusercontent.com/19733963/195984301-7f75a5fb-14c3-46e0-a879-13d86b63db66.png)

### Which features of the application do not work as expected?

Setting - PowerPlan
It notices that "Unexpected exception occurred:Feature SmartFanMode is not supported."

![image](https://user-images.githubusercontent.com/19733963/195984283-a086f534-efc9-4c2d-bf3d-92a86897f87a.png)

**Comment by BartoszCichecki** [comment]
As per README:

"If your laptop is not part of Legion or Ideapad Gaming lines, this software is not for you. Please do NOT open compatibility requests for other devices. Issues will be closed and not looked at!"

**Comment by TayLin99** [comment]
Ok. I got it. I am sorry. Thank you.
