### ISSUE TITLE
Change power plan after Fn+Q shortcut

### ISSUE THREAD

**Issue by BartoszCichecki** [BartoszCichecki/LenovoLegionToolkit#28]

**Comment by BartoszCichecki** [comment]
Reference: https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/22

**Comment by sickypedia** [comment]
Hi, thanks for adding this! Looks like some changes for this resulted in a bug - changing with Fn+Q is still possible and the app listens and responds, but selecting the radio buttons does not trigger any change now.

**Comment by BartoszCichecki** [comment]
Damn, you are right, when using radio buttons power plan does not change. I'll try to patch it today/tomorrow! Thanks for noticing!

**Comment by BartoszCichecki** [comment]
Fixed in 1.3.1
