### ISSUE TITLE
Hello!Can you increase your support for the thinkbook series？please!!!

### ISSUE THREAD

**Issue by Firefly-Xu** [BartoszCichecki/LenovoLegionToolkit#291]
### Version

2.62

### OS

Windows 11 Pro  22H2

### Device

ThinkBook 14 G3 ACL

### Is your feature request related to a problem?

My device is a thinkbook series. I specially downloaded and tried the software you developed. It's amazing. Can I adapt to the thinkbook series?

### How would you like the problem to be solved?

adapt to the thinkbook series，please!

### What alternatives have you considered?

I don't know

**Comment by Firefly-Xu** [comment]
Hello,here is a log for my device!
https://firefly-xu.lanzout.com/i3YYt0dzc2mf

**Comment by BartoszCichecki** [comment]
Hi, thanks for kind words.

Unfortunately, there are big differences on the Hardware level in other Lenovo laptops. I simply don't have the time and resources to support more types of devices. It is also incredibly difficult to add support for devices that I don't have access to.

**Comment by Firefly-Xu** [comment]
I can provide the hardware information and drivers of the device. Is this convenient? I can also install and test the device and feed back the log at the same time
