### ISSUE TITLE
[FEAT]: Allow waiting for exit in Run automation step

### ISSUE THREAD

**Issue by mstieranka** [BartoszCichecki/LenovoLegionToolkit#293]
### Version

2.6.2

### OS

Windows 11 21H2 Build 22623.741 (Insider Beta)

### Device

Lenovo Legion 5 15ARH05H 82B1

### Is your feature request related to a problem?

I wanted to use Quick Actions to create a custom battery conservation mode, where the battery mode would be set to Normal, then a script would run until the battery reaches x%, and afterwards the battery mode would be set to Conservation again. This is so I can keep my laptop at ~80% instead of the normal 60%, which isn't enough for daily usage.

However, this doesn't work as the script is simply run in the background while the battery mode is set back to Conservation.

This could be solved by adding a checkbox to the Run step which would make the automation step wait until the script/program terminates.

### How would you like the problem to be solved?

I haven't done much C# development, but from what I see, the following would be enough:

* add a parameter to `LenovoLegionToolkit.Lib.Automation.Steps.RunAutomationStep` called `waitForExit`, saving it to `boolean? WaitForExit { get; }`, then passing `WaitForExit ?? false` instead of `false` in

https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/125f58ecce9d245ea60ddbd106fc0f8d14aa377d/LenovoLegionToolkit.Lib.Automation/Steps/RunAutomationStep.cs#L27

* add a `default` here

https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/125f58ecce9d245ea60ddbd106fc0f8d14aa377d/LenovoLegionToolkit.WPF/Controls/Automation/Pipeline/AutomationPipelineControl.cs#L352

* add a checkbox to https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/125f58ecce9d245ea60ddbd106fc0f8d14aa377d/LenovoLegionToolkit.WPF/Controls/Automation/Steps/RunAutomationStepControl.cs

### What alternatives have you considered?

Adding the custom battery charging level feature itself into the app, though that's too much work 😄 

### Additional information

I may end up submitting a PR for this if I end up having the time.

**Comment by BartoszCichecki** [comment]
Hey, `waitForExit` can't be set to `true`, because that will effectively block the whole `AutomationProcessor`. Another thing is that if you use battery regularly just charge it to a 100%. There is no reason to keep it at 60% or 80% if you use it. Honestly, even if you keep battery at 80%, and use it regularly, you still cycle it and degrade it. Conservation mode is only useful if you almost never use your laptop on battery - and you mentioned daily usage.

Previously discussed here: #20.

**Comment by BartoszCichecki** [comment]
And if you really need this (seriously you shouldn't need it), then write the script in a way that runs in background. Like [this](https://stackoverflow.com/questions/649634/how-do-i-run-a-bat-file-in-the-background-from-another-bat-file) for example.
