### ISSUE TITLE
'Flip to boot' should be renamed, add info to toggles

### ISSUE THREAD

**Issue by Elrondolio** [BartoszCichecki/LenovoLegionToolkit#3]
The "Flip to boot" toggle should probably be renamed "Flip to Start" as that is what Lenovo has this named.

Would also be nice to have info pop-overs that give a short description to each of the toggle options as some may not know what these do.

"About" menu option is currently not programmed, would be nice to provide a link to this github from there as well as your credits, etc.

Thanks.

**Comment by BartoszCichecki** [comment]
All done in 1.1 release! Thanks for feedback!
