### ISSUE TITLE
[FEAT]: Auto touchpad lock

### ISSUE THREAD

**Issue by Godl1nk** [BartoszCichecki/LenovoLegionToolkit#304]
### Version

LATEST

### OS

21H@

### Device

Legion 5

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

add an option in touchpad lock to auto lock when a mouse is connected

### What alternatives have you considered?

no

**Comment by BartoszCichecki** [comment]
https://windowsreport.com/disable-touchpad-mouse-connected-windows-10/
