### ISSUE TITLE
[BUG]: Battery mode doesn't preserve after reboot or sleep

### ISSUE THREAD

**Issue by RoadToDream** [BartoszCichecki/LenovoLegionToolkit#307]
### Version

3.6.3

### OS

Windows 11 22H2

### Device

Legion 7i 16IAX7

### BIOS version

K1CN31WW

### What's wrong?

I am not sure if it's a bug in LLT or a flaw in Lenovo firmware. It seems the battery mode doesn't survive after reboot or sleep, it will always go back to Normal even if Conservation is selected. 

### How to reproduce the bug?

1. Select Conservation in Battery Mode
2. Reboot
3. Battery Mode switched to Normal.

### What is the behavior that you expected?

Battery Mode maintains Conservative 

### Logs

[log_2022_10_18_17_48_02.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9813829/log_2022_10_18_17_48_02.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Hey, it actually is a bug in FW. Happens either all the time or almost never, but it has been reported many times now. For some EC reset fixes things, for some it doesn't. It happened on my L5P, but doesn't happen anymore on my L7 (same model and BIOS as yours).

For reference LLT always reads current values from FW, it doesn't store any state.

Related issues: #180, #112, #82.
