### ISSUE TITLE
[FEAT]: Navigation bar cuts off some words

### ISSUE THREAD

**Issue by younyokel** [BartoszCichecki/LenovoLegionToolkit#315]
### Version

2.6.4

### OS

Windows 11

### Device

Lenovo Legion 5

### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/53343081/196831779-6ffc6c03-e7da-4b67-a33b-12155d30b3a8.png)
This is not a bug, so I used "feature" tag. The problem is that some long words are being cut off in the left navigation menu for some languages.

### How would you like the problem to be solved?

I don't know how this can be fixed, but I suggest either limiting the number of letters or making a line break in the middle of the word.

### What alternatives have you considered?

I don't even know, it seems like there are at least 20 more free pixels to continue the text but the word is still cut off.

**Comment by BartoszCichecki** [comment]
Well, it's a limiation of the WPFUI lib that I am using. I already mentioned this issue to the author and at some point it will be corrected. For now the only work around is to choose shorter text.
