### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by freetbash** [BartoszCichecki/LenovoLegionToolkit#320]
### Version

2.6.4

### OS

Windows 11

### Device

Legion Y9000X IAH7

### Is your feature request related to a problem?

![image](https://user-images.githubusercontent.com/88578981/197135273-d0516120-e7ff-441c-a77d-78ba431d4366.png)

My trackpad prompts appear as normal as this one, and I want to be able to pin the tooltips for this feature in front of all windows

### How would you like the problem to be solved?

My trackpad prompts appear as normal as this one, and I want to be able to pin the tooltips for this feature in front of all windows

### What alternatives have you considered?

My trackpad prompts appear as normal as this one, and I want to be able to pin the tooltips for this feature in front of all windows

**Comment by BartoszCichecki** [comment]
@KarlLee830 please help.

**Comment by KarlLee830** [comment]
> @KarlLee830 please help.

He wants notifications for Touchpad lock and wants notifications always on top.

**Comment by BartoszCichecki** [comment]
Closing because #328 is done now, so issues should be resolved in next release.

**Comment by freetbash** [comment]
> > @KarlLee830 please help.
> 
> He wants notifications for Touchpad lock and wants notifications always on top.
> Also I'm not sure because he used English instead of Chinese and I couldn't understand exactly what he meant.

不好意思啊，没想到是国人的项目啊，我以为是国外的，机器翻译了一下😱
