### ISSUE TITLE
[FEAT]: Improve scrolling speed with Touchpad

### ISSUE THREAD

**Issue by WhatDamon** [BartoszCichecki/LenovoLegionToolkit#322]
### Version

2.6.4

### OS

Windows 11 Pro Insider Preview Build 25217

### Device

Legion Y9000P IAH7H

### Is your feature request related to a problem?

Using **Legion's touchpad** to slide the page has obvious traces of stuttering, and the sliding speed is too fast to facilitate the selection of the required configuration items

### How would you like the problem to be solved?

Smoother sliding and not so fast as to end in a single swipe, like the Microsoft Store or Microsoft Edge swipe experience

### What alternatives have you considered?

If conditions allow, I recommend switching to WinUI or UWP, the animation will also be more native, but if you insist on using WPF development, please try to optimize it, now I can rely on the sliding bar to use

**Comment by WhatDamon** [comment]
I don't have more time to help you track down this problem, but you can try it yourself. If you really can't fix it and are not in a position to switch to WinUI or UWP, you can Close this issue, sorry!

**Comment by BartoszCichecki** [comment]
Good point, I will take a look at this.

**Comment by BartoszCichecki** [comment]
As a side note: switching to WinUI is not going to happen any time soon. When this project was started it wasn't production ready and now the amount of effort to switch is too much. Simply: I don't have the time to do this.
