### ISSUE TITLE
[FEAT]: Add game detection to actions

### ISSUE THREAD

**Issue by GiraffeGoGoGo** [BartoszCichecki/LenovoLegionToolkit#323]
### Version

2.6.4

### OS

Windows10 22H2 19045.2130

### Device

Legion R7000P2020H 15ARH05H

### Is your feature request related to a problem?

Request to add the function in Lenovo Vantage, automatically switch to performance mode when starting the game, and switch to balance mode when closing the game.

### How would you like the problem to be solved?

Add "When CPU/GPU utilization/temperature reaches......" in automation(Actions) to switch to power mode.

The function of Lenovo Vantage to automatically switch the performance mode may be judged according to the utilization rate of the GPU.

### What alternatives have you considered?

Manually add applications in automation, but cannot add Microsoft Store uwp applications.

**Comment by BartoszCichecki** [comment]
As a sidenote if you only play a couple of games, you can add them to "when process started" action. 

But anyway, good suggestion.
