### ISSUE TITLE
[FEAT]: Request the addition of the ability to disable the notebook's own keyboard

### ISSUE THREAD

**Issue by luyaozhang00** [BartoszCichecki/LenovoLegionToolkit#324]
### Version

2.6.4

### OS

windows11 22h2

### Device

r7000

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

Like disabling Windows Key

### What alternatives have you considered?

Remove the notebook keyboard driver

**Comment by BartoszCichecki** [comment]
This functionality isn't provided by any interface that Lenovo exposed.
