### ISSUE TITLE
[FEAT]: Compatibility with 14ARH7

### ISSUE THREAD

**Issue by hinchyman** [BartoszCichecki/LenovoLegionToolkit#331]
### Version

2.6.4

### OS

Windows 11 22H2

### Device

Slim 7 Prox 14ARH7

### Is your feature request related to a problem?

I donated to say thank you for your hard work and would be happy to fund this if you're interested. I was hoping to add support for the Slim 7 ProX 14ARH7, Ryzen 6800HS, 3050 Ti. I'd be happy to work with you on this. If not, no worries. Thanks again for making such a great tool 

### How would you like the problem to be solved?

In time, compatibility is added similar to Legion 

### What alternatives have you considered?

n/a

**Comment by BartoszCichecki** [comment]
Hey, unfortunately there is no way for me to support devices from other line ups. There are just too many differences, and it's really hard to support a device properly without having it physically.

I understand that this is probably not the outcome you expected, so if you want to get a refund of the donation let me know.

**Comment by hinchyman** [comment]
Thanks for replying. No worries! I understand. No refund or anything needed :)
