### ISSUE TITLE
[FEAT]: Ability to make brightness static on all power modes

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#332]
### Version

any

### OS

11

### Device

Legion 5 Pro 16ACH6H

### Is your feature request related to a problem?

Having a brightness level for each power mode doesn't make sense to me, I think having an option to make brightness level static on all power modes is best.
Thanks!

### How would you like the problem to be solved?

none

### What alternatives have you considered?

none

**Comment by BartoszCichecki** [comment]
Hey, I have already looked into this before. Unfortunately there is no way of doing this that I could find.

Even if there was, LLT is not going to fix all your problems.
