### ISSUE TITLE
[BUG]: minor chinese translation in home

### ISSUE THREAD

**Issue by Likexiao** [BartoszCichecki/LenovoLegionToolkit#341]
### Version

2.6.4

### OS

Windows 10

### Device

Legion Y7000P IAH7

### BIOS version

J2CN46WW

### What's wrong?

关于显卡工作模式中 
混合显示模式的介绍中，中文翻译错误。
“仅使用独显”，应为“仅使用核显”

### How to reproduce the bug?

以上

### What is the behavior that you expected?

以上

### Logs

以上

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [X] I disabled some things on my own (please write below what you did)

**Comment by KarlLee830** [comment]
This translation issue has been fixed 13 days ago. The new Beta version is now the corrected translation, and you will see the corrected translation in the next release. (which is, 2.6.5).
此翻译问题已经在13天前被修复了。目前新的Beta版已经是修正后的翻译，在下一个正式版（也就是2.6.5）你将看到修正后的翻译。
