### ISSUE TITLE
[FEAT]: The warnings at startup can be shut down

### ISSUE THREAD

**Issue by Ptilopsis01** [BartoszCichecki/LenovoLegionToolkit#343]
### Version

2.6.4

### OS

Win11 22H2 22621.755

### Device

Legion Y9000X IAH7(S7 16IAH7)

### Is your feature request related to a problem?

I have changed the UEFI when booting system, which changes the returned value of "product type". It caused a problem that every time I start LLT, there will be a warning window shown to me, although actually my device matches LLT, which is a little annoying.

### How would you like the problem to be solved?

I hope that there could be a switch in LLT which can shut the warning at startup down, so that I don't need to wait for 5s and close the window mannually every time I start LLT.

### What alternatives have you considered?

As mentioned above.

**Comment by BartoszCichecki** [comment]
Well, I suggest you fix it.

In the meanwhile check this out: https://github.com/BartoszCichecki/LenovoLegionToolkit#my-motherboard-was-replaced-and-now-llt-gives-me-incompatible-message-what-do-i-do
