### ISSUE TITLE
[FEAT]: Allow to choose where notifications appear.

### ISSUE THREAD

**Issue by KarlLee830** [BartoszCichecki/LenovoLegionToolkit#344]
### Version

2.6.5 Beta 4

### OS

Windows 11 22H2

### Device

Legion S7 IAH7

### Is your feature request related to a problem?

Notifications now only appear in the bottom right corner, not customizable enough.

### How would you like the problem to be solved?

Allow to choose where notifications appear, including corners, and below or above the center of the screen.

### What alternatives have you considered?

None

**Comment by 302991530** [comment]
agree
