### ISSUE TITLE
[FEAT]: Suggest taking over the display of the num lock button

### ISSUE THREAD

**Issue by ArielHeleneto** [BartoszCichecki/LenovoLegionToolkit#345]
### Version

2.6.4

### OS

Windows 10 专业版 19045.2194

### Device

Legion Y9000P IAH7H

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

add key link?

### What alternatives have you considered?

no

**Comment by BartoszCichecki** [comment]
Duplicate of #244.

**Comment by BartoszCichecki** [comment]
Caps/Num lock notifications will be part of 2.6.5.
