### ISSUE TITLE
[FEAT]: Settings, capitalized language variables

### ISSUE THREAD

**Issue by younyokel** [BartoszCichecki/LenovoLegionToolkit#347]
### Version

2.6.4

### OS

Windows 11

### Device

Lenovo Legion 5

### Is your feature request related to a problem?

Sorry to disturb but some languages in Settings tab are written in lower case.

![image](https://user-images.githubusercontent.com/53343081/199841945-139f0e44-9b86-43e0-a4ec-1489bbaedf86.png)

### How would you like the problem to be solved?

I would appreciate consistency in the language names based on Latin and Cyrillic.

### What alternatives have you considered?

:D

**Comment by BartoszCichecki** [comment]
Very good point :)
