### ISSUE TITLE
[BUG]: fn funtion can't display in full-screen mode game

### ISSUE THREAD

**Issue by HMwancheng** [BartoszCichecki/LenovoLegionToolkit#349]
### Version

2.6.4

### OS

win11

### Device

y9000p

### BIOS version

J2CN46WW

### What's wrong?

fn key funtion can't display in full-screen mode game

### How to reproduce the bug?

no

### What is the behavior that you expected?

good

### Logs

no have

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Not planned at the moment. Most games run in full screen exclusive mode, and it is not possible to show anything over these.
