### ISSUE TITLE
[BUG]: Notebook touchpad lock Error

### ISSUE THREAD

**Issue by hufengwei0315** [BartoszCichecki/LenovoLegionToolkit#350]
### Version

2.6.4

### OS

版本	Windows 11 家庭中文版 版本	22H2 安装日期	‎2022/‎09/‎26 ‎周一 操作系统版本	22621.674 序列号	PF3X22NZ 体验	Windows Feature Experience Pack 1000.22634.1000.0

### Device

Legion Y7000P IAH7

### BIOS version

J2CN45WW

### What's wrong?

1.use system hotkey fn+f10 to lock  touchpad  
did not follow in the llt
2. sometime later touchpad   will be unlock

### How to reproduce the bug?

1.fn+f10 to lock  touchpad
2.wait sometime 
3. touchpad unlocked

### What is the behavior that you expected?

like legion zone 
after lock will not unlock

### Logs

null

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
If something like this happens, it means that there is a bug in Lenovo's driver or EC or something. LLT always reads the current state from Lenovo provided interface. IF touchpad lock resets for you I suggest working around this with Actions.

**Comment by hufengwei0315** [comment]
> If something like this happens, it means that there is a bug in Lenovo's driver or EC or something. LLT always reads the current state from Lenovo provided interface. IF touchpad lock resets for you I suggest working around this with Actions.

Thank you , I will test more actions about this issue

**Comment by BartoszCichecki** [comment]
I know that it sucks, but bugs like this are not uncommon. Similar thing happens to battery conservation mode - it also resets for some. Their drivers/ec is full of bugs like this and it's impossible to create "workarounds" for each model and BIOS/EC/driver version.
