### ISSUE TITLE
[FEAT]: Program icon in the system tray.

### ISSUE THREAD

**Issue by SU-ZaKaT** [BartoszCichecki/LenovoLegionToolkit#352]
### Version

2.6.4

### OS

Windows 10

### Device

Legion 5 17ITH6H

### Is your feature request related to a problem?

No.

### How would you like the problem to be solved?

Can you add the ability to turn off the icon in the system tray to the program?

### What alternatives have you considered?

Or.
Are there any ways to do it yourself?

### Additional information

The first option (How would you like the problem to be solved?) is preferable.
Thank you.

**Comment by BartoszCichecki** [comment]
You can hide the icon in the fly out in the tray.

In general there needs to be an icon for various reasons.

**Comment by SU-ZaKaT** [comment]
> You can hide the icon in the fly out in the tray.

I understand what trick you are talking about.


> In general there needs to be an icon for various reasons.

I agree. But not for everyone. )
Are there any arguments (suitable —minimized) to launch a program without an icon?

**Comment by BartoszCichecki** [comment]
Nope, you cannot disable the tray icon in any way.

**Comment by SU-ZaKaT** [comment]
> I am also unsure why would you need to hide the icon.

I myself am very tired of my excessive perfectionism. )
Thank you for the answers.
Good project.
I am satisfied.
