### ISSUE TITLE
[BUG]: Custom Power Mode not available 15IAH7H J2CN45WW

### ISSUE THREAD

**Issue by yAllahuzin** [BartoszCichecki/LenovoLegionToolkit#353]
### Version

2.6.4 

### OS

Windows 11 22h2

### Device

Legion 5i 15IAH7H

### Which features of the application did you test?

 I just installed in on my **Legion 5i 2022** model but **Custom Power Mode** and **Fan Control** is _not showing_. BTW I'm using Legion Fan Control at the moment and it's working without any issue.

### Which features of the application do not work as expected?

 Custom Power Mode and Fan Control

### Logs

[log_2022_11_05_20_27_36.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9944685/log_2022_11_05_20_27_36.txt)

### Additional information

BIOS VERSION: J2CN45WW

**Comment by BartoszCichecki** [comment]
Are you absolutely sure, you don't have custom mode in the drop down with power modes? J2CN bios is supported.

**Comment by yAllahuzin** [comment]
I'm 100% sure, does not appear the Custom Mode option, just Quiet, Balance and Performance

**Comment by BartoszCichecki** [comment]
I think we will need to do some more troubleshooting. Can you upload a log from this build:
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9944783/LenovoLegionToolkitSetup.zip)

**Comment by yAllahuzin** [comment]
After I uninstall LTT, clear windows cache, restart and install again, custom mode appeared

**Comment by BartoszCichecki** [comment]
OK, interesting... I will close this for now, since I am not sure why this happened, but if it happens again, please reopen this issue and let me know!
