### ISSUE TITLE
[BUG]: The excluded refresh rates have disappeared

### ISSUE THREAD

**Issue by rp1231** [BartoszCichecki/LenovoLegionToolkit#354]
### Version

2.6.4

### OS

Windows 11 22H2

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN51WW

### What's wrong?

I unselected some of the refresh rates that I didn't want to exclude and now they seem to have disappeared completely and I can't seem to find them anywhere.......

### How to reproduce the bug?

Unselect the refresh rates you don't want from the `Exclude refresh rates` option in the LLT settings.

### What is the behavior that you expected?

I expected that I could re-enable the refresh rates when needed, but they have completely disappeared.

### Logs

...

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by KarlLee830** [comment]
Maybe because the number of refresh rates is different in dGPU mode and Hybrid-iGPU mode.

**Comment by KarlLee830** [comment]
> @KarlLee830
> 
> Yes that was it. I didn't know the refresh rates were different in the different modes. Thanks.

You are welcome.😎
