### ISSUE TITLE
[BUG]: Scripts Wont Run under Actions category

### ISSUE THREAD

**Issue by darthctrlvder** [BartoszCichecki/LenovoLegionToolkit#355]
### Version

2.6.4

### OS

Windows 10 22H2

### Device

Legion 7i 16ITHg6

### BIOS version

H1CN49WW

### What's wrong?

Under the actions tab when I try to run an action to launch a python script it does nothing.
Same script works just fine with `Win + R` .

### How to reproduce the bug?

Actions tab
Run a script 
path:`C:\\Users\\paliw\\Documents\\Scripts\\wp.py`
Arguments: 
Run now

### What is the behavior that you expected?

To run the python script and change wallpaper

### Logs

[log_2022_11_06_08_12_45.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9945372/log_2022_11_06_08_12_45.txt)
[log_2022_11_06_08_13_29.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9945373/log_2022_11_06_08_13_29.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Nope, that's not a bug. Whatever you put in the Run step is on you to make sure it can run - I can't support people asking how to run stuff.

**Comment by darthctrlvder** [comment]
> Nope, that's not a bug. Whatever you put in the Run step is on you to make sure it can run - I can't support people asking how to run stuff.

and what exactly does it allow to run? bash scripts? there is no clear explanation what it runs and what it doesn't. the python script is running fine on cmd prompt -_-

**Comment by BartoszCichecki** [comment]
It definitely does not run anything in bash, because there is not bash on Windows. 

It behaves more or less like Run (Win+R) window.

In the first fields as the hint indicates, you need to point to an executable. *.py file is not a Windows executable, you probably should put a path to Python shell in the first field, and path to your script as an argument.

Under the hood it uses this: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start

**Comment by darthctrlvder** [comment]
> It definitely does no run anything in bash, because there is no bash on Windows.
> 
> It behaves more or less like Run (Win+R) window.
> 
> In the first fields as the hint indicates, you need to point to an executable. *.py file is not a Windows executable, you probably should put a path to Python shell in the first field, and path to your script as an argument.
> 
> Under the hood it uses this: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start

Thank you for the reference docs it helped me understand the args and properly parse them. Script is working as intended. I would suggest you to add this in documentation. Cheers! lovely software you have developed :)
