### ISSUE TITLE
[COMPATIBILITY]: Menu options have no keyboard selection compatibility

### ISSUE THREAD

**Issue by linzedong666** [BartoszCichecki/LenovoLegionToolkit#358]
### Version

2.6.4

### OS

window11

### Device

Lenovo Legion R9000K 2021H

### Which features of the application did you test?

no

### Which features of the application do not work as expected?

no

### Additional information

![image](https://user-images.githubusercontent.com/106944736/200179765-8ce3a694-b429-4a75-847b-584cfbe144a7.png)

**Comment by BartoszCichecki** [comment]
You opened another issue #357 and you didn't provide any information except for the model you have. I don't know what keyboard you have or what's in the logs. Now you open exactly the same issue without any description, so how am I supposed to help you?

Either provide actual information or stop opening issues like this.

**Comment by BartoszCichecki** [comment]
On top of that, README contains information about which keyboards are supported and which are not. Please read it before opening issues.
