### ISSUE TITLE
[FEAT]: Fn + U key notification for legion 7 series

### ISSUE THREAD

**Issue by darthctrlvder** [BartoszCichecki/LenovoLegionToolkit#360]
### Version

2.5.6

### OS

Windows 10 22h2

### Device

Legion 7i 16ITHg6

### Is your feature request related to a problem?

There is an extra hot key in Legion 7i to toggle the light switch for the IO port label white lighting. Without the notification you have to stand up and look behind the laptop to confirm if the desired settings are applied. 

### How would you like the problem to be solved?

A notification just like others indicating the current state would help a lot since you no longer have to stand up and bend the display to look behind your system

### What alternatives have you considered?

If notification cannot be added. Some other visual cue would help a lot.

**Comment by BartoszCichecki** [comment]
Will be added as part of #223 :)
