### ISSUE TITLE
[BUG]: Overdrive Mode toggle is buggy 

### ISSUE THREAD

**Issue by theunknowninfinite** [BartoszCichecki/LenovoLegionToolkit#361]
### Version

2.6.5

### OS

Windows 10 Pro 22H2

### Device

Legion 5 Pro 2021 RTX 3060 

### BIOS version

GKCN57WW

### What's wrong?

The overdrive mode toggle is always toggled to on. I can reproduce it when I toggle it off and switch to some other tab and come back to the main page, it gets toggled on automatically. 

### How to reproduce the bug?

1.Go to overdrive toggle and turn it off.
2. Switch to battery or settings tab. 
3. Come back to toggles page and overdrive is on.
4. Similarly, disable overdrive, close app and change power mode.
5. Open app and overdrive shows it's enabled. 

### What is the behavior that you expected?

The toggle to stay off. 

### Logs

[log_2022_11_07_07_12_11.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9948981/log_2022_11_07_07_12_11.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [x] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information
I can observe the same happens when I do the same with vantage without LTK running.

**Comment by BartoszCichecki** [comment]
> I can observe the same happens when I do the same with vantage without LTK running.

I can see from logs that whenever LLT reads the state of OverDrive it is reported as "On" even though it is subsequently toggled to "Off".

However, if Vantage is doing the same, that doesn't look like a bug in LLT. I would recommend that you do EC reset, because sometime it gets bugged. You can find info on how to do it on the Discord server linked in README - there are people there who can help you with that.

**Comment by theunknowninfinite** [comment]
I have done a EC reset , downgraded Bios and reinstalled gpu Drivers. I haven't had any success. Is there any way I could find out what's happening? I assume that it's the firmware that's not turning it off at this point ?

**Comment by BartoszCichecki** [comment]
Your assumption is correct, but I don't know what can you do.
