### ISSUE TITLE
[FEAT]: Quick action to toggle display refresh rate

### ISSUE THREAD

**Issue by Sebastian-Hothaza** [BartoszCichecki/LenovoLegionToolkit#365]
### Version

2.6.5

### OS

Windows 10

### Device

Legion 7 16ITHg6

### Is your feature request related to a problem?

NO

### How would you like the problem to be solved?

N/A

### What alternatives have you considered?

N/A

### Additional information

Great idea adding the Fn+F9 hotkey support. I want to create a quick action to toggle refresh rate from 60hz to 165hz so I can then map this quick action to Fn+F9. However, I can only create a quick action for either setting to 60hz or 165Hz.

The intended behavior would be:

User enters Fn+F9 and laptop toggles between 60hz and 165hz

**Comment by KarlLee830** [comment]
Why don't you just use Fn + R to toggle the refresh rate.

**Comment by BartoszCichecki** [comment]
I am also wondering this. Do you have one of the models where Fn+R just doesn't work?

**Comment by ahweisync** [comment]
Fn+R doesn't work on new model gen 7

**Comment by BartoszCichecki** [comment]
Well, it does work on 2022 L7, but some models don't support it.

**Comment by BartoszCichecki** [comment]
Enable logging, start LLT, press Fn+R a couple of times and upload the log.
