### ISSUE TITLE
[FEAT]: Require for matching with XiaoxinPro 16

### ISSUE THREAD

**Issue by listentide** [BartoszCichecki/LenovoLegionToolkit#368]
### Version

2.6.5

### OS

windows 11 22H2

### Device

XiaoxinPro 16 ARH7

### Is your feature request related to a problem?

If you can try to adapt XiaoxinPro 16, I will be very appreciative and will try to support you when you adapt and donate.

### How would you like the problem to be solved?

XiaoxinPro 16 be adapted

### What alternatives have you considered?

No, thank you for your effort.

**Comment by listentide** [comment]
I know it will be difficult and time-consuming. So tell me if you are free and you want to make the software compatible with it. I appreciate it.

**Comment by BartoszCichecki** [comment]
Hey, as stated in the readme, support for non-Legion devices will not be added.
