### ISSUE TITLE
Doesn't Run on Startup on Windows 11

### ISSUE THREAD

**Issue by chenm0416** [BartoszCichecki/LenovoLegionToolkit#37]
I have tried checking and unchecking the option however this doesn't run on startup for some reason.

**Comment by BartoszCichecki** [comment]
Is it by any chance that you are on battery power? There is a bug currently related to this that I noticed today.

**Comment by chenm0416** [comment]
Yes, I was on battery power!

**Comment by BartoszCichecki** [comment]
Cool, I will push an update over this weekend most likely and it should start working also on battery (it will require to disable and enable autorun).

**Comment by BartoszCichecki** [comment]
Fixed in: https://github.com/BartoszCichecki/LenovoLegionToolkit/commit/e394f15010fa20da18294db4778e20ecb757b715
