### ISSUE TITLE
[BUG]:  "CUP Sensor" error in Fan curve

### ISSUE THREAD

**Issue by Airy-Tian** [BartoszCichecki/LenovoLegionToolkit#370]
### Version

2.6.5

### OS

Windows 11 Pro 22H2 Build 22621.819

### Device

Legion Y9000P IAH7H 2022 CHINA

### BIOS version

J2CN46WW

### What's wrong?

The "CPU Sensor" keeps displaying 127℃ since the forth one from the left.
<img width="514" alt="屏幕截图 2022-11-10 203852" src="https://user-images.githubusercontent.com/81451357/201094060-c0c513da-788b-4a87-b43e-25af65da14e8.png">
I tried downgrading bios from J2CN46WW to J2CN45WW and J2CN40WW,but it didn't fix it.

### How to reproduce the bug?

1.Switch power mode to custom mode.
2.Clisk the settings icon to enter the "custom mode settings".
3.Go to the fan curve
4.Select a ...slider?  since the forth one from the left.

### What is the behavior that you expected?

I think it should displays tempertures number which increase one by one regularly like the the "CPU" and "GPU" columns.

### Logs

[log_2022_11_10_13_41_10.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9981195/log_2022_11_10_13_41_10.txt)
Operation as "How to reproduce the bug?".

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

XTU installed but nothing was changed.
Hyper-v was enabled but Intel-VT was disabled in bios.

**Comment by BartoszCichecki** [comment]
Unfortunately, it's not a bug. Some devices report this weird curve for one of the sensors. Why? I have no clue.

**Comment by Airy-Tian** [comment]
Get it.
Thanks for your response.
