### ISSUE TITLE
[FEAT]: Notification for smart key secondary action

### ISSUE THREAD

**Issue by GheorgheMorari** [BartoszCichecki/LenovoLegionToolkit#371]
### Version

2.6.5

### OS

Windows 11 22h2

### Device

Legion 5 Pro 16ACH6H

### Is your feature request related to a problem?

I have an action set to the double press of the smart key that runs in an instant, i'd like to see some sort of confirmation or notification that it did run

### How would you like the problem to be solved?

Just a notification like in the other actions

### What alternatives have you considered?

no alternatives

**Comment by BartoszCichecki** [comment]
Good idea. I will add a notification with Action name that ran after F9 single/double press.
