### ISSUE TITLE
The rear power indicator light will not change from white to yellow after the protective charging mode is selected for the battery mode. This cannot prove whether it can switch the charging mode normally

### ISSUE THREAD

**Issue by losrss** [BartoszCichecki/LenovoLegionToolkit#373]
### Version

2.6.5

### OS

Windows 11 Pro 22H2

### Device

Legion Y9000P IAH7H 2022 CHINA

### BIOS version

J2CN40WW

### What's wrong?

The rear power indicator light will not change from white to yellow after the protective charging mode is selected for the battery mode. This cannot prove whether it can switch the charging mode normally

### How to reproduce the bug?

Turn on the charging mode and select the protection mode for charging. The indicator light on the back of the computer does not change

### What is the behavior that you expected?

I think after changing the charging mode, the power indicator at the back will change with the charging mode. The Lenovo Vantage supports this function

### Logs

nothing

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Thanks for reporting in English!

When you enable Conservation mode (or protective mode as you wrote) does the battery stop charging at around 60% or 80%?

**Comment by losrss** [comment]
Fully available! It's just that I don't understand that the indicator light should also be available. I often forget what mode it is in because it hasn't changed. At the beginning, my phone turned on the automatic translation function when I didn't use English. I don't know that they all submitted questions in English. I'm very sorry

**Comment by losrss** [comment]
Fully available! It's just that I don't understand that the indicator light should also be available. I often forget what mode it is in because it hasn't changed. At the beginning, my phone turned on the automatic translation function when I didn't use English. I don't know that they all submitted questions in English. I'm very sorry

**Comment by BartoszCichecki** [comment]
I am not sure if I understand you right, but the color of the LED in the back never changes based on battery charge mode.

If power adapter is connected and battery is charged (100%) it's white.
If power adapter is connected and battaery is not charged (less than 100%) it's orange.

There is not way to change this and it doesn't mattaer if you chose normal charging, conservation mode or rapid charge.

**Comment by losrss** [comment]
No, not really. What you understand may be the light of the big logo on the back, right? What I said is that the dot at the rear charging interface will be orange or white. It is located in the middle of the rear power socket and USB socket. Now W is too late in my country. Tomorrow I will see the log and reply. Thank you!

**Comment by losrss** [comment]
![Uploading image.jpg…]()

**Comment by BartoszCichecki** [comment]
No, I understand that it's the small LED. I am saying that there is no way of controlling it.

It will be orange when power adapter is connected and battery is not fully charged (100%) and it will be white if power adapter is connected and battery is charged to 100%.

**Comment by losrss** [comment]
The problem I have now is that it appears white when the battery is not fully charged or has been fully charged

**Comment by BartoszCichecki** [comment]
I see. It might be a specific behavior of the model you have, but I can't control the color of this LED in any way, so I am afraid I can't help here.

**Comment by losrss** [comment]
Thank you. I can change after using Lenovo Vantage just now. I will try to uninstall and install it again tomorrow. Thank you very much!
