### ISSUE TITLE
[BUG]: Can't select german language

### ISSUE THREAD

**Issue by Expello** [BartoszCichecki/LenovoLegionToolkit#376]
### Version

2.6.5

### OS

Windows 11

### Device

Legion 7 16ARH

### BIOS version

6

### What's wrong?

Hi,

unfortunately, i can't select the german language. strangely enough, the source code also shows DE with english text.

According to "https://crowdin.com/project/llt" the GERMAN is 100% translated.

I am confused, what am I doing wrong?

Thanks a lot!

### How to reproduce the bug?

Install it

### What is the behavior that you expected?

That I can select the german language. :-)

### Logs

NO LOGS

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
German isn't available yet, because it wasn't fully translated. It will be available in next release if all goes well.

**Comment by Expello** [comment]
Ok...the answer was quick! Thank you!

The 100% have irritated me...then we wait and see.
