### ISSUE TITLE
[BUG]: The power mode cannot be changed

### ISSUE THREAD

**Issue by libra-29** [BartoszCichecki/LenovoLegionToolkit#378]
### Version

2.6.5

### OS

Windows11 21h2 build22000.1219

### Device

legion y9000p

### BIOS version

J2CN46WW

### What's wrong?

An error occurred while changing the power mode

### How to reproduce the bug?

<img width="370" alt="84e07e46f9bdd532cdee0c6dd6f4389" src="https://user-images.githubusercontent.com/117370302/201467235-2dab5ce8-6a33-427d-9b5f-fd49e919af9f.png">

### What is the behavior that you expected?

Fix this bug

### Logs

[error_2022_11_12_06_35_45.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994609/error_2022_11_12_06_35_45.txt)
[error_2022_11_12_06_36_47.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994610/error_2022_11_12_06_36_47.txt)
[error_2022_11_12_06_40_46.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994611/error_2022_11_12_06_40_46.txt)
[error_2022_11_12_08_44_52.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994612/error_2022_11_12_08_44_52.txt)
[error_2022_11_12_08_45_50.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994613/error_2022_11_12_08_45_50.txt)
[error_2022_11_12_08_51_35.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994614/error_2022_11_12_08_51_35.txt)
[error_2022_11_12_08_58_45.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994615/error_2022_11_12_08_58_45.txt)
[error_2022_11_12_09_11_39.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994616/error_2022_11_12_09_11_39.txt)
[error_2022_11_12_09_12_00.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994617/error_2022_11_12_09_12_00.txt)
[error_2022_11_12_05_45_58.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994618/error_2022_11_12_05_45_58.txt)
[error_2022_11_12_05_46_50.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994619/error_2022_11_12_05_46_50.txt)
[error_2022_11_12_06_10_23.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994620/error_2022_11_12_06_10_23.txt)
[error_2022_11_12_06_15_43.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994621/error_2022_11_12_06_15_43.txt)
[error_2022_11_12_06_22_39.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994622/error_2022_11_12_06_22_39.txt)
[error_2022_11_12_06_29_55.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994623/error_2022_11_12_06_29_55.txt)
[error_2022_11_12_06_30_57.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994624/error_2022_11_12_06_30_57.txt)
[error_2022_11_12_06_32_47.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994625/error_2022_11_12_06_32_47.txt)
[error_2022_11_12_06_34_59.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9994626/error_2022_11_12_06_34_59.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Can you run this command in PowerShell and show the output?

`Get-WmiObject -namespace root\CIMV2\power -class Win32_PowerPlan`

**Comment by libra-29** [comment]
![屏幕截图 2022-11-14 210628](https://user-images.githubusercontent.com/117370302/201667842-aa81ef96-767d-4664-9fee-91687ad018d3.png)
Still can't, this result occurs

**Comment by BartoszCichecki** [comment]
It looks like there is something wrong with power plans on your Windows installation. I am not sure what, but if LLT can't get power profile information, it will not work correctly.

You need to fix this problem somehow on your Windows installation, because it's not a bug in LLT.
