### ISSUE TITLE
[FEAT]: New Action to change the Display Resolution

### ISSUE THREAD

**Issue by Aloopyn** [BartoszCichecki/LenovoLegionToolkit#382]
### Version

2.6.5

### OS

Windows 11 21H2 build 22000.1219

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

The display has resolution of 1440p (2K), draws more power than 1080p.

### How would you like the problem to be solved?

Allow changing in resolution as an action option

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment]
What kind of difference did you measure in battery life? When I was testing this I saw no measurable difference on two different laptops.
