### ISSUE TITLE
[BUG]: Power Mode switching is Buggy 

### ISSUE THREAD

**Issue by theunknowninfinite** [BartoszCichecki/LenovoLegionToolkit#384]
### Version

Latest Stable Release

### OS

Windows 10 Pro 22H2

### Device

Legion 5 Pro 2021 RTX 3060 

### BIOS version

GKCN44WW

### What's wrong?

The power mode switching refuses to switch to defined power mode, instead toggles back to default quiet mode despite after setting it in the LTK settings panel. Video and screenshots attached. 

https://user-images.githubusercontent.com/68436564/201787623-b8f9aaa5-2b17-4823-bcb0-442961230edc.mp4

![image](https://user-images.githubusercontent.com/68436564/201787682-397ca6cf-7a91-491e-8f42-79cca6d44718.png)

### How to reproduce the bug?

Happens every time when I run actions or use FN+Q to change power modes, regardless of AC power. 

### What is the behavior that you expected?

To switch to specified power mode. 
 

### Logs

[log_2022_11_14_23_18_54.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10007762/log_2022_11_14_23_18_54.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
If you look into the log you sent and search for: `[Power.cs#118:ActivatePowerPlanAsync] Power plan` you will see that the only power plan that LLT activates is power plan with GUID `1b54612f-e15b-4d28-b3f7-affc1b940e63` (Kira power plan) and `85d583c5-cf2e-4197-80fd-3789a227a72c` (Legion Balanced).

I don't know what is switching back to Legion Quiet plan, but it's not LLT. Maybe you have LFC installed? Or LegionZone?

**Comment by theunknowninfinite** [comment]
Yea, I have LFC installed. 
Legionzone is not installed
