### ISSUE TITLE
[FEAT]: Automatically set the LLT language according to the system language.

### ISSUE THREAD

**Issue by KarlLee830** [BartoszCichecki/LenovoLegionToolkit#393]
### Version

2.6.5

### OS

Windows 11 22H2

### Device

Legion S7 IAH7

### Is your feature request related to a problem?

Some people who can't read English have some trouble with switching languages.

### How would you like the problem to be solved?

Automatically set the LLT language according to the system language.

### What alternatives have you considered?

Nope

**Comment by KarlLee830** [comment]
And don't forget to make Inno Setup translatable. 
😘

**Comment by BartoszCichecki** [comment]
> And don't forget to make Inno Setup translatable. 😘

Installer unfortunately will stay English only for now.
