### ISSUE TITLE
[BUG]: Battery mode is reset on rapid charge after each reboot

### ISSUE THREAD

**Issue by mooms06** [BartoszCichecki/LenovoLegionToolkit#394]
### Version

265

### OS

Windows 11 22H2 build 22621.755

### Device

Legion 5 15IAH7 (machine type 82RC)

### BIOS version

J2CN46WW

### What's wrong?

I've set Battery Mode on Conservation, but after a reboot, it reset itself on Rapid Charge.

I've made a log, but I'm not sure it will be useful as the problem is only after a reboot, and then the application is started by the task scheduler and is not in log mode.

### How to reproduce the bug?

Go to power mode,
set battery mode to conservation
reboot
The battery mode is now on rapid echarge

### What is the behavior that you expected?

Battery mode should be remembered.

### Logs

[log_2022_11_16_16_11_18.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10023629/log_2022_11_16_16_11_18.zip)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Looks like the same case as #120. You can try working around this with actions or resetting EC might also help sometimes.

**Comment by mooms06** [comment]
OK, I've added the action when the power adapter is connected. Is it run if the power adapter is already plugged before application launch though ?
How can I reset the EC ?

**Comment by mooms06** [comment]
Also, I should mention that I never encountered this bug with Vantage, so I'm not entirely sure that this is a bug in the BIOS.

**Comment by BartoszCichecki** [comment]
Yes, it will run when adapter is plugged in, but also LLT starts when adapter was plugged in before.

About the EC reset I recommend that you join the discord server that is mentioned in README, people will guide you how to do it. 

Regarding Vantage, it is a bug in BIOS. LLT doesn't store any settings - it always loads them directly from FW/EC/Drivers.

**Comment by mooms06** [comment]
OK thank you. I've already joined the discord server.
