### ISSUE TITLE
Clear apps from nVidia GPU

### ISSUE THREAD

**Issue by BartoszCichecki** [BartoszCichecki/LenovoLegionToolkit#4]
Sometimes weird apps start running on nVidia GPU, for example with Hybrid mode on and external display connected. After disconnecting they keep dGPU active increasing the load on battery.

This feature will allow dGPU to go to sleep and reduce power usage.

Preconditions:
1. There is more than one GPU active - hybrid mode is on
2. There are no displays connected to the dGPU

Note to self:
Use ``nvidia-smi`` and ``Win32_VideoController`` WMI object.

**Comment by sickypedia** [comment]
I updated to the latest 1.4 release to try this feature - Usually my L5P (16ACH6H) idles at 10W (discharge monitored through HWInfo64) when dGPU is inactive and screen is at 60Hz with Legion Quiet power plan. Now even after pressing 'Deactivate' in the toolkit, I see idle discharge of 25W. However closing the toolkit itself fixes the drain and I go back to 10W. Looks like the toolkit itself is keeping the gpu active. Can someone else check and confirm too?

**Comment by sickypedia** [comment]
Since the switch to NVAPI, the deactivate button no longer works for me, I am using an external FHD monitor over USB-C (Displayport Alt mode). Tried restarting as well as fully disconnecting anything attached.

From the earlier version you shared with [logging](https://1drv.ms/u/s!ApDfgN6g_FJ6hNFs72enLgOHpbDaJQ?e=KabpJy), I see this everytime I click the button:
pnputil /restart-device /deviceid "PCI\VEN_10DE&DEV_24DD&SUBSYS_3A4F17AA&REV_A1"

But trying to execute this through cmd directly does nothing as well, just shows the pnputil help, so I'm assuming it is a command syntax issue.

**Comment by BartoszCichecki** [comment]
Are you by any chance on Windows 10?

Can you send me the output from `pnputil /?`?

**Comment by sickypedia** [comment]
Yes, using Win 10 21H2. Attached the output of the help command.
[pnputil_help.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/7670985/pnputil_help.txt)

**Comment by sickypedia** [comment]
Tried this command without /deviceid, received an error:

`C:\Windows\system32>pnputil /restart-device "PCI\VEN_10DE&DEV_24DD&SUBSYS_3A4F17AA&REV_A1"
Microsoft PnP Utility

Failed to restart device:  PCI\VEN_10DE&DEV_24DD&SUBSYS_3A4F17AA&REV_A1
The device instance name is invalid.`

**Comment by BartoszCichecki** [comment]
Ok it looks like pnputil on Windows 10 does not understand the deviceid parameter. I'll need to find a way around this

**Comment by sickypedia** [comment]
I'm curious as to why it worked before the 1.5 update - was pnputil not being used earlier?

**Comment by BartoszCichecki** [comment]
Yes, it was used but i get device id from NVAPI instead of instance id so I had to change the parameter. The switch to NVAPI was needed to avoid waking up the GPU unnecessarily. 

I try to check Microsoft docs to make sure I don't break anything but needless to say they are not great for the APIs I need to use ☹️

**Comment by BartoszCichecki** [comment]
The existing features are getting really stable now, so hopefully situations like this will not happen often in next releases.

**Comment by sickypedia** [comment]
Would you be able to share the right pnputil command to use in Win 10?

**Comment by sickypedia** [comment]
Oh got it, using instance path from device manager works:

C:\Windows\system32>pnputil.exe /restart-device "PCI\VEN_10DE&DEV_24DD&SUBSYS_3A4F17AA&REV_A1\4&1D71CFEE&0&0009"
Microsoft PnP Utility

Restarting device:         PCI\VEN_10DE&DEV_24DD&SUBSYS_3A4F17AA&REV_A1\4&1D71CFEE&0&0009
Device restarted successfully.

**Comment by BartoszCichecki** [comment]
Corrected in https://github.com/BartoszCichecki/LenovoLegionToolkit/commit/dcf75beff3ad16390e67064b5d62da908bd35912
