### ISSUE TITLE
At startup, the program correctly reads the Fn + Q state, but does not switch windows profiles to it

### ISSUE THREAD

**Issue by ateplih** [BartoszCichecki/LenovoLegionToolkit#40]

**Comment by ateplih** [comment]
if the power profile was switched at a time when the program is not running

**Comment by BartoszCichecki** [comment]
Fixed in https://github.com/BartoszCichecki/LenovoLegionToolkit/commit/ce41b07bbbc273ac955a08ea31f571bd10937a7e

**Comment by ateplih** [comment]
Super! Thank you!
