### ISSUE TITLE
[BUG]: Saved Quick Action option still runnable, while option is unavailable.

### ISSUE THREAD

**Issue by jojo2massol** [BartoszCichecki/LenovoLegionToolkit#400]
### Version

BETA 20221120

### OS

Windows 11 22H2 build 22623.891

### Device

Legion 5 15ACH6A

### BIOS version

G9CN28WW

### What's wrong?

In a previous version, the "Deactivate GPU" option was available, and I saved a "Quick Action" for it. Now I can't add this action (see image below), while the old one is still runnable.
Maybe the action has been removed from the options, because it is not compatible with my graphics card (AMD Radeon RX 6600M), I don't know. But in that case, I shouldn't be able to run the action.
PS: I don't know how to test the efficiency of this action just to know if it is compatible. All I know is that I don't get any error messages at execution.

![image](https://user-images.githubusercontent.com/54369031/202904826-43d36990-dd20-4a63-bc15-bcb7adb049cd.png)

### How to reproduce the bug?

1. Create a quick action for deactivating the GPU with an old release of the toolkit
2. Get the last version of the toolkit
3. The action is still available, while you can't create a new one doing the same action.

### What is the behavior that you expected?

I think saved Quick Actions are not checked for compatibility when the toolkit version is upgraded.

### Logs

[log_2022_11_20_13_50_07.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10049806/log_2022_11_20_13_50_07.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
I think that it was actually a bug that you saw it before. Deactivate GPU requires NVAPI so if you have a Radeon card you shouldn’t see it.

Not sure why you did, but I am happy you don’t anymore 😎
