### ISSUE TITLE
[BUG]: Balance Mode AI Cycling Issue

### ISSUE THREAD

**Issue by kaelib12** [BartoszCichecki/LenovoLegionToolkit#403]
### Version

2.6.5

### OS

Windows 11 Home 22H2 22621.819

### Device

Legion 7 16IAX7

### BIOS version

K1CN38WW

### What's wrong?

When using balance mode with AI On, cycling through the power modes (Quiet / Balance / Performance) with the hotkey function (FN+Q) Causes Quiet to show up 2 times in the loop and causes the second quiet in the loop to show a white ring instead on blue. For example, it will go from Quiet -> Balance -> Quiet (White Ring) -> Performance -> Quiet -> etc.

### How to reproduce the bug?

Just cycle the power modes with the hotkey function (FN+Q) while have balance AI turned on. For example, it will go from Quiet -> Balance -> Quiet (White Ring) -> Performance -> Quiet -> etc. It will loop normally once AI is turned off.

### What is the behavior that you expected?

Quiet -> Balance -> Performance -> Quiet -> etc.

### Logs

no logs

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
As stated in the FAQ sections, some BIOS versions have this issue and there is unfortunately no way to fix it.
