### ISSUE TITLE
[FEAT]: Fan control improvements

### ISSUE THREAD

**Issue by demostenescz666** [BartoszCichecki/LenovoLegionToolkit#408]
### Version

2.6.5

### OS

WIndows 11

### Device

L5P 16ARH7H

### Is your feature request related to a problem?

1) Fan control cant go under 1600RPM. Does it have any reason? Underclocked CPU in hybrid mode can easily have MUCH less and thus can be totally silent.
2) Why is fan control only in custom mode? Wouldnt make more sense to have separate fan profile for each power mode, or at least have it independent on power modes?

Thanks.

### How would you like the problem to be solved?

1) Fan control can go lower than 1600RPM (like lenovofancontrol does).
2) Separate fan profile for each power mode

### What alternatives have you considered?

So far I am using lenovofancontrol. It works, It can do 1)+2), but it throws exceptions from time to time.

**Comment by BartoszCichecki** [comment]
LLT uses APIs that Lenovo exposed, instead of writing directly to EC like LFC. 

So answer to both your questions is: because that's how Lenovo designed it.

**Comment by demostenescz666** [comment]
Pitty. This mean I have to find out tool, which can control Fans and not throwing exceptions. Because currently I dont see any other way, how to make NB silent (when web browsing...), 1600rpm is overkill for underclocked CPU.

**Comment by BartoszCichecki** [comment]
I am afraid you are out of luck. LFC is no longer maintained and it also opens up quite some security vulnerability. Lenovo provided methods are not actually adjusting fan speed in RPM, but rather work based on predefined fan speed table - that's why adjusting the speed is in steps in LLT. No other tool is available atm.

**Comment by demostenescz666** [comment]
Thats bad news. Obviously wanting notebook to be silent when not under load is too big requirment. Pitty is, that LFC works, my notebook is silent, everything works great. It only throws exception I cant close, or it shut downs the LFC.
