### ISSUE TITLE
[FEAT]: option to end a program in step options

### ISSUE THREAD

**Issue by matias1233218** [BartoszCichecki/LenovoLegionToolkit#409]
### Version

2.6.5

### OS

Windows 10 21H2 build 19044.2006

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

no

### How would you like the problem to be solved?

add the option to end tasks or programs to the step options. 

![image](https://user-images.githubusercontent.com/107080783/203871992-f51bf63c-0cc9-485c-aa6f-5008a8414002.png)

### What alternatives have you considered?

An alternative would be to create a script for it, but it would also mean configuring it again for each program you want to end.

**Comment by BartoszCichecki** [comment]
You don't need a script. Use a Run step and in executable path put `taskkill` and in arguments for example `/im notepad.exe`, there you go, problem solved.

![image](https://user-images.githubusercontent.com/7916915/203872918-c515eae8-8850-49c4-a881-fa7fea5a64e3.png)

The Run step was in fact designed and made for running scripts, because it gives most flexibility for users and least amount of work for me.

**Comment by matias1233218** [comment]
ooooh tanks im not think on that :S

So, in the agruments I put the path of the program? or just /im "task name"

**Comment by BartoszCichecki** [comment]
`taskkill` is just a small program built into Windows: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/taskkill

`/im` option expects process name.

**Comment by matias1233218** [comment]
![image](https://user-images.githubusercontent.com/107080783/203874776-2da1b06c-e8f3-411a-a524-43dd6abc0468.png)
![image](https://user-images.githubusercontent.com/107080783/203874798-5c7c9799-1b48-40a2-9e69-e5fa7f30dd72.png)
I think I did something wrong or I found a bug, when I save the script with the name of the program that I want to finish, it says that it was saved correctly, but it doesn't work and it stays with the option to save, as if it hadn't done it

**Comment by matias1233218** [comment]
I deleted it and reconfigured everything, and now it works, but the save/revert option still appears after saving, I think it's a bug
