### ISSUE TITLE
[BUG]: Device panel unclosable on smaller monitor

### ISSUE THREAD

**Issue by Eiim** [BartoszCichecki/LenovoLegionToolkit#410]
### Version

2.6.5

### OS

Windows 10 Pro 21H2 19044.2251

### Device

Legion 5 Pro 16ITH6

### BIOS version

H1CN47WW

### What's wrong?

When opening the "About your device" panel on an external 1080p monitor, it's too tall and the close box is unreachable. Since the window can't be moved or closed you have to force-close the app and restart it.

### How to reproduce the bug?

1. Open Lenovo Legion Toolkit on a 1080p monitor (it may matter that the main monitor is 2560x1600).
2. Click on the model name in the top right to open the device panel.

### What is the behavior that you expected?

The window would scale itself to the screen and allow for scrolling, rather than extend outside the limits of the screen.

### Logs

[log_2022_11_25_15_39_48.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10093939/log_2022_11_25_15_39_48.txt)
 

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

![image](https://user-images.githubusercontent.com/24627058/204016929-9ff8824c-038c-46c4-b422-b747e05fe8cb.png)

**Comment by BartoszCichecki** [comment]
I can see that not only you have a 1080p monitor but you also have 150% scaling set in Windows. That's w pretty extereme case, but yes it shouldn't happen.

**Comment by Eiim** [comment]
I believe 150% is only on my main monitor, not the 1080p one. Not sure if LLT is taking the scaling from my main monitor to my secondary? I did think the main window seemed a bit large, but I'm not sure.
