### ISSUE TITLE
[BUG]: 安装其他软件后托盘图标会规律的隐藏

### ISSUE THREAD

**Issue by sudikezhene** [BartoszCichecki/LenovoLegionToolkit#415]
### Version

2.6.5

### OS

win11 22H2

### Device

Y9000K

### BIOS version

H1CN49WW

### What's wrong?

已经反复出现好多次了，我喜欢将所有的托盘图标不隐藏，安装其它软件后，好多软件都会，LLT的托盘图标会不规律的自动隐藏，其它软件的图标都不会。

### How to reproduce the bug?

不知道

### What is the behavior that you expected?

不知道

### Logs

以前出现的 你看看有没有吧

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
I don't speak Chinese. Issues should be created only in English.
