### ISSUE TITLE
[BUG]: Driver installers downloaded from packages section give error at launch

### ISSUE THREAD

**Issue by calin-semeniuc** [BartoszCichecki/LenovoLegionToolkit#416]
### Version

2.7.0

### OS

Windows 10 22H2

### Device

Legion 5 15ACH6H

### BIOS version

GKCN57WW

### What's wrong?

When I launch the installer that I downloaded from the "Packages" menu, it throws the error "Windows cannot access the specified device, path or file". You may not have the appropiate permissions to access them.

I tried to see the permissions of the executable. I noticed something funky there. It throwed me an error related to executable permission order. Also it kind of began hanging when checking the permissions, even with a "Not responding" warning.

### How to reproduce the bug?

1. Go to packages.
2. Get the list of drivers.
3. Download it. (For some strange reason, default is in C:\Users\Default\Downloads)
4. Launch the executable that you downloaded

### What is the behavior that you expected?

To launch the installer without errors.

### Logs

[log_2022_11_28_00_45_13.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10099603/log_2022_11_28_00_45_13.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

![explorer_TqP1mr53v0](https://user-images.githubusercontent.com/93979214/204170481-625148bf-6a45-410b-9ce1-0d87d77811c4.png)
![explorer_Zv4s16Wc9W](https://user-images.githubusercontent.com/93979214/204170485-4ef63f8d-483a-4baf-b886-40fa31328924.png)
![explorer_eEu1YC938X](https://user-images.githubusercontent.com/93979214/204170509-ba8a2192-d066-466b-9138-d12a44ee5306.png)
![explorer_Cxpoe8Dpfc](https://user-image

**Comment by BartoszCichecki** [comment]
Sorry but I am not responsible for any installers downloaded via LLT.
