### ISSUE TITLE
[FEAT]: microphone mute and unmute

### ISSUE THREAD

**Issue by 4D374D44** [BartoszCichecki/LenovoLegionToolkit#417]
### Version

2.7.0

### OS

Windows 11 Home 21H2

### Device

Legion 5 15ACH6A

### Is your feature request related to a problem?

I can't find a microphone mute and unmute option in LLT

### How would you like the problem to be solved?

Add a button to mute and unmute the microphone 

### What alternatives have you considered?

Vantage?

### Additional information

I know it's available in Nahimic, I would like it to be in LLT too

**Comment by BartoszCichecki** [comment]
Mute/unmute can be done with Fn+F4. Do you think a specific UI toggle is needed?

**Comment by 4D374D44** [comment]
Yes, my friend and I who both are going to use this software want a UI toggle for it, because toggling the mic using software through teamviewer remotely is one of the things that we need to do often and it's only available in Vantage afaik

**Comment by 4D374D44** [comment]
Clarification I know it's available in Nahimic but my friend doesn't have Nahimic thus the only place to toggle it by software is only Vantage
