### ISSUE TITLE
[BUG]: App asks for Admin perms even if it is running

### ISSUE THREAD

**Issue by decipher3114** [BartoszCichecki/LenovoLegionToolkit#421]
### Version

2.7.0

### OS

Windows 11 22H2

### Device

Ideapad Gaming 3

### BIOS version

EGCN39WW

### What's wrong?

The app is running and is in the taskbar. If I launch it from the taskbar, it is fine.
But if I launch it from start menu, it asks for admin permissions again.

### How to reproduce the bug?

1. Open Toolkit and keep it running.
2. Allow it to stay in taskbar and close the window.
3. Then, open it from Startmenu.
4. It will ask admin permissions and relaunch.

### What is the behavior that you expected?

It should open that same instance currently running, instead of this new version.

### Logs

Can't log. Since I tried both ways and I didn't got the logs.

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Of course it's asking for for permissions. If it's running and you click on taskbar, you open the currently running one. And if you click open it from start menu then you are launching it again. So it's asking for permissions.

**Comment by decipher3114** [comment]
But Instead, it should open the already running instance.

**Comment by BartoszCichecki** [comment]
It is opening an already running instance. You are starting instance A, you need to accept UAC prompt. When you try to start a new one - like when you click on the shortcut or exe or start menu, instance B has to start (because that's how windows works), it checks for other instances, finds instance A, brings it to the foreground and closes itself.

**Comment by BartoszCichecki** [comment]
Ref: https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/3ac95545fe1f4840fe257bf0e28df9f28abacbe2/LenovoLegionToolkit.WPF/App.xaml.cs#L223

**Comment by decipher3114** [comment]
Okay, thanks for clearing this doubt. It is truly amazing, Well done. ❤️❤️
