### ISSUE TITLE
[FEAT]: Separate Caps Lock and Num Lock notification toggle

### ISSUE THREAD

**Issue by rp1231** [BartoszCichecki/LenovoLegionToolkit#422]
### Version

2.7.0

### OS

Win 11

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

I use capslock in combination with other keys as macros.

The caps lock notification shows up even when I use the caps lock as a macro and it gets very annoying.

So I want to  turn off the caps lock notification, but not the numlock notification.

### How would you like the problem to be solved?

Separate Caps Lock and Num Lock notification toggle.

### What alternatives have you considered?

Turning off notifications for both caps lock and num lock.

**Comment by BartoszCichecki** [comment]
I suggest you turn it off if it's annoying.
