### ISSUE TITLE
[FEAT]: Add overclocking

### ISSUE THREAD

**Issue by Scormonth** [BartoszCichecki/LenovoLegionToolkit#427]
### Version

2.7.0

### OS

win10 21H2

### Device

Lenovo Legion R9000P2021H

### Is your feature request related to a problem?

The legion zone comes with the OC overclocking function, which can increase the frequency of the video card by 200MHZ, thus improving the performance

### How would you like the problem to be solved?

I hope the Lenovo LegionToolkit can also join this function

### What alternatives have you considered?

I don't know

**Comment by BartoszCichecki** [comment]
Duplicate of #216.
