### ISSUE TITLE
Activate / deactivate the availability of the option "Tools-> Lenovo Vantage" depending on the situation

### ISSUE THREAD

**Issue by ateplih** [BartoszCichecki/LenovoLegionToolkit#43]
Activate / deactivate the availability of the option "Tools-> Lenovo Vantage" -> [Enable | Disable] depending on the situation with Vantage: [Running | Disabled | Not installed]

**Comment by BartoszCichecki** [comment]
Done in: https://github.com/BartoszCichecki/LenovoLegionToolkit/commit/e415b4978690fff0ce19c2320c89194ada40b5e3

**Comment by ateplih** [comment]
👍

**Comment by fan-73** [comment]
Its me again. Little idea for a future release:
Remove the ability to activate the already activated menu item "Lenovo Vantage". 
In the current version, for example, I can disabled Vantage many times, although this does not make sense.
