### ISSUE TITLE
Camera banning and using

### ISSUE THREAD

**Issue by YuhuiHuang2021** [BartoszCichecki/LenovoLegionToolkit#434]
### Version

2.7.0

### OS

Windows 10 21H2

### Device

Legion Y7000P 2019

### Is your feature request related to a problem?

It seems that LLT does not offers an option about banning and using the Camera, which the original hotkey "Fn + F10" offers.

### How would you like the problem to be solved?

A new option about banning and using the Camera would be appreciated.

### What alternatives have you considered?

No idea yet...

**Comment by BartoszCichecki** [comment]
Hey, you have a 2019 device. Devices from before 2020 are only partially supported, that means "whatever works, works", but no effort is put into making the support better. Therefore, I will close this ticket as not planned.
