### ISSUE TITLE
[FEAT]: Add OSD for CapsLock and NumLock

### ISSUE THREAD

**Issue by decipher3114** [BartoszCichecki/LenovoLegionToolkit#435]
### Version

2.7.0

### OS

Windows 11 22H2

### Device

Ideapad Gaming 3

### Is your feature request related to a problem?

Nope.

### How would you like the problem to be solved?

Null

### What alternatives have you considered?

A toast should be shown on the screen when the caps lock and num lock is toogled.

**Comment by BartoszCichecki** [comment]
Notification like this are already added. You can turn them on in Settings.

Duplicated of: #328
