### ISSUE TITLE
[FEAT]: Add nvidia advanced optimus option.

### ISSUE THREAD

**Issue by KarlLee830** [BartoszCichecki/LenovoLegionToolkit#437]
### Version

2.7.0

### OS

Windows 11 22H2

### Device

Legion S7

### Is your feature request related to a problem?

Nvidia's tray icon often has crashes, and changing the mode of nvidia advanced optimus at this point will become very painful.

### How would you like the problem to be solved?

I wish LLT would have built in the option to switch nvidia advanced optimus mode.

### What alternatives have you considered?

Tried to update the Nvidia related software, but the tray icon crash happens from time to time.

**Comment by BartoszCichecki** [comment]
I get the point, but nVidia didn't expose any API for 3rd party apps for Advanced Optimus settings. So, it's not doable AFAIK.
