### ISSUE TITLE
[BUG]: GPU power limits are corrupted after switching to "Custom" Power Mode

### ISSUE THREAD

**Issue by ikrasnopeev** [BartoszCichecki/LenovoLegionToolkit#438]
### Version

2.7.0

### OS

Windows 11 22H2

### Device

Legion S7 15ACH6

### BIOS version

HACN35WW

### What's wrong?

GPU power limits are corrupted after switching to "Custom" Power Mode

### How to reproduce the bug?

0. Restart 
1. W/o starting LLT set "Performance" mode via Fn-Q
2. Run 3D application with NVidia overlay enabled
3. Check power limit is 100W
4. Run LLT
5. Switch to Custom mode
6. Run 3D application with NVidia overlay enabled
7. Check power limit is reduced to 80W
8. Switch to Performance mode (doesn't matter if via Fn-Q or from LLT)
9. Run 3D application with NVidia overlay enabled
10. Check power limit is now 90W

### What is the behavior that you expected?

1. Expect GPU power limit is restored to 100W on step 10
2. Expect to be able to configure power limit to 100W for "Custom" power mode

### Logs

N/A

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by ikrasnopeev** [comment]
Hi @BartoszCichecki,

I also tried to figure out how can I set fan to max speed while in Performance mode from PowerShell. 
Checked your code and discovered you are using WMI to do this. Tried a couple of method. Like this:

Invoke-WmiMethod -Namespace "root\WMI" -Class "LENOVO_FAN_METHOD" -Name "Fan_Set_MaxSpeed" -ArgumentList $true

or this:

$class = "LENOVO_FAN_METHOD"
$method = "Fan_Set_FullSpeed"
$mc = [wmiclass]"root\WMI:$class"
$inparams = $mc.PSBase.GetMethodParameters($method)
$inparams.Status = $true

$result = $mc.PSBase.InvokeMethod($method,$inparams,$null)


But keep getting "Invalid method Parameter(s)" error.
At the same time when I type:

$inparams

I see it contains "Status" property.

Am I missing something?

Thank you!

**Comment by ikrasnopeev** [comment]
I finally managed to figure out how to run WMIs from PS. And it seems it is not LLT's but firmware's problem.

Following commands produce same 80/90W limit as described in steps:

$lgzd = gwmi -Class "LENOVO_GAMEZONE_DATA" -Namespace "root\WMI"
$lgzd.SetSmartFanMode(255)
$lgzd.SetSmartFanMode(3)

Any ideas to address this?

**Comment by BartoszCichecki** [comment]
Hey, it indeed is a firmware issue. Usually what would help is to cycle power modes with Fn+Q.
