### ISSUE TITLE
[COMPATIBILITY]: Legion 5 17ACH6H自定义风扇控制

### ISSUE THREAD

**Issue by Ytimes2** [BartoszCichecki/LenovoLegionToolkit#439]
### Version

2.7.0

### OS

Windows 11 22H2 Build 22621.819

### Device

Legion 5 17ACH6H

### BIOS version

GKCN54WW

### Which features of the application did you test?

Legion 5 17ACH6H没有风扇控制的选项，希望可以兼容！

### Which features of the application do not work as expected?

Legion 5 17ACH6H没有风扇控制的选项，希望可以兼容！

**Comment by BartoszCichecki** [comment]
#440
