### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by DocDDD** [BartoszCichecki/LenovoLegionToolkit#44]
I tried to make a variant of the icon for your program. Because your program is connected with power supply profiles, and all that is connected with electricity, I decided to beat the theme of electric lightning. Well, the first two letters of the LT program.
[https://ibb.co/DCYmX91](url)
Here you can take a ready-made version with different resolutions (16x16,  24x24, 32x32, 64x64, 128x128) [https://disk.yandex.ru/d/5mRVv3R4sqIAHw](url)

**Comment by BartoszCichecki** [comment]
Nice! Thanks for the work :)

**Comment by DocDDD** [comment]
We help in any way we can. Thank you very much for your work!

**Comment by DocDDD** [comment]
Added more missing icon permissions: 256x256, 48x48
[https://disk.yandex.ru/d/W2OF4ebH_IY5IQ](url)

**Comment by DocDDD** [comment]
If someone needs an icon in vector form.
[https://disk.yandex.ru/d/T7L91QBsO08YOg](url)
