### ISSUE TITLE
[BUG]: Toolkit starts, but only shows a 'shadow overlay'

### ISSUE THREAD

**Issue by Trid3c** [BartoszCichecki/LenovoLegionToolkit#441]
### Version

2.7

### OS

Windows 11 Pro 21996.1

### Device

Legion 7  16IAX7

### BIOS version

K1CN38WW

### What's wrong?

I've installed the program on a fresh windows install. When I open the application I see a shadow overlay in the center of the screen and that's all. If I hover over the application in the taskbar I  see a preview of the application running, but on screen I can only see a small shadow overlay.

### How to reproduce the bug?

Open the application.

### What is the behavior that you expected?

View the application as normal.

### Logs

I can't collect log's because I can't get in the application.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Link to a screenshot of the 'shadow overlay'. 
https://ibb.co/GVLbr04

**Comment by Trid3c** [comment]
Thanks BartoszCichecki,

I've updated everything and reinstalled all the graphics drivers, but I'm still stuck with the issue. I must be missing something. The strange thing it I can access certain options when I click on the overlay, like the power modes. I must be missing something

**Comment by BartoszCichecki** [comment]
I will close the issue for now, since there isn't anything I can do.
