### ISSUE TITLE
[FEAT]: Highlighting packages that have appeared since the last check

### ISSUE THREAD

**Issue by DmShAl** [BartoszCichecki/LenovoLegionToolkit#445]
### Version

2.7.0

### OS

Windows 11 Pro 22H2 build 22621.900

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

Thanks a lot for such a great product!
It would be great if you could highlight the packages that have appeared since the last refresh. 
Something like this :
<img width="789" alt="LLT" src="https://user-images.githubusercontent.com/4715551/206762647-a49b7d65-b7c9-46fe-9d52-217a72871ca1.png">
It seems to be useful, because you can see new packages. Now I'm trying to remember the last package and then check if something new has appeared.

### What alternatives have you considered?

Any solution that shows new packages since last check

**Comment by BartoszCichecki** [comment]
You can right click on the list and select "Hide all", that way when you check for updates you will only see newer packages if there are any available.

Isn't that enough for what you need?

**Comment by BartoszCichecki** [comment]
If that is good enough, then let's keep it as it is. I'd rather spend the time on proper update detection (#367).
