### ISSUE TITLE
[FEAT]: Save an RGB profile as a "template", and able to instantly change an existing RGB profile to a saved one.

### ISSUE THREAD

**Issue by ZZZXXX0110** [BartoszCichecki/LenovoLegionToolkit#448]
### Version

2.7.0

### OS

Windows 11 22H2 build 22621.900

### Device

Legion 7i 16IAX7 (7th gen)

### Is your feature request related to a problem?

No, this is a request for a quality of life enhancement feature.

### How would you like the problem to be solved?

Currently on the 7th gen Legion 7i the keyboard RGB is managed by the firmware, and as such there can only be 6 RGB profiles configured at any time, I doubt this can be expanded easily, However, one thing that might be easy to do is to have the RGB setting of any profile saved into LTT instead of into the keyboard firmware, as sort of a "template", and have LTT able to instantly overwrite all the RGB setting in one of the 6 existing profiles on the keyboard. This way it would allow users to be able to create and (importantly) store an infinite amount of additional "profiles", and able to apply any of them onto one of the 6 profile slots on the keyboard very easily at any time, without having to worry about trying to overcome the 6 profile limit that might be hard-coded in the firmware. This could also be implemented with a feature that would allow users to export and import the RGB profiles, to share their creative designs with friends and foes alike.

### What alternatives have you considered?

This proposed feature is already an alternative to a potentially more difficult task of trying to figure out how to store more than 6 RGB profiles into the keyboard, which might be impossible if the number of profiles is indeed hard-coded in the keyboard firmware.

**Comment by BartoszCichecki** [comment]
Would simply exporting a profile to a file work for you? As in being able to export/import a single profile.

**Comment by BartoszCichecki** [comment]
Great I understood that you might want to export all 6 profiles at once.

PS: 6 is the limit, the controller only has 6 slots for profiles.

**Comment by ZZZXXX0110** [comment]
> Great I understood that you might want to export all 6 profiles at once.
> 
> PS: 6 is the limit, the controller only has 6 slots for profiles.

Yeah, even though the controller only has 6 slots, if we can export/import each individual profile in each individual slot, then we can in practice be able to store and switch between infinitely many different RGB schemes at will! :D
