### ISSUE TITLE
[BUG]: Fan profile at custom mode reset to no fans at all

### ISSUE THREAD

**Issue by enoversum** [BartoszCichecki/LenovoLegionToolkit#449]
### Version

2.7.1 b2

### OS

Windows 11 22623.1028

### Device

Legion 7i Gen 7 (12900HX, 3080Ti)

### BIOS version

K1CN38WW

### What's wrong?

I'm honestly not sure when this happened, but I have two installations on my machine, and Custom Mode had an a) untouched and b) slightly modified fan curve on my installations. Hadn't really tried it out lately, but realised, after my laptop ran dangerously hot, that no fans were running. At some point, an update must have reset the fan curve for Custom Mode. Sure as hell I did not reset it to never run the fans.

### How to reproduce the bug?

1. Not sure, but install the latest update.
2. Switch to Custom Mode in LLT.
3. Open settings and see fan curve being reset to zero.

### What is the behavior that you expected?

Former default or modified fan curve stays intact.

### Logs

No logs needed I assume?

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
What do you mean by two installations? Also what do you mean that fan curve resets to zero? The fan control that LLT provides is based on a fan speed table that is baked into the firmware of the laptop - that curve doesn't even allow to stop the fans completely, so I suspect something might be wrong either with the firmware you have or the BIOS, because my L7 on K1CN31WW does not have any issues.

**Comment by enoversum** [comment]
Okay, I should have made it clearer, sorry for the obvious confusion. 

1) I have a dual-boot installation with two differently configured Windows 11 installations, hence using two installations instead of two users on one machine.

2) On both I have LLT installed, and had a seemingly 'normal' fan curve in Custom mode (rising from A to B) as default when I took a look after installing LLT a few weeks back. I slightly changed it to lower fan noise on one of the installations, but both were the typical rising 'curve' from left to right. This goes to show that I am _certain_ I didn't reset it to a flat line at the lowest possible fan speed for all temperatures.

3) When I used Custom mode again today, for the first time in weeks, the fans were indeed set to the _lowest value_ in Custom mode. That might not be zero fan action, but at least it made the laptop go really hot, and the fans spin only inaudible (hence my 'no fans at all' expression). No harm done, because I was around and realised the temperature of the laptop, but it took me a while to do so, and I'm glad I didn't let it install stuff on its own. 

Judging by your surprise, you have no idea what's causing this? Maybe it has something to do with my more current BIOS version?

**Comment by BartoszCichecki** [comment]
There are some weird things happening sometimes with Lenovo firmware but this is the first time I hear about this.

If you are in the Legion Series discord server you can try asking if someone noticed something similar.

Did it happen once or can you reproduce it more regularly?

**Comment by enoversum** [comment]
I could certainly try asking there, just thought, before someone trashed his laptop this way, I'd better report it here directly.
I'll have to see if it is reproducible. After I set a healthy curve again and switched through modes, Custom mode behaved normally. Will have to see what happens after more restarts or updates of LLT, but switching installations (= full reboots) so far made the 'healthy' curves stick on both.

**Comment by BartoszCichecki** [comment]
The thing is that LLT applies a curve when you switch to custom mode. The curved is kept in %localappdata%\LenovoLegionToolkit\godmode.json. So if it ever happens again kill LLT from task manager and copy this file somewhere. It will be easy to see the curve there so we will know if it got corrupted in LLT setting or if it was a bug in firmware.

Sorry for poor formatting- replying from my phone.

**Comment by enoversum** [comment]
All well, no worries about formatting! 

I just freshly booted to one of my installations, and voilà, curves reset _again_ to lowest values. So, when should I copy the godmode.json, after I set it (correctly) or when it happens to be reset to zero?

**Comment by enoversum** [comment]
Okay, I could reproduce it easily. I just have to quit LLT and start it again after I set the curves. The godmode.json looks the same in both scenarios, after I set it and when it resets to lowest values, exactly like this: 

`{
  "CPULongTermPowerLimit": {
    "Value": 130,
    "Min": 20,
    "Max": 130,
    "Step": 1
  },
  "CPUShortTermPowerLimit": {
    "Value": 180,
    "Min": 40,
    "Max": 180,
    "Step": 1
  },
  "CPUCrossLoadingPowerLimit": {
    "Value": 30,
    "Min": 20,
    "Max": 60,
    "Step": 1
  },
  "CPUTemperatureLimit": {
    "Value": 97,
    "Min": 85,
    "Max": 100,
    "Step": 1
  },
  "GPUPowerBoost": {
    "Value": 0,
    "Min": 0,
    "Max": 25,
    "Step": 5
  },
  "GPUConfigurableTGP": {
    "Value": 0,
    "Min": 0,
    "Max": 35,
    "Step": 5
  },
  "GPUTemperatureLimit": {
    "Value": 87,
    "Min": 75,
    "Max": 87,
    "Step": 1
  },
  "FanTable": {},
  "FanFullSpeed": false,
  "MaxValueOffset": 0
}`

**Comment by BartoszCichecki** [comment]
OK that looks really weird, the fan table is empty that's why your fans stop after a while, so we will need to do some troubleshooting.

Can you run on power shell this: `(Get-WmiObject -namespace ROOT\WMI -class LENOVO_FAN_TABLE_DATA)` and post the result?

**Comment by enoversum** [comment]
Yes, I can, here is the result.
[fantable.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10235718/fantable.txt)

**Comment by BartoszCichecki** [comment]
OK that looks correct, that's good. Now could you:
1. Open LLT
2. Switch to Custom Mode
3. Open the settings for it
4. Set a fan curve and hit Apply
5. Without doing anything else in LLT copy the `godmode.json` again and share it here.

I am just trying to figure out where should I add some more logging so we can figure out what's going on.

**Comment by enoversum** [comment]
There you go, changed the file type to .txt for Github to let me upload it. 
[godmode.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10235865/godmode.txt)

**Comment by BartoszCichecki** [comment]
OK thanks a lot, I will post a build with some extra logs later today, so that we can figure out where exactly it goes wrong.

**Comment by BartoszCichecki** [comment]
Managed to find and fix the issue, fortunately it was limited to 2.7.1 beta.

**Comment by enoversum** [comment]
Oh, so it was indeed a bug that I found here, nothing stemming from anything weird on my machine 👯 ? So I'm glad I posted it, someone could have had his machine fried like a steak after all.

**Comment by BartoszCichecki** [comment]
Yes, great catch, wasn't easy to find! But fortunately only in beta release :)

**Comment by enoversum** [comment]
Glad I found it, and no-one got hurt :). Thank you for all your hard work put into LLT anyway!
