### ISSUE TITLE
UI Glitches - Resolution/DPI Changes?

### ISSUE THREAD

**Issue by sickypedia** [BartoszCichecki/LenovoLegionToolkit#45]
Hello, I frequently see weird UI issues as shown in the image below. Very frequent when switching monitors and in some cases after resolution changes on the laptop display itself (if and when a game changes it). Not sure if this because of DPI changes or some other runtime limitation. I restart the app when this happens, but it would be great to know what causes it and if the app can redraw/reload UI when this happens, without a restart. Happy to do more testing.

![image](https://user-images.githubusercontent.com/73606172/144384876-8643472c-023b-4b99-9e40-c8cf52aa8eac.png)

**Comment by sickypedia** [comment]
Btw, this happens on clean installs of Win 10 as well as Win 11. Another one:

![image](https://user-images.githubusercontent.com/73606172/144392875-596e58e3-c53c-46ea-910b-8cd235842ff5.png)

**Comment by BartoszCichecki** [comment]
Yeah I am not super proficient with WPF, but I'll see what can be done.

**Comment by sickypedia** [comment]
I compiled the app from source in VS 2022 with one change - removed `ResizeMode="CanMinimize"` from MainWindow.xaml, which allows the app window to be resizable and it can be maximized to allow it to redraw. Tried a bunch of res and DPI changes but haven't seen any black patches on the UI yet. I'm not a dev, so this is me just tinkering :)

**Comment by BartoszCichecki** [comment]
Nice, it seems like a good direction. It also means that I will probably get it fixed together with https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/41, which will most likely be in next release :)

**Comment by sickypedia** [comment]
Awesome, thanks!

**Comment by BartoszCichecki** [comment]
Closing this one. #41 is done, so if this will persist in 1.5, please reopen this issue.

**Comment by sickypedia** [comment]
Still seeing this unfortunately on 1.5.2:

![image](https://user-images.githubusercontent.com/73606172/145011795-ad47681f-f2bc-49d6-be25-01129a5a3a16.png)

**Comment by BartoszCichecki** [comment]
Ouch, can you help with writing some repro steps?
I have two screens: internal 2560x1600 @125% scaling and external 2560x1400 @100% scaling and I have never seen it.

**Comment by sickypedia** [comment]
I have been trying to figure it out but apparently it is random - I have an external monitor - FHD @ 100% scaling and internal is at 150%. Will continue testing and leave an update here if there's a specific sequence.

**Comment by younyokel** [comment]
Same thing.
![image](https://user-images.githubusercontent.com/53343081/153955031-d4a02c50-f4d2-458b-ace5-bd69f6a85541.png)

**Comment by BartoszCichecki** [comment]
Please check if the BETA (#105) has the same issue.
