### ISSUE TITLE
[BUG]: Autorun doesn't work on 2022 Legion 5 15IAH7H

### ISSUE THREAD

**Issue by RNarayan73** [BartoszCichecki/LenovoLegionToolkit#450]
### Version

2.7.0

### OS

Windows 11 22H2 Build 22621.963

### Device

 Legion 5 15IAH7H with i7-12700H and RTX 3070

### BIOS version

J2CN46WW

### What's wrong?

Hello,

1. I have selected "Enabled, delayed" for the Autorun option in Setting, however, LLT doesn't start automatically.
2. Furthermore, when I start LLT manually as a Standard User, it always asks for admin credentials. Is there a way to prevent this?

Note that I have installed LLT in admin mode within the C:\Program Files\ folder rather than the default ~\AppsData\... path proposed during LLT installation so that multiple users can use it without me having to install LLT for each one.

### How to reproduce the bug?

Let me know if you need any more information.

### What is the behavior that you expected?

I expect LLT to start automatically after a delay of starting and expect the logo to appear in the Taskbar without an admin prompt.

### Logs

No log files are generated for this option as it doesn't do anything in the app itself!

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

I had initially disabled Lenovo Vantage through the LLT settings, yet it didn't auto-start. Besides, deactivating Lenovo Vantage meant that I couldn't use a few features like Overclock GPU, Boost Network, Auto Close programs when playing games. While LLT tries to replicate most features of Vantage, there are a number of things in Vantage it doesn't cater for.

So I decided to install LLT side-by-side with Vantage and it works fine. All the Power Modes work fine, the automated Actions and Quick Actions work well too. In fact, I got a bonus Custom Mode that isn't in Vantage. Everything except for the automatic startup.

One more issue that I managed to work around was that the Windows Power Plans aren't automatically activated when I switch Power Modes in LLT. So, I mapped them in the "Settings > Power Plan" to the respective Power Modes and they didn't work initially. I had to switch on the "Always Activate Windows Power Plan" to get it to work. I am not sure if this is how it is intended to work, but can raise another issue if need be.

**Comment by BartoszCichecki** [comment]
I am sorry I can reproduce the issue. Please try to switch it to "Enabled" (not delayed) and see it it runs on startup. "Delayed" option delays startup by around 30 seconds so you need to wait quite a bit for LLT to start. 

Also please check Task Scheduler and see if you can find the autorun task - it's name should start with "LenovoLegionToolkit".

If you have multiple users that might be an issue as currently LLT doesn't work properly in such setup, see #246.

**Comment by RNarayan73** [comment]
Thanks for the tip. 

I tried your suggestion. The autorun task is indeed created in Task Scheduler for the user admin with Administrator rights that I used to install the program.

It's trigger is set to run on "logon of specific user - admin" and it does autorun when admin logs in.
I tried to set the trigger as "logon of any user", but it doesn't run when I log in (as a different standard user)
I also tried to set the trigger as "logon of specific user - <standard user>" but it didn't run when I log in as the standard user.

All the above changes were done in Task Scheduler within the admin login

Is this how it is expected to run?

FWIW, I also tried to create a new task in Task Scheduler within the login for the <standard user> for the program to start as admin when the <standard user> logs in, but I couldn't create it, apparently as admin is not recognised.

Regards
Narayan

**Comment by BartoszCichecki** [comment]
I would disable autorun completely in LLT and then create tasks manually in Task Scheduler. However keep in mind that if user A logs in and runs LLT, and then user B logs in while user A is still logged in, LLT will not start for user B. There can be only one instance of LLT running on a machine.

I don't plan on adding support for multi user setups any time soon and judging by your description this is a cause of the issue you have.


I will add a note to readme that running LLT for multiple users is not something that works well atm.

**Comment by BartoszCichecki** [comment]
Related #246.

**Comment by RNarayan73** [comment]
Thanks for the tip @BartoszCichecki . 

I tried adding a new task in Task Scheduler in Windows 11 and it raises issues with user not having the rights to add a task!
Anyway, I'll try uninstalling and re-installing it to the default installation folder in ~\AppsData\... 
Can you advise where the configuration files containing changes I make in the program are stored?

Thanks
Narayan

**Comment by BartoszCichecki** [comment]
> it raises issues with user not having the rights to add a task

You need the select on the task that it should run with highest privileges.

> where the configuration files containing changes 

`%localappdata%\LenovoLegionToolkit`

**Comment by RNarayan73** [comment]
Hi @BartoszCichecki 

I tried various configurations of user types and realised the following:

1. When run through Task Manager, LLT only auto-starts when users who belong to the Administrators group log in. This requires that field the "When running the task, use the following user account" is set to either an admin user or the group Administrators and the Trigger is set to "At log on of any user". This actually works for multiple users who are Administrators which is in contrast to #246 and the limitation you mention above!
2. It does not auto-start when 'standard users' log in. A standard user needs to manually start the GUI which unfortunately necessitates typing in the admin credentials.
3. One potential way to work around is to set the "Run whether user is logged on or not" option and Trigger "At Startup". This in facts auto-starts LLT as a background process and it seems to be able to run some of the automated Actions, but the GUI doesn't show up after log on. I also don't think it is stable until a user logs on and starts the GUI.

Perhaps LLT can coded to run like a proper service to enable the automated Actions to run? And the GUI can be coded separately to run on log on like Lenovo Vantage?

I hope these observations are useful to you in diagnosing the issue and possibly enhancing the app.

Good work! Keep it up.

Regards
Narayan
