### ISSUE TITLE
[BUG]: Ideapad Gaming 3 15ARH05 Battery conservation mode disappeared after uninstalling OneKeyOptimizer

### ISSUE THREAD

**Issue by tezpadhye** [BartoszCichecki/LenovoLegionToolkit#458]
### Version

2.7.1

### OS

Win10 21H2

### Device

Ideapad Gaming 3 15ARH05

### BIOS version

FCCN16WW

### What's wrong?

I had OKO installed just for battery conservation setting as I didn't want Vantage to keep hogging resources. Upon installing this found out it too had the battery conservation setting so now  when I uninstalled OKO, the setting disappeared from LLT too!

### How to reproduce the bug?

Install OneKeyOptimizer
Enable Battery Conservation
Install LenovoLegionToolkit
>See Battery Conservation setting toggle under power section\
Uninstall OneKeyOptimizer
Restart PC
Battery Conservation Disappears in LenovoLegionToolkit

### What is the behavior that you expected?

I didn't expect a setting to disappear after uninstalling OKO

### Logs

no logs

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Logs?

**Comment by BartoszCichecki** [comment]
Also even if you don't provide logs. If the setting disappeared then LLT can't talk to the energy driver. Whether you have some apps from Lenovo installed or not is a different story. Make sure you have the driver and setting will be visible.
