### ISSUE TITLE
[FEAT]: Fan control on Legion slim 7 2022 AMD version?

### ISSUE THREAD

**Issue by aaamitster1** [BartoszCichecki/LenovoLegionToolkit#459]
### Version

2.7.1

### OS

Windows 11

### Device

Legion S7 16ARHA7, 82UG

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

It would be nice to have fan control on the 2022 AMD Slim 7 version too.
Model:             Legion S7 16ARHA7
Machine type:  82UG
BIOS:                KFCN32WW

Willing to test and troubleshoot, if that helps.

### What alternatives have you considered?

There is no hardware monitoring software out there that even shows me my fan speed let alone give me any control over it.

### Additional information

Thank you for all the hard work. It's a great piece of software.

**Comment by BartoszCichecki** [comment]
Hey, here is a build that has custom mode enabled for your BIOS version. Please do the testing if custom mode works properly and report back.

[LenovoLegionToolkitSetup_kfcn.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10324536/LenovoLegionToolkitSetup_kfcn.zip)

**Comment by aaamitster1** [comment]
> Hey, here is a build that has custom mode enabled for your BIOS version. Please do the testing if custom mode works properly and report back.
> 
> [LenovoLegionToolkitSetup_kfcn.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10324536/LenovoLegionToolkitSetup_kfcn.zip)

Hey, The custom mode works exactly as expected. I set a 95C temp limit for CPU and it didn't exceed that when running a benchmark. I also set the fans to be around 1700 RPM till CPU reaches 65C and i think it followed that well too but it doesn't show the current fan speed and no way to set the fan to zero. Is either of the feature possible? - Thanks

**Comment by BartoszCichecki** [comment]
Great. All seems to be working fine then. Settings fans to zero is not possible.

You can use this build above until next version is released.
