### ISSUE TITLE
[FEAT]: Keyboard backlight steps number

### ISSUE THREAD

**Issue by DmShAl** [BartoszCichecki/LenovoLegionToolkit#460]
### Version

2.7.1

### OS

Windows 11 Pro 22H2 build 22621.963

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

Toolkit has 10 keyboard backlight steps (0,1,2 ... 9), but using Fn + Arrow you can only change keyboard backlight like 0, 3, 6, 9. It there any possibility to increase number of steps for Fn + Arrow?

### How would you like the problem to be solved?

Increasing number of steps to 10

### What alternatives have you considered?

Switch: 3 steps / 9 steps

**Comment by BartoszCichecki** [comment]
Not possible unfortunately.
