### ISSUE TITLE
[BUG]: Dashboard Power Mode and Actions Work in a Counterintuitive Way

### ISSUE THREAD

**Issue by boiled-water-tsar** [BartoszCichecki/LenovoLegionToolkit#461]
### Version

2.7.1

### OS

Windows 11 Home 22H2 build 22621.963

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN49WW

### What's wrong?

On reboot when plugged into power the Power Mode setting set in the Dashboard will be overridden by the default Action "When AC power adapter is connected". This makes the out of the box experience counter-intuitive as it makes it appear that the Dashboard settings do not persist through reboot.

### How to reproduce the bug?

1. Have laptop plugged into power
2. Set power mode to anything but "Balanced"
3. Reboot
4. Notice your settings have been overridden by an action

### What is the behavior that you expected?

I would expect settings set in Dashboard to stick by default. This could be accomplished by having actions disabled by default.

### Logs

N/A

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Suppose this is not really a bug, but also not really a feature.

**Comment by BartoszCichecki** [comment]
Yes, exactly this is by design. When LLT starts it will run AC adapter connected/disconnected actions if they are enabled. It has been like this since Actions were added back in the summer.
