### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by sudikezhene** [BartoszCichecki/LenovoLegionToolkit#463]
### Version

2.7.1

### OS

win11 22H2

### Device

Y9000K2021h

### BIOS version

H1CN49WW

### What's wrong?

LLT托盘图标经常会自己隐藏掉，其它程序都正常。好多情况下都会，其中很容易复现的一种情况改变分辨率，托盘图标也会自己隐藏

### How to reproduce the bug?

改变分辨率

### What is the behavior that you expected?

希望能修改掉

### Logs

有录屏文件怎么发给你

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please post issues in English.
