### ISSUE TITLE
[BUG]: Legion S7 fan control not functional

### ISSUE THREAD

**Issue by sprucejuice** [BartoszCichecki/LenovoLegionToolkit#465]
### Version

2.7.1

### OS

Windows 11 Home 22H2 build 22621.963

### Device

Legion S7 16IAH7

### BIOS version

JYCN48WW

### What's wrong?

Fan control not working for sliders in custom profile.

Tried all at max, all at min and inceasing gradient. All non-responsive.

Assuming it can be fixed,  would a 0% fan speed be possible for the lower temps.

Max fan toggle works.

### How to reproduce the bug?

adjusting fan control sliders in custom profile

### What is the behavior that you expected?

I would expect fans to adjust to 

### Logs

.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

I have the toolkit set to autorun, with vantage disabled as per the settings toggles. I've undertaken a clean isntall, but am getting the same results.

**Comment by BartoszCichecki** [comment]
I have reports that Fan Control works properly on this BIOS version. I suggest you try with Legion Zone: https://legionzone.lenovo.com/

I suspect that if it doesn't work in LLT it also won't work in LZ, which would indicate some issue in your BIOS version or your machine specifically.

Here is a zip file with screenshots to help you navigate LZ (it's chinese only): [lz_fan_curve.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10351890/lz_fan_curve.zip)

Let me know the results.

**Comment by cfvescovo** [comment]
I have a Legion S7i (16IAH7) and LLT works on my machine. When in custom mode I can change the fan curve and my fans change speed accordingly. My only concern is that I cannot set 0 rpm as the minimum speed for any point in the fan curve is 2100 rpm. Is this limitation intended behavior?

**Comment by mind12** [comment]
> I have a Legion S7i (16IAH7) and LLT works on my machine. When in custom mode I can change the fan curve and my fans change speed accordingly. My only concern is that I cannot set 0 rpm since the minimum speed for any point in the fan curve is 2100 rpm. Is this limitation intended behavior?

It's a limitation of BIOS, 0 is not possible. 
There is an advanced setting in bios where you can lower it to 1600rpm if I remember correctly. Check it out.

**Comment by cfvescovo** [comment]
I tried that but the minimum is still 2100 rpm, even if Level 3 (1600) is selected in the BIOS

**Comment by mind12** [comment]
> I tried that but the minimum is still 2100 rpm, even if Level 3 (1600) is selected in the BIOS

Yeah I must have forgotten that, had tested it month ago. 1600 is working outside custom mode afaik.
@BartoszCichecki why isnt it applying to custom mode?

**Comment by BartoszCichecki** [comment]
@mind12 no clue, but the fan table seems to be hardcoded so it's not very surprising that it doesn't change.

**Comment by sprucejuice** [comment]
> I have reports that Fan Control works properly on this BIOS version. I suggest you try with Legion Zone: https://legionzone.lenovo.com/
> 
> I suspect that if it doesn't work in LLT it also won't work in LZ, which would indicate some issue in your BIOS version or your machine specifically.
> 
> Here is a zip file with screenshots to help you navigate LZ (it's chinese only): [lz_fan_curve.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10351890/lz_fan_curve.zip)
> 
> Let me know the results.

Hey, 
I'd tried LZ too, but again the sliders have no impact. When I enter the custom profile the fans start spinning up, but they stay static. I don't know what speed. 

Is it possible that it's just my laptop that doesn't respond? Might need to RMA it. ☹️

**Comment by BartoszCichecki** [comment]
It looks like an issue with your laptop not sure what can be done here. @mind12 any ideas?

**Comment by sprucejuice** [comment]
> > It looks like an issue with your laptop not sure what can be done here. @mind12 any ideas?
> 
> I would try an EC reset and/or bios reflash. After that contact Lenovo.

I've tried the EC reset. I'll try to relash the BIOS and see where we land. 
Thanks for trying guys. Good work, despite my shonky laptop not playing nice :)

**Comment by sprucejuice** [comment]
> > > It looks like an issue with your laptop not sure what can be done here. @mind12 any ideas?
> > 
> > 
> > I would try an EC reset and/or bios reflash. After that contact Lenovo.
> 
> I've tried the EC reset. I'll try to relash the BIOS and see where we land. Thanks for trying guys. Good work, despite my shonky laptop not playing nice :)

Well, something worked (BIOS reset another EC reset???). Either way, it seems to be functioning now.  Thanks for you help guys!

One more thing, is there a cheat sheet that suggests where the custom sliders for CPU/GPU would be for the each of the non custom profiles?

![image](https://user-images.githubusercontent.com/121689755/211105528-fa6c3fe0-1244-4c27-9cb8-6149f8eb3a70.png)

I'm trying to see how I can tweak things to keep temps down given I can't undervolt.

Cheers.

**Comment by mind12** [comment]
> > > > It looks like an issue with your laptop not sure what can be done here. @mind12 any ideas?
> > > 
> > > 
> > > I would try an EC reset and/or bios reflash. After that contact Lenovo.
> > 
> > 
> > I've tried the EC reset. I'll try to relash the BIOS and see where we land. Thanks for trying guys. Good work, despite my shonky laptop not playing nice :)
> 
> Well, something worked (BIOS reset another EC reset???). Either way, it seems to be functioning now. Thanks for you help guys!
> 
> One more thing, is there a cheat sheet that suggests where the custom sliders for CPU/GPU would be for the each of the non custom profiles?
> 
> ![image](https://user-images.githubusercontent.com/121689755/211105528-fa6c3fe0-1244-4c27-9cb8-6149f8eb3a70.png)
> 
> I'm trying to see how I can tweak things to keep temps down given I can't undervolt.
> 
> Cheers.

Idk the exact values for every mode for your device but you can check them this way:
- CPU: Change to a power mode, run hwinfo, main windows, central processor: CPU PL1 PL2
- GPU: You can run any benchmark to test the power levels like heaven and check the usage with hwinfo
