### ISSUE TITLE
[FEAT]: Add a command-line tool

### ISSUE THREAD

**Issue by DarylCantrell** [BartoszCichecki/LenovoLegionToolkit#466]
### Version

2.7.1

### OS

Windows 11 / 64-bit / current

### Device

Legion 5i Pro

### Is your feature request related to a problem?

- Currently the product doesn't have a usage story for non-admin users. For example, a family laptop with accounts for a parent (admin) and children (non-admin).

- The process is run when a user logs in, which means none of the configurations are in place until login. Even if you start it minimized, the process runs in the system tray.

### How would you like the problem to be solved?

Add a command-line tool. Ideally this would be placed in a non-user-specific folder like `%ProgramFiles%`.

The tool doesn't need any user interface; it could work purely based on a configuration file. That way an admin could set up a scheduled task which runs at machine startup. The task would turn on battery conservation, choose new keyboard colors, etc.

Since it's being run by the system these settings would apply for all users, or even when no user is logged in.

The usage pattern could be as simple as:

```
"%ProgramFiles%\Legion Toolkit\Apply-Config" my_global_config.json
```

### What alternatives have you considered?

I don't think there's any way to apply configuration options globally using a UI. There's nowhere to put the UI.

Glancing at the code, it appears the UI and the Legion-specific library are fairly separate, so running this headless should not be too hard.

**Comment by BartoszCichecki** [comment]
LLT is not able to work without admin rights that is true, but to function properly it also needs to run in background to change power profiles after Fn+Q or support Hybrid mode on gen 7 devices, or even handle 4-zone RGB keyboard.

Placing anything in Program Files will not fix any issues now. The only way out of this is to introduce a Windows service that will run as System and be available to all users. That is however a big rework of the architecture, so I am not sure when will I have time to do it.

There is already a similar issue reported: #246
