### ISSUE TITLE
[BUG]: FN-Q not selecting custom mode

### ISSUE THREAD

**Issue by Rinzler081** [BartoszCichecki/LenovoLegionToolkit#467]
### Version

2.7.1

### OS

Windows 11 22H2

### Device

Legion 7I 2022

### BIOS version

K1CN38WW

### What's wrong?

Functino-q isn't switching to custom mode

### How to reproduce the bug?

function-q until you select custom mode

### What is the behavior that you expected?

custom mode with the purple color around the power button

### Logs

waiting to see if this is a legit bug

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Fn+Q will not switch not Custom mode unfortunately - limitation from Lenovo.
