### ISSUE TITLE
[FEAT]: Add an option to turn screen off

### ISSUE THREAD

**Issue by hacker-hackman** [BartoszCichecki/LenovoLegionToolkit#468]
### Version

2.7.1

### OS

Windows 10 / 64-bit 

### Device

Legion 5

### Is your feature request related to a problem?

I miss a simple feature from Acer laptops – turning screen off by a Fn+F6 shortcut. And while screen is off one can switch it on by touchpad or keyboard but not by mouse drag. This is so handy.

Currently I'm using a workaround script adjusted to the Fn+F9 Smart Key:
```bat
@echo off
set "$mouse_state="

2> nul (set /P $mouse_state= < "%~nx0:mouse_state") || set "$mouse_state=enabled"

echo actual [%$mouse_state%]

if /i "%$mouse_state%"=="enabled" (
    pnputil /disable-device "HID\VID_09DA&PID_000A\8&22CA48BC&0&0000"
    echo disabled>%~nx0:mouse_state
    C:\MyPrograms\NirCmd\nircmd.exe monitor off
    ) else (
    pnputil /enable-device "HID\VID_09DA&PID_000A\8&22CA48BC&0&0000"
    echo enabled>%~nx0:mouse_state
    )
```
It uses the NirCmd program and a built in command "pnputil".

You can notice here that I'm disabling the mouse either. It's because my mouse always wakes up the screen after some time passed. So I have to use the same keyboard shortcut not only for turning the screen off but for turning it back on. And it's an obvious downgrade in comparison with my old Acer laptop.

### How would you like the problem to be solved?

Add a "Screen off" option as a step that can be added to Action or Quick action. And maybe let a user to choose whether to allow to wake up the screen by mouse drag or not.
I'd like to see true display's switching off, not just setting brightness to the minimal level.

**Comment by BartoszCichecki** [comment]
It is rather a niche request, and especially that you have a script working for that already I am not sure if it is needed to add this as a feature. This is exactly the reason why `Run` step is there - so you can extend the functionality to fit your needs.

**Comment by KrisCris** [comment]
I think this is a reasonable request. The current "Turn off displays" feature is quite useless since it can be easily woken up by any keyboard/mouse input - where I could simply close the lid to achieve the same thing.

In my opinion, having a specified key for controlling the backlight on/off would be useful especially when you are outside of the home and doing some sort of remote control, or game streaming, when you don't want the display on.

**Comment by BartoszCichecki** [comment]
Lenovo didn't expose a way to turn off display backlight, so what you are asking for isn't possible.
