### ISSUE TITLE
[BUG]: CPU frequecy abnormally restricted when booting with Custom mode

### ISSUE THREAD

**Issue by Ptilopsis01** [BartoszCichecki/LenovoLegionToolkit#469]
### Version

2.7.1

### OS

Win11 22H2 22621.963

### Device

Legion Y9000X IAH7(S7 16IAH7)

### BIOS version

JYCN48WW

### What's wrong?

When I set the performance mode in Custom Mode and reboot the system, the CPU frequecy was abnormally restricted extremely low ( even lower than 1Ghz), which makes the divice lagging severely. 

It was not observed in other performance modes.

### How to reproduce the bug?

1. Set the performance mode in Custom Mode
2. Reboot the system
3. With high probability you will meet the situation

### What is the behavior that you expected?

This kind of problem don't show again.

### Logs

[log_2023_01_04_15_20_00.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10345958/log_2023_01_04_15_20_00.txt)

I've used a boot file from MI, which actually has no effect on LLT

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
There are some BIOS versions that are impacted by this problem. There is nothing I can do to fix it, maybe a BIOS update will resolve it in the future.

**Comment by Ptilopsis01** [comment]
> There are some BIOS versions that are impacted by this problem. There is nothing I can do to fix it, maybe a BIOS update will resolve it in the future.

Got it.
thx a lot
