### ISSUE TITLE
Limitation of running a duplicate utility.

### ISSUE THREAD

**Issue by DocDDD** [BartoszCichecki/LenovoLegionToolkit#47]
Hello. Can I still ask to implement a ban on running a duplicate program? For example, so that when the executable file is restarted, the already active version of the utility pops up from the tray, and a parallel new window does not open?

**Comment by BartoszCichecki** [comment]
Hey that is already implemented since 1.3.

**Comment by BartoszCichecki** [comment]
Ah, but as I see it's broken... Hmm.. Let me take a look.

**Comment by DocDDD** [comment]
https://postimg.cc/TLgVb34N

**Comment by BartoszCichecki** [comment]
Good catch! I broke it and I don't even know when :D

**Comment by BartoszCichecki** [comment]
Fixed, will be released in next release.

**Comment by DocDDD** [comment]
Thank you very much in advance!
