### ISSUE TITLE
[FEAT]: Import & Export of Actions

### ISSUE THREAD

**Issue by alantoblooddy** [BartoszCichecki/LenovoLegionToolkit#470]
### Version

2.7.1

### OS

Windows 11 Pro 22H2 22621.963

### Device

Legion 7 16ACHg6

### Is your feature request related to a problem?

The title speaks for itself. Having an option to export and import actions will help in case you make an OC reinstall, or somebody needs a specific thing (for example, setting different OC profiles depending on the Power Mode).

### How would you like the problem to be solved?

Adding "Import Actions" and "Export Actions" buttons in the action or settings section.

### What alternatives have you considered?

Not much of a developer.

### Additional information

Below is the screenshot of actions I'll have to redo after an OC reinstall.

![List of Actions](https://user-images.githubusercontent.com/22687186/210921871-2bc87819-e402-46b2-854a-e42e55256566.png)

**Comment by BartoszCichecki** [comment]
You can make a backup of settings, including actions. They are stored in %LocalAppData%\LenovoLegionToolkit. I don't think adding an option on the UI is necessary.
