### ISSUE TITLE
[FEAT]: Copy text from packages / readme

### ISSUE THREAD

**Issue by GreatApo** [BartoszCichecki/LenovoLegionToolkit#472]
### Version

2.7.1

### OS

Windows 11 Home 22H2

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

You can't copy text from the displayed packages / drivers or their readme (e.g. driver version etc)

### How would you like the problem to be solved?

Proposal:
- Auto-copy when you click on package version (copy title + version maybe?)
- Make everything in the readme file selectable so that you can copy any desired info

### What alternatives have you considered?

Make the text of each package selectable / copy-able

### Additional information

None

**Comment by BartoszCichecki** [comment]
Added copy button to readme window + right click on text on package list will copy it to clipboad.
