### ISSUE TITLE
[FEAT]: Keyboard step as action for non RGB keyboards

### ISSUE THREAD

**Issue by mind12** [BartoszCichecki/LenovoLegionToolkit#477]
### Version

2.7.1

### OS

Win 10 22H2

### Device

Legion 5 15ARH05 (G5 2020)

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

I would like to disable keyboard backlight if the AC power is disconnected so add a step for it in Actions. It's unavailable for this device with a two step white backlight keyboard. If it's hard to implement dont bother. Thx 

### What alternatives have you considered?

None

### Additional information

<img width="787" alt="image" src="https://user-images.githubusercontent.com/22614709/211217297-13978bf3-2f94-4b56-b8f8-089f7f389aca.png">
Goal is in the picture, like on my 5P.

**Comment by BartoszCichecki** [comment]
I thought it was already there... if it isn't we'll do some troubleshooting.

**Comment by mind12** [comment]
> I thought it was already there... if it isn't we'll do some troubleshooting.

I thought so, let me know what to do in discord.
