### ISSUE TITLE
[BUG]: [K9CN] whenever opening the edit modal the fan curve has been flattened

### ISSUE THREAD

**Issue by pjtinker** [BartoszCichecki/LenovoLegionToolkit#479]
### Version

2.8.0

### OS

Windows 11 22H2 build 22621.963

### Device

Legion 7 16ARHA7

### BIOS version

K9CN38WW

### What's wrong?

After creating a new custom power mode, whenever opening the edit modal the fan curve has been flattened; all points are set to 0%.

![image](https://user-images.githubusercontent.com/9274728/211390649-7efd70dd-9764-4eda-a66f-47d173c72ac2.png)

### How to reproduce the bug?

1.  Goto Dashboard
2. Select custom power mode
3. Change fan curve.  Apply and close.
4. Reopen custom power mode edit modal

### What is the behavior that you expected?

Fan curve settings persist

### Logs

First log is when I set the new fan curve.  Second log is reopening LLT and checking the curve.
[log_2023_01_09_19_07_24.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10376277/log_2023_01_09_19_07_24.txt)
[log_2023_01_09_19_09_14.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10376278/log_2023_01_09_19_09_14.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Can you send the `godmode.json` from `%LOCALAPPDATA\LenovoLegionToolkit`?

**Comment by pjtinker** [comment]
```
{
  "CPULongTermPowerLimit": {
    "Value": 112,
    "Min": 45,
    "Max": 175,
    "Step": 1
  },
  "CPUShortTermPowerLimit": {
    "Value": 156,
    "Min": 45,
    "Max": 175,
    "Step": 1
  },
  "CPUCrossLoadingPowerLimit": null,
  "CPUTemperatureLimit": {
    "Value": 100,
    "Min": 85,
    "Max": 100,
    "Step": 1
  },
  "GPUPowerBoost": null,
  "GPUConfigurableTGP": null,
  "GPUTemperatureLimit": null,
  "FanTable": {},
  "FanFullSpeed": false,
  "MaxValueOffset": 0
}
```

**Comment by BartoszCichecki** [comment]
@pjtinker Here is a test build with more logging enabled, please try to open LLT switch to Custom Mode, open it's settings, set some curver and hit Apply. And one more log after restarting LLT, and switching to Custom Mode.

[LenovoLegionToolkitSetup_479.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10376674/LenovoLegionToolkitSetup_479.zip)

**Comment by pjtinker** [comment]
The curve persisted on the test build.  Here are the logs:
[log_2023_01_10_13_57_41.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10383362/log_2023_01_10_13_57_41.txt)
[log_2023_01_10_13_56_36.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10383363/log_2023_01_10_13_56_36.txt)
