### ISSUE TITLE
[COMPATIBILITY]: IdeaPad Gaming 3 15IHU6

### ISSUE THREAD

**Issue by LipefipeFelps** [BartoszCichecki/LenovoLegionToolkit#484]
### Version

2.7.1

### OS

Windows 11 Pro 2H22 22621.963

### Device

Lenovo IdeaPad Gaming 3i 15IHU6

### BIOS version

H4CN25WW(V1.10)

### Which features of the application did you test?

![image](https://user-images.githubusercontent.com/106934109/211462423-10e0cb0a-1947-43cc-b62f-c965d1b595a2.png)
Everything in the Dashboard works as intended

![image](https://user-images.githubusercontent.com/106934109/211462498-e5f1d422-34c8-43ea-abd4-ecb7a2c7debf.png)
Battery information is accurate

![image](https://user-images.githubusercontent.com/106934109/211462577-22846af1-517c-47f3-afb3-dd42f99565de.png)
The default actions setup by the app work as intended

![image](https://user-images.githubusercontent.com/106934109/211462726-590abef7-622e-4060-a295-22866ecc1e02.png)
Downloads dont show anything on the primary server, but secondary server shows stuff, so working fine (probably because i have everything up to date idk)

### Which features of the application do not work as expected?

No, not really. Everything works as intended. Since this app is meant to be a replacement for Vantage (which ideapad gaming also uses), most of the stuff carries over seamlessly. Well, except the Legion exclusive functions, like variable refresh rate and RGB customization

**Comment by BartoszCichecki** [comment]
Thanks for the info! I'll add support to version 2.8.0.
