### ISSUE TITLE
Hotkeys Fn+Q in version 1.5 does not switch windows power profiles (on 2020 platform)

### ISSUE THREAD

**Issue by ateplih** [BartoszCichecki/LenovoLegionToolkit#49]
Version 1.5. Thank you so much for the update! All the wishes that we have told you have been fulfilled! However, switching WINDOWS power profiles by hotkeys Fn + Q stopped working. Vantage is disabled from this app. I have a 2020 laptop, 82B5008JRU. On the 2020 platform out of the box, the Fn + Q hotkeys only toggle BIOS power, but not Windows power profiles. This function is available to us, only in your program). In order for version 1.4 to work, we have to import power profiles from the 2021 platform, while keeping the original Lenovo GUIDs. Hope this information helps. Thanks again!

**Comment by BartoszCichecki** [comment]
Hey,

So how it works currently is that when you press Fn+Q, Toolkit will switch the power plan according to the settings.

So, if in settings the values are set to `(Default)` Toolkit will use the default power profiles (GUIDs) from year 2021 (list is [here](https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/9f386c7e85dcdebd690a3ecb7c7ee894cbff42e8/LenovoLegionToolkit.Lib/Utils/Power.cs#L59)).

If you set custom ones in the Settings those will be used instead.

For compatibility Vantage needs to be disabled to avoid conflicts, since on some models it's also changing the power plan.

So, few things that you can check:
1. Open Services.msc and check if `LenovoVantageService` and `ImControllerService` are stopped. (Picture 1)
2. Does that work with power profiles set to `Default` and/or power profiles defined.
3. Run this as Administrator in PowerShell: `gwmi -class Win32_PowerPlan -Namespace Root\CIMV2\power` and paste the output here.
4. See if you keep Toolkit open and use Fn+Q if Toolkit correctly shows selected power mode.

Picture 1:
![image](https://user-images.githubusercontent.com/7916915/144760624-e24ea398-be97-4148-8965-697df97d547f.png)

**Comment by ateplih** [comment]
1. Are Stopped.
![image](https://user-images.githubusercontent.com/16780758/144761714-7d9ff858-8927-47bb-9d18-d0e21470ec12.png)
2. It does not work in any case
3. 
`PS C:\Windows\system32> gwmi -class Win32_PowerPlan -Namespace Root\CIMV2\power


__GENUS          : 2
__CLASS          : Win32_PowerPlan
__SUPERCLASS     : CIM_SettingData
__DYNASTY        : CIM_ManagedElement
__RELPATH        : Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{16edbccd-dee9-4ec4-ace5-2f0b5f2a8975}"
__PROPERTY_COUNT : 5
__DERIVATION     : {CIM_SettingData, CIM_ManagedElement}
__SERVER         : LAPTOP-77Q7OTUA
__NAMESPACE      : Root\CIMV2\power
__PATH           : \\LAPTOP-77Q7OTUA\Root\CIMV2\power:Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{16edbccd-dee9-4
                   ec4-ace5-2f0b5f2a8975}"
Caption          :
Description      :
ElementName      : Legion Quiet Mode
InstanceID       : Microsoft:PowerPlan\{16edbccd-dee9-4ec4-ace5-2f0b5f2a8975}
IsActive         : False
PSComputerName   : LAPTOP-77Q7OTUA

__GENUS          : 2
__CLASS          : Win32_PowerPlan
__SUPERCLASS     : CIM_SettingData
__DYNASTY        : CIM_ManagedElement
__RELPATH        : Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{1a4ccfab-0689-41cf-91b3-d138ea699da1}"
__PROPERTY_COUNT : 5
__DERIVATION     : {CIM_SettingData, CIM_ManagedElement}
__SERVER         : LAPTOP-77Q7OTUA
__NAMESPACE      : Root\CIMV2\power
__PATH           : \\LAPTOP-77Q7OTUA\Root\CIMV2\power:Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{1a4ccfab-0689-4
                   1cf-91b3-d138ea699da1}"
Caption          :
Description      :
ElementName      : Высокая производительность
InstanceID       : Microsoft:PowerPlan\{1a4ccfab-0689-41cf-91b3-d138ea699da1}
IsActive         : False
PSComputerName   : LAPTOP-77Q7OTUA

__GENUS          : 2
__CLASS          : Win32_PowerPlan
__SUPERCLASS     : CIM_SettingData
__DYNASTY        : CIM_ManagedElement
__RELPATH        : Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{381b4222-f694-41f0-9685-ff5bb260df2e}"
__PROPERTY_COUNT : 5
__DERIVATION     : {CIM_SettingData, CIM_ManagedElement}
__SERVER         : LAPTOP-77Q7OTUA
__NAMESPACE      : Root\CIMV2\power
__PATH           : \\LAPTOP-77Q7OTUA\Root\CIMV2\power:Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{381b4222-f694-4
                   1f0-9685-ff5bb260df2e}"
Caption          :
Description      : Автоматическое соблюдение баланса между производительностью и энергопотреблением на пригодном для эт
                   ого оборудовании.
ElementName      : Сбалансированная
InstanceID       : Microsoft:PowerPlan\{381b4222-f694-41f0-9685-ff5bb260df2e}
IsActive         : False
PSComputerName   : LAPTOP-77Q7OTUA

__GENUS          : 2
__CLASS          : Win32_PowerPlan
__SUPERCLASS     : CIM_SettingData
__DYNASTY        : CIM_ManagedElement
__RELPATH        : Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{52521609-efc9-4268-b9ba-67dea73f18b2}"
__PROPERTY_COUNT : 5
__DERIVATION     : {CIM_SettingData, CIM_ManagedElement}
__SERVER         : LAPTOP-77Q7OTUA
__NAMESPACE      : Root\CIMV2\power
__PATH           : \\LAPTOP-77Q7OTUA\Root\CIMV2\power:Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{52521609-efc9-4
                   268-b9ba-67dea73f18b2}"
Caption          :
Description      :
ElementName      : Legion Performance Mode
InstanceID       : Microsoft:PowerPlan\{52521609-efc9-4268-b9ba-67dea73f18b2}
IsActive         : False
PSComputerName   : LAPTOP-77Q7OTUA

__GENUS          : 2
__CLASS          : Win32_PowerPlan
__SUPERCLASS     : CIM_SettingData
__DYNASTY        : CIM_ManagedElement
__RELPATH        : Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{65bceb1e-b05f-444b-9b0b-f211abe084b5}"
__PROPERTY_COUNT : 5
__DERIVATION     : {CIM_SettingData, CIM_ManagedElement}
__SERVER         : LAPTOP-77Q7OTUA
__NAMESPACE      : Root\CIMV2\power
__PATH           : \\LAPTOP-77Q7OTUA\Root\CIMV2\power:Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{65bceb1e-b05f-4
                   44b-9b0b-f211abe084b5}"
Caption          :
Description      :
ElementName      : Экономия энергии
InstanceID       : Microsoft:PowerPlan\{65bceb1e-b05f-444b-9b0b-f211abe084b5}
IsActive         : False
PSComputerName   : LAPTOP-77Q7OTUA

__GENUS          : 2
__CLASS          : Win32_PowerPlan
__SUPERCLASS     : CIM_SettingData
__DYNASTY        : CIM_ManagedElement
__RELPATH        : Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{85d583c5-cf2e-4197-80fd-3789a227a72c}"
__PROPERTY_COUNT : 5
__DERIVATION     : {CIM_SettingData, CIM_ManagedElement}
__SERVER         : LAPTOP-77Q7OTUA
__NAMESPACE      : Root\CIMV2\power
__PATH           : \\LAPTOP-77Q7OTUA\Root\CIMV2\power:Win32_PowerPlan.InstanceID="Microsoft:PowerPlan\\{85d583c5-cf2e-4
                   197-80fd-3789a227a72c}"
Caption          :
Description      : Автоматическое соблюдение баланса между производительностью и энергопотреблением на пригодном для эт
                   ого оборудовании.
ElementName      : Legion Balance Mode
InstanceID       : Microsoft:PowerPlan\{85d583c5-cf2e-4197-80fd-3789a227a72c}
IsActive         : True
PSComputerName   : LAPTOP-77Q7OTUA
`


4. Toolkit correctly shows the selected power mode.

**Comment by BartoszCichecki** [comment]
OK, I'll take a look but in any case I am working on adding some logging features to better trace issues that appear. I'll get back as soon as I have something ;)

**Comment by BartoszCichecki** [comment]
OK, small request :)

Here is a very early version that can do some debug logging: https://1drv.ms/u/s!ApDfgN6g_FJ6hNFs72enLgOHpbDaJQ?e=KabpJy

You need to start it with `--log` argument and the log will appear in `%LocalAppData%\LenovoLegionToolkit`.

If you could try to run it, press Fn+Q once or twice, and send here the log, maybe we can more easily figure out what is wrong with power plans!

**Comment by ateplih** [comment]
ок.
[log_2021_12_06_02_01_50.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/7656970/log_2021_12_06_02_01_50.txt)

**Comment by sickypedia** [comment]
Similar issue at my end - I have the default 2021 power plans imported on a clean windows installation without Vantage- 1.4 works, but not the latest update.

**Comment by sickypedia** [comment]
[log_2021_12_06_04_56_58.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/7657007/log_2021_12_06_04_56_58.txt)

Log attached

**Comment by BartoszCichecki** [comment]
OK, so that is really interesting guys. What has changed between 1.5 and 1.4 is that power plans are not activated using command line `powercfg` but using a WMI methods which seem to not be working and is not activating power plans on your machines.

I actually have no idea why would that be happening...

Can you try in power shell (again as admin) to see if you can use this command to activate quiet mode power plan?

`$pp = Get-WmiObject -Namespace "root/cimv2/power" -Query "select * from win32_powerplan where ElementName='Legion Quiet Mode'"; $pp.Activate()`

**Comment by ateplih** [comment]
Exception when calling "Activate": "This method is not implemented in any of the classes"
Row: 1 Sign: 129
+ ... IN32_POWERPLAN WHERE ELEMENTNAME = 'LEGION QUIET MODE', "$ PP.ActiveVATE ()
+ ~~~~~~~~~~~~~~
    + CategoryInfo: NotSpecified: (:) [], MethodInvocationException
    + FULLYQUALIFIEDERRORID: WMimethodeException

**Comment by BartoszCichecki** [comment]
OK, that explains a lot. It seems like Activate method is missing (https://stackoverflow.com/a/61121407) in some Windows versions. Crazy.

I will revert this back tomorrow and provide a hot fix.

**Comment by ateplih** [comment]
It's clear. Thanks!

**Comment by BartoszCichecki** [comment]
1.5.2 is out, let me know if that works again.
