### ISSUE TITLE
Fan Control on Legion 5 15IAH7H

### ISSUE THREAD

**Issue by Tymmey** [BartoszCichecki/LenovoLegionToolkit#498]
### Version

2.8.0

### OS

Windows 10 22H2

### Device

 Legion 5 15IAH7H

### Is your feature request related to a problem?

Hi there,
really like this tool! 
Sadly Fan Control is not available for my model.

Is it possible to add it for this?

Thanks in advance!

### How would you like the problem to be solved?

in future release?

### What alternatives have you considered?

using legion fan control, but don't like having to use multiple apps..

**Comment by Tymmey** [comment]
J2CN30WW it is.

**Comment by BartoszCichecki** [comment]
Custom Mode including fan control is supported since J2CN40WW as stated in the readme.

**Comment by Tymmey** [comment]
Ahh Updated bios to J2CN49WW, sadly still no fan control :(
