### ISSUE TITLE
[COMPATIBILITY]: Keyboard Blacklight feature

### ISSUE THREAD

**Issue by DmShAl** [BartoszCichecki/LenovoLegionToolkit#499]
### Version

2.7.1

### OS

Windows 11 Pro 22H2

### Device

Legion 7 16ACHg6

### BIOS version

GKCN59WW

### Which features of the application did you test?

Keyboard Blacklight tab is missing.

### Which features of the application do not work as expected?

Keyboard Blacklight feature is missing. Is any possibility to support this functionality on Legion 7 16ACHg6 (2021 model)

**Comment by BartoszCichecki** [comment]
As stated in the Readme, no.

**Comment by BartoszCichecki** [comment]
Duplicate of #178
