### ISSUE TITLE
 If you do not uncheck the autorun checkbox in version 1.4 and replace the .exe file with the new version 1.5, there will be an error at startup.

### ISSUE THREAD

**Issue by ateplih** [BartoszCichecki/LenovoLegionToolkit#50]

**Comment by BartoszCichecki** [comment]
What if you toggle autorun?

**Comment by BartoszCichecki** [comment]
And btw, it would be nice to know what error is that, because I cannot repro that on my machine :/

**Comment by ateplih** [comment]
Strange, but I can not repeat yourself, let's close the question.

**Comment by mind12** [comment]
I did the same, replaced an older exe with 1.5 version and at first start there was an error that the program can't find some settings.json file. Exited, ran again, but no error after that, so I dont have a screenshot.

**Comment by BartoszCichecki** [comment]
Ah! That's my fuck up! You can safely ignore it, but I will correct it in a hotfix.

**Comment by BartoszCichecki** [comment]
Just pushed 1.5.1. Sorry guys, that was a stupid fuck up :D
