### ISSUE TITLE
[FEAT]: Fan Control on Lenovo Legion 5 Pro 16ACH6H

### ISSUE THREAD

**Issue by RunningDead89** [BartoszCichecki/LenovoLegionToolkit#500]
### Version

2.8.0

### OS

Windows 11 22H2 build 22623.1095

### Device

Legion 5 Pro 16ACH6H

### Is your feature request related to a problem?

Hi Bartosz,

i don't know if i missed something but for my Laptop Fan Control isn't avaivable.

Is it possible to add this for my model?

BIOS version is GKCN59WW.

Thanks in advance!

### How would you like the problem to be solved?

If possible, add Fan Control for 16ACH6H.

### What alternatives have you considered?

For now i use Lenovo Fan Control.

**Comment by BartoszCichecki** [comment]
https://github.com/BartoszCichecki/LenovoLegionToolkit#can-you-add-fan-control-to-other-models

**Comment by sceraser** [comment]
> https://github.com/BartoszCichecki/LenovoLegionToolkit#can-you-add-fan-control-to-other-models
> 
> Your laptop is 2021 model, you can use LFC if you need fan control.

Can LLT add fan control for older model like LFC? LFC have some bugs that would cause BS but the developer seems not working on solve it after more than half years of bug report
