### ISSUE TITLE
[FEAT]: New Action - Switch nvidia display mode

### ISSUE THREAD

**Issue by Prakyy** [BartoszCichecki/LenovoLegionToolkit#502]
### Version

2.8.1

### OS

Windows 11 22H2 Build22621

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

Advanced optimus' display mode switching takes way longer on windows 11 compared to windows 10 where it was instant. Since we cannot do anything about this, I would like the display to switch to the dedicated GPU when AC power is connected and switch back to integrated display mode when disconnected instead of switching every time a game is launched, as it does currently, which absolutely wrecks my continuity. There is no native way to achieve this behavior...  yet. This is something I'd like to see tackled by this project.

### How would you like the problem to be solved?

Add a new action to switch display mode using advanced Optimus between "Nvidia GPU only" and "Optimus". Also, add a safety condition so the display doesn't switch back if, say, the power goes out which would trigger a switch otherwise since you technically removed AC. Doing this while a 3D app is still running would be problematic. 

You could pull the list of apps from Nvidia's control panel (display switch allowed: on)

### What alternatives have you considered?

N/A

**Comment by BartoszCichecki** [comment]
Advanced Optimus is not exposed to 3rd party apps so what you are suggesting can't be done unfortunately.
