### ISSUE TITLE
[BUG]: Cannot start program v2.7.0 or later ("Couldn't read the AppsUseLightTheme setting")

### ISSUE THREAD

**Issue by zwresn453** [BartoszCichecki/LenovoLegionToolkit#504]
### Version

2.8.1 (actively using 2.6.5)

### OS

Windows 11 21H2 build 22000

### Device

Legion 7 16ACHg6 (AMD/Nvidia)

### BIOS version

GKCN59WW (Latest)

### What's wrong?

Application does not start when 2.7.0 or later is installed.

- ~~Installer closes as if it installed successfully, but the program is not present at `%LOCALAPPDATA%\Programs\LenovoLegionToolkit`~~
- Program seems to have installed successfully. I believe that the error occurs when the application is run.
- When running the program, the below error is shown. When OK is selected, the application closes.
- This occurs both from clean install and after installing over version 2.6.5 
- Version 2.6.5 does not have this error. It seems that there may have been a change to the light/dark mode auto-detect feature in 2.7.0 that doesn't work with my system.

>Unexpected exception occurred:
>Couldn't read the AppsUseLightTheme setting.
>
>Please report the issue on
>https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/new/c
>hoose.

### How to reproduce the bug?

1. Install program on the affected device
2. Run program

### What is the behavior that you expected?

The program launches properly. 

I would also appreciate if error messages had a "continue anyway at your own risk" function, especially for minor problems

### Logs

Here is the [error log](https://pastebin.com/gCAvVU3N)

There was [one other log](https://pastebin.com/rk0dNYfG) (a crash log) in the logs folder, but it seems be unrelated.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Here are the things I have tried:

Windows settings:
- Both light and dark modes
- Transparency both on and off
- HDR both on and off

Others:
- Close X-Rite Color Assistant (preinstalled color management software)

**Comment by BartoszCichecki** [comment]
Can you go to `%LOCALAPPDATA%\LenovoLegionToolkit` and see if there is a logs folder? Does it contain anything?
Are installing this by any chance on a user without admin rights?

**Comment by zwresn453** [comment]
Good thinking, here is the related error log:

https://pastebin.com/gCAvVU3N

**Comment by zwresn453** [comment]
Let me know if you also need the "--trace" log. I haven't posted it because I'm not sure if it has any sensitive information in it.

**Comment by BartoszCichecki** [comment]
What about the other questions?

**Comment by zwresn453** [comment]
Sorry, my bad.

It was installed under an administrator account, and I use the administrator account in the UAC prompt each time I run the program. 
There is a logs folder, and it contains many error logs caused by this problem, and one other one created due to a crash.

**Comment by BartoszCichecki** [comment]
Can you check if you have these registry keys?
`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme`
`HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\ColorizationColor`

**Comment by zwresn453** [comment]
Yes, both are present.

**Comment by zwresn453** [comment]
I log in to a different account, and authenticate with the admin account when the UAC prompt is shown.

**Comment by BartoszCichecki** [comment]
OK than that's the problem. Neither 2.8.1 nor any other previous version will function correctly when it's not running on the current account. I suggest that since you already have access to admin account just make the current account admin too.

Duplicate #246

**Comment by zwresn453** [comment]
Ok, thank you. Would you consider adding an option to continue launching the program on non-fatal errors?

**Comment by BartoszCichecki** [comment]
Yes, I will try to make a workaround so that at least LLT doesn't crash in next version. There is also a possibility that proper multiuser support will come, but I don't have any specific plans for it.
