### ISSUE TITLE
[FEAT]: Battery Charge Threshold

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#505]
### Version

2.8.1

### OS

Windows 11 Latest build

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

Vantage has an option to set when to start charging, and the maximum charge limit; this is very beneficial for preserving battery life.
The only workaround I do now using LegionToolkit is to switch battery mode to conservation on the battery percentage I want, but the issue is when using the laptop on battery and the percentage drops, I have to enable charging and keep track of the percentage till it reaches what I want and then switch back to conservation.

If you can, please add this to your software too, thanks!

![qKIAa](https://user-images.githubusercontent.com/29382999/213896676-4ca5fac0-57bb-4a9e-95e7-2a2b89ab5e6c.png)

### How would you like the problem to be solved?

Specified

### What alternatives have you considered?

Switching conservation on/off

**Comment by BartoszCichecki** [comment]
Setting the threshold is not supported on Legions.

**Comment by galitus** [comment]
Sorry, for posting in this closed issue, but the information is not quite true, especially for that model which I also own.

I use this piece of software to control my threshold.
https://github.com/chening567/LenovoController-CustomChargeLevels 

I have set mine to minimum 50 and max. 85% once in Windows while using it, 
and it still applies in every other system (linux, etc.).

So, it is possible. I'm not a coder and I don't know how the person has done it, but I know it is possible.

Maybe it helps and maybe not applicable for every device.
So the FAQ for the "Can I customize Conservation mode threshold?" is not quite right, or my firmware has a bug/feature, which is quite usable. : )

**Comment by BartoszCichecki** [comment]
There is no bug or magic here. This app only turns on Conservation mode "manually" at desired percentage level, meaning it only works when this app is running in the background. I suggest you do some better testing, because you are not correct. This behaviour is obvious when you look at the implementation: https://github.com/ViRb3/LenovoController/commit/b12d196ea8d63def9b2981b4413dc79c3cf0c147.
