### ISSUE TITLE
[FEAT]: Detection of USB-PD chargers under 65W as low-wattage chargers

### ISSUE THREAD

**Issue by zwresn453** [BartoszCichecki/LenovoLegionToolkit#512]
### Version

2.8.1

### OS

Windows 11 21H2

### Device

Legion 7 16ACHg6

### Is your feature request related to a problem?

Connecting a 45W charger does not activate the "low-wattage charger" action. The 45W adapter that I use does provide enough power to run the computer indefinitely, so I would like to be able to have it trigger the action. 

However, because Windows is unaware that the computer is charging during this time, it may be difficult to implement. I don't know how LLT's wattage detection works though.

### How would you like the problem to be solved?

The 45W charger triggers the "low-wattage charger" action list.

### What alternatives have you considered?

Manually opening LLT and running the "low-wattage charger" action

### Additional information

Contrary to the user manual, the computer does charge the battery and run on wall power when connected to a charger between 45-65W. However, Windows is unaware that the computer is charging, probably because of the way the BIOS is designed.

**Comment by BartoszCichecki** [comment]
> However, Windows is unaware that the computer is charging, probably because of the way the BIOS is designed.

You answered your own question here, if the charger is not detected there is no way for LLT to react to that.

**Comment by BartoszCichecki** [comment]
> Also, kind of related, LLT sometimes shows the wattage as -700W when a 45W charger is connected. I can't reproduce it reliably though.

Regarding this: when you connect a charger that just barely charges to laptop, Windows will report all kinds of weird stuff, which is probably caused by strange indications from the battery controller.
