### ISSUE TITLE
[COMPATIBILITY]: Legion 5 Pro 16ARH7h

### ISSUE THREAD

**Issue by lasksafj** [BartoszCichecki/LenovoLegionToolkit#518]
### Version

2.8.1

### OS

 Windows 11, version 22H2 

### Device

Legion 5 Pro 16ARH7h

### BIOS version

JUCN55WW

### Which features of the application did you test?

Custom mode and fan control

### Which features of the application do not work as expected?

No option for custom mode and fan control

**Comment by BartoszCichecki** [comment]
I am pretty sure JUCN is supported since 51WW. Can you show a screenshot of custom mode missing? Paste a log file?

**Comment by lasksafj** [comment]
I look around the whole app but cannot see where the custom mode is.
Here is the screenshot
<img width="859" alt="image" src="https://user-images.githubusercontent.com/102700368/215286850-c9ab59c2-0bd1-4561-84b1-ace3e6219c7b.png">

**Comment by BartoszCichecki** [comment]
It's a power mode. Expand Power Modes.

**Comment by lasksafj** [comment]
Oh, thank you! I got it worked now
