### ISSUE TITLE
Is it possible to make an option to be able to switch power profiles while the Vantage is running?

### ISSUE THREAD

**Issue by ateplih** [BartoszCichecki/LenovoLegionToolkit#52]

**Comment by BartoszCichecki** [comment]
I understand this is because 2020 Legions do not switch power profiles at all?

**Comment by ateplih** [comment]
> I understand this is because 2020 Legions do not switch power profiles at all?

Yes:)

**Comment by BartoszCichecki** [comment]
Sure, I can make it for you guys :)

BTW, thanks for spreading the word on 4pda forum. I used to use it many years ago when I had a Symbian phone!

**Comment by ateplih** [comment]
We will be glad and grateful

**Comment by BartoszCichecki** [comment]
https://github.com/BartoszCichecki/LenovoLegionToolkit/commit/03f7f67547d69c30da5cb7b37165dbb85915fb34

**Comment by fan-73** [comment]
Unfortunately this still doesn't work on legion 5 2020.

**Comment by BartoszCichecki** [comment]
Please attach logs.

**Comment by fan-73** [comment]
[log_2021_12_14_13_07_35.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/7710643/log_2021_12_14_13_07_35.txt)
Look here!

**Comment by BartoszCichecki** [comment]
Did you check the checkbox in settings to turn this feature on?

**Comment by fan-73** [comment]
Yes. Tools -> Lenovo Vantage -> [x] Enables

**Comment by BartoszCichecki** [comment]
@fan-73  This line in the log tells me that the option in Tools -> More Settings -> Activate power plans even when Vantage is enabled is not enabled:

`[14.12.2021 13:08:03] [Power.cs#119:ShouldActivate] Criteria for activation not met [**overide=False**, isDefault=True, alwaysActivateDefaults=False, status=Enabled]`

**Comment by fan-73** [comment]
I know it. Because of this, I am using your wonderful program. Since version 1.3.1

**Comment by fan-73** [comment]
Вы правы, это я такой невнимательный. Я не знал извините. Сейчас переключение заработало.

**Comment by fan-73** [comment]
It seems to me that this should be written in the README !?

**Comment by BartoszCichecki** [comment]
Fair point, I'll add this to readme!
