### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by balkeet** [BartoszCichecki/LenovoLegionToolkit#528]
### Version

2.8.1

### OS

Windows 10 22H2 build 19045.2546

### Device

Lenovo Legion Y540-15IRH

### BIOS version

BHCN45WW

### What's wrong?

The Fn lock feature gets disabled on restarting the system. The toolkit is on auto run mode on start up, the battery conservative mode is working fine and doesn't get reset on restart.

### How to reproduce the bug?

Open toolkit, on dashboard in others section the Fn lock button works but the setting is reset on reboot of system

### What is the behavior that you expected?

The Fn lock setting should be saved so that we don't have to manually do it every time

### Logs

None

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Fn Lock is controlled by BIOS, so if it get's disabled it's a bug in BIOS. I suggest working around this issue with Actions and re-enable the lock. You can use "when on battery" and "when on ac power" actions.

**Comment by balkeet** [comment]
Ok, but the battery conservation mode is working perfectly,  I used your toolkit for that primarily. Fn lock is a bonus if it works.

**Comment by BartoszCichecki** [comment]
There are all kinds of weird issues in older (before gen 6) bioses so it is what it is unfortunately.

**Comment by balkeet** [comment]
Ok, thanks. The conservation mode disappeared from vantage for me. Tried installing acpi driver but still not showing in vantage.

**Comment by balkeet** [comment]
Tried your method of add action of Start Fn lock on start up. Its working thanks!
