### ISSUE TITLE
Restore state of the keyboard backlight when the laptop is turned on.

### ISSUE THREAD

**Issue by ateplih** [BartoszCichecki/LenovoLegionToolkit#53]

**Comment by BartoszCichecki** [comment]
Keyboard handling is currently out of scope. My model has only white backlight and that from what I have seem is working differently from simple RGB (in Lenovo 5 Pro) and full RGB (Lenovo 7) so there is no way for me to implement this.

I'll keep it open, but chances are slim.

**Comment by revanmj** [comment]
Any chance for a backlight schedule - like enable backlight at night? (I also have a model with just white backlight)

**Comment by BartoszCichecki** [comment]
Well, it is somewhere on the roadmap, would like to add it but no estimate on that yet.
