### ISSUE TITLE
[FEAT]: Add the Instant boot option

### ISSUE THREAD

**Issue by Glimspe** [BartoszCichecki/LenovoLegionToolkit#531]
### Version

2.8.1

### OS

win10 home 21H2

### Device

Legion 5 15ACH6A

### Is your feature request related to a problem?

Add the function of  power on device after  plugging in Adapter /Type-c power Delivery.I can change it  in BIOS,but i think it is trobulesome. 
I  think adding this function  is very nice,
![1675664367830](https://user-images.githubusercontent.com/100057577/216897658-f8c6880f-2c91-45c8-966c-94698b0365c5.jpg)

### How would you like the problem to be solved?

none

### What alternatives have you considered?

none

### Additional information

none

**Comment by BartoszCichecki** [comment]
Good idea. I don't think this setting is exposed to the OS, but I'll keep the issue around.

**Comment by BartoszCichecki** [comment]
OK, so after some quick investigation, this settings is not exposed as a dedicated UEFI variable, so there is basically no way to expose it safely as this value can be stored in different places depending on BIOS versions.

**Comment by Glimspe** [comment]
I found that you are testing this feature in beta version，but your changelog said   
 it only  supports  in gen7 and gen8.  however gen6 also support  this feature,so whether 
 can  add gen6 into  the  adapted  model.😃😃

**Comment by BartoszCichecki** [comment]
The issue is that as I mentioned that there is no interface to control it on Gen 6. Gen 7 and 8 have an interface exposed via WMI therefore it could be added to LLT.
