### ISSUE TITLE
[BUG]: When connecting a secondary monitor, the resolution and refresh rate options disappear

### ISSUE THREAD

**Issue by matias1233218** [BartoszCichecki/LenovoLegionToolkit#533]
### Version

2.9.0

### OS

Windows 10 22H2 19045.2486

### Device

Legion 5 15ACH6H

### BIOS version

GKCN46WW

### What's wrong?

when connecting a secondary monitor, the resolution and refresh rate options disappear
![image](https://user-images.githubusercontent.com/107080783/217100278-4b8da2c9-3e6d-483f-8b76-e250e6d4243a.png)
![image](https://user-images.githubusercontent.com/107080783/217100297-3fe692c3-ca54-4ed1-9805-00fb446969a5.png)

### How to reproduce the bug?

1. Open LLT
2. Select dashboard
3. Connect an external monitor

### What is the behavior that you expected?

when connecting the secondary monitor most of the screen options disappear, including the resolution and refresh rate

### Logs

[log_2023_02_06_22_07_01.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10669634/log_2023_02_06_22_07_01.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

in the previous version, this did not happen

**Comment by BartoszCichecki** [comment]
Thanks for making the issue. Can you also upload the log from this build? (I added a bit more logging)

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10669740/LenovoLegionToolkitSetup.zip)

**Comment by matias1233218** [comment]
[log_2023_02_06_23_39_21.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10670078/log_2023_02_06_23_39_21.txt)

**Comment by Jaysama137** [comment]
> Thanks for making the issue. Can you also upload the log from this build? (I added a bit more logging)
> 
> [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10669740/LenovoLegionToolkitSetup.zip)


hi, I have the same problem, and here is the log from your beta version
hope it can be helpful
[log_2023_02_07_14_37_31.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10676187/log_2023_02_07_14_37_31.txt)

**Comment by BartoszCichecki** [comment]
@matias1233218 @Jaysama137 I have another build for you. Can you check if the issue is resolved now?

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10679278/LenovoLegionToolkitSetup.zip)

**Comment by matias1233218** [comment]
I just installed it, now it works

![image](https://user-images.githubusercontent.com/107080783/217369907-f4dff194-64ff-4848-9702-de105daf5fed.png)

**Comment by Jaysama137** [comment]
> @matias1233218 @Jaysama137 I have another build for you. Can you check if the issue is resolved now?
> 
> [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10679278/LenovoLegionToolkitSetup.zip)

It works!
