### ISSUE TITLE
[FEAT]: Quick Access to "Rapid Charge"

### ISSUE THREAD

**Issue by Stories8106** [BartoszCichecki/LenovoLegionToolkit#535]
### Version

2.8.0

### OS

Windows 10 Home

### Device

Lenovo Ideapad Gaming 3

### Is your feature request related to a problem?

No.  Just a QOL improvement.  I cant be the only one who needs a super fast charge frequently.

### How would you like the problem to be solved?

A button to activate it quickly from the quick access settings, simlar to the Lenovo Vantage software. ( e.g. Right-Click on the Toolkit and then it would right there.

### What alternatives have you considered?

Switched back to Vantage, since if I want to use this on the Toolkit I have to open the toolkit (or quick access to Battery from right-click) then go to the Rapid Charge toggle, then close the software.

**Comment by SmokelessCPUv2** [comment]
Hi, you can already do that, just add a quick action for rapid charge, and will be available on right click of the LLT icon

**Comment by BartoszCichecki** [comment]
Just like Smokeless mentioned you can create any Quick Action you want and it will show up in context menu.
