### ISSUE TITLE
[BUG]: Graphics card status is abnormal

### ISSUE THREAD

**Issue by Niexiawei** [BartoszCichecki/LenovoLegionToolkit#536]
### Version

2.9.0

### OS

win 11 22h2 22621.1194

### Device

Lenovo Legion R9000P2021H

### BIOS version

GKCN59WW

### What's wrong?

Has been switched to display only the direct connection in ttl or will display the mixed mode is turned on

![image](https://user-images.githubusercontent.com/29922984/217247519-3077bef0-962e-41c3-b664-d8389ef2136c.png)

### How to reproduce the bug?

Shortly after the software starts

### What is the behavior that you expected?

Normal display of graphics card status

### Logs

none

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
I have no idea if I understand you correctly but this is not an abnormal state.

Lenovo designed it in a way that you can turn on hybrid mode and it will not take effect until machine is restarted, which will result in exactly in the situation you have. There is no way to check "what is the current status", it is only possible to check "what will the status be after restart".

Also, some BIOS versions have an issue where they reenable hybrid mode.

**Comment by Niexiawei** [comment]
@BartoszCichecki 
I didn't turn on mixed mode. ttl will turn on this button automatically

**Comment by BartoszCichecki** [comment]
By saying TTL i assume you mean LLT (Lenovo Legion Toolkit).

LLT doesn't turn on anything automatically - status is always read from EC/drivers/BIOS.

**Comment by Niexiawei** [comment]
Okay, thank you for your answer. Maybe I should reset my bios

**Comment by BartoszCichecki** [comment]
> Also, some BIOS versions have an issue where they reenable hybrid mode.

You might also have one of the "lucky" devices where BIOS just turns it on randomly.
