### ISSUE TITLE
[FEAT]: keyboard shortcut for the new "Turn off displays" feature

### ISSUE THREAD

**Issue by a402245** [BartoszCichecki/LenovoLegionToolkit#541]
### Version

2.9.0

### OS

windows 11 pro 22h2

### Device

legion 5 pro 16IAH7H

### Is your feature request related to a problem?

the new feature in legion toolkit to turn off displays would be useful if there was a keyboard shortcut (Fn+keys)

### How would you like the problem to be solved?

add keyboard shortcut to turn off displays (Fn+keys)

### What alternatives have you considered?

currently have to open legion toolkit and click the option

**Comment by BartoszCichecki** [comment]
Can already by done using Quick Action assigned to SmartKey (Fn+F9).
