### ISSUE TITLE
[FEAT]: Please add: export settings

### ISSUE THREAD

**Issue by rezpower** [BartoszCichecki/LenovoLegionToolkit#546]
### Version

2.9.1

### OS

Windows 11 22H2 22621.1105

### Device

Legion 7i 16IAX7

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

It would be great and practical to be able to export our personal settings once we have customized LegionToolkit (The Actions section, power plans etc) so you can import and restore your settings easily on  new windows or be able to share it . 

### What alternatives have you considered?

Maybe to backup a registry entry (if exist) or backing up a file in the application's folder!

**Comment by BartoszCichecki** [comment]
Settings are stored in %LOCALAPPDATA%\LenovoLegionToolkit. You can just make a backup of it.
