### ISSUE TITLE
[FEAT]: Add user active/inactive trigger to Actions

### ISSUE THREAD

**Issue by huarzone** [BartoszCichecki/LenovoLegionToolkit#552]
### Version

2.9.1

### OS

Windows11 22H2 22621.1105

### Device

Legion Y9000X IAH7

### Is your feature request related to a problem?

I want to automatically turn on the keyboard backlight when the keyboard is tapped, and automatically turn off the keyboard backlight when the keyboard is not used for a long time.

### How would you like the problem to be solved?

Is it possible to add such a functional judgment in the automation: when the keyboard is pressed and when the keyboard is not pressed for a minute.

### What alternatives have you considered?

Add this function option directly in the console

**Comment by BartoszCichecki** [comment]
Good idea! 👍

**Comment by BartoszCichecki** [comment]
@huarzone just to clarify, do you have a completely custom timeout in mind or this should be synchronized with for example when Windows turns off/on monitors (the value you set in Windows power settings)?

**Comment by huarzone** [comment]
> @huarzone just to clarify, do you have a completely custom timeout in mind or should this be synchronized with for example when Windows turns off/on monitors (the value you set in Windows power settings)?

Thank you for taking time out of your busy schedule to answer my question, maybe I didn't think about it in detail at the time. For this timeout setting, I think there are two ways, one is to set the system monitor to judge the operation timeout; the other is to only set the user activity trigger, but in the trigger operation, an operation delay can be set between the two operations. For example, trigger an action when using the keyboard: turn on the keyboard backlight ~ wait for a time value ~ turn off the keyboard backlight. But I'm not sure which of the two solutions takes up less system resources.

**Comment by BartoszCichecki** [comment]
Both are viable options. 

Utilizing Windows monitor off/on events will be more lightweight and easier to implement, but it will be less flexible. 

Creating custom timer will be more difficult since you also need to keep track off many more system settings (like which devices are allowed to wake computer). 

So if option 1 would be enough, that would preferable and more consistent with default Windows behavior.

**Comment by BartoszCichecki** [comment]
Just FYI: I decided to got with using Windows' monitor on/off events since they are more reliable and far less complex.
