### ISSUE TITLE
[FEAT]: Hide notification area icon 隐藏通知区域图标

### ISSUE THREAD

**Issue by youlan2333** [BartoszCichecki/LenovoLegionToolkit#553]
### Version

2.8.1

### OS

Windows 11 22623.1255

### Device

Lenovo Legion Y7000 2020

### Is your feature request related to a problem?

Has the author considered the function of hiding the notification area icon? I think it takes up too much space there.

作者是否考虑过隐藏通知区图标这个功能吗，我觉得它在那里太占用空间了？

### How would you like the problem to be solved?

Use a switch to control display and hide

使用一个开关来控制显示和隐藏

### What alternatives have you considered?

not applicable

**Comment by BartoszCichecki** [comment]
Duplicate of #352.
