### ISSUE TITLE
[FEAT]: possible to show wake/sleep status using battery LED?

### ISSUE THREAD

**Issue by a402245** [BartoszCichecki/LenovoLegionToolkit#556]
### Version

2.9.1

### OS

windows 11 pro 22h2

### Device

legion 5 pro 16IAH7H

### Is your feature request related to a problem?

i often leave my laptop set to sleep mode with the lid closed. for whatever reason, sometimes the laptop wakes up from sleep and turns back on. with the lid closed, there is absolutely no way of knowing the laptop has done this as none of the LED's are visible.

### How would you like the problem to be solved?

is it possible to manipulate the LED which shows charging/battery status to also show sleep/wake status? this led is the only one which is visible when the laptop lid is closed. perhaps set it to flash or change colour if the laptop is awake/asleep?

### What alternatives have you considered?

have to leave the laptop open when using sleep mode - no good if travelling or the laptop is in a bag etc.

**Comment by BartoszCichecki** [comment]
Sorry, this is unfortunately not possible. Power LED is not accessible from OS _and_ LLT has no control over the laptop when it's sleeping.
