### ISSUE TITLE
[FEAT]: Can it support desktop computers?

### ISSUE THREAD

**Issue by xb0or** [BartoszCichecki/LenovoLegionToolkit#558]
### Version

2.9.1

### OS

Windows 10 21H2 19044.2486

### Device

Lenovo Legion REN7000K

### Is your feature request related to a problem?

Hope to support the rescuer desktop computer

### How would you like the problem to be solved?

Hope to support the rescuer desktop computer

### What alternatives have you considered?

Hope to support the rescuer desktop computer

**Comment by BartoszCichecki** [comment]
Project page is very clear when it comes to this question.
