### ISSUE TITLE
[FEAT]: No fan curve

### ISSUE THREAD

**Issue by jzjohn789** [BartoszCichecki/LenovoLegionToolkit#566]
### Version

2.9.1

### OS

WIN11

### Device

Lenovo Legion 7 16ACH6

### Is your feature request related to a problem?

No fan curve for the old version laptop in customize settings?

### How would you like the problem to be solved?

ADD CURVE control function

### What alternatives have you considered?

ADD CURVE control function

**Comment by BartoszCichecki** [comment]
https://github.com/BartoszCichecki/LenovoLegionToolkit#can-you-add-fan-control-to-other-models

Your laptop is 2021 model, you can use LFC if you need fan control.
