### ISSUE TITLE
[BUG]: Text in light mode is too light 

### ISSUE THREAD

**Issue by bdaniesz** [BartoszCichecki/LenovoLegionToolkit#568]
### Version

2.9.1

### OS

Windows 11

### Device

Legion 5 15AcH6H

### Is your feature request related to a problem?

Technically yes. 
Reading the text with light theme is hard on the eyes. The gray text is barely readable.
![image](https://user-images.githubusercontent.com/43230532/219629659-ba475453-6eff-4d01-b220-8dfd8272cae0.png)

### How would you like the problem to be solved?

The subtexts should be darker in my opinion.

### What alternatives have you considered?

Same as above, subtext darker gray or black

**Comment by BartoszCichecki** [comment]
Updated some colors to be stronger. I am quite limited here by WPFUI that I am using, but it should be better.
