### ISSUE TITLE
[FEAT]:  Camera blocking support

### ISSUE THREAD

**Issue by Watermelon-henu** [BartoszCichecki/LenovoLegionToolkit#569]
### Version

2.9.1

### OS

win10

### Device

Y7000 2020

### Is your feature request related to a problem?

-

### How would you like the problem to be solved?

There is a camera on my computer. I hope the software can add the function of "turning off" the camera.

### What alternatives have you considered?

-

### Additional information

-

**Comment by BartoszCichecki** [comment]
What do you mean opening and closing the camera?

**Comment by Watermelon-henu** [comment]
> What do you mean opening and closing the camera?

I hope to control the opening and closing of the camera similar to the microphone. At present, this function cannot be realized through software

**Comment by BartoszCichecki** [comment]
Ah, I see, you mean "turning off" the camera. Support for this is not planned since newer models have a hardware switch for it, but if someone wants to implement it I will not oppose.

**Comment by Watermelon-henu** [comment]
> Ah, I see, you mean "turning off" the camera. Support for this is not planned since newer models have a hardware switch for it, but if someone wants to implement it I will not oppose.

Well, thank you, but on my computer, this function is not realized through hardware buttons. You may realize it through shortcut in the automation function

**Comment by Watermelon-henu** [comment]
You can add a function interface for this

**Comment by BartoszCichecki** [comment]
I am not spending more time on adding features that are used only on older models. Only features that are still used on newer ones are maintained/developed by me. But as I said, if someone wants to contribute and implement it I will accept Pull Requests.

**Comment by Watermelon-henu** [comment]
Ok, thank you for your quick reply and sharing this great software
