### ISSUE TITLE
[FEAT]: Adding a power mode indicator 

### ISSUE THREAD

**Issue by PureComedi** [BartoszCichecki/LenovoLegionToolkit#571]
### Version

2.9.1

### OS

Windows 11 Pro 22H2 preview build 25267.1000

### Device

Lenovo Ideapad Gaming 3 15ACH6

### Is your feature request related to a problem?

Currently there's no way to know what power mode the laptop is in without changing the power mode with the respective Fn+Q shortcut and the lack of a power button LED indicator, which does not shine in colors other than white

### How would you like the problem to be solved?

Adding a simple indicator bar of sorts in the menu that appears when the LLT icon is clicked in the taskbar
![example](https://user-images.githubusercontent.com/64898881/219852594-021b3a03-cf20-4fe7-ae3c-6596cc7ef387.png)

### What alternatives have you considered?

There's no real alternative other than setting shortcuts to the wanted power mode or cycling through every single one until the requested one is found

### Additional information

The ability to have this toggleable whether to appear would also be nice, just like the menus in the dashboard

**Comment by BartoszCichecki** [comment]
Blocked by https://github.com/hardcodet/wpf-notifyicon/issues/95
