### ISSUE TITLE
[BUG]: Cannot set 8th to last fan speeds below 2200RPM, 3000RPM and 3800RPM respectively in Custom Mode

### ISSUE THREAD

**Issue by PeaceForWar3** [BartoszCichecki/LenovoLegionToolkit#576]
### Version

2.9.1

### OS

Windows 10 21H2 Build 19044

### Device

Legion 5 15ARH7H

### BIOS version

JUNN57WW

### What's wrong?

As the title says it was possible to set 1 fan speed for all temperatures to avoid temperatures going up and down, or fans continuously changing speeds, but after the BIOS update I did a week ago I can't do so because I can't drag the fan speeds any lower than 2200RPM for the 8th temperature threshold and so on. I can set them with the arrow keys tho, but after clicking "Apply and Close" and checking back, the fan curve is not what you set it. Unfortunately I can't remember the previous version (and lenovo doesn't show them on their website), it was from November 2022 I think. Legion Fan Control allows me to set the same fan speed for all temperatures and it's an older version from may 2022, so it should be possible in Custom Mode even after the update. 

### How to reproduce the bug?

1. Open Legion Toolkit
2. Set Power mode to Custom Mode
3. Open Custom Mode settings
4. Scroll down to "Fans"
5. Try to set all fan speeds to a number below 2200RPM
6. Click "Apply and Close"
7. Repeat 3. to 4. and verify that the fan curve is flat
8. The fan curve isn't flat

### What is the behavior that you expected?

I expected to be able to set all fan speeds at the same speeds, whether it's 2200RPM or 1900RPM

### Logs

[log_2023_02_19_12_38_15.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10776894/log_2023_02_19_12_38_15.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [X] I disabled some things on my own (please write below what you did)

### Additional information

I uninstalled Vantage from the Control Panel and installed Legion Toolkit, I never installed Lenovo Hotkeys. I have "Lenovo Fn and function keys service" running in the background, but I don't think they're the same thing.

**Comment by BartoszCichecki** [comment]
This is done as a safety measure, to avoid setting fan speeds to low and overheating the machine.

**Comment by PeaceForWar3** [comment]
Oh. I use very low temp limits to avoid this, Is there a way for me to enable it. Please, I need this feature back. I can even compile it myself If you tell me what I have to change. Pretty please.

**Comment by PeaceForWar3** [comment]
> This is done as a safety measure, to avoid setting fan speeds to low and overheating the machine.

I don't want fans to ramp up because I live in a quiet environment and I can0t bother anyone with noise.

**Comment by BartoszCichecki** [comment]
I can lower the minimum fan speeds a bit in next release, but I don't want to allow any lower, because already at 2300 RPM you can heavily overheat the laptop. Keep in mind that if you see fans ramping up to 3800 RPM with current settings you already hit 94C on the CPU meaning that the fan curve is too low.

So as I said, I can lower the speeds a little, but I definitely won't allow 2200RPM at 94C on the CPU.

**Comment by PeaceForWar3** [comment]
> I can lower the minimum fan speeds a bit in next release, but I don't want to allow any lower, because already at 2300 RPM you can heavily overheat the laptop. Keep in mind that if you see fans ramping up to 3800 RPM with current settings you already hit 94C on the CPU meaning that the fan curve is too low.
> 
> So as I said, I can lower the speeds a little, but I definitely won't allow 2200RPM at 94C on the CPU.

Listen, I understand but can't you tell me at least how do I set it back the way it was? So that only I will do it at my own risk and no one else will be affected? I accept the risks and you're not liable in any way, I already have CPU temp limit to 85 C and TDP to 18W so 94C is not happening. i'll compile it for my use only. just tell me how, you can even send me and email so that no one else can do it: ric.pet@outlook.it

**Comment by BartoszCichecki** [comment]
This is the place: https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/8189bae1e71eecfda6cae89a8c126e4e38c80495/LenovoLegionToolkit.Lib/Structs.cs#L113

If you change this to something like:

`public static readonly FanTable Minimum = new(new ushort[] { 0, 0, 0, 0, 0, 0, 1, 1, 1, 1 });`

it will allow you to set it to the minimum fan speed which in your case is 1800 RPM.

**Comment by PeaceForWar3** [comment]
Thank you very much, I understand you're doing it for safety but I have my special use case.  Again, thank you for your time.

**Comment by BartoszCichecki** [comment]
No problem, just be careful.
