### ISSUE TITLE
[BUG]: Cannot Start Toolkit: Could not load file or assembly 'System.Private.Xml, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The module was expected to contain an assembly manifest.

### ISSUE THREAD

**Issue by Kraftprotz** [BartoszCichecki/LenovoLegionToolkit#578]
### Version

2.9.1

### OS

w11 22h12

### Device

Legion 5 Pro 16ACH6H

### BIOS version

GKCN59WW

### What's wrong?

![Toollkiit error](https://user-images.githubusercontent.com/9665388/220070906-c7f09196-b5ca-4cce-b938-26debb91570e.jpg)

### How to reproduce the bug?

start the app

### What is the behavior that you expected?

start the toolkit

### Logs

[error_2023_02_20_09_38_04.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10783123/error_2023_02_20_09_38_04.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [X] I disabled some things on my own (please write below what you did)

### Additional information

i also tried deinstall all vintage software and then using legion toolkit doesnt work either

**Comment by BartoszCichecki** [comment]
What type of Windows account do you use (admin/regular)?

**Comment by Kraftprotz** [comment]
im using admin
