### ISSUE TITLE
[FEAT]: Actions : Switch GPU working mode

### ISSUE THREAD

**Issue by rezpower** [BartoszCichecki/LenovoLegionToolkit#579]
### Version

2.9.1

### OS

Windows 11 22h2 

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

.

### What alternatives have you considered?

.

### Additional information

I was hoping for an action that would change GPU working mode after running a specific app and after stopping that application.

let me explain what I exactly mean:

I want to set my laptop to always be in Hybrid-iGPU mode. I then want to add few applications (games) in  LenovoLegionToolkit "Actions" and make it switch to Hybrid when I run my games and set the laptop again to Hybrid-iGPU mode when I stop (close) the applications. 

Do you thing this is possible ? wouldn't switching to Hybrid be too late once the game is launched?

**Comment by BartoszCichecki** [comment]
> wouldn't switching to Hybrid be too late once the game is launched?

Unfortunately it would be. Hybrid modes are also not _guaranteed_ to switch due to the way they were implemented by Lenovo - that is the primary reason why they are not included. They are basically almost impossible to automate.

**Comment by 1aTa** [comment]
It would be great if GPU working mode switching could be exposed to CLI to allow something like the following in a batch script:

1) Enable Hybrid-Auto mode
2) Apply MSI Afterburner clocks
3) Start game
4) Once game closes re-enable Hybrid-iGPU mode

I appreciate from reading your comments that GPU switching is not guaranteed however I never have an issue switching manually as long as the game is closed. I don't believe there is any CLI functionality right now so even if they were added to actions would be super handy at this point.

Example batch script:

`@(SETLOCAL
  echo off )

CALL :Main

( ENDLOCAL
  EXIT /B )

:Main
  start "Hybrid-Auto" /D"C:\Users\1aTa\AppData\Local\Programs\LenovoLegionToolkit\" "C:\Users\1aTa\AppData\Local\Programs\LenovoLegionToolkit\Lenovo Legion Toolkit.exe" /Hybrid-Auto
  start "Afterburner" /D"C:\Program Files (x86)\MSI Afterburner\" "C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe" /s
  start "Rocket" /D"C:\Program Files (x86)\Steam\steamapps\common\rocketleague\Binaries\Win64\" "C:\Program Files (x86)\Steam\steamapps\common\rocketleague\Binaries\Win64\RocketLeague.exe"
  CALL :Loop
  TIMEOUT 2
  start "Hybrid-iGPU" /D"C:\Users\1aTa\AppData\Local\Programs\LenovoLegionToolkit\" "C:\Users\1aTa\AppData\Local\Programs\LenovoLegionToolkit\Lenovo Legion Toolkit.exe" /Hybrid-iGPU
GOTO :EOF

:loop
  SET /A "n=10"
  TIMEOUT 10
  tasklist /V /NH /FI "IMAGENAME eq RocketLeague.exe" | FIND /I "Rocket" &&(
    GOTO :loop
  )
GOTO :EOF`
