### ISSUE TITLE
Can it be launching without admin rights?

### ISSUE THREAD

**Issue by younyokel** [BartoszCichecki/LenovoLegionToolkit#58]
Maybe a stupid question. Just a small request that Lenovo Vantage doesn't require admin rights to work while LLT does?

**Comment by BartoszCichecki** [comment]
Yes, because Vantage is not really doing anything on it's own. All of the logic is infact executed with services like "ImController" which runs with elevated (admin) rights. Since Toolkit is a single exe app, it does not have a service, therefore it needs to start with admin rights.

**Comment by BartoszCichecki** [comment]
If you enable autorun, Toolkit configures a scheduled task to start it with admin rights and does not show UAC prompt.
