### ISSUE TITLE
[FEAT]: adding maximum processor frequency modification

### ISSUE THREAD

**Issue by sceraser** [BartoszCichecki/LenovoLegionToolkit#583]
### Version

2.9.1

### OS

Windows 11 22H2

### Device

R9000P 2021H

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

Maximum processor frequency can be changed in LLT

### What alternatives have you considered?

by changing Registry like https://www.majorgeeks.com/content/page/how_to_add_or_remove_maximum_processor_frequency.html

**Comment by BartoszCichecki** [comment]
This option was made obsolete in Windows 10 1807, and doesn't even work properly on many modern systems, therefore it will not be added.

**Comment by sceraser** [comment]
![image](https://user-images.githubusercontent.com/42718757/221418889-81ae99c8-68fe-43b5-a99d-104baadb55a2.png)
works pretty well at my device(R9000P2021H 5800H RTX3060), maybe it could be a hidden experimental function?
