### ISSUE TITLE
[COMPATIBILITY]: 

### ISSUE THREAD

**Issue by viktorbek** [BartoszCichecki/LenovoLegionToolkit#587]
### Version

2.9.1

### OS

Windows 10 Pro 22H2 19045.2604

### Device

Legion 7-16ACHg6

### BIOS version

GKCN59WW

### Which features of the application did you test?

~

### Which features of the application do not work as expected?

Hi!

Why can't I individually adjust the backlight? Corny there is no this section in the program. I wanted to change the backlight color, but I was upset when I didn't find the settings menu.

![image](https://user-images.githubusercontent.com/126261554/221200952-d6e4421f-1cc6-440a-be65-99352653dff8.png)

**Comment by BartoszCichecki** [comment]
It's a gen 6 device from what I see and it uses iCue for RGB control. LLT does not support iCue keyboards as described in readme.
