### ISSUE TITLE
[FEAT]: Add different color for Pop-ups

### ISSUE THREAD

**Issue by GKVStory** [BartoszCichecki/LenovoLegionToolkit#588]
### Version

2.9.1

### OS

Windows 11

### Device

Legion Y7000P 2019

### Is your feature request related to a problem?

When i focus on writing something, the use of CapsLock is quite often. But the colors of the pop-ups are the same, so i have to look the word on the button, it's quite inconvenient.

### How would you like the problem to be solved?

Maybe we can add color on the CapsLock Pop-ups so that we don't have to look the words.

### What alternatives have you considered?

For example, change  "CapsLock On" color red and "CapsLock On" color stay white, then we just have a look at the color to differ from the CapsLock state.

**Comment by BartoszCichecki** [comment]
On/off popups already have a different icon and my opinion is that it's enough, but let's keep this open for now and see what others say.

![Screenshot_20230227_203137](https://user-images.githubusercontent.com/7916915/221664276-ae6821ad-7ae6-49c4-8c09-6d16ba2d2c9a.png)
![Screenshot_20230227_203132](https://user-images.githubusercontent.com/7916915/221664277-df08aa27-db1f-4e6b-b335-a86cd0ee0264.png)
