### ISSUE TITLE
[COMPATIBILITY]: How to disable check device information when start up?

### ISSUE THREAD

**Issue by SoldierRMB** [BartoszCichecki/LenovoLegionToolkit#589]
### Version

2.9.1

### OS

Windows 11 22H2 build 22623

### Device

Legion Y7000P 2020H

### BIOS version

EFCN58WW

### Which features of the application did you test?

Device check when start.

### Which features of the application do not work as expected?

I lost my DMI information when I repaired. When start the program it will prompt me my device is invalid. How to disable it?

### Logs

[log_2023_02_27_00_41_09.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10835318/log_2023_02_27_00_41_09.txt)

### Additional information

![image](https://user-images.githubusercontent.com/75345944/221450369-fd9accd3-2f56-490a-99b6-cb113aa0fee4.png)

**Comment by BartoszCichecki** [comment]
https://github.com/BartoszCichecki/LenovoLegionToolkit#my-motherboard-was-replaced-and-now-llt-gives-me-incompatible-message-what-do-i-do
