### ISSUE TITLE
[BUG]: Single Display Brightness

### ISSUE THREAD

**Issue by Mikistorm10** [BartoszCichecki/LenovoLegionToolkit#598]
### Version

2.10.0

### OS

windows 10 home version 10.0.19045 Build 19045

### Device

Legion 5 Pro 16ACH6H

### BIOS version

GKCN59WW

### What's wrong?

When i enable "single display brightness" on performance mode the laptop is stuck at 115w on the Dgpu. When disabled, come back to normal to 140w. Btw, Hybrid mode disabled 

### How to reproduce the bug?

Just enable the option and play a game with afterburner overlay with gpu power enabled

### What is the behavior that you expected?

idk

### Logs

[log_2023_03_03_20_14_49.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10888047/log_2023_03_03_20_14_49.txt)

I dragged the log in there, let me know if it's the right way to do it

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
There is absolutely no way that this option causes your GPU TGP to drop - this option synchronizes brightness setting on all power plans and that is it. What is more in the log you sent, there was no change in brightness, so this option didn't even do anything.

**Comment by Mikistorm10** [comment]
Well, idk how, but it happened to me. Restarting the laptop doesn't change
anything. Is there a way to help me finding the solution? or it is an
isolated case?

Il sab 4 mar 2023, 16:32 Bartosz Cichecki ***@***.***> ha
scritto:

**Comment by BartoszCichecki** [comment]
No, I understand, but this option is just not related at all to what you are describing, so I am not sure how can I help.
