### ISSUE TITLE
[BUG]: Uncommon shut down

### ISSUE THREAD

**Issue by Han159753** [BartoszCichecki/LenovoLegionToolkit#599]
### Version

2.10.0

### OS

Windows 11 22H2 22623.746

### Device

Lenovo Legion Y7000P2020H 82AX

### BIOS version

EFCN58WW

### What's wrong?

The whole toolkit app crashes after playing a game full screen. In most cases, this would not create an error log, which is another problem. I have this problems about 5 times in the past week, but only one log is created in the indicated folder.

### How to reproduce the bug?

Start up a fullscreen game that will lead Windows to clear out some background software memory. Star Citizen is a good example. After I close the game, I can see that the system RAM used is smaller than before starting the game. Legion Toolkit is killed during this process. It is shut down without notice. When I put my cursor onto the icon at the right bottom corner of Windows, the toolkit icon disappears. I have to restart the program by hand. 

### What is the behavior that you expected?

It should not stop working. Even if it does, there should be a message and a log produced.

### Logs

[error_2023_02_15_06_46_31.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10888522/error_2023_02_15_06_46_31.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Are you maybe using Legion Fan Control?

**Comment by Han159753** [comment]
> Are you maybe using Legion Fan Control?

No. My model is 2020H, which doesn't support manually controlling fan speed.

**Comment by BartoszCichecki** [comment]
Here is a test build that you can try. I added some more logging in hopes of getting a reason of the crashes you have. Try running this build and check if you get more error logs from it.

When you notice LLT crashed, you can also check Windows Event Viewer to see if Windows logged some kind of error about LLT.

Unless we manage to get any information about why the crashes are happening, I won't be able to help.

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10891611/LenovoLegionToolkitSetup.zip)

**Comment by Han159753** [comment]
It hasn't crashed yet after the new version was installed. I will let you know when it crashes as soon as possible.

**Comment by Han159753** [comment]
[error_2023_01_30_04_13_19.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10915306/error_2023_01_30_04_13_19.txt)
I think this file is one of the recorded crashes. It seems to be related to the refreshing rate of the internal display.

**Comment by Han159753** [comment]
By the way, I am connecting my laptop with an external 1080p 240hz display using an HDMI port, which does not support direct connection from my 2060. Maybe this is useful for you.

**Comment by BartoszCichecki** [comment]
> [error_2023_01_30_04_13_19.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10915306/error_2023_01_30_04_13_19.txt) I think this file is one of the recorded crashes. It seems to be related to the refreshing rate of the internal display.

This one is not related.

I suggest you clear the logs and then once a crash happens you zip them and send them over.

**Comment by Han159753** [comment]
I am closely monitoring the log folder, and after you sent me the more logging version, it hasn't crashed yet.

**Comment by BartoszCichecki** [comment]
So let's do this. I will close this issue for now, but if it crashes and you get some logs, please attach them here. Without logs I can't do anything. If it crashes without logs that could mean that LLT process is killed by some other app or Windows for some reason.

**Comment by Han159753** [comment]
It has crashed again today and is still without any logs. Before it crashed, I unplugged my laptop, closed the cap, and took it to another classroom. Then I plugged it in and opened the cap again, and I found out that it crashed. I tried to log in to Onedrive before I found it crashed.
