### ISSUE TITLE
Lenovo Legion 5 15ARH05

### ISSUE THREAD

**Issue by KittenDrone** [BartoszCichecki/LenovoLegionToolkit#6]
== Full model name (i.e. Legion 5 Pro 16ACH6H) ==

Legion 5 15ARH05

== List of features that are working as expected. ==

- Power mode
- fn lock
- touchpad lock
- Hybrid mode
- Disable Vantage 

== List of features that seem to not work (they do nothing). ==

- over drive

== List of features that crash the app. ==

Starting the app.  README says to use --no-compat-check but it's actually --skip-compat-check. I have submitted a patch.

== Features not tested ==

- Always on USB

**Comment by amanrakwal** [comment]
flip to boot?
