### ISSUE TITLE
Simple note on how to update 

### ISSUE THREAD

**Issue by ARYN-27** [BartoszCichecki/LenovoLegionToolkit#60]
Just a few lines like

How to update
- "Exit" the application 
- Download and replace the current "Lenovo.Legion.Toolkit.exe" 
- Start the toolkit with Admin privileges.
- Check if the update is successful by checking the version in "About"

**Comment by BartoszCichecki** [comment]
You mean that there should be an auto update feature?

**Comment by ARYN-27** [comment]
Actually, I meant a how-to guide to updating the toolkit in the README.md; but an auto-update feature will be also great.

**Comment by BartoszCichecki** [comment]
Updated readme, I will look at auto-updating later :)
