### ISSUE TITLE
[BUG]: Device has become unsupported

### ISSUE THREAD

**Issue by MstrThePlague** [BartoszCichecki/LenovoLegionToolkit#602]
### Version

2.10.0

### OS

Windows 11 22H2 22624.1391

### Device

Legion 7 16IAX7 Type 82TD

### BIOS version

K1CN40WW

### What's wrong?

Started my laptop today and am getting the message "This device is not compatible with Lenovo Legion Toolkit", which is strange as it was working yesterday without issue.  The only change I've made in the meantime is to enable a group policy object.

### How to reproduce the bug?

Start Lenovo Legion Toolkit either via the shortcut or at startup.

### What is the behavior that you expected?

The application to run and sit in the task bar.

### Logs

Nothing in AppData\Local\LenovoLegionToolkit\log, the folder is empty

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [x] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please attach logs.

**Comment by MstrThePlague** [comment]
Well, this is a bit weird.  I didn't have any logs to share with you, but I did go back in to Gpedit.msc and reverse the change I made to 

Computer Configuration->Windows Settings->Windows Components->Data Collection and Preview Builds->Allow Diagnostic Data

I had it set to disabled but have now set it to not configured and LenovoLegionToolkit now launches.  Would it be helpful for me to test this further?

**Comment by MstrThePlague** [comment]
[log_2023_03_07_11_27_49.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10908834/log_2023_03_07_11_27_49.txt)

**Comment by BartoszCichecki** [comment]
I disabled the Policy to test and I am not getting any errors. I need a log or at least a screenshot of the message that LLT shows you when it doesn't want to start.

**Comment by MstrThePlague** [comment]
I'll close this bug for now as I can't reproduce what it was doing, I did a snapshot of my device first thing so will revert when I can and provide a screenshot of the window when I can.  Sorry to have raised this and then closed it.
