### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by AzizartheGreat** [BartoszCichecki/LenovoLegionToolkit#608]
### Version

2.10

### OS

Version	10.0.22621 Build 22621

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN49WW

### What's wrong?

When using the **balance** power mode, selecting **enable ai engine** doesn't seem to enable the engine in Lenovo Vantage or visa versa (selecting **enable ai engine** in Lenovo Vantage doesn't enable the engine in Legion Toolkit)

So someone is lying ;-)

### How to reproduce the bug?

1. open Legion Toolkit
2. Go to POWER
3. Select power mode balance
4. Go to settings
5. select enable ai engine and save
6. open Legion Vantage
7. select thermal mode setting
8. look at ai setting on balance (not checked)

1. open Legion Vantage
2. select thermal mode setting
3. select balance AND ai engine
5. open Legion Toolkit
6. Go to POWER
7. Go to settings
8. Look at ai setting 

### What is the behavior that you expected?

1. If you select enable ai engine using the toolkit , you will see the same option enabled on Legion Vantage.
2. If you select enable ai engine using legion vantage , you will see the same option enabled on the Legion Toolkit

### Logs

[log_2023_03_11_16_42_12.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/10948970/log_2023_03_11_16_42_12.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Noone is lying. AI Engine is a purely software option and as indicated in the Readme when both LLT and Vantage are running, not all features will work correctly.

**Comment by AzizartheGreat** [comment]
Sorry, the 'lying' part was a joke because I saw a difference. Of course no
one is lying

Thanks for your reply

Op za 11 mrt. 2023 17:48 schreef Bartosz Cichecki ***@***.***
