### ISSUE TITLE
Refresh Rate switcher targeting incorrect monitor

### ISSUE THREAD

**Issue by ldstein** [BartoszCichecki/LenovoLegionToolkit#61]
Hi, I noticed a small issue in Legion Toolkit v1.6:

When an external monitor is attached, the "Built-in Display" toggle is changing the refresh rate of the external monitor, not the built-in display.

Tested on a 2021 Legion 7 5800H / 3070.

**Comment by BartoszCichecki** [comment]
Thanks for reporting this. When I implemented this, I couldn't find a solid way of detecting which monitor is internal, but was hoping that it's solid enough.
Since then I found out about WmiMonitorConnectionParams which will probably be a lot more reliable. I'll try to include it in next hotfix ;)

**Comment by BartoszCichecki** [comment]
https://github.com/BartoszCichecki/LenovoLegionToolkit/commit/bdc00f2b299423d5c7566bfcee90b9cfb113228d
