### ISSUE TITLE
[FEAT]: Boot animation change

### ISSUE THREAD

**Issue by XHeiHi** [BartoszCichecki/LenovoLegionToolkit#613]
### Version

2.10.0

### OS

Windows 11 22H2 22621.1344

### Device

legion R7000P2021H

### Is your feature request related to a problem?

Want to change the boot animation

### How would you like the problem to be solved?

Add the ability to change the boot animation

### What alternatives have you considered?

无

**Comment by KarlLee830** [comment]
You can try https://github.com/Coxxs/LogoDiy

**Comment by BartoszCichecki** [comment]
You will be happy to hear that there has been some progress on changing the boot logo.

**Comment by BartoszCichecki** [comment]
Here is a very early build. Works on Gen 5, 6 and 7. Gen 8 probably has some differences so boot logo doesn't seem to change.

Image must be exactly the resolution of the screen, there seems to be some maximum size constraint (relevant for BMP). There also seems to be some conflict with Vanguard DRM where boot logo doesn't get applied and stays default.

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12448821/LenovoLegionToolkitSetup.zip)

**Comment by bcutter** [comment]
Very interesting (2.17.0 release).

Does this feature has the possibility of damaging the system? Afaik boot logo is part of the UEFI, modifying stuff in there is kind of dangerous per default. Is there some kind of error correction (input verification, test prior to first restart/boot etc.)?

**Comment by BartoszCichecki** [comment]
@bcutter I updated the README and described how this works [here](https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/master/README.md#boot-logo)

**Comment by bcutter** [comment]
Thanks. I don't have a "Gen 6 or 7" laptop (I think), it's not a Legion at all and therefore "unsupported". As the software does not filter/check/block this, I tend to stay away from this basically extremely nice feature.
