### ISSUE TITLE
[FEAT]: Performance Optimization

### ISSUE THREAD

**Issue by RoadToDream** [BartoszCichecki/LenovoLegionToolkit#616]
### Version

2.10.0 

### OS

Windows 11 22H2 22621.1413

### Device

Legion 7i 16IAX7

### Is your feature request related to a problem?

May I ask if anyone else experienced the interface feels choppy when on HiDPI display? Especially when the window is maximized. If this is expected behavior, is it possible to optimize the UI rendering performance. If not expected, is there anything I may do wrong about the application? 
Thanks! 

### How would you like the problem to be solved?

Maybe optimization on UI rendering by buffering WPF element? 

### What alternatives have you considered?

None till now.

**Comment by BartoszCichecki** [comment]
A word of comment from my side here:

WPF like many recent UI frameworks is hardware accelerated, which also means that it might run on dGPU. To avoid this LLT is forced to use software rendering which is slower. For this reason the UI will never be perfectly smooth especially on high DPI, high refresh rate screens.

**Comment by RoadToDream** [comment]
Thank you for the explanation! I was not aware that LLT is rendering in SoftwareOnly mode. I guess I can close this ticket and compile myself if really needed (fully understand your concern for this choice).
