### ISSUE TITLE
[FEAT]: I would like an option to set shortcuts

### ISSUE THREAD

**Issue by aschuhl** [BartoszCichecki/LenovoLegionToolkit#618]
### Version

2.9.1

### OS

Windows 11

### Device

Legion 7 16ACHg6

### Is your feature request related to a problem?

I would like an option to set shortcuts (I apologize if there is a place and I can't find it).

Control-shift-l appears to be used to start performance logging, but that is also the shortcut of a popular password manager's password completion ([bitwarden](https://bitwarden.com/)). 

### How would you like the problem to be solved?

I would like to be able to set this shortcut to some other keybinding.

### What alternatives have you considered?

I could look to changing bitwarden's keybinding, but I use it across various devices and would rather keep and change this one since it is only for my Legion laptop.

**Comment by BartoszCichecki** [comment]
What shortcut are you talking about? LLT doesn't bind to any keyboard shortcuts.
