### ISSUE TITLE
[BUG]: Cannot switch to Custom Mode

### ISSUE THREAD

**Issue by CNSCSQ** [BartoszCichecki/LenovoLegionToolkit#620]
### Version

2.11.0

### OS

Windows 11 22H2 Build 22624.1391

### Device

Lenovo Legion R9000P2021H

### BIOS version

GKCN59WW

### What's wrong?

In the software console interface, when switching performance mode to custom mode, will automatically switch back to the previous performance mode, stable reproduction, followed by my manual installation of Lenovo Vantage this problem disappeared, but I do not want to install two Lenovo Manager at the same time, please see if the problem can be fixed on Lenovo Zone, the following log provided is not installed Lenovo Vantage test when the test log

### How to reproduce the bug?

1. Open "Console"
2. Click on the "drop-down menu" of "Performance Mode"
3. Click on "Custom Mode"

### What is the behavior that you expected?

Restore the ability to switch custom modes under the Lenovo Zone service

### Logs

[log_2023_03_18_05_52_43.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11007617/log_2023_03_18_05_52_43.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [X] I disabled some things on my own (please write below what you did)

### Additional information

Lenovo Zone is installed
In the software disable Lenovo Zone
![image](https://user-images.githubusercontent.com/40529518/226088743-badd251c-599d-467f-bf91-1272a83fab30.png)

**Comment by BartoszCichecki** [comment]
Please try this build: [LenovoLegionToolkitSetup_hotfix.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11007898/LenovoLegionToolkitSetup_hotfix.zip)

**Comment by BartoszCichecki** [comment]
Please also upload `%LOCALAPPDATA%\LenovoLegionToolkit\godmode.json` file.

**Comment by BartoszCichecki** [comment]
Please try this build: [LenovoLegionToolkitSetup_hotfix2.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11008065/LenovoLegionToolkitSetup_hotfix2.zip)

**Comment by BartoszCichecki** [comment]
Tested with a different user.
