### ISSUE TITLE
[FEAT]: 

### ISSUE THREAD

**Issue by HandsomeYDZ** [BartoszCichecki/LenovoLegionToolkit#626]
### Version

2.11.2

### OS

Win11

### Device

Y7000P 2020H

### Is your feature request related to a problem?

None

### How would you like the problem to be solved?

None

### What alternatives have you considered?

I hope to add the functionality of "LegionFanControl", so that I can maximize fan speed to increase my CPU frequency.(You know, beast mode doesn't maximize the fan speed) If you ask me why not just use the LegionFanControl,  I just want to say that it will take up my taskbar space.(lol) And if that works, thank you for your efforts！

**Comment by BartoszCichecki** [comment]
There is a max fan option inside Custom Mode settings and that's the only option that is possible to implement with what Lenovo provided.
