### ISSUE TITLE
[FEAT]: Ability to change Touchpad Cursor Speed as quick action

### ISSUE THREAD

**Issue by DOGGOWoo** [BartoszCichecki/LenovoLegionToolkit#629]
### Version

2.11.2

### OS

Windows 10 Pro 22H2 19045.2728

### Device

Lenovo Ideapad 3 15ACH6

### Is your feature request related to a problem?

No, just a feature request.

### How would you like the problem to be solved?

I would like a quick action that allows you to set the touchpad cursor speed. It would be useful for people who like to use the touchpad for drawing purposes. By quick action I mean as a step (like how you can change battery mode as a step).

### What alternatives have you considered?

I believe it might be possible to do this without implementing it as a specific feature (ie just making a script) but I couldn't find any information on that. By Sensitivity, I don't mean the Touchpad Sensitivity option but the "Cursor Speed" option.

**Comment by BartoszCichecki** [comment]
I will keep this issue open, in case there is some interest in this, but I suggest you look into power she'll scripts and run them using Run action if you need this option.

**Comment by BartoszCichecki** [comment]
Closing as there doesn't seem to be any interest from others for adding this feature.

If this is really important I suggest making a script and using the Run step in actions. Googling returns couple examples, for example: https://stackoverflow.com/questions/71194925/cmd-command-application-to-change-mouse-sensitivity .
