### ISSUE TITLE
Don't change brightness after Power Plan change 

### ISSUE THREAD

**Issue by vkingoff** [BartoszCichecki/LenovoLegionToolkit#63]
I want you to ask to add the feature: don't change screen brightness when I change power plans with Fn+Q.
It's especially useful in dark room.

**Comment by BartoszCichecki** [comment]
Nice one, I'll take a look at this - it might be useful.

For now I know that brightness i changing because this is how windows power plans work. You can set lower brightness for all power profiles and at least it will not get super bright.

**Comment by BartoszCichecki** [comment]
Can't find any reliable way to do it unfortunately, so I'm closing the issue.
