### ISSUE TITLE
[FEAT]: Ability to select on which gpu to run an app.

### ISSUE THREAD

**Issue by InsanityM** [BartoszCichecki/LenovoLegionToolkit#630]
### Version

2.11.2

### OS

Windows 10 21H2 iot

### Device

Lenovo Legion 5 15ARH05 ( 4800h gtx 1650)

### Is your feature request related to a problem?

Feature request. I would like to have an option to quickly select on which gpu to run an app. Also an option to run all programs on integrated gpu while i am on battery mode and while i use the charger to have all programs running on dgpu. Right now there is an option from "action" screen to either kill the apps running on dgpu or restart the dgpu, but that is of no use for me. Right now i can somehow do this from windows settings. Under display setting in graphics setting i can select on which gpu to run an app, but it is a hassle to change it every time. I would like something more automatic if it is possible. Thanks for this awesome program anyway that completely replaced lenovo vantage for me.

### How would you like the problem to be solved?

With the knowledge of the developer. :-)

### What alternatives have you considered?

Maybe something even more simple. When i unplug the laptop all programs to run on integrated gpu. Even this would be very useful.

**Comment by BartoszCichecki** [comment]
As you know these setttings are in Control Panel. There is no API these options so it can't be done currently.
