### ISSUE TITLE
[BUG]: RTX 3070Ti is 150 watts but when I create a new power mode, it stays only at 140w 

### ISSUE THREAD

**Issue by etson32** [BartoszCichecki/LenovoLegionToolkit#632]
### Version

2.11.2

### OS

Windows 11 22H2 22621.1413

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN58WW

### Which features of the application did you test?

Custom performance mode

### Which features of the application do not work as expected?

My gpu is RTX 3070ti and it shows up to 150 watts but when I create a new power mode, it stays only at 140w, when I modify the dynamic boost bars and the power for the gpu they don't work correctly

### Additional information

The GPU Subsystem Power (W) of RTX 3070ti its to 120 - 125w on my model, but 25 - 30w more with dynamic boost.
https://www.nvidia.com/en-us/geforce/laptops/compare/30-series/

**Comment by BartoszCichecki** [comment]
Logs?

**Comment by BartoszCichecki** [comment]
> they don't work correctly

What does that mean?

**Comment by etson32** [comment]
With this configuration I expected to have 150w

<img width="860" alt="Captura de pantalla 2023-03-22 110434" src="https://user-images.githubusercontent.com/57652634/226971003-aae9a8be-dfc7-4a4b-a0b3-b6f1bebfbec4.png">

But the power limit is up to 140

<img width="567" alt="only 140w" src="https://user-images.githubusercontent.com/57652634/226971464-8c5bad82-e9b9-4a29-8ab4-fd50edd34423.png">

**Comment by BartoszCichecki** [comment]
Will you upload logs or should I just close this issue?

**Comment by etson32** [comment]
yes, I attached the log

[log_2023_03_22_16_30_01.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11042454/log_2023_03_22_16_30_01.txt)
