### ISSUE TITLE
[FEAT]: Different tray symbol for each Power Mode

### ISSUE THREAD

**Issue by bobdig** [BartoszCichecki/LenovoLegionToolkit#633]
### Version

2.11.2

### OS

Win10 22H2

### Device

Legion 5 17ACH6H

### Is your feature request related to a problem?

-

### How would you like the problem to be solved?

-

### What alternatives have you considered?

I use my laptop as a desktop replacement and have it closed all the time. Now I am not able to tell for sure which power mode is active because I can't see the LED on the keyboard. 
It would be fantastic, although not urgent at all, if the tray symbol would change according to the power modes. Some simple color changes like the LED colors would do.
Thanks for reading. 

PS: Fan control for 2021 models is not planned, even if it is running without problems with LFC? I like the idea of only using your tool though. Thanks.

**Comment by BartoszCichecki** [comment]
No plans for altering the tray icon, sorry.
