### ISSUE TITLE
[BUG]: In the "Custom" Power-profile, the power limits are not applied immediately

### ISSUE THREAD

**Issue by Audianer1990** [BartoszCichecki/LenovoLegionToolkit#634]
### Version

2.11.2

### OS

Windows 10 22H2

### Device

Legion 5 17ACH

### BIOS version

GKCN59WW

### What's wrong?

Hello,
I have specified certain power limits in the "Custom" power profile, otherwise the CPU will get too hot. CPU 30 watts and GPU maximum. If I now switch to the profile, the performance profile always comes first. Only when I select the custom again is it activated. However, it does not accept the power limits, it only accepts the power limits when I go to the custom profile and save there again.

### How to reproduce the bug?

See in "Whats wrong"

### What is the behavior that you expected?

I dont know

### Logs

.

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

[Logs.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11043715/Logs.zip)

**Comment by Audianer1990** [comment]
[Logs.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11043722/Logs.zip)

Here...but i´m note care if there a right...

**Comment by BartoszCichecki** [comment]
I am not sure what you sent but it's not it. Instruction for collecting logs are on the project page [here](https://github.com/BartoszCichecki/LenovoLegionToolkit#how-to-collect-logs).

**Comment by BartoszCichecki** [comment]
The log contains no errors, Custom Mode limits are applied correctly when you select "Custom" mode from the dropdown as well as when you hit Apply in the Custom Mode settings window.

If this doesn't seem to work, I suggest trying EC reset as the problem seems to be not in LLT. I also can't reproduce the behavior.
