### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by gawtDamn** [BartoszCichecki/LenovoLegionToolkit#638]
### Version

2.11.99

### OS

Win 11 22H2 Build 22621.1413

### Device

Legion 5 pro 16ARH7H

### BIOS version

JUCN55WW

### What's wrong?

Was playing a VR game in hybrid mode. unplugged VR headset and main power adapter, plugged in USB-c power adapter. LLT Crashed, with its window going gray. An error message popped upUCERR_RENDERTHREADFAILURE(0x88980406)   then it popped up several instannces of the same error message. 

### How to reproduce the bug?

unknown how to reproduce. First time I've see it on this version of LLT.

### What is the behavior that you expected?

not crashing.

### Logs

will turn on logging so this can be caught with logs next time. 

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Render thread failure indicates incompatibility with GPU drivers and is something out of my control. Sorry.

**Comment by BartoszCichecki** [comment]
> The majority of render thread failures are caused by WPF attempting to utilize the hardware rendering pipeline in a way that exposes some flaw in the driver.

Ref: https://learn.microsoft.com/en-us/troubleshoot/developer/dotnet/framework/general/wpf-render-thread-failures
