### ISSUE TITLE
[BUG]: Forza Horizon from MS Store is not detected as a game.

### ISSUE THREAD

**Issue by nadtorus** [BartoszCichecki/LenovoLegionToolkit#641]
### Version

2.11.2

### OS

Windows 11 Version 22H2 (OS Build 22621.1413)

### Device

Legion 7i 16ITHg6

### Is your feature request related to a problem?

The Action feature, which I have 1 step in it to change the Power Mode to Custom when the game is running/closed does not work for every game. I don't know why my Forza Horizon 5 doesn't trigger this action so I need to change it manually  from Lenovo Legion Toolkit.

### How would you like the problem to be solved?

I understand it may be really difficult to detect every game out there. If it's possible, I'd like to have the Custom Mode in power mode cycle when using Fn+Q shortcut. Thank you!

### What alternatives have you considered?

Make a separated shortcut (not using the Fn+Q).

**Comment by BartoszCichecki** [comment]
> I'd like to have the Custom Mode in power mode cycle when using Fn+Q shortcut

That is not possible.

Regarding game detection, check in Gamebar (Win+G) when running the game if this checkbox is selected.

![image](https://user-images.githubusercontent.com/7916915/227782338-c07d3cf2-bb5c-4fd5-b669-c21821d95b53.png)

If it is and it still doesn't work, upload logs, we'll take a look what's up.

**Comment by nadtorus** [comment]
The checkbox isn't available since GameBar already detects it as a game.
![image](https://user-images.githubusercontent.com/111151039/227993085-3fef09f0-2c85-4cc2-a6af-0aa55aff718a.png)

Here's the log file, I did it by opening the log-enabled LLT mode and then opening FH5.
[log_2023_03_27_15_39_03.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11080545/log_2023_03_27_15_39_03.txt)

Thank you.

**Comment by BartoszCichecki** [comment]
Yeah, Forza is not in the log for some reason...

Can you export `HKEY_CURRENT_USER\System\GameConfigStore` key from the registry and upload it here?

![image](https://user-images.githubusercontent.com/7916915/228047339-62cae2a4-d6b7-44a2-a0c0-86edd494be5e.png)

**Comment by nadtorus** [comment]
Okay, here's the file you requested.
[GameConfigStore.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11086193/GameConfigStore.zip)

**Comment by BartoszCichecki** [comment]
It seems there is one more "format" of paths so I will need to add support for that. Seems like some MS Store games might be affected.

Ref: https://superuser.com/questions/1539461/is-this-registry-string-inconsequential

**Comment by BartoszCichecki** [comment]
That is an interesting result. I tested with Forza Horizon from MS Store and the while 2.11 doesn't recognise it as a game the updated one worked fine.

On top of what is already in 2.11 the build above also utilises something called "effective power mode" which should be set to "game" by Windows and for me Windows was correctly setting it when Forza was already started and full screen.

Not sure if I can improve it more.

**Comment by nadtorus** [comment]
I just did a windows update before doing the test (to OS Built 2261.1482). Does it have something to do with this?

Anyway, I'm fine with the latest results. It's not perfect in my case but I can live with that. Thank you so much. So is it fine to use the 2.11.99? or I should wait for the official next release?

**Comment by BartoszCichecki** [comment]
You can use this version until next release :)

**Comment by nadtorus** [comment]
Okay, thanks!
