### ISSUE TITLE
[BUG]: unexpected exception occured: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by clav64** [BartoszCichecki/LenovoLegionToolkit#643]
### Version

2.11.2

### OS

Windows 11 Education 22H2

### Device

Legion S7  15ACH6

### BIOS version

HACN37WW

### What's wrong?

During system start up, after both shut down and restart, the lenovo legion toolkit displayes the following message:

"unexpected exception occured: Object reference not set to an instance of an object", asking me to report it here.

### How to reproduce the bug?

1. start up system
2. Log in
3. wait for system to load
4. double click on lenovo legion toolkit in system tray
5. lenovo legion toolkit displayed
6. error appears

### What is the behavior that you expected?

No error should appear. On clicking OK, the erro disappears and the program closes. 

Re-opening the program from start menu does not produce the error, only occurs at system start up.

### Logs

Unable to produce logs as Legion will start without error when starting in this manner. 

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
If you go to %LocalAppData%\Lenovo LegionToolkit\log are there any error logs?

**Comment by DOGGOWoo** [comment]
Had something similar to this error happen every time I hovered over the icon to get the popup. Here is a log, maybe it helps.
[error_2023_03_21_18_34_57.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11095944/error_2023_03_21_18_34_57.txt)

**Comment by BartoszCichecki** [comment]
@clav64  @DOGGOWoo The crash seems to be coming from deep inside WPF and I can't reproduce.

Could you please check if the build below improves the situation?

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11105710/LenovoLegionToolkitSetup.zip)

**Comment by BartoszCichecki** [comment]
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11106275/LenovoLegionToolkitSetup.zip)

**Comment by DOGGOWoo** [comment]
Well, I only had this error happen twice (according to the log files names, once on 20/3/2023 and again on 21/3/2023). Since I'm now running windows 11, I have not had this error happen again.

**Comment by BartoszCichecki** [comment]
Merging current possible fix, due to lack of responses. It doesn't break anything, it may not solve it but it's an improvement.

If issue persists in 2.12, please re-open this issue.
