### ISSUE TITLE
[FEAT]: Ability to Re-arrange Quick Actions

### ISSUE THREAD

**Issue by DOGGOWoo** [BartoszCichecki/LenovoLegionToolkit#650]
### Version

2.11.2

### OS

Windows 11 Pro 22H2 22621.1413

### Device

Lenovo Ideapad 3 15ACH6

### Is your feature request related to a problem?

Nope, just wanted the ability to re-arrange the Quick Actions. Currently, it is not possible to re-arrange the quick actions, which means the most recently added action goes to the top. 

### How would you like the problem to be solved?

While this is a very small feature to add, I feel like it would improve the Toolkit experience since you wouldn't have to re-adapt your muscle memory every time you added a new Quick Action (Also I'm mostly adding this feature request since I've now started messing with powershell more and more and that "Run" action is VERY handy)

### What alternatives have you considered?

I tried to drag the quick actions up and down, but doesn't seem to work.

**Comment by DOGGOWoo** [comment]
oh my god I'm dumb
Ok, is it ok if I ask another question here? What do I do if Legion Toolkit says "Finished running with errors"? The logs folder doesn't appear to have an error in it.

**Comment by BartoszCichecki** [comment]
You need to enable logging and look through the main log.

**Comment by DOGGOWoo** [comment]
Perfect, it works now, thanks :D


Also in-case anyone who reads this wonders how to enable logging, go to the main code section and down to "How to collect logs"
