### ISSUE TITLE
[BUG]: [16IAX7 ] PL1/PL2 switch from custom mode not changing

### ISSUE THREAD

**Issue by rickygjun** [BartoszCichecki/LenovoLegionToolkit#651]
### Version

2.12 beta4

### OS

Windows 11 22H2 22621.1485

### Device

Legion 7 16IAX7 - Type 82TD

### BIOS version

K1CN40WW

### What's wrong?

When I switch from Custom mode to Quiet mode, the PL1 and PL2 power limit doesnot change.
I have noticed this issue only happens when switching from Custom mode to Quiet mode, switching from Custom mode to other mode (balance, performance) all working as expected.

### How to reproduce the bug?

1. Switch to Custom mode
2. Switch to Quiet mode

### What is the behavior that you expected?

The power limit will remain on Custom mode value.

### Logs

[log_2023_03_30_22_59_41.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11116849/log_2023_03_30_22_59_41.txt)
![image](https://user-images.githubusercontent.com/125786452/228985399-30f1dcd1-85d9-4345-b1ee-f38eb61f50f8.png)
![image](https://user-images.githubusercontent.com/125786452/228985417-d8eb87ce-389e-41e1-b313-a3dc078a3308.png)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
@rickygjun check this one out. I think it works for me, so let's see if you get similar results.

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11124288/LenovoLegionToolkitSetup.zip)

**Comment by rickygjun** [comment]
Hi @BartoszCichecki , I can confirm the above build works fine for me. It seems like it switch to Performance mode quickly, and then quiet :)
