### ISSUE TITLE
[FEAT]: Application based Profiles.

### ISSUE THREAD

**Issue by hemiipatu** [BartoszCichecki/LenovoLegionToolkit#653]
### Version

2.11.2

### OS

Windows 11 22H2 Build 22621

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

The feature I am requesting is **NOT** related to a software or hardware problem that I am aware of; Nor is the software _(LenovoLegionToolkit)_ causing a problem - Everything works as it was intended.

However, unlike the Legions of old that are compatable with iCUE, the newer ones with Spectrum don't have the option to create "application/software based lighting profiles".

### How would you like the problem to be solved?

I would like to request the development and implementation of "application/software based lighting profiles" that enable the user to create additional profiles to the current six. Additionally, these profiles should be completely customisable the same as the current ones but have have the ability to be bound to a specific application(s) which would determine whether it'd activate when the aformentioned application(s) are in-use.

For reference; https://help.corsair.com/hc/en-us/articles/4424235581837-Link-a-custom-iCUE-profile-to-a-game

_I apologize in advance if my explanation/request is not clear as I am not great at explaining._

### What alternatives have you considered?

I have checked other projects such as Spectrum, OpenRGB and SignalRGB for such a feature but they either don't support the 7th generation of Legion laptops or the feature is not currently implemented. I have therefor decided to request it.

**Comment by BartoszCichecki** [comment]
I guess I could add a trigger for "When app is in foreground" and then you can assign one of the 6 profiles to some EXE that is currently running. Would that be enough? You could also utilize the "When app is running" trigger and assign a backlight profile when a program is running which would almost be enough (combined with when app is stopped to revert to some "default" profile that you use otherwise).

You will need to pick one of the 6 profiles anyway, as introducing more will be very very tricky giving how the RGB controller works.

**Comment by hemiipatu** [comment]
Hi @BartoszCichecki,

Apologies for the late reply! You're pretty close to what I had in mind but additional to your statement/suggestion; is it possible to setup profiles which are 'saved' or 'stored' inside the Toolkit itself **NOT** the controller. 

When "when app is in forground/running" detects a pre-defined executable which is bound to one of the 'saved' or 'stored' profiles it would automatically apply aformentioned profile to one of the 6 stored on the controller? Reverting back to a different profile once "when app is in background/stopped" is detected.

In theory this would allow countless profiles to be made. In theory.


I am really poor at explaining so here is what is going on in my head with the idea;
1. .exe is launched.
2. Toolkit detects the .exe automagically or via a launch script?
3. Toolkit checks if .exe has a profile saved/stored.
4. Toolkit finds a saved/stored profile.
5. Toolkit applies the saved/stored profile to a predefined slot on the controller. Let's say the last _(6 of 6)_
6. .exe is closed, terminated, put in background.
7. Toolkit detects this.
8. Toolkit reverts to a predefined slot of the controller. Let's say the first _(1 of 6)_ 

I hope this helps you understand my thoughts process. Thank you in advance for taking the time.

**Comment by BartoszCichecki** [comment]
Hmmm I guess, if I added an "Import profile" step to Actions that would make it possible to do what you want.

You could save a number of profiles on the the disk (with existing Export function) and then load them with Actions when app/game is started.

**Comment by hemiipatu** [comment]
That sounds plausible. I hope it does indeed work if you decide to work on such a feature.
