### ISSUE TITLE
[FEAT]: Automatic preservation

### ISSUE THREAD

**Issue by YamadaHideki** [BartoszCichecki/LenovoLegionToolkit#656]
### Version

2.11.2

### OS

Windows 11

### Device

Lenovo Legion 5 17ARH05H

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

I would like to see a function so that when the battery is charged to {n%}, the mode itself switches to preservation.

### What alternatives have you considered?

You can't do this in Actions, there's not enough functionality.

### Additional information

With love <З

**Comment by YamadaHideki** [comment]
edit title

**Comment by BartoszCichecki** [comment]
What's the purpose of this?

**Comment by YamadaHideki** [comment]
> What's the purpose of this?

When you connect a laptop to the charger at 20%, I want it to go into preservation mode itself when the charge is 80%, for example. Now I have to change it manually.

**Comment by BartoszCichecki** [comment]
So you want to enable conservation mode at different than standard level? For example at 80% instead of 60%?

**Comment by YamadaHideki** [comment]
> So you want to enable conservation mode at different than standard level? For example at 80% instead of 60%?

For example yes. But I don't have any % of it on right now. It always goes to 100%, and I have to control it manually.

**Comment by BartoszCichecki** [comment]
There is already a ticket for triggering actions at specific % of battery but the chances of this being done are next to zero due to issues. Check discussion in: #564.

**Comment by BartoszCichecki** [comment]
There is already a ticket for triggering actions at specific % of battery but the chances of this being done are next to zero due to issues. Check discussion in: #564.

**Comment by YamadaHideki** [comment]
Sad
