### ISSUE TITLE
[BUG]: Battery still charge when Conservation mode enabled

### ISSUE THREAD

**Issue by ivanius51** [BartoszCichecki/LenovoLegionToolkit#657]
### Version

2.11.2

### OS

Windows 10 22H2

### Device

Legion 5 17ACH6H

### BIOS version

GKCN59WW

### What's wrong?

Battery charging to 100% while is "Conservation" mode was enabled.

### How to reproduce the bug?

1. Use battery until 60-90%
2. Open Dashboard
3. Set Battery mode to "Conservation"
4. Check battery status - changing 

### What is the behavior that you expected?

When battery already charged to 60%+ its stop charging in "Conservation" mode.

### Logs

no logs are created

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Error appear after last update.

**Comment by BartoszCichecki** [comment]
I would ask you to verify again.  There were no changes to battery charging configuration related code for like 5 or 6 releases now. I suggest EC reset.

**Comment by ivanius51** [comment]
Hmm, same, but I think It's can be by last BIOS version (GKCN59WW) from GKCN57WW.
Thank you for answer.

**Comment by ivanius51** [comment]
EC reset and reinstall driver back conservation mode (guide on official lenovo site, known issue).

**Comment by sakgoyal** [comment]
This is happening for me too!
Lenovo y700p-1060
Machine Type: `81LF`
Bios: `9VCN22WW`
