### ISSUE TITLE
[BUG]: .Net desktop runtime forward compatibility

### ISSUE THREAD

**Issue by gerab** [BartoszCichecki/LenovoLegionToolkit#658]
### Version

2.11.2.0

### OS

Windows 11 22H2 22621.1485

### Device

Legion 7 16ACHg6 

### BIOS version

GKCN59WW

### What's wrong?

It stopped working. 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/4732243/230305800-bf9dd8dc-fea9-4366-b8a5-b27ca3c51ffc.png">

### How to reproduce the bug?

1. Start the app
2. Warning windows will appear.
3. Clicking yes or no won't do anything. 
4. The app won't run.

### What is the behavior that you expected?

The requirements check should be more like > 6.0.14 && < 7.0.0, not exactly 6.0.14. I have 6.0.15 installed.

### Logs

The app won't start so it doesn't produce any logs.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Thank you for being so supportive of Ukraine.

**Comment by BartoszCichecki** [comment]
Please check readme next time before making an issue.

https://github.com/BartoszCichecki/LenovoLegionToolkit#problems-with-net

**Comment by gerab** [comment]
Nice to know you have a specific readme point I mentioned in the bug description: I DO HAVE NET INSTALLED. It would be best if you still read the bug description sometimes. Ok, I'll try to fix it on my own.

**Comment by BartoszCichecki** [comment]
That is the requirement. If it still doesn't work reinstalling .net usually fixes the problem.

**Comment by gerab** [comment]
As expected, it didn't help. I had to publish a self-contained app that works well despite losing settings.
