### ISSUE TITLE
[BUG]: Popup.OnWindowResize: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by BraveSam** [BartoszCichecki/LenovoLegionToolkit#662]
### Version

2.11.2

### OS

Windows 11 22H2 Build 22621

### Device

Legion 5 15ACH6H

### BIOS version

GKCN59WW

### What's wrong?

Legion Toolkit crashes randomly (I don't know how or when it happens exactly) and gives an exception error.

### How to reproduce the bug?

I don't know, it usually happens when I click the taskbar icon to open it but it doesn't always crash.

### What is the behavior that you expected?

The program not to crash

### Logs

[error_2023_04_08_17_30_27.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11183792/error_2023_04_08_17_30_27.txt)
[error_2023_04_08_17_30_34.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11183793/error_2023_04_08_17_30_34.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please try this build: [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11183871/LenovoLegionToolkitSetup.zip)

This issue was reported before, but the author wasn't interested in troubleshooting, so let me know if the situation is better in this build.

Related #643

**Comment by BraveSam** [comment]
thanks! I'll try it out

**Comment by BartoszCichecki** [comment]
Did you notice an improvement?

**Comment by BraveSam** [comment]
Can confirm latest version 2.12.0 still has the bug related #673 
[error_2023_04_19_18_06_48.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11276405/error_2023_04_19_18_06_48.txt)
[error_2023_04_19_18_09_00.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11276406/error_2023_04_19_18_09_00.txt)

**Comment by BartoszCichecki** [comment]
@eddie-LA: https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/673#issuecomment-1641089810
