### ISSUE TITLE
[FEAT]: Date based automation task

### ISSUE THREAD

**Issue by Ghost-chu** [BartoszCichecki/LenovoLegionToolkit#663]
### Version

2.11.2

### OS

Windows 11 22H2 Build 22621.1485

### Device

Legion R9000P

### Is your feature request related to a problem?

I need to protect my battery, so my battery is usually in care mode.
But every Monday I need to bring my laptop to school to use it, and it runs out of power because I often forget to switch the charging mode back to regular.
If I could specify a date for the automated task to be performed, I could have the laptop switch back to regular mode on Mondays and back to care mode on Tuesdays.

### How would you like the problem to be solved?

I would like to automate tasks that can be executed on a specified day of the week.
So far I have only found execution triggers based on a specific time.

### What alternatives have you considered?

If the program could provide a CLI, I might be able to do this with a task scheduler.

### Additional information

For your time, I am very grateful.
This program saved me a lot of tedious operations and it works perfectly. Thank you for your excellent work, more powerful and better than Lenovo's official application.

Thank you very much for your dedication!

**Comment by Ekscentricitet** [comment]
I sat down to see if I can implement it by allowing the user to specify a date in the same manner as time is specified now. I got to adding the prompt to the WPF form and realized that we would need to allow a different max value for the day number based on the selected month. While this is not that difficult to implement, it made me realize that the whole "trigger on a very specific date" idea will be used less than the effor that it will yet take to add it and solve all of the problems that will occur (one that I have in mind, for example, is what should be the max year for such a trigger and what will be the practical purpose of setting an action to take place in 2050 or one year from now). 

Tomorrow I will try a different approach by allowing the user to specify a day of the week along with time, which should be more useful and is exactly what you described as a feature. A second opinion if this approach is acceptable would be appreciated @BartoszCichecki. Some refactoring had/has to be done to the PipelineTrigger, but it is not that problematic.

**Comment by Ekscentricitet** [comment]
Alright, I have implemented it. The solution might not be that elegant so suggestions would be appreciated. However, I do not have the rights to push my branch. @BartoszCichecki how can I request write access to the repository?

**Comment by BartoszCichecki** [comment]
> how can I request write access to the repository?

You should fork this repository and submit a pull request. Check [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by BartoszCichecki** [comment]
> Tomorrow I will try a different approach by allowing the user to specify a day of the week along with time, which should be more useful and is exactly what you described as a feature.

Also, yes, I think day of week would be enough here instead of "real" dates.

**Comment by Ekscentricitet** [comment]
@BartoszCichecki Thanks! It is my first time with such a workflow and I appologize for not researching better. I have made the pull request. Let me know what can be improved.
