### ISSUE TITLE
[FEAT]: Can't update via app while in China

### ISSUE THREAD

**Issue by Windows11-MEMZ** [BartoszCichecki/LenovoLegionToolkit#666]
### Version

2.11.2

### OS

WIndows1122H2 25536.1000

### Device

Legion R9000P ARH7H

### Is your feature request related to a problem?

Can't update just in app,must goto github download it,but in chinese,github is very slow

### How would you like the problem to be solved?

add a function

### What alternatives have you considered?

just download it

**Comment by BartoszCichecki** [comment]
Closing the issue then. Moving the project to other hosting than GitHub is not a feasible option atm.

**Comment by Windows11-MEMZ** [comment]
> 这主要是由于 中国大陆 年 GFW 对 Github 的 DNS 缓存污染以及 GFW 在 中国大陆 年对国际网络导出的随机干扰。所以没有解决这个问题的好方法。

凌卡，可以使用Kgithub的镜像获得最新版本并检测，下载更新，刚刚我已经让BingGPT生成了示例C++代码了，证明了可行性
