### ISSUE TITLE
[FEAT]: Would be nice to have a hex code field for RGB colors.

### ISSUE THREAD

**Issue by ZZZXXX0110** [BartoszCichecki/LenovoLegionToolkit#669]
### Version

2.11.2

### OS

Windows 11 current latest build

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

No just a quality of life feature suggestion :)

### How would you like the problem to be solved?

In the UI panel for configuring the color for each keyboard RGB element, it would be very nice to also have a hex code input field alongside the fields for separate RGB color values, and having the hex field and RGB field matching to each other (converted between) each time one is changed.

As a quality of life feature, this makes it more convenient to copy and paste each color, as only one value would need to be copied/pasted instead of three. As such this is also a standard feature seen on most RGB color management suite, even though none of them are currently available to the 7th+ gen Legion laptops as of yet.

### What alternatives have you considered?

This can be very simply a conversion between RGB values and hex code, there should be numerous different simple ways to implement this either using external libraries or perhaps features already built-in in the UI framework that's currently being used.

**Comment by BartoszCichecki** [comment]
Good idea. I will try to add it in one of next releases. (Probably 2.13.0, because 2.12 is almost ready for release).
