### ISSUE TITLE
Feature Request - Refresh Rate shortcut.

### ISSUE THREAD

**Issue by Undervoltologist** [BartoszCichecki/LenovoLegionToolkit#67]
Can you add a refresh rate change shortcut? I currently use HRC to change the refresh rate on my Legion 5, Ctrl+1 for 120hz, Ctrl+2, for 60hz. Is it possible to implement something like this in your app? (an auto refresh rate changer when plugging/unplugging the laptop would be even better) Cheers!

**Comment by BartoszCichecki** [comment]
That is on the roadmap at some point.

Issues #54 and #36.
