### ISSUE TITLE
[FEAT]: More RGB effects

### ISSUE THREAD

**Issue by kevtran101** [BartoszCichecki/LenovoLegionToolkit#671]
### Version

2.12.0

### OS

Windows 11 22h2 home pro

### Device

Legion 5i 15IAH7H

### Is your feature request related to a problem?

Kind of. The rgb options included with Ltk are limited. While rgb keyboard control offers more effects. I was wondering if it would be possible to add some of those options, especially smooth wave, or maybe a way you could make Ltk complement rgb keyboard control

### How would you like the problem to be solved?

Possibly adding more options for rgb effects or a way for it to complement rgb keyboard control.

### What alternatives have you considered?

Using rgb keyboard control. Only problem with it is that it doesn’t run on startup and when you close the lid, it doesn’t turn off the rgb.

**Comment by BartoszCichecki** [comment]
Only RGB effects natively supported by RGB controller are supported in LLT. Check readme: https://github.com/BartoszCichecki/LenovoLegionToolkit#can-i-have-more-rgb-effects
