### ISSUE TITLE
[FEAT]: Add minimum value offset adjustment option for CPU temperature in custom mode preset.

### ISSUE THREAD

**Issue by xxhhlk** [BartoszCichecki/LenovoLegionToolkit#675]
### Version

2.5.12

### OS

Windows 10 Pro 22H2 19045.2846

### Device

Legion Y9000P IAH7H

### Is your feature request related to a problem?

Probably won't be relevant to any issue... but I'd appreciate it.
For some reason, I need to set it to a lower temperature every night. While there are other software that can do this, it would be easier to do it with one software and not have to worry about multiple software all controlling the CPU temperature limit.

### How would you like the problem to be solved?

For me, it is enough to set the minimum CPU temperature 10 (minimum 75) lower. But really, if you can change it to allow custom settings, it will be more applicable to others.

### What alternatives have you considered?

Setting the PROCHOT offset in ThrottleStop is an alternative.

### Additional information

I have tried to change the "Value" (not the "Min") in the godmode.json file and it works fine after testing, but it is overridden to the default value when saving the preset through the UI.
Additionally, the GPU temperature limit value is not effective below 75. And I think the power limit minimum value is small enough.

**Comment by BartoszCichecki** [comment]
Hey,

Check this build and let me know if it works as expected:
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11290339/LenovoLegionToolkitSetup.zip)

**Comment by xxhhlk** [comment]
Hello,

Yes, I tested it and it works correctly. But the various drop-down lists, including the tray menu, would flicker and be difficult to select.
