### ISSUE TITLE
[FEAT]: Option to turn Virtualization ON/OFF in bios!

### ISSUE THREAD

**Issue by rezpower** [BartoszCichecki/LenovoLegionToolkit#676]
### Version

2.12.0

### OS

Windows 11 22h2 22621.1555

### Device

Legion 7i 2022 16IAX7

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

I think that LenovoLegionToolkit has access to bios settings and some of the changes we make are applied to bios. So I was wondering if it would be possible to also have an option to "Enable/Disable" Virtualization from LenovoLegionToolkit without the need to do into the bios. Maybe we would still need to restart the PC for changes to be applied, but it will still be more practical then making the change through bios.

The reason I am asking this is because some of us use "ThrottleStop" or "XTU" to for undervolting and these apps do not work with Virtualization enabled. A fast switch would allow us to enable virtualization when needed. (Ex: to use vmware etc..) 

### What alternatives have you considered?

Ideal would be that LenovoLegionToolkit allow us to undervolt up to 200mV the CPU Core, and the P and E cache! But I'm not sure this could be easily implanted.

**Comment by BartoszCichecki** [comment]
No feature except Flip To Boot is easily exposed from BIOS and this one would still require reboot so there would be very little value in doing this, even if it was possible.
