### ISSUE TITLE
[BUG]: LLT override FN+R double switches refresh rate with one keypress

### ISSUE THREAD

**Issue by bfrancom22** [BartoszCichecki/LenovoLegionToolkit#678]
### Version

2.12.0

### OS

Win11 Home 22621.1555

### Device

Legion S7 16IAH7

### BIOS version

JYCN49WW

### What's wrong?

I have the LLT FN key override (Lenovo Hotkeys disabled). I have 3 total refresh rates on my computer 60hz 120hz and 165hz. When I press Fn+R to switch refresh rates, I see the screen flicker twice. It is acting as if I am pressing FN+R twice in rapid succession, effectively skipping the next refresh rate in line, and going from #1 to #3, or #3 to #2, etc. I have tried deleting one of them and running only 2 refresh rates, but it puts me back where I start. So if I try to go #1 to #2, it flickers twice and puts me back where I started at #1. Once my display is done changing (twice), the notification for the refresh change shows the correct one, immediately followed by the second one it shouldn't have switched to.

### How to reproduce the bug?

Disable Lenovo Hotkeys, change refresh rate with Fn+R with built in LLT functionality

### What is the behavior that you expected?

I expect it to switch only one refresh rate at a time, not 2.

### Logs

[log_2023_04_19_06_57_48.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11269638/log_2023_04_19_06_57_48.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
After checking your log I can see that refresh rate is changed correctly and it cycles between 90 > 120 > 165. If you look at timestamps of these events (beginning of the line) there is at least 1 second delay between them (pic 1), so Fn+R events are debounced correctly (pic 2).

Pic 1:
![image](https://user-images.githubusercontent.com/7916915/233064266-ad4e73d9-04cf-4b8e-b35c-a2a96e4c1466.png)

Pic 2:
![image](https://user-images.githubusercontent.com/7916915/233065187-9afefaf3-6607-4284-a447-8a42e2d3ad0a.png)

**Comment by BartoszCichecki** [comment]
Actually let me take a look at this since the debounce period should be 2 seconds not one.
