### ISSUE TITLE
MUX switch randomly failing

### ISSUE THREAD

**Issue by ARYN-27** [BartoszCichecki/LenovoLegionToolkit#68]
The MUX switch randomly fails and sometimes refused to switch the display over to dGPU. 
 Before coming to the conclusion, I tried
 
  - DDU the graphics driver 
  - Performed a clean graphic driver installation
  - Installed Nvidia Driver 496.13 [Known to not mess up MUX]
  - Install Nvidia Driver provided by Lenovo [Nvidia Driver 472.56]

But when I turned off LenovoLegionToolkit and switched to Vantage, the MUX worked properly. So I tried again with LenovoLegionToolkit and the MUX activates and fails to switch to iGPU. Had to reset the graphics card with [Alt+Crtl+Shift+b].  

Problem started after updating to LenovoLegionToolkit version 1.6.2.

[log_2022_01_03_14_51_21.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/7800703/log_2022_01_03_14_51_21.txt)

**Comment by BartoszCichecki** [comment]
When you say it is randomly failing you mean that dGPU does not activate when you start a game for example? Or the screen goes black or what exactly? Is the Toolkit in the foreground or in tray? And when you says it fails to switch to iGPU only, what processes are listed by nVidia driver? (You can enable optimus indicator in tray from nVidia Control Panel)

**Comment by ARYN-27** [comment]
I am asking regarding the MUX switch. 
- `When you say it is randomly failing you mean that dGPU does not activate when you start a game for example?`
   - Yeah, the game usually triggers the MUX to use dGPU as a display driver. If it doesn't it sends the signal through the iGPU for display.

**Comment by BartoszCichecki** [comment]
Ok, so your laptop has Advanced Optimus right?

**Comment by ARYN-27** [comment]
> When you say it is randomly failing you mean that dGPU does not activate when you start a game for example? Or the screen goes black or what exactly? Is the Toolkit in the foreground or in tray? And when you says it fails to switch to iGPU only, what processes are listed by nVidia driver? (You can enable optimus indicator in tray from nVidia Control Panel).
> 
> I understand we are talking about Optimus not MUX switch.

I am asking regarding the MUX switch. 
- `When you say it is randomly failing you mean that dGPU does not activate when you start a game for example?`
   - Yeah, the game usually triggers the MUX to use dGPU as a display driver. If it doesn't it sends the signal through the iGPU for  #display.

**Comment by ARYN-27** [comment]
> Ok, so your laptop has Advanced Optimus right?

I think so. As per my understanding, MUX and Advanced Optimus are different things; but I figured out what was causing the whole issue. It was "ColorPicker.exe" from Microsoft PowerToys that was causing the issue. Once I turned of the ColorPicker module, the issue went away.
