### ISSUE TITLE
[BUG]: Dead link in FAQ entry

### ISSUE THREAD

**Issue by zwresn453** [BartoszCichecki/LenovoLegionToolkit#681]
### Version

-

### OS

-

### Device

-

### BIOS version

-

### What's wrong?

The [FAQ entry](https://github.com/BartoszCichecki/LenovoLegionToolkit#my-motherboard-was-replaced-and-now-llt-gives-me-incompatible-message-what-do-i-do) titled:  _"My motherboard was replaced and now LLT gives me incompatible message. What do I do?"_  has a link to an article, which no longer points to the article (laptopwiki.eu/index.php/guides-and-tutorials/important-bios-related-guides/recover-original-model-sku-values), and instead redirects to the homepage.

### How to reproduce the bug?

1. [https://github.com/BartoszCichecki/LenovoLegionToolkit#my-motherboard-was-replaced-and-now-llt-gives-me-incompatible-message-what-do-i-do](https://github.com/BartoszCichecki/LenovoLegionToolkit#my-motherboard-was-replaced-and-now-llt-gives-me-incompatible-message-what-do-i-do)
2. Click on "You should try [this tutorial](https://laptopwiki.eu/index.php/guides-and-tutorials/important-bios-related-guides/recover-original-model-sku-values/)"
3. The link redirects to the homepage

### What is the behavior that you expected?

The original article is not available on archive.org, but I found another article (possibly the same article but at a different URL?) available on archive.org: [https://web.archive.org/web/20221207073038/https://laptopwiki.eu/index.php/docs/lvar-recovery/](https://web.archive.org/web/20221207073038/https://laptopwiki.eu/index.php/docs/lvar-recovery/)

I didn't read the original article so I don't know if this one can replace the one that is currently shown in the FAQ.

### Logs

-

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Thanks, updated link.
