### ISSUE TITLE
[BUG]: GPU Working Mode Setting not saved after restart

### ISSUE THREAD

**Issue by rezpower** [BartoszCichecki/LenovoLegionToolkit#683]
### Version

2.12.0

### OS

Windows 11 22h2 22621.1555

### Device

Legion 7i 2022 16IAX7

### BIOS version

k1cn40ww

### What's wrong?

Since I installed LenovoLegionToolkit 2.12.0 GPU Working Mode Settings are no longer saved when I restart my laptop. I was used to leave this setting to "Hybrid - iGPU" and it was working perfectly. But after 2.12.0 install when I restart my PC in LenovoLegionToolkit I can still see that GPU Working Mode is set to "Hybrid - iGPU" , but the dGPU is also active (Both in device manager and in LenovoLegionToolkit! I uninstalled 2.12.0 and installed 2.11.2, but the problem is still present!
<img width="1138" alt="Screenshot 2023-04-20 153500" src="https://user-images.githubusercontent.com/28585954/233399825-70aaebf6-1822-414f-a7e5-c585ca2d1ef3.png">

### How to reproduce the bug?

Open legion toolkit and set GPU Working Mode to Hybrid-igpu
then restart PC and check if this setting is still applied.

### What is the behavior that you expected?

Before the GPU Working Mode Settings were always same as what I choose and would remain after PC reboot.

### Logs

.

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Because it's not a problem with LLT. In hybrid iGPU only mode, dGPU will not be ejected if it's in use or if EC doesn't eject it.
