### ISSUE TITLE
[FEAT]: Portable Release

### ISSUE THREAD

**Issue by ConcurrentCrab** [BartoszCichecki/LenovoLegionToolkit#685]
### Version

2.12.0

### OS

Windows 10

### Device

Ideapad 3 Gaming

### Is your feature request related to a problem?

N/A

### How would you like the problem to be solved?

Hi! Thank you for creating this lovely application.

Can a portable option be added to the releases? Just a zip of the executable's folder.

Thanks!

### What alternatives have you considered?

N/A

**Comment by BartoszCichecki** [comment]
What is the benefit of a portable release?

**Comment by ConcurrentCrab** [comment]
I programatically script installation and upgrades of my programs in non-admin contexts, which a zip package would enable.

**Comment by BartoszCichecki** [comment]
I see. I don't plan to introduce portable. LLT requires account with admin rights (see readme) and there are plans of introducing windows service which would need installer to run as admin anyway.

**Comment by ConcurrentCrab** [comment]
> LLT requires account with admin rights (see readme)

I know, but that's only during runtime, when I am in front of the screen. There isn't really a requirement for install/update process currently.

> and there are plans of introducing windows service which would need installer to run as admin anyway.

In that case, I may suggest something that other portable programs usually do, and create a script to install/uninstall that service if the user desires to use those features (I am assuming the service will only be relevant for service-like things e.g. event handling, and not other features like toggling settings statically). So then the installer wizard simply becomes a program that exracts a package and then runs that script.

In any case, these are just my suggestions. Your decision would be understandable either way. Thanks again!
