### ISSUE TITLE
[BUG]: Cannot disable nvidia gpu. says monitor is connected

### ISSUE THREAD

**Issue by gsabater** [BartoszCichecki/LenovoLegionToolkit#687]
### Version

2.12

### OS

win 11 22h2 22624.1616

### Device

legion 5 pro

### BIOS version

dont know

### What's wrong?

I cannot disable the nvidia gpu. A tooltip says that a monitor is connected. (Nothing is connected)
I tried to shut down displays, but the message of monitor connected persists.
The issue persists after a reboot as well.

### How to reproduce the bug?

option greyed out

### What is the behavior that you expected?

i used to disable on previous builds of the toolkit

### Logs

--

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
You didn't attach log, you didn't put full model name and you didn't even put a BIOS name. How am I supposed to look into this? 
Check your Advanced Optimus settings and Hybrid mode.

Can't reproduce the issue.

**Comment by gsabater** [comment]
I might be retarded, but the issue was that hybrid mode wasnt active.
I reinstalled the app and forgot to enable the option.
Maybe the message could be more clear and state that hybrid mode was disabled, but now is working fine.
