### ISSUE TITLE
[FEAT]: Show "AC-Power" when using AC power only (battery at 100% and connect to charger)

### ISSUE THREAD

**Issue by Ace-Radom** [BartoszCichecki/LenovoLegionToolkit#688]
### Version

2.12.0

### OS

Windows 11 22H2 Build 22621

### Device

Legion R9000p 2021H

### Is your feature request related to a problem?

No: it's just a normal feature request, doesn't relate to any problem on software or hardware

### How would you like the problem to be solved?

If I've remembered that correctly, in some software like AIDA64, the Discharge Rate will display as something like AC Power (maybe, I don't actually know what it look like in english version), not 0.00W when the battery is at 100% full and also using AC Power only.
I don't know if it's okay when asking you to add this battery-use-judgement into LTT.

I'm also trying to open a PR and solve this feature request by myself, but it seems to be too hard for me lol.

### What alternatives have you considered?

Well, this is definitely not a necessary feature, therefore i've not considered other alternatives.

### Additional information

![image](https://user-images.githubusercontent.com/104905842/233773605-c13f4b57-ecc1-4b4a-bd9c-96261bb19f57.png)
The thing I want to change are here: `Discharge Rate` under `Battery` and in the bar menu.

**Comment by BartoszCichecki** [comment]
You mean you would like to see how much power is used from AC? As far as I know there is no way to find out, but it's an interesting idea.

**Comment by Ace-Radom** [comment]
Right that's exactly what I meant (although maybe I didn't explain what I thought clearly)
Yeah I know it may be quite hard...anyway I'll continue work on it and see if I can find a solution for that. And also thx for your reply xD

**Comment by BartoszCichecki** [comment]
Checked AIDA64, but it doesn't report power consumption for whole system on the machines I have available so I'd say that it isn't supported on most Legions.

**Comment by Ace-Radom** [comment]
> Checked AIDA64, but it doesn't report power consumption for whole system on the machines I have available so I'd say that it isn't supported on most Legions.
>
> This would indicate that there isn't a "sensor" anywhere that reports this. After searching internet also seems that this isn't possible.

I see...well it might be the difference between different laptops (I mean also different manufactures). Anyway thx
