### ISSUE TITLE
[BUG]: Hybrid mode switch appearing as on, even when no iGpu active

### ISSUE THREAD

**Issue by Nero51** [BartoszCichecki/LenovoLegionToolkit#689]
### Version

2.12.0

### OS

Windows 11 22H2 build 22621.1555

### Device

Legion 5 15ACH6H

### BIOS version

GKCN60WW

### What's wrong?

Even if disabled, **hybrid mode switch** will pop up as activated and deactivating it, will prompt a restart that does nothing (it was turned off already)

### How to reproduce the bug?

Just open the toolkit, sometimes, randomly, the hybrid mode switch will apper as turned on.

### What is the behavior that you expected?

that the switch should match the actual gpu mode

### Logs

[log_2023_04_22_09_52_26.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11301034/log_2023_04_22_09_52_26.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [X] I disabled some things on my own (please write below what you did)

### Additional information

<img width="921" alt="image" src="https://user-images.githubusercontent.com/104154719/233776819-2fef0dbe-bf38-4e30-ba8b-27cf58efd12c.png">

**Comment by BartoszCichecki** [comment]
Hybrid mode status is always read from BIOS/EC. It is a known issue on some BIOS versions.

**Comment by Nero51** [comment]
Ok thank you, I didn’t know it. Il giorno 22 apr 2023, alle ore 12:06, Bartosz Cichecki ***@***.***> ha scritto:﻿
Closed #689 as not planned.
