### ISSUE TITLE
Legion T5 28IMB05 support

### ISSUE THREAD

**Issue by CE1CECL** [BartoszCichecki/LenovoLegionToolkit#69]
Ref: https://github.com/ViRb3/LenovoController/issues/4

![Capture](https://user-images.githubusercontent.com/52040854/148462403-24556aec-ef20-4ac6-8354-4ff6cad2ba2e.PNG)

**Comment by BartoszCichecki** [comment]
There are too many differences between desktop and laptop Legions. Support will not be added.
