### ISSUE TITLE
[FEAT]: Please take it back: CPU Boost Mode settings

### ISSUE THREAD

**Issue by Ricky2576** [BartoszCichecki/LenovoLegionToolkit#690]
### Version

2.12.0

### OS

Windows11

### Device

Y9000P2022

### Is your feature request related to a problem?

CPU Boost Mode settings are removed, while I need it.
And I'm confused about what happened to the CPU Boost Mode settings that have been modified by me during the update to v2.12.0.

### How would you like the problem to be solved?

Just want it back: CPU Boost Mode settings.

### What alternatives have you considered?

Some alternatives software or solution which can modify CPU Boost Mode.

### Additional information

Please at least explain why it was removed, and what happens to the CPU Boost Mode settings that have been modified during the update to v2.12.0. 
Thanks.

**Comment by BartoszCichecki** [comment]
CPU boost modes are a property of Windows power plans - this is why there is no need to duplicate these settings in LLT. See readme for details.

**Comment by Ricky2576** [comment]
> CPU boost modes are a property of Windows power plans - this is why there is no need to duplicate these settings in LLT. See readme for details.

Thank you for your explanation. I apologize for not seeing the details in the readme by myself. I only checked the release notes of the version 2.12.0. It would be helpful if you could add these details into it. 
However, the other question I mentioned has not been answered yet, which is “What happened to the CPU Boost Mode settings that I modified before the update to v2.12.0?” It may be a silly question, but I’m really not sure about this, and I don’t want to leave any issue unresolved. Did the CPU Boost Mode settings of the Windows system remain unchanged or revert to the default after the update? Thank you again.

**Comment by mind12** [comment]
> > CPU boost modes are a property of Windows power plans - this is why there is no need to duplicate these settings in LLT. See readme for details.
> 
> Thank you for your explanation. I apologize for not seeing the details in the readme by myself. I only checked the release notes of the version 2.12.0. It would be helpful if you could add these details into it. However, the other question I mentioned has not been answered yet, which is “What happened to the CPU Boost Mode settings that I modified before the update to v2.12.0?” It may be a silly question, but I’m really not sure about this, and I don’t want to leave any issue unresolved. Did the CPU Boost Mode settings of the Windows system remain unchanged or revert to the default after the update? Thank you again.

It will remain unchanged.
