### ISSUE TITLE
[BUG]: Toolkit mistakenly shows nvidia discrete gpu as "powered off" when it is on and running searchapp.exe

### ISSUE THREAD

**Issue by user270452967850** [BartoszCichecki/LenovoLegionToolkit#691]
### Version

2.12.0

### OS

windows 10

### Device

Legion 7 16ITHg6

### BIOS version

H1CN47WW

### What's wrong?

toolkit is telling me my gpu is off but nvidia activity panel says its on. this started happening shortly after i updated to 2.12.0. i've only seen it happen when the sole program using gpu is searchapp.exe.

### How to reproduce the bug?

1. launch a game
2. close the game
3. check if nvidia gpu activity panel shows gpu as active and running "searchapp.exe"
4. open toolkit
5. it will show gpu as powered off

### What is the behavior that you expected?

to show gpu as active and allow me to kill searchapp.exe like i could before updating to 2.12.0

### Logs

[log_2023_04_23_05_17_42.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11302879/log_2023_04_23_05_17_42.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information
The only other program i ever see in activity panel is rktuwp.exe, and when thats running toolkit shows the gpu as active, and allows me the kill apps/deactivate gpu options as expected. If searchapp and rktuwp are both running, everything works as expected and the kill apps command kills both apps. The problem only occurs when searchapp is the sole program in nvidia activity panel

**Comment by BartoszCichecki** [comment]
If LT is telling you that GPU is powered off, then it is powered off. Or at least nVidia API is reporting that GPU was powered down.

The activity indicator that you can enable from nVidia Control Panel (the one in tray) has a huge delay in showing the real state of GPU so it's not uncommon that it will show "old" state. LLT checks the status much more frequently and precisely.
