### ISSUE TITLE
[BUG]:  Power mode Custom does not update CPU Thermal Limit when computer restarts

### ISSUE THREAD

**Issue by kaelib12** [BartoszCichecki/LenovoLegionToolkit#693]
### Version

2.12.0

### OS

Windows 11 , Newest

### Device

Legion 7 16IAX7

### BIOS version

K1CN40WW

### What's wrong?

Apon computer restart, the custom power mode is not setting the CPU Temp Limit (I set it to 100c). It looks like it is, but testing with throttlestop shows that it is indeed locked to 97c, not to the 100c that I have set it to until I set the computer it to performance mode then back to custom mode. Doing this makes the Temp Limit setting work.

### How to reproduce the bug?

Set Custom Mode Power Option
Set CPU Temp Limit to 100c
Save it and restart computer
run cinebench or some other program to test temp limit (while monitoring with hwInfo or something)
You will see it throttles at 97c not 100c
swap to performance mode then back to custom mode to make the 100c temp limit start working
test again with cinebench
Now you can see it hits 100c

### What is the behavior that you expected?

The 100c limit to kick in on restart, it is not (I have the Lenovo Legion Toolkit set to start minimized on restart).

### Logs

none sadly

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

This is a minor bug, as you shouldn't in normal use be hitting 97 or 100, just a weird bug I noticed.

**Comment by kaelib12** [comment]
Found the issue, had to just start it as Autostart, Delayed

**Comment by BartoszCichecki** [comment]
I don't think that is the issue, but rather some weird behaviour of the EC in the way limits are applied. These are not uncommon, but sadly I can't fix them because "bugs" (if any) are in the EC's code not in LLT.
