### ISSUE TITLE
[FEAT]: Select fans speed from any range in Custom Mode Settings.

### ISSUE THREAD

**Issue by wiluszdamian** [BartoszCichecki/LenovoLegionToolkit#696]
### Version

2.12.0

### OS

Windows 11 22H2 build 22621.1635

### Device

Legion 5 Pro 16IAH7H

### Is your feature request related to a problem?

Currently, we can only move at specific points, e.g. 0 RPM -> 1700 RPM -> 1800 RPM etc, when editing the custom mode settings on the fan speed curve.
![image](https://user-images.githubusercontent.com/40581509/234398011-bafb3c63-bf53-4a85-bdd1-a0cfd63d8286.png)

### How would you like the problem to be solved?

I want the user to choose which RPM range they want to select, e.g. 1000 RPM, not be forced to select one of a dozen ranges on the curve. 

### What alternatives have you considered?

Alternatively, reduce the speed range so that 1700rpm is not the minimum option (in addition to 0rpm) if it is not possible to give the user a choice.

**Comment by BartoszCichecki** [comment]
Speeds are predefined by Lenovo in the EC firmware and there is no way to customize them unfortunately.

Related #408.

**Comment by richardsolti** [comment]
LegionFanControl seem to be able to se it as low as 600RPM, how does that work?

**Comment by BartoszCichecki** [comment]
> LegionFanControl seem to be able to se it as low as 600RPM, how does that work?

Check related issue to find out.
