### ISSUE TITLE
[FEAT]: Support white backlit keyboards on 2023 Legion 7 Pro (Y9000P 2023) (Machine Type 82WQ)

### ISSUE THREAD

**Issue by pengweiqhca** [BartoszCichecki/LenovoLegionToolkit#697]
### Version

2.12.0

### OS

Windows 11 22624

### Device

Legion Y9000P IRX8H

### Is your feature request related to a problem?

No.

### How would you like the problem to be solved?

Use legion zone.
![image](https://user-images.githubusercontent.com/3982826/234828060-31220af7-6527-4a55-b654-0f2998dbde6e.png)

### What alternatives have you considered?

No.

**Comment by BartoszCichecki** [comment]
You need to provide more information.

1. Logs from current version
2. What type of keyboard backlight is it (white/per-key rgb/4-zone rgb)?
3. How many backlight levels are there?
4. What are the current keyboard shortcuts to control the keyboard?

**Comment by BartoszCichecki** [comment]
> 1. Who's log? LLT(folder is empty) or legion zone?
https://github.com/BartoszCichecki/LenovoLegionToolkit#how-to-collect-logs

**Comment by BartoszCichecki** [comment]
Also,

> white/per-key

You mean it's white only or you can set each key color separately?

**Comment by pengweiqhca** [comment]
Sorry, I misunderstand, Is single color, not per-key.

**Comment by pengweiqhca** [comment]
[log_2023_04_27_10_34_38.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11342461/log_2023_04_27_10_34_38.txt)

**Comment by BartoszCichecki** [comment]
OK so the place you want to debug is here:

https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/68f341e255d4874cf3461e8c16d14c8d0d3e581f/LenovoLegionToolkit.Lib/Features/WhiteKeyboardBacklightFeature.cs#L15

Please check what value do you have in `outBuffer` on line 17 (or if you get an exception). It might be that Lenovo either uses a different result code or they changed the interface completely.

**Comment by pengweiqhca** [comment]
Exception in https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/master/LenovoLegionToolkit.Lib/Features/AbstractDriverFeature.cs#L83.

**Comment by BartoszCichecki** [comment]
It looks like there is again another method for controlling the backlight unfortunately. 

I will need to do some reverse engineering so it will probably take some time.

**Comment by Zysor** [comment]
Legion Slim 7 also cannot change change keyboard backlight with FN + Backspace

**Comment by BartoszCichecki** [comment]
Related #772

**Comment by BartoszCichecki** [comment]
@pengweiqhca Hey, could you try version 2.14.1, and run `SpectrumTester.exe`? I would like to see what kind of keyboard do you have. It will also try to adjust brightness as a test to see if the keyboard is responding.

**Comment by BartoszCichecki** [comment]
I would also appreciate output of this PS command: `Get-WmiObject -namespace root\WMI -class LENOVO_LIGHTING_DATA`

**Comment by BartoszCichecki** [comment]
And one last thing: can you test this build?
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11838045/LenovoLegionToolkitSetup.zip)

**Comment by pengweiqhca** [comment]
Sorry, I already sold it for other reasons, I can't test.

**Comment by BartoszCichecki** [comment]
That's ok, I managed to find someone with 2023 Slim 7 who did some tests and I think it's ok to assume that this will be solved for 2023 7 Pro too.
