### ISSUE TITLE
[BUG]: Multiple Lighting Effects with whole Keyboard effects aren't working

### ISSUE THREAD

**Issue by tpuppe92** [BartoszCichecki/LenovoLegionToolkit#698]
### Version

2.12.0

### OS

Windows 11  22H2 Build  22621.1555

### Device

Legion Pro 7 16IRX8H

### BIOS version

KWCN28WW

### What's wrong?

When adding/modifying a lighting effect that affects the whole Keyboard all other Effects disappear.(e.g there is a predefined Profile with a ripple effect that combines a color pulse effect for the front lighting and when adjusting the ripple effect the socond effect disapears)

### How to reproduce the bug?

1: Go to Keyboard
2: Choose Preset 3 (Ripple + color pulse)
3: Click on the Edit Button for the ripple effect
4: Change "Speed" to "Fast"
5: Press "Apply"
6: the second Effect disappears
Default State:
![image](https://user-images.githubusercontent.com/18326572/234865527-fe27254a-4942-4583-9464-ab83702bca62.png)
After Editing:
![image](https://user-images.githubusercontent.com/18326572/234865782-7b12bd95-9b10-4a61-8a8f-47fdf61fae63.png)

### What is the behavior that you expected?

The second effect should stay if it only affects the front RGB bar

### Logs

[log_2023_04_27_12_19_14.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11343392/log_2023_04_27_12_19_14.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please attach a screenshot with the effects you have and what is the result state.

**Comment by tpuppe92** [comment]
I've done that!
Thanks for the great work 👍

Bartosz Cichecki ***@***.***> schrieb am Do., 27. Apr. 2023,
14:23:
