### ISSUE TITLE
[Feature Request] Performance Mode GPU Overclocking Control

### ISSUE THREAD

**Issue by OttCS** [BartoszCichecki/LenovoLegionToolkit#70]
Firstly, thanks for a fantastic program, this saves a ton of headache!
The only big feature that I like in Vantage is the "Enable GPU Overclocking" option in performance mode. The separate power plans are a nice touch that controls a lot more than Vantage ever did, but the GPU Overclocking option helped to boost performance consistently.

![image](https://user-images.githubusercontent.com/76815426/148563348-c1ccc5f3-df05-4341-9130-dd569b7cf27b.png)

![image](https://user-images.githubusercontent.com/76815426/148563470-25b42ed3-5d9e-42d0-89eb-fe3b69970b21.png)

Thanks!

**Comment by BartoszCichecki** [comment]
Thanks!

I'll try to look into it, but my Legion does not have this option in Vantage, so I am not sure if I will be able to do it.

**Comment by OttCS** [comment]
Sounds good, just a little more device info in case there's a hardware difference that makes the option appear: (I don't know what's useful or not, I'm just trying to provide any help I can):

Lenovo Legion 5:
- AMD Ryzen 5 4600H
- 16.0 GB RAM
- NVIDIA GeForce 1660 Ti (Driver version 497.29)

If there's any way I can assist with this feature, let me know.

**Comment by OttCS** [comment]
SUMMARY: Closing issue because the feature isn't needed.

Generally, the Vantage-allowed overclock  doesn't do enough to matter, and users who are actually looking to get good results from overclocking aren't using Vantage. I've honestly swapped over to using EVGA Precision X1 to activate the 1660ti's boost clock and it's markedly better.
