### ISSUE TITLE
[FEAT]: Add the "I/O ports" and "Y logo" backlight control (including Actions support)

### ISSUE THREAD

**Issue by Ptilopsis01** [BartoszCichecki/LenovoLegionToolkit#701]
### Version

2.12.0

### OS

Win11 22H2 22621.1635

### Device

Legion Y9000X IAH7(S7 16IAH7)

### Is your feature request related to a problem?

No

### How would you like the problem to be solved?

There's a "port backlight" option to control the port backlight in actions

### What alternatives have you considered?

As described above

**Comment by BartoszCichecki** [comment]
There has been discussions about adding this in #223, #428, #649, #665. The issue is that while someone found a way to control it, there isn't a known way to check if specific laptop models support it. I want to avoid hardcoding model names since it's a high-maintenance solution.

I will keep this issue open and change it to include lid light (aka Y logo backlight), since this regularly attracts attention.

**Comment by BartoszCichecki** [comment]
There has been a small development: compativility can be checked using class `LENOVO_UTILITY_DATA` method `GetIfSupportOrVersion `.

Parameter for panel logo is `13` and ports backlight is `14`.

**Comment by BartoszCichecki** [comment]
Test build: 
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11759659/LenovoLegionToolkitSetup.zip)

**Comment by Ptilopsis01** [comment]
> Can you send the log?

[log_2023_06_15_15_38_06.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11760092/log_2023_06_15_15_38_06.txt)

**Comment by BartoszCichecki** [comment]
Let's try this one: 
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11760117/LenovoLegionToolkitSetup.zip)

BTW, do you see this option in Vantage/LegionZone?

**Comment by Ptilopsis01** [comment]
> Let's try this one: [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11760117/LenovoLegionToolkitSetup.zip)
> 

OK, it's usable now

> BTW, do you see this option in Vantage/LegionZone?

I've already not used Lenovo vantage for a long time since I found LLT😂

**Comment by BartoszCichecki** [comment]
> I've already not used Lenovo vantage for a long time since I found LLT

Haha ok :) I am asking because this version doesn't have "is supported" check. So you laptop reports that ports lighting is not supported, but it actaully is. Lenovo's mess is always amazing to work with :)

**Comment by Ptilopsis01** [comment]
> > I've already not used Lenovo vantage for a long time since I found LLT
> 
> Haha ok :) I am asking because second version doesn't have "is supported" check. So you laptop reports that ports lighting is not supported, but it actaully is. Lenovo's mess is always amazing to work with :)

I remember that there's the option in Legion Zone when I used it the last time, but I've just checked and didn't find it in Lenovo vantage

**Comment by BartoszCichecki** [comment]
@Ptilopsis01 Can you run these two commands for me on PowerShell as admin?

`(Get-WmiObject -namespace root\WMI -class LENOVO_UTILITY_DATA).GetIfSupportOrVersion(12)`
`(Get-WmiObject -namespace root\WMI -class LENOVO_UTILITY_DATA).GetIfSupportOrVersion(13)`

**Comment by BartoszCichecki** [comment]
One more test build: 
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11763852/LenovoLegionToolkitSetup.zip)

**Comment by Ptilopsis01** [comment]
> One more test build: [LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11763852/LenovoLegionToolkitSetup.zip)

Nothing wrong with it
By the way, will this option be added into actions?

**Comment by BartoszCichecki** [comment]
Yes :)
