### ISSUE TITLE
[BUG]: HidD_SetFeature Failed (RGB Keyboard reverts back to demo waterfall rainbow)

### ISSUE THREAD

**Issue by Punkd86** [BartoszCichecki/LenovoLegionToolkit#703]
### Version

2.12.0

### OS

Windows 11 Home 10.0.22621 build 22621

### Device

Lenovo Legion PRO 5i 82S0

### BIOS version

Lenovo J2CN49WW, 11/25/2022

### What's wrong?

<img width="860" alt="Screenshot 2023-05-03 101645" src="https://user-images.githubusercontent.com/132475102/235960740-0d712e78-2d65-47d5-8d8d-644b65479afc.png">

The Keyboard randomly and often (almost constantly) reverts to the demo rainbow waterfall mode and when I go to change it back I see the error in the screenshot

### How to reproduce the bug?

Wait a minute or 2 and it will just happen.

### What is the behavior that you expected?

The keyboard to stay set as setup in the keyboard RGB menu.

### Logs

[error_2023_05_03_14_50_46.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11384178/error_2023_05_03_14_50_46.txt)
[error_2023_05_03_15_08_56.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11384179/error_2023_05_03_15_08_56.txt)
[error_2023_05_03_15_09_10.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11384180/error_2023_05_03_15_09_10.txt)
[log_2023_05_03_15_21_40.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11384181/log_2023_05_03_15_21_40.txt)
[error_2023_05_02_17_30_01.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11384182/error_2023_05_02_17_30_01.txt)
[error_2023_05_03_14_43_29.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11384183/error_2023_05_03_14_43_29.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Before looking at this issue I would like someone else to confirm the issue since I have a feeling it might be a problem with your machine.

The error indicates that Windows couldn't send a message to the keyboard RGB controller, but if all devices are working properly that shouldn't happen, especially that there is no error code.

**Comment by BartoszCichecki** [comment]
There are a couple things that _may_ be worth trying:
1. Make sure that if Vantage was installed, is uninstalled properly.
2. See if Vantage communicates with your keyboard properly or if you see similar problems.
3. Do an EC reset.

But this is the first I see this so I am kinda puzzled what could be the issue. Usually there would be an error code which would indicate what's wrong.
