### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#705]
### Version

2.12.0

### OS

Windows 11 22H2

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN51WW

### What's wrong?

Application not appearing, it's showing in task manager but not task bar.
Issue not present with older versions

### How to reproduce the bug?

Start the app

### What is the behavior that you expected?

.

### Logs

[log_2023_05_04_01_25_40.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11392315/log_2023_05_04_01_25_40.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Cannot reproduce.

**Comment by RickyTVs** [comment]
I'm having the same exact issue :( been using ver 2.11.2 since

**Comment by Oblivious02** [comment]
> Cannot reproduce.

Is there anything I can do to help you reproduce the issue?
