### ISSUE TITLE
[BUG]: Fanspeed is not set correctly in custom mode

### ISSUE THREAD

**Issue by Razer2412** [BartoszCichecki/LenovoLegionToolkit#706]
### Version

2.12.0 and 2.13.0 BETA 1

### OS

Windows 11 22H2

### Device

Legion Pro 5 16IRX8

### BIOS version

KWCN32WW

### What's wrong?

Sometimes the fan speed is not set correctly in custom mode. 
fans remain at one speed and do not change their speed, no matter how I adjust the slider control.

### How to reproduce the bug?

go to custom mode 
adjust fan speed

### What is the behavior that you expected?

Fan speed changes according to the set adjustment

### Logs

-

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
"Sometimes" doesn't help. If you find concrete scenario, create an issue.
