### ISSUE TITLE
[BUG]: Custom Power Mode unavailable on new R9000p

### ISSUE THREAD

**Issue by Ace-Radom** [BartoszCichecki/LenovoLegionToolkit#711]
### Version

2.12.0

### OS

Windows 10 22H2 build 19045.2846

### Device

Legion R9000P ARX8

### BIOS version

LPCN27WW

### What's wrong?

"Custom mode" inside Performance mode tab isnt available on my laptop, which is the new model in 2023

### How to reproduce the bug?

1. go to Performance mode tab
2. click on the drop down menu
3. observe only 3 modes available

### What is the behavior that you expected?

"Custom mode" is available on 2023 models

### Logs

[log_2023_05_09_15_10_10.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11432702/log_2023_05_09_15_10_10.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

![%NX{F C(PZ068 HJCSI6AO4](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/104905842/d5bd55bb-9b21-436e-ac14-06e76e383172)
You can see the Performance mode tab interface on my laptop here (from top to bottom: Quiet, Balance, Performance, Custom mode is missing)
<img width="626" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/104905842/1a871d2a-8850-474a-b4e5-625673bc39d9">
Here is how this tab used to be (on an older R9kp 2021H).

**Comment by BartoszCichecki** [comment]
Support is coming in 2.13.0
