### ISSUE TITLE
[COMPATIBILITY]: No Fan Control for Legion 5 Pro 16ARH7H

### ISSUE THREAD

**Issue by LacixHU** [BartoszCichecki/LenovoLegionToolkit#716]
### Version

2.12

### OS

Windows 11 Pro 22H2

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN59WW

### Which features of the application did you test?

I don't see fan control in the application (on Ryzen 7 6800H / RTX 3700 model)
(using LegionFanControl instead)

### Which features of the application do not work as expected?

no fan control

**Comment by BartoszCichecki** [comment]
Fan controls are in custom mode settings. Please put minimum amount of effort into exploring the app before creating stupid issues.
