### ISSUE TITLE
[COMPATIBILITY]: Fan Control on Lenovo Legion 5 15ARH7H

### ISSUE THREAD

**Issue by paul-michael** [BartoszCichecki/LenovoLegionToolkit#719]
### Version

2.12.0

### OS

Windows 11

### Device

Legion 5 15ARH7H

### BIOS version

JUCN59WW

### Which features of the application did you test?

All other features besides the fan control seems to be working fine.

### Which features of the application do not work as expected?

Fan Control. I couldn't see the option to change fan control settings.

**Comment by BartoszCichecki** [comment]
Related: #716
