### ISSUE TITLE
[BUG]: lenovo hotkey

### ISSUE THREAD

**Issue by Sosea1** [BartoszCichecki/LenovoLegionToolkit#732]
### Version

2.13

### OS

Windows 11

### Device

Legion 5 15ACH6A

### BIOS version

G9CN33WW

### What's wrong?

I figured out the problem with the legion hotkeys. This program is in the autostart, if you disable its startup, then switching from legion toolkit starts to work.

### How to reproduce the bug?

1. click on disable lenovo hotkeys
2. restart PC
Lenovo hotkeys continues to work 

How I fixed it

1. Disable lenovo hotkeys from autostart
2. Repeated the steps above
Legion toolkit hotkeys work

### What is the behavior that you expected?

.

### Logs

.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
But toolkit is already disabling autorun for Hotkeys. Unless Lenovo changed something.
