### ISSUE TITLE
[BUG]: Power Mode in dashbord doesnt update with fn+Q

### ISSUE THREAD

**Issue by Quenom** [BartoszCichecki/LenovoLegionToolkit#739]
### Version

2.23.1

### OS

Windows 11 Pro 22H2 22621.1702

### Device

Legion 5 15ACH6H

### BIOS version

GKCN60WW

### What's wrong?

Power Mode in dashbord doesnt update when pressing fn+Q shortcut

### How to reproduce the bug?

Open dashbord
Press fn+Q

### What is the behavior that you expected?

It does update.

### Logs

I dont think that's required for this issue.

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

if i remember correctly in previous versions it might have worked correctly(not sure)

**Comment by BartoszCichecki** [comment]
Releasing 2.13.2 hotfix now.
