### ISSUE TITLE
[FEAT]: Shortcut for switching to custom power mode

### ISSUE THREAD

**Issue by Quenom** [BartoszCichecki/LenovoLegionToolkit#740]
### Version

2.23.1

### OS

Windows 11 Pro 22H2 22621.1702

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

There is no easy way to switch to custom power mode

### How would you like the problem to be solved?

Adding option to switch to custom power mode with fn+q shortcut, holding it maybe?

### What alternatives have you considered?

Adding switch to custom power mode to quick action and launching it with smart key action, but that is limited to 2 currently

**Comment by BartoszCichecki** [comment]
Sorry, commented on wrong issue.

You can bind custom mode to Fn+F9, use actions or quick actions. There is no possibility to change Fn+Q behavior.
