### ISSUE TITLE
[COMPATIBILITY]: Custom Power Mode on Legion R7000P APH8

### ISSUE THREAD

**Issue by TimeTrapzz** [BartoszCichecki/LenovoLegionToolkit#745]
### Version

2.13.2

### OS

Windows11 22H2 build 22621.1778

### Device

Legion R7000P APH8

### BIOS version

M3CN32WW

### What's wrong?

"Custom mode" is not available on R7000P APH8.

### How to reproduce the bug?

1. go to Performance mode tab
2. click on the drop down menu
3. observe only 3 modes available

### What is the behavior that you expected?

"Custom mode" is available on R7000P APH8.

### Logs

No valid logs

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Here is a test build with Custom Mode enabled for M3CN BIOS. Please test custom mode and report back with results.

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11582427/LenovoLegionToolkitSetup.zip)

**Comment by TimeTrapzz** [comment]
It works well. Thanks for your great work!
