### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by TuanZiGit** [BartoszCichecki/LenovoLegionToolkit#746]
### Version

0.0.1 Beta Build 20230526105125 (Github Action)

### OS

Windows 11 22H2 Canary 25357.1

### Device

GeekPro G5000

### BIOS version

LZCN23WW

### What's wrong?

The CapsLock Notify doesn't display and raised an error.

### How to reproduce the bug?

1. Caps Lock
2. Caps Lock
3. ...(Try More Time)
4. An Error Pops Up

### What is the behavior that you expected?

Normally Display the Notify

### Logs

[error_2023_05_26_13_36_30.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581470/error_2023_05_26_13_36_30.txt)
[error_2023_05_26_13_36_34.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581471/error_2023_05_26_13_36_34.txt)
[error_2023_05_26_13_36_35.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581472/error_2023_05_26_13_36_35.txt)
[error_2023_05_26_13_36_36.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581473/error_2023_05_26_13_36_36.txt)
[error_2023_05_26_13_36_37.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581474/error_2023_05_26_13_36_37.txt)
[error_2023_05_26_13_36_38.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581475/error_2023_05_26_13_36_38.txt)
[error_2023_05_26_13_36_41.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581476/error_2023_05_26_13_36_41.txt)
[error_2023_05_26_13_36_42.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581477/error_2023_05_26_13_36_42.txt)
[error_2023_05_26_13_50_15.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581478/error_2023_05_26_13_50_15.txt)
[error_2023_05_26_13_36_25.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581479/error_2023_05_26_13_36_25.txt)
[error_2023_05_26_13_36_27.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581480/error_2023_05_26_13_36_27.txt)
[error_2023_05_26_13_36_28.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581481/error_2023_05_26_13_36_28.txt)
[error_2023_05_26_13_36_29.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11581482/error_2023_05_26_13_36_29.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
This looks like an issue in Windows. You are using a Canary build of Windows, so that is most likely the issue.
