### ISSUE TITLE
[FEAT]: Localization of "On" and "Off" states of various actions

### ISSUE THREAD

**Issue by Ekscentricitet** [BartoszCichecki/LenovoLegionToolkit#754]
### Version

Latest

### OS

Windows 10

### Device

Legion 5 Pro

### Is your feature request related to a problem?

The "On" and "Off" states of various actions are not localized. Refer to the image.

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/49730291/d241c4ed-4c29-41b2-9833-487112a61e10)

### How would you like the problem to be solved?

I see that the AbstractToggleFeatureCardControl is implemented with the help of enums, which are used to display a value. On some of the enums there is a, for example, `[Display(ResourceType = typeof(Resource), Name = "BatteryState_RapidCharge")]`. Simply add it to the missinbg ones.

### What alternatives have you considered?

None.

### Additional information

I will add this feature and make a pull request.

**Comment by BartoszCichecki** [comment]
Good catch. Waiting for PR. 👍

**Comment by Ekscentricitet** [comment]
Another text that is not localized:

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/49730291/94aeae54-8d2a-4303-9d3e-ef5ba3d6deed)

I can localize it as well. Should I directly make pull requests without an issue if I find something similar in the future or should I always make an issue first?

**Comment by BartoszCichecki** [comment]
If it's simple stuff, make a PR.

**Comment by Ekscentricitet** [comment]
Alright, will have it in mind for the future.
