### ISSUE TITLE
[Feature Request] Add a toggle for Power Plan Boost Mode

### ISSUE THREAD

**Issue by arkkkk** [BartoszCichecki/LenovoLegionToolkit#76]
I think it would be nice to have a button with the ability to toggle between Aggressive and Disabled in the Power Plan Boost Mode setting of the currently selected Power Plan. This tool already gives us the ability to switch between Power Plans along with Performance Modes, so i think adding that option might come in handy for some people.

Not sure how it affects Intel systems, but in AMD systems what this does is disable Turbo Boost. Turbo Boost disabled allows the laptop to run cooler with a slight performance impact in applications where CPU usage isn't as intensive. For example in modern AAA GPU intensive games the performance impact is very small, but the CPU temps go down quite a lot. The toggle will just give us more versatility and allow us to enable/disable boost on the go without having to go into power plan settings every time.

Note: The Power Plan Boost Mode setting is usually hidden by default. In order to enable it we must run cmd and execute the following command:

`powercfg -attributes sub_processor perfboostmode -attrib_hide`

**Comment by BartoszCichecki** [comment]
It is not a bad idea to add this, I just need information on how it affects Intel systems, especially the upcoming 12th gen.

I myself disabled Turbo Boost only in Quiet and Balance modes and when I switch to Performance Turbo Boost works again.

**Comment by dpearson2699** [comment]
Not sure if this helps but a similar program called LegionFanControl allows you to do this. Might be a way to figure this out by looking at that program.

**Comment by BartoszCichecki** [comment]
Forgot to close this. Already done :)
