### ISSUE TITLE
object reference not set to an instance of an object [BUG]: 

### ISSUE THREAD

**Issue by royalcoachman** [BartoszCichecki/LenovoLegionToolkit#761]
### Version

2.13.2

### OS

Windows 11 Home, 22H2, os build 22631.1825, Windows Feature Experience Pack 1000.22642.1000.0

### Device

Legion 5 Pro, 16ARH7H

### BIOS version

none available

### What's wrong?

Starting after a reboot and the error turned up.
I expect that the boot order required something to be active, and it was not.

### How to reproduce the bug?

none available

### What is the behavior that you expected?

none available

### Logs

none available

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [X] I disabled some things on my own (please write below what you did)

### Additional information

I have been testing the various modes of operation, dGPU, etc. With Civ6 and Distant worlds 2.

**Comment by BartoszCichecki** [comment]
Log logs and repro steps - closing.
