### ISSUE TITLE
[BUG]: Stripe sponsorship can not use Alipay payment, payment panel shows merchant status exception

### ISSUE THREAD

**Issue by snakizjy** [BartoszCichecki/LenovoLegionToolkit#765]
### Version

2.13.2

### OS

win11 22H1

### Device

r7000 2020

### BIOS version

EUCN39WW

### What's wrong?

Stripe sponsorship can not use Alipay payment, payment panel shows merchant status exception

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Thanks for reporting this. I have reachedout to Stripe (the payment provider) and they are investigating the issue. At the moment it looks like AliPay is blocking my account for some reason.
