### ISSUE TITLE
[FEAT]: Fan control for Legion 5 Pro 16ARH7H

### ISSUE THREAD

**Issue by bvleonov** [BartoszCichecki/LenovoLegionToolkit#766]
### Version

2.13.2

### OS

Windows 11 22H2 build 22621.1555

### Device

Legion 5 Pro 16ARH7H, 82RG

### Is your feature request related to a problem?

I don't see fan control as an option. Custom mode can't be selected (it immediately switches back to quiet or balanced). I'm not sure where fan control would appear, but it seems like custom mode is related based on what I've been seeing in the other issue tickets I've read.

### How would you like the problem to be solved?

Please add fan control support for this machine/BIOS version? 

### What alternatives have you considered?

Legion Fan Control app. Causes crashes after hibernating/sleeping.

### Additional information

BIOS: JUCN57WW
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/14365178/11ce5e0f-bf6d-4d8b-aa2b-24f18e889b1c)
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/14365178/d92e08c5-1346-4b94-9af1-0447c8306533)

**Comment by BartoszCichecki** [comment]
Custom mode should be available in the drop down and as it's written is Readme it's available only when AC adapter is connected. You didn't attach a log so how can I help?

**Comment by bvleonov** [comment]
Ok I didn't realize Fan Control is only available with AC adapter starting with 2.11.

And apologies for the wrong category, I wasn't sure if the fan control was implemented via Custom mode or in some other menu, so I thought the feature was missing.
