### ISSUE TITLE
[COMPATIBILITY]: Legion Slim 7 16IRH8

### ISSUE THREAD

**Issue by Zysor** [BartoszCichecki/LenovoLegionToolkit#772]
### Version

2.13.99

### OS

Windows 11 22621.1778

### Device

Legion Slim 7 16IRH8

### BIOS version

M0CN27WW

### Which features of the application did you test?

pretty much everything, dashboard settings, battery settings, actions (auto switching between battery and ac, refreshrate, disable vantage and fn hotkey replacement.

### Which features of the application do not work as expected?

Keyboard backlight switching, power modes buggy with ai and perfomance mode

**Comment by BartoszCichecki** [comment]
> perfomance mode

Please write in steps what do you see that is wrong. Also, attach one log file where you start LLT and perform the steps and the close LLT.

> Keyboard backlight switching

Attach output from SpectrumTester.exe that is in the install directory of LLT: %LocalAppData%\Programs\Lenovo LegionToolkit. Follow the steps that the program shows you. You can stop when it asks you about making one of the keys white.

**Comment by Zysor** [comment]
> > perfomance mode
> 
> Please write in steps what do you see that is wrong. Also, attach one log file where you start LLT and perform the steps and the close LLT.
>

I switch to perfomance mode with llt and it sometimes switches back to balance mode, llt still shows that perfomance mode is the the current one while the home button is white not red. i disabled AI on balance mode, maybe that is the cause.

[log_2023_06_09_18_29_19.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11709205/log_2023_06_09_18_29_19.txt)

> > Keyboard backlight switching
> 

> Attach output from SpectrumTester.exe that is in the install directory of LLT: %LocalAppData%\Programs\Lenovo LegionToolkit. Follow the steps that the program shows you. You can stop when it asks you about making one of the keys white.


Output:
```
Spectrum keyboard found

Reading response for 0xD1...
07 D1 01 00 01

Reading response for 0xC6...
07 C6 2E 00 0D 01 02 02 03 02 02 02 04 03 02 02
05 04 02 02 05 05 03 02 04 05 06 02 02 05 07 02
02 05 08 02 02 05 09 00 0A 00 0B 01 05 0C 02 02
05 0D

Reading response for 0x04...
07 04 01 00 19

Reading response for 0xC7...
07 C7 01 00 01

Reading response for 0xC4 7...
07 C4 03 00 07 07 14

Reading response for 0xC4 8...
07 C4 03 00 08 01 0D

Reading response for 0xC5 7 0...
07 C5 41 00 07 00 00 01 00 01 02 00 02 03 00 03
04 00 04 05 00 05 06 00 06 07 00 07 08 00 08 09
00 09 0A 00 0A 0B 00 0B 0C 00 0C 0D 00 0D 0E 00
0E 0F 00 0F 10 00 10 11 00 11 12 00 12 13 00 13
14 00 00 00 00

Reading response for 0xC5 7 1...
07 C5 41 00 07 01 00 16 00 01 17 00 02 18 00 03
19 00 04 1A 00 05 1B 00 06 1C 00 07 00 00 08 1D
00 09 1E 00 0A 1F 00 0B 20 00 0C 21 00 0D 22 00
0E 38 00 0F 38 00 10 26 00 11 27 00 12 28 00 13
29 00 00 00 00

Reading response for 0xC5 7 2...
07 C5 41 00 07 02 00 40 00 01 42 00 02 00 00 03
43 00 04 44 00 05 45 00 06 46 00 07 47 00 08 48
00 09 49 00 0A 4A 00 0B 4B 00 0C 00 00 0D 4C 00
0E 4D 00 0F 4E 00 10 4F 00 11 50 00 12 51 00 13
68 00 00 00 00

Reading response for 0xC5 7 3...
07 C5 41 00 07 03 00 55 00 01 55 00 02 6D 00 03
6E 00 04 58 00 05 59 00 06 5A 00 07 71 00 08 00
00 09 72 00 0A 5B 00 0B 5C 00 0C 5D 00 0D 5F 00
0E 77 00 0F 77 00 10 79 00 11 7B 00 12 7C 00 13
68 00 00 00 00

Reading response for 0xC5 7 4...
07 C5 41 00 07 04 00 6A 00 01 6A 00 02 82 00 03
83 00 04 00 00 05 6F 00 06 70 00 07 87 00 08 88
00 09 73 00 0A 74 00 0B 75 00 0C 00 00 0D 76 00
0E 8D 00 0F 8D 00 10 8E 00 11 90 00 12 92 00 13
A7 00 00 00 00

Reading response for 0xC5 7 5...
07 C5 41 00 07 05 00 7F 00 01 80 00 02 96 00 03
97 00 04 98 00 05 98 00 06 98 00 07 98 00 08 98
00 09 98 00 0A 9A 00 0B 9B 00 0C 00 00 0D 00 00
0E 9D 00 0F 00 00 10 A3 00 11 A3 00 12 A5 00 13
A7 00 00 00 00

Reading response for 0xC5 7 6...
07 C5 41 00 07 06 00 00 00 01 00 00 02 00 00 03
00 00 04 00 00 05 00 00 06 00 00 07 00 00 08 00
00 09 00 00 0A 00 00 0B 00 00 0C 00 00 0D 9C 00
0E 9F 00 0F 00 00 10 A1 00 11 00 00 12 00 00 13
00 00 00 00 00

Reading response for 0xC5 7 7...
07 C5 41 00 07 07 00 FF FF 01 FF FF 02 FF FF 03
FF FF 04 FF FF 05 FF FF 06 FF FF 07 FF FF 08 FF
FF 09 FF FF 0A FF FF 0B FF FF 0C FF 01 0D 02 03
0E 04 05 0F 06 07 10 08 09 11 0A 0B 12 0C 0D 13
0E 0F 00 00 00

Reading response for 0xC5 7 8...
07 C5 41 00 07 08 00 10 FF 01 11 FF 02 12 FF 03
13 FF 04 14 FF 05 16 17 06 18 19 07 1A 1B 08 1C
1D 09 1E 1F 0A 20 21 0B 22 A8 0C FF 38 0D FF 26
0E FF 27 0F FF 28 10 FF 29 11 FF 16 12 17 18 13
19 1A 00 00 00

Reading response for 0xC5 7 9...
07 C5 41 00 07 09 00 1B 1C 01 1D 1E 02 1F 20 03
21 22 04 A8 FF 05 38 FF 06 26 FF 07 FF FF 08 FF
FF 09 FF FF 0A 40 42 0B 43 44 0C 45 46 0D 47 48
0E 49 4A 0F 4B 60 10 60 4C 11 4C 77 12 77 4F 13
4F 50 00 00 00

Reading response for 0xC5 8...
07 C5 41 00 08 00 00 DD 05 CA B7 E6 A0 02 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00

Keyboard is white only.
Keyboard is is not extended.

Reading config complete.
```

**Comment by BartoszCichecki** [comment]
@Zysor,

> I switch to perfomance mode with llt and it sometimes switches back to balance mode

There is nothing abnormal in the log you sent. I can see you cycled power modes and they are read from EC correctly. So it's either some weird EC behavior and reset should help or BIOS might have a bug. Let's leave this for now.

Regarding the keyboard output:
1. On Gen 6 & 7, keyboards that were White backlight only only had 3 intensity settings: Off, Low and High, can you confirm that this is still the case on you laptop?
2. Is Fn+Space a shortcut that works when Vantage is running? Does it cycle between 3 settings? Or maybe it's Fn+Up/Down that changes the brightness?

Here is another build you can try out, I enabled Custom mode for your BIOS, which should work properly: it was tested on regular Legion 7 gen8 and also Legion Slim 7 gen 8 (with AMD processor).

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11715308/LenovoLegionToolkitSetup.zip)

**Comment by BartoszCichecki** [comment]
Closing after discussion on Discord. Backlight control works fine, if the issue with performance mode reverting repeats, log it and attach the log with approximate time when switch happened (I suspect EC issue if status is not reflected in LLT).
