### ISSUE TITLE
[FEAT]: Fan control in every power mode

### ISSUE THREAD

**Issue by LacixHU** [BartoszCichecki/LenovoLegionToolkit#776]
### Version

2.13.2

### OS

Windows 11 Pro 22H2

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

Firstly thanks for this very useful app.

My feature suggestion:
Fan control is now only avialable only in custom mode. Legion agressive fan curve is not handled in other power modes.

I think it would be good to have it in every power mode.

I am using Lenovo Legion Fan Control v2 at the moment for this but it sometimes crashes and it is not an open source app.

### How would you like the problem to be solved?

- Fan Control in Every power mode (Quiet, Balanced, Power)
- 100rpm steps from 0. Not 1600rpm as minimum. As possible in Legion Fan Control.

### What alternatives have you considered?

LegionFanControl

**Comment by BartoszCichecki** [comment]
As described many times already, it's not possible. Look for closed issues and in discussions section for details.
