### ISSUE TITLE
[BUG]: Smart Key Action and Secondary Action settings are lost upon saving in the Actions tab

### ISSUE THREAD

**Issue by RNarayan73** [BartoszCichecki/LenovoLegionToolkit#781]
### Version

2.13.2

### OS

Windows 11 22H2 Build 22621.1178

### Device

Legion Pro 5 16ARX8 (82WM)

### BIOS version

LPCN39WW

### What's wrong?

Smart Key Action and Secondary Action settings are lost upon saving in the Actions tab. This behaviour occurs whether Lenovo Vantage is disabled or not.

### How to reproduce the bug?

1. Disable Lenovo Hotkeys
2. In the Settings tab, select a quick action in the Smart Key Action and Smart Key Secondary Action popups
3. Check that these Smart Key and Secondary Actions are working
4. In the Actions tab, click Save
5. Test the Smart Key and Secondary Actions again and note that they don't work
6. Go back to the Settings tab and open the Smart Key and Secondary Action popups; notice that the quick actions are not selected anymore.

### What is the behavior that you expected?

The Smart Key and Secondary Actions quick actions shouldn't be lost upon saving in the Actions tab

### Logs

None

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Good catch, fixed 👍
