### ISSUE TITLE
[FEAT]: CPU overclock like vantage

### ISSUE THREAD

**Issue by rickygjun** [BartoszCichecki/LenovoLegionToolkit#787]
### Version

2.1.3

### OS

Windows 11 22H1

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

I'd like to request CPU overclock feature to be available in LLT, similar to the options in Vantage.

Understand it requires Intel XTU SDK. 

### How would you like the problem to be solved?

New feature

### What alternatives have you considered?

ThrottleStop, however TS only support underclock, not overclock, hence has to use either Intel XTU or Vantage.

**Comment by BartoszCichecki** [comment]
> Understand it requires Intel XTU SDK.

Yup, that's correct, so you might as well use XTU. Another thing is that pricing and licensing of XTU is unclear and therefore will not be included. It also would be basically a lot of work to replicate XTU user interface which isn't something I want to do ;)

**Comment by BartoszCichecki** [comment]
PS: Simple GPU overclock is coming though in 2.14 ;)
