### ISSUE TITLE
Delayed loading of "Run of startup"

### ISSUE THREAD

**Issue by DocDDD** [BartoszCichecki/LenovoLegionToolkit#79]
Hello. For me and not only for me, Lenovo apparently starts very early when booting the system.Legion.Toolkit. Therefore, windows with different errors are often shown. But when you manually start the program again, it is quietly loaded into memory. Is it possible to make another item next to "Run of startup" - "Run of startup delayed loading" - which will load Lenovo.Legion.Toolkit is 5-8 seconds later. Manually modify your profile for a slightly delayed launch in the task scheduler, when activating "Run of startup" I failed.

**Comment by BartoszCichecki** [comment]
Good idea. I haven't had much time lately, but will change it in next release.

**Comment by DocDDD** [comment]
Thank you so much for improving your program!

**Comment by BartoszCichecki** [comment]
Hey, startup will be delayed by 1 minute in next release!
