### ISSUE TITLE
[BUG]: Panel logo backlight notices

### ISSUE THREAD

**Issue by lineMg** [BartoszCichecki/LenovoLegionToolkit#792]
### Version

214.0

### OS

Windows 11 22H2

### Device

Lenovo Legion R9000K2021H 82N6

### BIOS version

GKCN60WW

### What's wrong?

When using ' Fn + L ' to turn on or off panel logo backlight, the notice always shows ' Legion logo on '

### How to reproduce the bug?

using ' Fn + L ' to turn on or off panel logo backlight

### What is the behavior that you expected?

using ' Fn + L ' to turn on panel logo backlight, the notice always shows ' Legion logo on '，
using ' Fn + L ' to turn off panel logo backlight, the notice always shows ' Legion logo off '

### Logs

[log_2023_06_20_02_09_27.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11795142/log_2023_06_20_02_09_27.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Thanks for reporting.

On your machine panel logo is handled by iCue and therefore LLT can't support showing the state. I fixed this and in next release that shouldn't happen anymore.
