### ISSUE TITLE
[BUG]: Panel Logo backlight didn't appear on the dashboard

### ISSUE THREAD

**Issue by Glimspe** [BartoszCichecki/LenovoLegionToolkit#793]
### Version

2.14.0

### OS

Win10home 22H2

### Device

Legion 5 15ACH6A

### BIOS version

G9CN33WW

### What's wrong?

My machine have the panel logo backlight,and I can use 'Fn+l" to switch it,but this  switch button didn't appear on my dashboard.

### How to reproduce the bug?

None

### What is the behavior that you expected?

Make this buuton show on my dashboard

### Logs

[log_2023_06_20_02_48_17.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11795331/log_2023_06_20_02_48_17.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/100057577/827ff1da-a995-40e3-b77f-94a567abe3b4)

**Comment by BartoszCichecki** [comment]
Thanks for reporting the issue.

I added a fix and panel logo should show up for you when next version is released.
