### ISSUE TITLE
[FEAT]: 希望在自定义模式中，增加电源计划选择

### ISSUE THREAD

**Issue by exgilgamesh** [BartoszCichecki/LenovoLegionToolkit#797]
### Version

2.14.0

### OS

win11 22h2

### Device

Legion R9000P ARX8

### Is your feature request related to a problem?

当我使用自定义模式时，发现没有电源计划选择，官方的legion zone有这个功能，我这导致我明明将cpu功耗拉的很高，频率却跑不上去，这是因为自定义模式默认使用均衡模式的电源计划，我却无法更改。

### How would you like the problem to be solved?

像官方legion zone 一样，增加自定义模式下的电源计划选择

### What alternatives have you considered?

像官方legion zone 一样，增加自定义模式下的电源计划选择

**Comment by BartoszCichecki** [comment]
If I am translating this right, you can already assign a power plan of your choice to Custom mode in LLT settings.

If I understood wrong please create the issue next time in English.
