### ISSUE TITLE
[BUG]: NVIDA GPU Overclocking feature doesn't show up in Legion Toolkit

### ISSUE THREAD

**Issue by nadtorus** [BartoszCichecki/LenovoLegionToolkit#800]
### Version

2.14.0

### OS

Windows 11 Version 22H2 (OS Build 22621.1848)

### Device

Legion 7i 16ITHg6

### BIOS version

H1CN53WW

### What's wrong?

Just like the title says, the GPU overclocking feature doesn't show up even though I have turned on GPU Overclocking and GPU Advanced Overclocking in the BIOS. With that being said, I still don't know where it should be in the LLT but I've checked everywhere and still not found it (Doesn't exist in Custom Mode setting too).

### How to reproduce the bug?

I tried this several times.
1. Turn on GPU OC in BIOS
2. Open LLT
3. If it's still not there, I restart the Laptop
4. Turn off GPU OC in BIOS
5. Restart

### What is the behavior that you expected?

The GPU OC shows up.

### Logs

[log_2023_06_21_13_56_22.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11818674/log_2023_06_21_13_56_22.txt)
[log_2023_06_21_13_56_59.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11818675/log_2023_06_21_13_56_59.txt)

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Please read release notes next time:

> If you customized your Dashboard before, you will need to add new options manually.
