### ISSUE TITLE
[BUG]: Panel Backlight Control isn't working on Legion S7-15ACH6 Laptop (Lenovo) - Type 82K8

### ISSUE THREAD

**Issue by deadline-frontwind** [BartoszCichecki/LenovoLegionToolkit#803]
### Version

2.14.1

### OS

Windows 11 22H2 22621.1848

### Device

Legion S7-15ACH6 Laptop (Lenovo) - Type 82K8

### BIOS version

HACN40WW

### What's wrong?

When switching on Panel Backlight Control feature,I found my laptop backlight didn't change.

### How to reproduce the bug?

1.open the application
2.turn on/off "Panel Backlight Control" feature

### What is the behavior that you expected?

Panel Backlight should turn on /off as I turn on/off the feature

### Logs

[log_2023_06_22_04_34_16.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11828731/log_2023_06_22_04_34_16.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
If you see the option it means that your laptop claims it supports panel logo backlight control using Lenovo lighting methods. However if it doesn't work it means that you have one of the models which falsely indicate that they support it, in which case there isn't much I can do. You can remove the option from the Dashboard and just ignore it (use the Customize option at the bottom).

I will keep this open, but I am not sure if there is a better solution for this.

**Comment by BartoszCichecki** [comment]
Btw, could run this on PowerShell as admin `Get-WmiObject -namespace root\WMI -class LENOVO_LIGHTING_DATA` and post the output here?

**Comment by deadline-frontwind** [comment]
[result.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11843770/result.txt)

**Comment by BartoszCichecki** [comment]
Yup, that confirms it:

```
Active                   : True
Brightness_Level         : 0
Control_Interface        : 1 // 1 means that it can be controlled
Default_Brightness_Level : 0
Default_State            : 1
InstanceName             : ACPI\PNP0C14\GMZN_3
Lighting_Id              : 3 // This is panel logo
Lighting_Type            : 0 // 0 indicates it can be controlled with lighting methods
State_Type_Num           : 2
```

So, it might be an issue in this BIOS version or in general with all BIOSes on this machine type.

**Comment by BartoszCichecki** [comment]
@deadline-frontwind Does you laptop originally used Corsair iCue to control backlight?

**Comment by deadline-frontwind** [comment]
I tried to enable Lenovo Hotkeys and surprisingly found that Fn+L panel backlight control works...

**Comment by henry-ji** [comment]
I am using the same device and the same bios but I don't have this problem, so maybe there's something wrong with you lenovo hotkeys.

P.S. isn't the backlight controlled by Fn + space

**Comment by henry-ji** [comment]
I am using the same device and the same bios but I don't have this problem, so maybe there's something wrong with you lenovo hotkeys.

P.S. isn't the backlight controlled by Fn + space
