### ISSUE TITLE
[COMPATIBILITY]: Lenovo Slim 7 ProX

### ISSUE THREAD

**Issue by stadsport** [BartoszCichecki/LenovoLegionToolkit#808]
### Version

2.14.1

### OS

Windows 11 22H2

### Device

Slim 7 ProX 14ARH7

### BIOS version

JVCN35WW

### Which features of the application did you test?

Battery mode, discrete GPU enable/disable, quick actions (changing power mode), Disable Lenovo Hotkeys, everything detected seems to work as expected. Battery health & status, system information, etc all looks correct. 

### Which features of the application do not work as expected?

There are a handful of options on the Home screen that are normally available in Lenovo Vantage I can see through "Customize Dashboard" but don't show on the Home screen, so are apparently not properly detected:

- Power Mode (which DOES work in Actions, but isn't available as a Step if you go to add a new Action/Quick Action)
- Overclock GPU
- Refresh Rate
- Keyboard Backlight

![Screenshot 2023-06-22 163451](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/133153109/c1612762-606d-4888-9608-9fb1b691658a)

### Logs

[log_2023_06_22_20_05_02.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11841221/log_2023_06_22_20_05_02.txt)

### Additional information

I know this isn't a Legion laptop, so no worries if you choose to never support it. But I know there's a lot of hardware overlap in this series and the Legion laptops, and I was pleasantly surprised to see just how much worked without a hitch. It's honestly enough where if you listed it as a supported device I wouldn't have known any different!

Also, just an idea, maybe a "Don't ask me again" checkbox on the warning screen at startup for unsupported devices? I could definitely see a reason for excluding such a checkbox, but just an idea. 

Anyway, thanks for making this tool, and happy to test stuff out on this device if you need!

**Comment by BartoszCichecki** [comment]
I don't have the time nor access to these devices so I can't add proper support for them. If you look into readme you will find a way to disable the dialog if you want to keep using LLT in the current state.

**Comment by stadsport** [comment]
I'll check that out then. Thanks for the response!
