### ISSUE TITLE
[FEAT]: fine-grained control over backlight intensity

### ISSUE THREAD

**Issue by Akronae** [BartoszCichecki/LenovoLegionToolkit#811]
### Version

2.14.1

### OS

Windows 11

### Device

Legion Pro 7 16IRX8

### Is your feature request related to a problem?

I sometimes find the keyboard backlight to be too bright

### How would you like the problem to be solved?

From Lenovo Legion Toolkit (or Lenovo Vantage) we have more granular control over the backlight level, we can set the luminsoty to "1" for instance:
<img width="196" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/17302866/0059ced2-f843-46ca-9baa-725e7fdfd70a">

However using keyboard shortcuts (`Fn + Up/Down`), it increments by 3 levels meaning that to get back to luminosity level = 1, I have to open Lenovo Legion Toolkit and slide it back to 1

I think it would be a really nice feature to have a granular control over the backlight luminosity increments, personally I would really apreciate to have a 1 increment on every key stroke

### What alternatives have you considered?

Using a custom macro, would feel dirty.

**Comment by BartoszCichecki** [comment]
I completely feel you, cause I would like the same to be done. Unfortunately it doesn't seem possible. Up/Down first changes the brightness on the EC level and then notifies the system that brightness was changed (hence the notification you see in Windows). I tried working around it but it results in weird flickering. I deal with this by avoiding fn up/down and just handling backlight with actions, but if I ever find a solution to this I will do it, but so far no luck.

**Comment by Akronae** [comment]
How can you setup actions triggered by key stroke? To my surprise I have not find any way

**Comment by BartoszCichecki** [comment]
You can't (also, Fn+Up/Down isn't really a "key" per se). What I meant is that I added actions to set keyboard backlight to level 1 when I connect it to AC. You can probably also find scenarios when you need keyboard backlight and do it this way.

**Comment by BartoszCichecki** [comment]
Not with Spectrum unfortunately, but you could make a Quick Action on the Actions page that will set backlight to 1 and then this quick action will appear in the right click context menu.

**Comment by Akronae** [comment]
Allright that will work, thanks!
I really like your utility keep the good work
