### ISSUE TITLE
[FEAT]: Add an option in Settings to disable UAC prompt when running LLT

### ISSUE THREAD

**Issue by Ardaninho** [BartoszCichecki/LenovoLegionToolkit#812]
### Version

2.14.1

### OS

W11 22H2 22621.1848

### Device

Lenovo IdeaPad Gaming 3 15ACH6 AMD

### Is your feature request related to a problem?

It gets so annoying having to run LLT as admin when you always get the UAC prompt. Every time press OK and let it launch.

### How would you like the problem to be solved?

Create a task schedule to run LLT with high privilege and uncheck both checked AC power options.
If turned on, change shortcut to 'C:\Windows\System32\schtasks.exe /run /tn "TaskName"'
If off, change back to default shortcut "C:\...\LenovoLegionToolkit\Lenovo Legion Toolkit.exe"

### What alternatives have you considered?

Same as above "How would you like the problem to be solved?"

**Comment by BartoszCichecki** [comment]
As written in the readme works best if you keep it running in tray. If you want to start it every time, then you can create these shortcuts yourself.
