### ISSUE TITLE
[BUG]: Power mode switches back upon switching windows for specific games

### ISSUE THREAD

**Issue by Yuri010** [BartoszCichecki/LenovoLegionToolkit#815]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.1

### OS

Windows 10 22H2 Build 19045.3086

### Device

Legion 5 15ARH05 (82B5)

### BIOS version

EUCN39WW

### What's wrong?

I have 2 actions enabled:
- When game closes
  - Power Mode: Balanced
- When game is running
  - Power Mode: Performance
  
Though upon alt tabbing in Roblox or Minecraft (haven't tested many other games) it switches back to balanced, rather than staying in performance until the game is closed.
  

### How to reproduce the bug?

1. Enable the actions I described earlier (When game closes switch power mode to balanced, when game is running switch power mode to performance)
2. Open a game I experienced this problem with (Roblox or Minecraft for example)
3. Just alt+tab to something other than the game and for some reason it switches back to balanced mode, then when you tab back in it goes to performance mode again.

### What is the behavior that you expected?

Expected behaviour would be that performance mode enables on startup of a game and stays enabled until the game closes.

### Logs

[log_2023_06_24_16_17_27.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11857562/log_2023_06_24_16_17_27.txt)

**Comment by BartoszCichecki** [comment]
That is expected. According to the log you sent, the game you started was detected with the effective power mode listener and not by process listener. That means that LLT can't hook up to the process to listen when the game stops, but instead monitors so called "[Effective Power Mode](https://learn.microsoft.com/en-us/windows/win32/api/powersetting/ne-powersetting-effective_power_mode)". That mode is set by Windows automatically when the game is on screen, so when you Alt Tab to desktop, it changes back to other value than "Game".

Minecraft is not registered as a game in your Windows registry at all, but Roblox is:
>[24/06/2023 16:17:35.212] [8] [GameDetector.cs#84:GetDetectedGamePaths]  - Name: RobloxPlayerBeta, ExecutablePath: C:\Users\YuriP\AppData\Local\Roblox\Versions\version-e28adbc917f34900\RobloxPlayerBeta.exe

not sure if that is the path of the Roblox you are starting, and not sure which game you started when you captured the log, but game detection worked based on the effective power mode, not the process.

This isn't ideal, but it's best that is possible with APIs Windows provides.
