### ISSUE TITLE
Keyboard backlight control and Panel Logo backlight option

### ISSUE THREAD

**Issue by lineMg** [BartoszCichecki/LenovoLegionToolkit#819]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.2

### OS

Windows11

### Device

Lenovo Legion R9000K2021H 82N6

### BIOS version

GKCN60WW

### What's wrong?

1. 'Keyboard backlight' option doesn't control the keyboard backlight. The computer controls the keyboard backlight through 'Fn+Up' and  'Fn+Down'.
2. 'Panel Logo backlight' option doesn't appear on the dashboard.

### How to reproduce the bug?

1.Swich 'Keyboard backlight' option, but it doesn't work. 
2.Trying to add 'Panel Logo backlight' option to my dashboard, but failed.

### What is the behavior that you expected?

1.'Keyboard backlight' option can control the keyboard backlight.
2.'Panel Logo backlight' option can show on the dashboard.

### Logs

[log_2023_06_26_06_49_36.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11865260/log_2023_06_26_06_49_36.txt)

### Additional information

![1](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/70734225/a7e2137e-6e05-4a40-985d-ee42210f2855)

![2](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/70734225/26ed30f3-17d4-4e71-9a31-f198b71ccc77)

**Comment by BartoszCichecki** [comment]
Is your keyboard RGB or white only?

**Comment by lineMg** [comment]
RGB

**Comment by lineMg** [comment]
I understand. Thank you for your reply
