### ISSUE TITLE
Battery mode switching back to normal without input

### ISSUE THREAD

**Issue by Yuri010** [BartoszCichecki/LenovoLegionToolkit#82]
**Device:** Lenovo Legion 5 (15ARH05)
**SKU:** 82B500NVMH
**Toolkit Version:** 1.6.2

Hello,

So basically, the Toolkit just switches the Battery Mode back to the "Normal" mode instead of "Conservation".
I don't really know how and when this happens, but it is either after reboots, sleep or just using the laptop unplugged.

Edit: Ok, apparently even after turning it off and on... It just doesn't save it at all.
Do note that I am using fast startup, idk if that makes a difference but maybe.

Any requests (like logs) or just solutions would be appreciated :)

**Comment by Yuri010** [comment]
Apparently, this problem is caused by a known BIOS side bug.
The tool works perfectly fine.

## Fix for this bug on this specific device.
I got this fix by a friendly helper in the Legion Series Discord server.
All you have to do is perform a BIOS Flashback.
**Do note that this comes with its risks. DO NOT RUN THIS IF YOU DON'T HAVE THE SAME DEVICE AS ME.**

Requirements:
 - The laptop
 - AC Power connected
 - Patience

**Step 0:** Save any unsaved work, close all apps and have the AC Power connected.
**Step 1:** Download and run the tool from [https://download.lenovo.com/consumer/mobiles/eucn29ww.exe](url).
**Step 2:** It should show the setup, just go through the screens. Leaving everything as default is fine.
**Step 3.1:** A window from "InsydeH2O" should pop up and a warning message. Drag this window to the side and verify that the model "current" matches the "new".
**Step 3.2:** Read and agree the warning message, and wait for the process to finish. Your device should reboot and start the flashing process. ***DO NOT DISCONNECT AC POWER, TURN OFF THE DEVICE OR CLOSE THE LID***.
  Just wait for that whole riddle to finish, your device should reboot straight back to Windows.

Note: After this, Conservation mode may have reset again. That is just because of the BIOS Flashback process. It should be fixed though.

**Comment by RawHere** [comment]
This problem is what i am facing too, battery mode changing to normal, it is a bios issues for actual fix you need t roll back your bios. 
I tried to fix it by turning *On Bluetooth > rebooting* , it works at least for now. Turning off Bluetooth afterwards works sometimes as fix  sometimes it does not, at least for me.
