### ISSUE TITLE
[BUG:] Keyboard backlight control in dashboard isn't working on Legion 5 Pro 16IAH7H - Type 82RF

### ISSUE THREAD

**Issue by RunningDead89** [BartoszCichecki/LenovoLegionToolkit#820]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.2

### OS

Windows 11 22H2 Pro Insider Preview (Dev) Build 23486.1000

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN51WW

### What's wrong?

When switching keyboard backlight in dashboard, nothing changes. If I change categories and go back in dashboard, keyboard backlight shows nothing.

### How to reproduce the bug?

1. Open application
2. Turn on/off keyboard backlight control in dashboard

### What is the behavior that you expected?

Keyboard backlight brightness should be changed if i change the option.

### Logs

[log_2023_06_26_14_12_39.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11870317/log_2023_06_26_14_12_39.txt)

[PowerShell_Result.txt (Get-WmiObject -namespace root\WMI -class LENOVO_LIGHTING_DATA)](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11870341/PowerShell_Result.txt)

### Additional information

<img width="850" alt="Screenshot 2023-06-26 160813" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/66883206/ac9552e7-4221-482d-b7b6-0167001967a4">

**Comment by BartoszCichecki** [comment]
> Wow i did not expect such a quick response from you.

You're lucky I was just checking GitHub :D

Can you try this build to see if it works properly? You shouldn't see the keyboard on the dashboard since you have RGB keyboard.

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11870602/LenovoLegionToolkitSetup.zip)

**Comment by RunningDead89** [comment]
> 
> You're lucky I was just checking GitHub :D
> 
:D Today seems to be my lucky day
> Can you try this build to see if it works properly? [...]
> 
Sure, i'll give it a try. Just give me a moment please i'll be right back :D

**Comment by RunningDead89** [comment]
> @RunningDead89 and one more just to be safe before I push an update:

Tested and works as expected 👍 
Thank you :D

OT: If there are new phrases to translate in the near future, it might take me longer to translate them into German

**Comment by BartoszCichecki** [comment]
There will be some but it will probably be a month before next release. Vacation time is wonderful 😎

**Comment by RunningDead89** [comment]
> There will be some but it will probably be a month before next release. Vacation time is wonderful 😎

Enjoy it!  😎 👍
