### ISSUE TITLE
[BUG]: Warranty displays end of "Premium Care Trial" instead of warranty itself

### ISSUE THREAD

**Issue by RunningDead89** [BartoszCichecki/LenovoLegionToolkit#824]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.3

### OS

Windows 11 22H2 Pro Insider Preview (Dev) Build 23486.1000

### Device

Legion 5 Pro 16IAH7H

### BIOS version

J2CN51WW

### What's wrong?

Hello again 🤣 

In "about your device", the end of the "Premium Care trial" is displayed as the warranty end date instead of the end of the actual warranty itself.

In my case, the end date is displayed as 19.09.2023, which is the date Lenovo's Premium Care trial ends. The warranty itself ends in April 2025.

I have observed this behavior since I bought my laptop in April, was just too lazy to report it here :D

### How to reproduce the bug?

1. Open application
2. click on "about your device"-badge in titelbar
3. check under section Warranty the end date

### What is the behavior that you expected?

It should be showing the correct end date of the warranty

### Logs

[log_2023_06_26_16_02_25.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11871341/log_2023_06_26_16_02_25.txt)

### Additional information

<img width="752" alt="Screenshot 2023-06-26 180256" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/66883206/87828ef3-4935-4a08-b0d0-51ec9c08f2b8">

<img width="360" alt="Screenshot 2023-06-26 173653" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/66883206/8a70ce6e-19d0-44aa-8c55-eb2a52a80693">

**Comment by BartoszCichecki** [comment]
I will probably need your serial number to check the response you are getting. If you could DM me on Discord that would be great.

**Comment by RunningDead89** [comment]
> If you could DM me on Discord that would be great.

Done :D
