### ISSUE TITLE
Request a feature

### ISSUE THREAD

**Issue by Daniki01** [BartoszCichecki/LenovoLegionToolkit#828]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.3

### OS

windows11

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

Request a feature

### How would you like the problem to be solved?

Request a feature

### What alternatives have you considered?

Request a feature

### Additional information

I just switched from vantage to your program and you wrote a really good program. I wanted to ask you if it is possible to add a system scanning feature like lenovo smart performance in vantage to your program?

**Comment by BartoszCichecki** [comment]
No, because system Smart Performance is a placebo/scam.

**Comment by Daniki01** [comment]
I didn't mean to put something like that in the program that doesn't work, I meant to put something like that that actually works.

**Comment by BartoszCichecki** [comment]
So what should it do? Because afaik Windows doesn't really need anything special to "clean it up".
