### ISSUE TITLE
Compatibility testing results - 15IRH8

### ISSUE THREAD

**Issue by marvav** [BartoszCichecki/LenovoLegionToolkit#832]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.14.3

### OS

Windows 11 10.0.22621 

### Device

Lenovo LOQ 15IRH8

### BIOS version

LZCN29WW

### Which features of the application did you test?

I tested nearly everything.
Switching power modes and battery modes works, Always on USB too.
Graphics working mode is working too. Display options + Other work alright. I tested them in Actions and there were no issues. RGB lightning works without issues. I let the application handle the hotkeys and found no issues. Windows Power Plan configuration is flawless.

### Which features of the application do not work as expected?

There's no option for Custom mode or Fan control. No Wattage setting and I think I saw screenshot of that somewhere.

**Comment by BartoszCichecki** [comment]
Thanks for testing. Can you please check the build? It should have you device on the compatibility list.

[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11910630/LenovoLegionToolkitSetup.zip)

**Comment by marvav** [comment]
I tested just now, but apart from real-time utilization stats and instant boot option nothing has changed.

**Comment by BartoszCichecki** [comment]
Can you upload a log from the last version? Instruction on collecting logs is in the readme.

**Comment by marvav** [comment]
Sure, here it is. I logged opening every tab.
[log_2023_06_30_08_20_14.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11914838/log_2023_06_30_08_20_14.txt)

**Comment by BartoszCichecki** [comment]
Everything looks perfect. Support will be added in 2.15.0. The wattage thing you saw (Custom Mode) does not seem to be supported on LOQ laptops so you won't be able to change it.

**Comment by marvav** [comment]
Thank you very much!
But the wattage thing is definitely supported on LOQ as I had this option in Vantage - Custom Mode with Wattage sliders. I didn't need it really as I run mostly on Quiet Mode. Your software is much better <3

**Comment by BartoszCichecki** [comment]
OK, I will take a look into this. It might be a new case where LOQ is reporting compatibility in a different way. I'll reach out if I find something new!

**Comment by BartoszCichecki** [comment]
@marvav Could you run this on PowerShell (with admin rights)?

`(Get-WmiObject -namespace root\WMI -class LENOVO_GAMEZONE_DATA).IsSupportSmartFan().Data`

**Comment by marvav** [comment]
I did and it returned "6" for both 2.15 b1 and 2.15 b2.
In 2.15 b2 Custom mode is visible and customizable. Seems alright, I was able to achieve fully silent mode.
However, when I unplugged adapter, I was no longer able to use custom mode.
When I clicked on "Custom", it flicked it's name and returned back to Balance.
I recorded this scenario with log. I tried to switch 3 times.

[log_2023_06_30_19_07_34.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11919804/log_2023_06_30_19_07_34.txt)

**Comment by BartoszCichecki** [comment]
Perfect!

> When I clicked on "Custom", it flicked it's name and returned back to Balance.

https://github.com/BartoszCichecki/LenovoLegionToolkit#why-i-cant-switch-to-performance-or-custom-power-mode-on-battery

**Comment by marvav** [comment]
Nice. Just did that and I can switch to Custom Mode on battery, except it does not do anything. I tried to spin fans on max rpm and they didn't even start spinning. There was also no cpu spike in utilization like when switching from Battery to Balance.
[log_2023_06_30_19_30_11.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11919952/log_2023_06_30_19_30_11.txt)

But I guess it all falls under the unpredictable behavior warning.

I'm impressed with your speed at fixing stuff.
Good Job and Thank You
