### ISSUE TITLE
Fans not spin down correctly even in custom mode.

### ISSUE THREAD

**Issue by Razer2412** [BartoszCichecki/LenovoLegionToolkit#833]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.3

### OS

Windows 11 22H2

### Device

Legion Pro 5 16IRX8

### BIOS version

KWCN36WW

### What's wrong?

Fans don't spin slower than 2100 rpm. No matter in which mode.

If I set the sliders further down in custom mode, the speed does not change. 
Higher speeds work normally.

Vantage is not installed.

### How to reproduce the bug?

go to custom mode
adjust fan speed

### What is the behavior that you expected?

Fan speed changes according to the set speed.

### Logs

[log_2023_06_29_10_14_05.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11904648/log_2023_06_29_10_14_05.txt)

**Comment by BartoszCichecki** [comment]
This is not a bug for me. Speeds are controlled by EC no by LLT. If they don't spin down, then EC apparently thinks it's too hot.

**Comment by Razer2412** [comment]
so whats the function of the fan curve then?

My Laptop is on idle in a air conditioned room. 
I also set all wattage limits to the lowest setting. 
CPU is arround 35 °C 
GPU off

Fans still don't spin slower than 2100 rpm.
