### ISSUE TITLE
Keyboard RGB color scheme profiles created using previous versions of LLT cannot be imported anymore in current version of LLT.

### ISSUE THREAD

**Issue by ZZZXXX0110** [BartoszCichecki/LenovoLegionToolkit#834]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.3

### OS

Windows 11 Build 22621.1928

### Device

Legion 7i 16IAX7 (7th gen)

### BIOS version

K1CN40WW

### What's wrong?

When attempting to import an already existing keyboard RGB color scheme profile (that were created using previous versions of LLT), the profile is not imported, and a toast message shows up saying "Couldn't import profile" and "Profile couldn't be imported". As seen in below screenshot:

<img width="1013" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/37162057/217bd7e3-0407-449c-9868-19f71aa6856f">

New profiles, such as new profiles created by exporting current keyboard RGB colors, using the current version of LLT, can be imported without problem.

Below is a link to an example of such profile files created with previous versions of LLT that cannot be imported (have to link via Google Drive as GitHub doesn't recognize the file extension and refuses to upload):
https://drive.google.com/file/d/1dl2Q8esnLZnMvLgZc4DzdttTxrPwfpIX/view?usp=sharing

### How to reproduce the bug?

- Attempt to import an old keyboard RGB profile in LLT using the import button.
- Notice nothing in the RGB setting panel changes.
- Notice the error message popping up at the bottom of LLT window.

### What is the behavior that you expected?

RGB profile is correctly imported and the current RGB settings as previewed in the LLT RGB setting page as well as the RGB color of the various keys on the keyboard changes accordingly.

### Logs

[log_2023_06_29_10_56_40.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11904974/log_2023_06_29_10_56_40.txt)

### Additional information

I cannot remember exactly, but I believe these profiles that broke on the latest LLT version were created with one of the first couple LLT versions that had keyboard RGB profiles import/export feature added.

**Comment by BartoszCichecki** [comment]
My apologies. The JSON format changed, due to change in how the data is handled. Long story short, the "old" files can be "fixed", here is how:

In the existing files you need to find all pieces that look like this:

```
"Keys": {
      "All": false,
      "KeyCodes": [
        1,
        16,
        17,
        18,
        19,
        20,
        56,
        64,
        85,
        106,
        141,
        127,
        128,
        150,
        151,
        154,
        155
      ]
    }
```

and modify them to look like this:

```
"Keys": [
        1,
        16,
        17,
        18,
        19,
        20,
        56,
        64,
        85,
        106,
        141,
        127,
        128,
        150,
        151,
        154,
        155
    ]
```

Basically you need to remove:

```
{
      "All": false,
      "KeyCodes": 
```

in the beginning and after keycodes are listed, you need to remove `}`.

If you have any issues, let me know and I can help out.
