### ISSUE TITLE
Decreasing the brightness of the keyboard backlight

### ISSUE THREAD

**Issue by Sn0wmaN-1** [BartoszCichecki/LenovoLegionToolkit#836]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.3

### OS

Windows 10 Pro 22H2

### Device

Legion 5 Pro 16ARH7H 82RG

### Is your feature request related to a problem?

too bright keyboard backlight even in brightness mode "low"

### How would you like the problem to be solved?

for example - add a multiplier for brightness to "keyboard settings" - 0.1, 0.2, .. 1 (low), 1.5, 2 (high)

### What alternatives have you considered?

just turn off the backlight, too bright for me

**Comment by BartoszCichecki** [comment]
That can't be done. Backlight levels are predefined. You can try making that actual color "darker". For example if you set it to white (255,255,255), set it to dark gray (128,128,128).
