### ISSUE TITLE
Question: cmd to toggle OverDrive

### ISSUE THREAD

**Issue by mergen3107** [BartoszCichecki/LenovoLegionToolkit#84]
Hi! 

Again, thank you very much for your great app! 
I use it to switch power plans according to the Fn+Q states, works like a charm!

I also setup automatic switching to 60 Hz when on battery, so I wondered is there a command line tool to toggle OverDrive as well? I'd like to add it to the 60 Hz switching script.

Thank you!

**Comment by BartoszCichecki** [comment]
It can be done from command line directly with WMI. If you look into `OverDriveFeature.cs` and `AbstractWmiFeature.cs` files, you can see which commands are execute on via WMI to achieve this.

**Comment by BartoszCichecki** [comment]
You can also enable tracing (see README) and toggle the switch in the app. Check trace logs after, and there should be the exact command somewhere :)

**Comment by mergen3107** [comment]
Thank you!
