### ISSUE TITLE
Automatic Power Plan switching: no change when (un)plugged

### ISSUE THREAD

**Issue by mergen3107** [BartoszCichecki/LenovoLegionToolkit#85]
This feature works great overall!

The only time when it doesn't kick in is when the laptop is being plugged or unplugged.
For example:
1) While plugged, switch Power Plan to Performance. Fn+Q toggles the plans accordingly.
2) Unplug: the Power Plan is still on Performance, which is actually should be not present while on battery at all. Unplugged laptop only allows Balanced and Battery Saver options via Fn+Q (white and blue LEDs, respectively).
3) Fn+Q toggles the plans accordingly while unplugged as well.

Can this be fixed? As a workaround, I can try to add this switching script to my 60 Hz switching script, if you can share the command line options.

Thank you!

**Comment by BartoszCichecki** [comment]
Hey, so this is actually a bug (?) in how Lenovo handles that. So, when you are in Performance mode and you unplug power, the LED changes to blue, but BIOS still reports Performance mode - almost as if it doesn't fully change to Balance. I would say that this is not exactly fixable. If I will have more time to work on the project I'll try to work around it somehow.

**Comment by mergen3107** [comment]
OK, thank you!
