### ISSUE TITLE
Combability Request for the Legion Slim 5 Gen 8

### ISSUE THREAD

**Issue by sentfromthehub** [BartoszCichecki/LenovoLegionToolkit#857]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.14.3

### OS

Windows 11 Home Version 10.0.22621 Build 22621

### Device

Legion Slim 5 16APH8

### BIOS version

M3CN34WW

### Which features of the application did you test?

- Power Mode (Quiet and Performance)
- Battery Mode (Conservation) 
- Always on USB (Off)
- Refresh rate (adaptive to AC on/off)
- GPU Working Mode (Hybrid-Auto)
- Keyboard Backlight
- Actions (When AC power is connected and disconnected. This is such a timesaver as I'm on-the-go a lot as a student)
- Disable Lenovo Hotkeys
- Power (Legion Toolkit Settings > Power > Power Plans; set Quiet and Performance modes to custom Windows Power Plans)

### Which features of the application do not work as expected?

N/A

**Comment by BartoszCichecki** [comment]
Thanks for testing! Support will be added in next release.
