### ISSUE TITLE
Action to prevent DGPU from running on battery

### ISSUE THREAD

**Issue by Aloopyn** [BartoszCichecki/LenovoLegionToolkit#858]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.3

### OS

Windows 11 21H2 Build 22000.2124

### Device

Legion 5 15ACH6H

### Is your feature request related to a problem?

If DGPU activates on battery power it drains a lot of power. On startup on battery it doesn't deactivate DGPU. If an app uses DGPU on battery it cannot deactivate it automatically.

### How would you like the problem to be solved?

1. Change/add trigger to be "When AC power adapter is not plugged in" instead of "When AC power adapter is disconnected". 
2. Change/add trigger to be "When Power Mode is X" instead of "When Power Mode is changed" (where X is the power plan).

### What alternatives have you considered?

Alert/popup when an application uses DGPU on battery.

**Comment by BartoszCichecki** [comment]
So how do you exactly want to prevent dGPU from running on battery? It is not clear from the description you wrote.
