### ISSUE TITLE
Keyboard backlight turns on by itself

### ISSUE THREAD

**Issue by gabbello** [BartoszCichecki/LenovoLegionToolkit#862]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.3

### OS

Windows 11

### Device

Lenovo Legion 5 15ARH05

### BIOS version

EUCN37WW

### What's wrong?

Keyboard RGB lights up automatically after some time of usage.

I'm using the toolkit to disable the backlight in the keyboard, it works fine, but then after some random time (few minutes) it starts with the wave effect and if I go back to toolkit->keyboard  I get this error if I try to change it (note that the profile is still on Off 

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/2505749/f42b2302-58c1-4435-9ab1-db08cd812c3b)

### How to reproduce the bug?

I don't have a way to replicate this consistently 

### What is the behavior that you expected?

Keep keyboard backlight off

### Logs

[log_2023_07_10_08_56_49.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/11999850/log_2023_07_10_08_56_49.zip)

**Comment by BartoszCichecki** [comment]
That error means that LLT can't communicate with the RGB keyboard. Giving that your backlight turns on by itself, either EC reset should fix it, or keyboard ribbon cable got loose or the keyboard is malfunctioning. 

You can check the Discord server linked in the readme for more help.

**Comment by gabbello** [comment]
thanks for feedback, the thing is that once the toolkit is restarted (as it crashes anyway with that error) it works again to set the correct profile. And this happens very consistently, don't see how it could be a cable error.  Maybe there is some other program that blocks access to RGB?

**Comment by BartoszCichecki** [comment]
> don't see how it could be a cable error

I didn't say it _has_ to be this, it's one of the options.

I don't know which program could be doing this. I can see that no lenovo services are running, if you use other RGB software that controls the keyboard, you can check the FAQ for instructions how to disable RGB in LLT so they don't conflict.

My point is, is that this is not the correct behaviour of this keyboard, so something is not right.
