### ISSUE TITLE
GPU is not waking up anymore with Hybrid mode on.

### ISSUE THREAD

**Issue by JarneStaalPXL** [BartoszCichecki/LenovoLegionToolkit#869]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.0

### OS

Windows 11 22H2 build 22621.1928

### Device

Legion 5 15IAH7H

### BIOS version

J2CN45WW

### What's wrong?

I changed to Hybrid mode and started up a game but it's not waking up the GPU anymore.

### How to reproduce the bug?

1. Open LTK
2. Change GPU working mode to Hybrid
3. Open a game
4. Notice that the game runs on the IGPU

<img width="614" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/68494791/299e897b-92ed-48b7-b7de-558312536ba1">

### What is the behavior that you expected?

I expect the GPU to awaken

### Logs

[log_2023_07_12_06_01_55.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12024305/log_2023_07_12_06_01_55.txt)

**Comment by BartoszCichecki** [comment]
I can see that when you switched to Hybrid Mode, response from EC was that dGPU couldn't be attached at the moment:

```
[12/07/2023 06:02:13.983] [8] [IGPUModeFeatureFlagsFeature.cs#50:SetStateAsync] Setting state to Default...
[12/07/2023 06:02:13.998] [8] [IGPUModeFeatureFlagsFeature.cs#56:SetStateAsync] Set state to Default, but dGPU check failed.
```

It's not un common. Switch between modes again and it will show up, but from the point of view of LLT, I can't do anything.

**Comment by JarneStaalPXL** [comment]
@BartoszCichecki So it's a bug on who's end? I switched between modes many times and it still didn't work. Had to go in dGPU mode, then switch to Hybrid mode for it to work again.

**Comment by BartoszCichecki** [comment]
Let me put it this way: Hybrid modes are not bullet proof on Lenovo and it sometimes bugs out. Usually restart (without switching to dGPU) fixes the problem.

You can try an alternative way of switching between GPU Working Modes, to see if it yields better experience, but from my experience the default way is more reliable. Anyway check [Arguments section in the FAQ](https://github.com/BartoszCichecki/LenovoLegionToolkit#arguments) for more info.
