### ISSUE TITLE
can`t see app icon on tray bar

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [BartoszCichecki/LenovoLegionToolkit#870]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.14.3

### OS

Windows 11 22h2 2023/‎7/‎5

### Device

r9000p7945hx

### BIOS version

LENOVO LPCN42WW, 2023/6/2

### What's wrong?

after the new sys update today i can`t see the icon on tray bar,while it is start and can see in the misson manager
<img width="786" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/62531937/b98e4c54-d5a0-4238-8af9-8460f38d0f20">

### How to reproduce the bug?

i dont know ,maybe after reboot?

### What is the behavior that you expected?

fix it

### Logs

empty

### Additional information

this things happened after i update my sys and reboot,i can easily open but it can`t be seen on tray bar after many times of reopen

**Comment by BartoszCichecki** [comment]
There are no changes to tray icon handling in the last release, everything is as it used to be before. If it didn't appear, kill the process, restart LLT. And it will show up. There is nothing I can do fix it.

**Comment by systemoutprintlnhelloworld** [comment]
ok,thank you for your instant reply 😊
