### ISSUE TITLE
The latest version 2.15.0 does not work

### ISSUE THREAD

**Issue by Bodya5196** [BartoszCichecki/LenovoLegionToolkit#871]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.0

### OS

Windows 11 22H2 22621.1928

### Device

Legion 5 Pro 16ITH6

### BIOS version

H1CN53WW

### What's wrong?

Latest version 2.15.0 does not open

### How to reproduce the bug?

When installing over a previous version or after a clean install, the programme does not open

### What is the behavior that you expected?

It should open

### Logs

There is no specific action required in LLT to cause this issue. So can't make a log

### Additional information

![Без імені](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/133980180/a9ac1334-bee0-48eb-83ae-e781ef2d0240)

**Comment by BartoszCichecki** [comment]
Check the logs folder, there will be an error log. If you don't attach the logs, I can't help, how hard is it to understand?

**Comment by Bodya5196** [comment]
Could you please tell me where this folder is located?

**Comment by BartoszCichecki** [comment]
All information is in the readme.

**Comment by Bodya5196** [comment]
I'm sorry, but I don't know where it is.

**Comment by BartoszCichecki** [comment]
Broken rule #1: "I made myself familiar with the README."
