### ISSUE TITLE
The latest version 2.15.0 does not work

### ISSUE THREAD

**Issue by Bodya5196** [BartoszCichecki/LenovoLegionToolkit#872]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.0

### OS

2.15.0

### Device

2.15.0

### BIOS version

2.15.0

### What's wrong?

When installing over a previous version or after a clean install, the programme does not open

### How to reproduce the bug?

When installing over a previous version or after a clean install, the programme does not open

### What is the behavior that you expected?

It should open

### Logs

[error_2023_07_12_08_34_55.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12025749/error_2023_07_12_08_34_55.txt)
[error_2023_07_12_08_35_28.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12025750/error_2023_07_12_08_35_28.txt)
[error_2023_07_12_08_35_39.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12025751/error_2023_07_12_08_35_39.txt)
[log_2023_07_12_08_35_36.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12025752/log_2023_07_12_08_35_36.txt)

### Additional information

![Без імені](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/133980180/fbfbb4df-1dff-4ca3-b808-52d1a734391b)

**Comment by BartoszCichecki** [comment]
Thanks for reporting. I will push a hotfix update shortly. Issue was that Ukrainian localization was misconfigured.

**Comment by BartoszCichecki** [comment]
Hotfix 2.15.1 is released.
