### ISSUE TITLE
Some false positive in VirusTotal 

### ISSUE THREAD

**Issue by DaEpicR** [BartoszCichecki/LenovoLegionToolkit#873]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.1 / later/older

### Is your feature request related to a problem?

As you can see in the virus total 
https://www.virustotal.com/gui/file/90c2cbbdb7d5cc2e756a0282ae84e2abc4cc617c7102f016d83857567224bbc9?nocache=1
there is some false positive here and there 

### How would you like the problem to be solved?

This is a known issue because most dev's in haven't gotten the Windows signature certificate.

All best for you thanks for the project ,its a real and even better alt for the vantage bloat .

**Comment by BartoszCichecki** [comment]
Broken rule 1: "I made myself familiar with the README."
