### ISSUE TITLE
Fan Control while on battery

### ISSUE THREAD

**Issue by Sebastian-Hothaza** [BartoszCichecki/LenovoLegionToolkit#874]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.1

### OS

Windows 11

### Device

Legion 7i Gen7

### Is your feature request related to a problem?

Fan control not available on battery

### How would you like the problem to be solved?

Allow custom power mode while on battery OR allow fan control changes for the default balanced, performance, quiet power modes.

### What alternatives have you considered?

There are no fan alternatives

**Comment by BartoszCichecki** [comment]
Why did you check "I made myself familiar with the README.", if you clearly didn't?
