### ISSUE TITLE
Add an option to permanently disable unsupported device popup

### ISSUE THREAD

**Issue by PirateGeek00** [BartoszCichecki/LenovoLegionToolkit#878]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.1

### OS

Windows 11 Home 22H2

### Device

Legion 5 15IAH7H

### Is your feature request related to a problem?

I have an issue with the motherboard of my laptop that causes programs to not be able to identify the model, machine type and serial number of my laptop. This causes lenovo legion toolkit to show the unsupported device popup window every startup even though the laptop is fully supported.

### How would you like the problem to be solved?

It would be very helpful to add an option to permanently disable the unsupported device popup window.

### What alternatives have you considered?

A way to manually enter the model, machine type and serial number and save it. Disable automatic check of these every startup and use the user provides specifications.

### Additional information

![Screenshot 2023-07-14 151547](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/139549955/1d82daa0-d31c-4857-a681-7ce37b1ce950)
Briefly to conclude, an option to disable this popup window is needed. Thank you.

**Comment by BartoszCichecki** [comment]
Broken rule: "I made myself familiar with the README."
