### ISSUE TITLE
[Compatibility Request] Legion Y520-15IKBN

### ISSUE THREAD

**Issue by pi4a7a** [BartoszCichecki/LenovoLegionToolkit#88]
Lenovo butchered their software for the series. I'm here to request a model support. Apologies if I'm doing it wrong. not sure how to add labels.

Legion Y520-15IKBN

**Comment by BartoszCichecki** [comment]
Hey, thanks. Did you check if all works correctly? You can check how to launch the app without compatibility check at the bottom of the README.
