### ISSUE TITLE
[BUG]: No Supported Feature Found

### ISSUE THREAD

**Issue by DevNightshade** [BartoszCichecki/LenovoLegionToolkit#886]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.2

### OS

Windows 10 Pro 22H2

### Device

Legion 7 16ACHg6

### BIOS version

GKCN60WW

### What's wrong?

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/106551976/a8f7347c-1876-46d4-9941-0d82391e3d4d)
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/106551976/15332cf5-d36f-4178-b0e6-7cfc7a73fc97)

### How to reproduce the bug?

1. Update to 2.15.2 (from the prev. 2.15.1 version)
2. Start the toolkit
3. See errors as provided

### What is the behavior that you expected?

That the progam starts as normal and runs as intented.

### Logs

[log_2023_07_18_12_57_00.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12080665/log_2023_07_18_12_57_00.txt)

### Additional information

downgrading back to 2.15.1 works perfectly fine.

**Comment by BartoszCichecki** [comment]
My bad! Apologies, 2.15.3 is already building!

**Comment by DevNightshade** [comment]
that was fast.

**Comment by BartoszCichecki** [comment]
2.15.3 is released now. Apologies again.
