### ISSUE TITLE
Legion RGB backlight effects permanents when booting up the laptop

### ISSUE THREAD

**Issue by Phexoe** [BartoszCichecki/LenovoLegionToolkit#889]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.1

### OS

Windows 22H2 22621

### Device

Legion 5 Slim 16APH8

### Is your feature request related to a problem?

Is it possible to have features from Legion RGB moved to Legion Toolkit backlight section or is there a way to make the Legion RGB defined preset to be the one booting up with the laptop at launch (currently I have to open Legion RGB manually every time which is not very convenient).

### How would you like the problem to be solved?

Make Legion RGB features available in toolkit (smooth wave effect) or Legion RGB last preset to be the one running at start.

### What alternatives have you considered?

Task scheduler.
Running argument line to disable rgb backlight in toolkit.

**Comment by BartoszCichecki** [comment]
Regarding more RGB effects: make yourself familiar with the readme.

Regarding Legion RGB: Ask the author.
