### ISSUE TITLE
LLT taskbar icon sometimes not visible after Windows Boot

### ISSUE THREAD

**Issue by klour** [BartoszCichecki/LenovoLegionToolkit#894]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.4

### OS

Windows 11 Pro 22H2 22621.1992

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN55WW

### What's wrong?

It looks like the taskbar icon (lower right) does not appear from time to time, although I have the setting "Minimize to close" activated all the time.

### How to reproduce the bug?

1. Windows Boot.
2. LLT taskbar icon not visible.
3. By clicking the exe/my LLT shortcut on the desktop, the LLT UI appears. 
4. But no taskbar icon is visible.
5. By clicking "X" in the LLT UI, the UI disappears (which is intended), but taskbar icon remains invisible.

I already checked taskbar settings in Windows. LLT icon is set to always be visible (and not hidden) in the taskbar.
In LLT settings, the "Minimize to Close" feature is also activated (my default).
LLT is also set to start automatically along with Windows.

Workaround: Usually this issue disappears by logging my Windows session off and on again.
The mentioned taskbar icon issue does not appear frequently. I cannot see a pattern, when this happens. Most of the time (90%) of my Windows boots the LLT taskbar icon is visible. 

I have the assumption, that this issue is observable since 2.15.x. But not 100% sure. Is this behaviour may known to you?

### What is the behavior that you expected?

Taskbar icon always visible.

### Logs

I have no logs. Required?

**Comment by klour** [comment]
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/77859971/860f26a3-5015-4a92-b3a1-daa3832b41d4)

**Comment by klour** [comment]
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/77859971/740f2e43-d7ef-4627-abcd-b5b3452936c8)

**Comment by klour** [comment]
> There are some issues with tray handling in Windows 11 in general. You can check out a test build linked in #673 and see if it still happens. 

Hi Bartosz.
Dziękuję ;-) Good to know that there is somehow a reason for this.

I think I am fine with it. As I said, it just happens rarely. You can close this ticket if you want.

**Comment by BartoszCichecki** [comment]
That's OK, but try the build anyway. I am trying to improve the situation but since I don't have the issue I can't check myself.

**Comment by klour** [comment]
Ok will do.

**Comment by BartoszCichecki** [comment]
Continues as part of #673.
