### ISSUE TITLE
Application load time after 2.15.0

### ISSUE THREAD

**Issue by rezpower** [BartoszCichecki/LenovoLegionToolkit#898]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.0 and Later

### OS

Windows 11 22h2 22621.1992

### Device

Legion 7i 2022 16IAX7

### Is your feature request related to a problem?

Since version 2.15.0 and later after adding sensors to the Dashboard Legion toolkit is taking much longer to open (load).  I am not sure, but my guess is that it takes some extra time to load the sensors information. This is alright as more features should take more resource. 

### How would you like the problem to be solved?

We also have the choice to remove sensors from dashboard. For those choosing to do this, is it possible to somehow disable totally this feature when disabling it in dashboard to have the application open as fast as before?

Of course this is nothing vital and we all can live with it if implementation is complicated.

### What alternatives have you considered?

non

**Comment by BartoszCichecki** [comment]
Can you attach a log? Let's see where/if it hangs. Startup takes around 1-2 seconds and if you hide sensors from dashboard, no code related to that is running.

**Comment by rezpower** [comment]
Thanks for your reply BartoszCichecki,
I was back on 2.14.2 and as you mentioned it takes max 2 secs to load. I installed 2.15.4 right now just to make the requested log and again I see that it takes a lot longer to load. I made two logs (one with sensors enabled and one with sensors disabled) in case you need to compare. 
[log_2023_07_24_17_33_49 (2.15.4) Sensor disabled.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12148518/log_2023_07_24_17_33_49.2.15.4.Sensor.disabled.txt)
[log_2023_07_24_17_28_10 (2.15.4) Sensor enabled.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12148519/log_2023_07_24_17_28_10.2.15.4.Sensor.enabled.txt)

**Comment by BartoszCichecki** [comment]
That is very bizarre. We have exactly the same laptop, same BIOS, same OS and .NET version, yet mine starts in 2 seconds:

`[24/07/2023 19:15:16.720] [1] [App.xaml.cs#68:Application_Startup] Flags: ...`
`[24/07/2023 19:15:18.749] [1] [App.xaml.cs#140:Application_Startup] Start up complete`

Yours has this weird ~4 seconds delay when LLT shows the main window where nothing is logged. Nothing really is happening there to be honest, but here is a test build where I changed the init process slightly, so check it out if you can.
[LenovoLegionToolkitSetup.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12149492/LenovoLegionToolkitSetup.zip)


My log for reference:
[log_2023_07_24_19_15_16.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12149314/log_2023_07_24_19_15_16.txt)

**Comment by rezpower** [comment]
Hmmm same laptop different result! I would then assume that something is wrong with my laptop or my settings!
But you fixed it for me with this beta version! If still my laptop is for any reason slower then yours, then with this new build, your toolkit should load even before clicking on it! ;)

Thanks a lot man. it's totally fixed now.

Here is the new log in case you want to check it:
[log_2023_07_24_23_57_53.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12155857/log_2023_07_24_23_57_53.txt)

**Comment by BartoszCichecki** [comment]
Glad to hear, it looks like performance counters are slow to create on your Windows install, but I am not sure why. They are needed for sensors and where created even when sensors were not shown. So you where kind of right that it was related - no code was running if sensors are shown, but some intialisation was done regardless.

> how did the new GPU Working Mode work for you?

It worked fine, it was a little faster to switch, and gives a error status in case switch failed. But, as I wrote, it caused issues for many and tbf I am also using the "old way" currently, because it is "good enough".

**Comment by rezpower** [comment]
Thanks a lot for the great support. Legion Toolkit is already a great gift and your support makes it even better.
