### ISSUE TITLE
Legion 5 15ITH6 is compatible

### ISSUE THREAD

**Issue by MrShawky** [BartoszCichecki/LenovoLegionToolkit#90]
Legion 5 15ITH6 (RTX 3050ti, I7-11800H, Windows 11 pro)

created a new shortcut and added the argument --skip-compat-check to open the app

List of features that are working as expected:
-Power Mode.
-Hybrid Mode.
-Battery Mode.
-Always on USB.
-Refresh Rate (worked for me after using CRU to add 60hz with the native 165hz)
-Discrete GPU.
-Misc.
-Enable/Disable Lenovo Vantage.

List of features that seem to not work:
-None.

List of features that crash the app:
-None.

**Comment by BartoszCichecki** [comment]
Thanks, will be added in next release.
