### ISSUE TITLE
2 Feature Request

### ISSUE THREAD

**Issue by hpx502766238** [BartoszCichecki/LenovoLegionToolkit#904]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.4

### OS

Windows 11 Home

### Device

Lenovo Legion R9000X2021R

### Is your feature request related to a problem?

BIOS HACN40WW
1.I want to adjust my CPU and GPU fan speed separately.
2.I want to adjust the UMA buffer size,there is no relative options in my bios,is there other method to adjust it?

### How would you like the problem to be solved?

update the software

### What alternatives have you considered?

edit bios,then flash it.

**Comment by BartoszCichecki** [comment]
Neither is possible unfortunately.
