### ISSUE TITLE
Strange Temp on Fan curve sensors

### ISSUE THREAD

**Issue by class77** [BartoszCichecki/LenovoLegionToolkit#905]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.0_b1

### OS

Windows 10 x64

### Device

Legion 5 Pro 16ARH7H

### BIOS version

JUCN59WW

### What's wrong?

On the fan curve, when I look at the different temp/ %fan levels, there are weird temperatures proposed

![screen](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/48809007/219a827f-c285-4cb8-9f4b-ab884fe9b362)

### How to reproduce the bug?

Create a custom profile to access the fan settings

### What is the behavior that you expected?

a logical series of temperatures

### Logs

[log_2023_07_29_19_22_03.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12207832/log_2023_07_29_19_22_03.txt)

**Comment by BartoszCichecki** [comment]
> a logical series of temperatures

That's a task for lenovo to use logical temps on the curve. Not for me.

**Comment by BartoszCichecki** [comment]
Also, duplicate of #370
