### ISSUE TITLE
Refresh rate selection is weird

### ISSUE THREAD

**Issue by MarvinFS** [BartoszCichecki/LenovoLegionToolkit#91]
Hey there, probably just filtering or something, but still a bit confusing with refresh rate selection (Legion 5 pro 16ACH6H)

![2022-04-24_00-48-53](https://user-images.githubusercontent.com/7998636/164944228-7f250aeb-3e1e-4a84-9592-3e2fdc5e8cce.png)

**Comment by BartoszCichecki** [comment]
Hey, yeah, that indeed looks weird. Did you set any custom resultions manually or something? I will add more logging to the next release so we can figure this one out.

**Comment by MarvinFS** [comment]
> Hey, yeah, that indeed looks weird. Did you set any custom resultions manually or something? I will add more logging to the next release so we can figure this one out.

no, not yet, no custom resolution or something. but that's a legion 5 pro laptop - hybrid video, dGPU and iGPU both are working, could be the reason? Happy to test of something.

**Comment by BartoszCichecki** [comment]
I added some filtering so that shouldn't happen anymore, but in case you encounter problems I also added more tracing, so if anything reopen this issue and attach the log (instructions in README).

**Comment by MarvinFS** [comment]
Bartosz, I'm sorry to reopen, thank you very much for the update, I'll test in right away and will report back. Do you have a release schedule or some kind of beta branch? Am I missing something? I haven't found testing branch and latest release was April 11th with 1.6.3.

**Comment by BartoszCichecki** [comment]
Ah, yes, I need to work on better communication :D The update should be up within couple of days, there is one more feature I need to wrap up :) I don't have a beta branch yet tbh, but that's probably a good idea.

**Comment by MarvinFS** [comment]
confirmed - 1.7.0 fixed the issue! thank you very much!
