### ISSUE TITLE
[COMPATIBILITY]: Custom Power Mode on IdeaPad Gaming 3 16IAH7

### ISSUE THREAD

**Issue by yannikmotzet** [BartoszCichecki/LenovoLegionToolkit#912]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.15.4

### OS

Windows 11 22H2 (Build 22621.1992)

### Device

IdeaPad Gaming 3 16IAH7

### BIOS version

JMCN42WW

### Which features of the application did you test?

Power Mode

### Which features of the application do not work as expected?

Custom Power Mode with Fan Control is not showing up

### Additional information

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/40294960/b7c24b8f-8823-4c05-935b-a3c3c35a9c06)

**Comment by BartoszCichecki** [comment]
If it doesn't appear, then it is not supported.
