### ISSUE TITLE
No GPU Working Mode / Hybrid Mode option

### ISSUE THREAD

**Issue by simonemurari** [BartoszCichecki/LenovoLegionToolkit#913]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.4

### OS

Windows 11 10.0.22621 build 22621

### Device

Legion Slim 5 Gen 8 16APH8

### BIOS version

M3CN34WW

### What's wrong?

There's no GPU Working Mode / Hybrid Mode option in the Graphics category.

### How to reproduce the bug?

I open the program and the option is not present, if I try to switch it on using Customize I can't.

### What is the behavior that you expected?

The option to exist.

### Logs

[log_2023_08_07_21_21_34.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12285323/log_2023_08_07_21_21_34.txt)

### Additional information

<img width="1108" alt="Screenshot 2023-08-07 233233" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/90158532/32639fb0-ffb8-416c-be52-88715bd04897">

**Comment by BartoszCichecki** [comment]
Based on the logs from other users (#857, #903) this seems to be a problem with your laptop. Either drivers are missing or something is wrong with your windows install.
