### ISSUE TITLE
Extra power will be applied to the GPU after setting Configurable TGP and Dynamic Boost to 0W

### ISSUE THREAD

**Issue by Alpha-Jim** [BartoszCichecki/LenovoLegionToolkit#915]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.4

### OS

Windows 11 22H2 22621

### Device

Legion R9000K2021H

### BIOS version

GKCN60WW

### What's wrong?

5W extra power will be applied to the GPU after setting Configurable TGP and Dynamic Boost to 0W
e.g. the base TGP of RTX 3060 Laptop is 80W, after setting, the result displayed in nvidia-smi is 85W.

### How to reproduce the bug?

1. Set power mode to Custom
2. Click the settings button beside the mode list
3. Drag Configurable TGP and Dynamic Boost to 0W
4. Click Save or Save & Exit
5. Open a console and execute nvidia-smi
6. The result is 85W rather than 80W

### What is the behavior that you expected?

The power should be equal to Base TGP, without extra power.

### Logs

[log_2023_08_15_03_49_32.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12341235/log_2023_08_15_03_49_32.txt)

### Additional information

Legion R9000K2021H should be the CN version of Legion 7 16ACHg6
GPU OC is enabled with GPU core +113MHz, VRAM +200MHz

**Comment by BartoszCichecki** [comment]
I don't see anything wrong in the log:

```
[15/08/2023 03:50:17.423] [34] [GodModeControllerV1.cs#155:ApplyStateAsync] Applying GPU Power Boost: Value: 0, Min: 0, Max: 15, Step: 5, Steps: [], DefaultValue : 
[15/08/2023 03:50:17.428] [32] [GodModeControllerV1.cs#172:ApplyStateAsync] Applying GPU Configurable TGP: Value: 0, Min: 0, Max: 35, Step: 5, Steps: [], DefaultValue :
```

`0` is applied for both parameters and according to EC it is an accepted value. It doesn't look like a bug on my side.
