### ISSUE TITLE
PPT Fast adjustment in Custom Mode for Gen 6/7 AMD models

### ISSUE THREAD

**Issue by Alpha-Jim** [BartoszCichecki/LenovoLegionToolkit#919]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.4

### OS

Windows 11 23H2 Build 25398.1

### Device

Legion R9000K2021H (82N6, aka Legion 7 16ACHg6 outside of CN)

### Is your feature request related to a problem?

For stock settings on Gen 6 and Gen 7 AMD models (slim models not included), while using the 135W GaN Adapter (connecting to the DC port, not USB-C), Lenovo only provides 50W PPT Slow/40W Sustained for CPU and 40W for GPU. 
I have been using LLT to re-adjust the power consumption since bypassing this limit, but in Custom Mode settings, the PPT Fast value is unable to adjust, keeping the maximum value, and in some scenario, for example, burst workload, the default PPT Fast may cause an adapter disconnect/connect loop.

### How would you like the problem to be solved?

I would only expect an extra slider for adjusting the PPT Fast value in the Custom Mode settings panel.

### What alternatives have you considered?

I have tried the Ryzen Controller, but it's less automated and the project seems to be out of maintenance.

### Additional information

The current Long Term/Short Term adjustment in Custom Mode settings is referred to Sustained Power Consumption/PPT Slow. 
<img width="1003" alt="screenshot" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/58557055/bf82c795-6c87-4703-b029-e8834f0c7669">

**Comment by BartoszCichecki** [comment]
Unfortunately, only these options are exposed by Lenovo. For other settings you need to stick to Ryzen Controller.
