### ISSUE TITLE
"System.InvalidOperationException: fileHandle is 0" on clean install Windows 11, disabled auto driver install

### ISSUE THREAD

**Issue by mvierssen** [BartoszCichecki/LenovoLegionToolkit#92]
I am getting a "System.InvalidOperationException: fileHandle is 0" on Windows 11:
[log_2022_04_24_00_21_21.txt](https://github.com/Bart\szCichecki/LenovoLegionToolkit/files/8548704/log_2022_04_24_00_21_21.txt)

The following may be relevant:
- No Legion drivers etc. installed. Do I need any for this to work? Which ones are minimally required?
- Lenovo legion power plans manually installed
- DotNet 5.0 x64 and x86 versions installed
- Auto driver install is disabled

**Comment by BartoszCichecki** [comment]
Hey, that is most likely because energy driver is missing. I recommend that you install Vantage to get all things in place and then deactivate Vantage from my app so it doesn't consume resources.
