### ISSUE TITLE
Legion R9000P2021H 82JQ cannot obtain warranty information

### ISSUE THREAD

**Issue by 1235789gzy1** [BartoszCichecki/LenovoLegionToolkit#925]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.4

### OS

win10 22H2

### Device

Legion R9000P2021H 82JQ

### BIOS version

GKCN60WW

### What's wrong?

My device is unable to obtain warranty information. After checking the issues, I believe it is a fixed issue, but it is still not available on my device

### How to reproduce the bug?

Open LenovoLegionToolkit normally to view warranty information
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/52618207/c630e816-01a3-4445-9bcf-0ace8f70f296)

### What is the behavior that you expected?

I would like to see the warranty information

### Logs

[log_2023_08_22_13_12_27.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12409052/log_2023_08_22_13_12_27.txt)

### Additional information

Perhaps it's because I recently used a discounted extended warranty service?

**Comment by BartoszCichecki** [comment]
Fix for #890 wasn't released yet.
