### ISSUE TITLE
Fn q bug

### ISSUE THREAD

**Issue by Sablad28** [BartoszCichecki/LenovoLegionToolkit#935]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.0

### OS

Windows 11 latest build

### Device

lenovo legion slim 5 7840hs rtx 4060

### BIOS version

M3CN34WW

### What's wrong?

Hey so i have located a problem with the new toolkit,on my slim 5 7840hs  switching power modes with the fn q shortcut doesn't update the mode in the app, for example say i switch to performance from balance,it stays in balanced in the app and doesn't change the menu(the modes actually do change) however when i rollback to 2.15 the issue disappears

### How to reproduce the bug?

1.Use fnq while in any power mode and you will notice right away

### What is the behavior that you expected?

IT should update the performance mode while using the shortcut

### Logs

[log_2023_08_25_17_59_33.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12442464/log_2023_08_25_17_59_33.txt)

**Comment by BartoszCichecki** [comment]
Great catch, totally missed this one. Hotfix is on the way.

**Comment by Sablad28** [comment]
Nice appreciate it,thanks for the quick response,love ya
