### ISSUE TITLE
Add Battery discharge rate to the "Sensors" block on the "Dashboard" page

### ISSUE THREAD

**Issue by gawtDamn** [BartoszCichecki/LenovoLegionToolkit#939]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.1

### OS

Win 11 22H2 

### Device

Legion 5 pro 16ARH7H

### Is your feature request related to a problem?

no. This is a feature request

### How would you like the problem to be solved?

In the "Sensors" block on the "Dashboard" page, there is a free line on the left side (the CPU side) because my Gen7 legion does not report the Memory Clock the way the GPU side does.  Please consider putting the battery discharge rate on this free line, so that the CPU/GPU utilization / fans can be seen at the same time as the discharge / charge rate.  

The main advantage of this is bringing the battery discharge rate onto the customizable dashboard page, so that I can easily see how any changes I make using the dashboard, or other reported statuses, affect power draw. 

 

### What alternatives have you considered?

My current best workaround is just switching between the dashboard and the battery page, or leaving the dashboard page up and the hovering over the System Tray icon to get the updated power draw.

**Comment by BartoszCichecki** [comment]
Not a bad idea, however I am not sure if it will be added. Each of the "sensor" shows a bar which what % of max is currently utilised. There is no way to get maximum charge/discharge, because that information is not available anywhere in the system, so I can render the battery charge/discharge in the same way.

Discharge rate is also reported by Windows with _some unknown_ delay, so it it won't be very useful for comparing CPU/GPU usage with discharge rate.

**Comment by gawtDamn** [comment]
Got it. Agreed on the potential limited utility. As for making the UI elements similar, if I were doing it, I would just keep persistent values of the observed charge and discharge rates, and update those as necessary when a larger value was seen by LLT, and use those maximal values to scale the graphical bars. I assume those could be observed and recorded only when the battery page and the sensors view were in use, and possibly when the LLT system tray was hovered over and displayed the battery activity.

**Comment by Quenom** [comment]
From what it seems from lenovo specification fastest charging speed possible would be around 200w 
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/30837190/c136206a-08d3-44d7-8c20-514fa963169b)
it could be safe to assume battery couldnt discharge faster then that(maybe add 50w safety, so 250w, i think fastest adapter lenovo offers is 300w) and change the color of the bar depending on if its charging or dischargning

**Comment by bcutter** [comment]
Looking at the battery charge/discharge rate a lot.

Would love to see it on the dashboard tab instead of needing to switch to the battery tab all the time.

**Comment by mctubster** [comment]
Agreed. Showing the battery charge/discharge rate and current capacity deserves its place on the home page. I am having to switch to the battery tab often to see only these metrics

**Comment by bcutter** [comment]
OK.

Community/users: "please add, please add, ..."

Maintainer:
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/13799156/d88cd43e-6c85-473e-8b24-2be020bda2aa)
