### ISSUE TITLE
Context menu is acting strange

### ISSUE THREAD

**Issue by oogpunt** [BartoszCichecki/LenovoLegionToolkit#94]
on the Legion 5 Pro 16ITH6H after update

![Animation](https://user-images.githubusercontent.com/73290736/166449266-801e5a25-798f-4a30-b4b9-73714edce7ae.gif)

**Comment by BartoszCichecki** [comment]
Hey, this looks like an issue with WPF that is used as a base for this app. Not sure what I can do about it though, problems like this happen from time to time with WPF unfortunately.
