### ISSUE TITLE
Add windows notifications that trigger based on data already available in Legion Toolkit

### ISSUE THREAD

**Issue by advanced03** [BartoszCichecki/LenovoLegionToolkit#942]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0 BETA

### OS

Windows 11 22H2

### Device

Legion 5 Pro Gen 7 AMD

### Is your feature request related to a problem?

No this is not related to a problem.

### How would you like the problem to be solved?

See the above

### What alternatives have you considered?

See the above

### Additional information

This could even be integrated into actions as a trigger, like for example I get notified when my battery drain exceeds a x amount which I can set myself. Or temps etc.

**Comment by BartoszCichecki** [comment]
What notifications? What existing data? I can't read your mind, put some effort into creating a ticket next time. "See above" is not a description.

Closing the issue.
