### ISSUE TITLE
Bug about battery mode on Thinkbook 16+

### ISSUE THREAD

**Issue by github-0-searcher** [BartoszCichecki/LenovoLegionToolkit#943]
### Rules

- [x] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.1

### OS

Windows 11 22H2 22621.2134

### Device

Thinkbook 16 G5+ APO

### BIOS version

MFCN26WW

### What's wrong?

The battery mode option is not working as expected.

The battery mode option in home page and battery page only appears occasionally on software startup. When the option is there, changing to conservation does not work. (The battery is still being charged, instead of only using AC input and leaving battery idle)

The battery mode option in actions is always there. But any action includes changing battery mode will end with errors.

### How to reproduce the bug?

Startup this software:
+ If the battery mode option is there, try change it to conservation, and battery page tells you that the battery is still being charged.
+ else, the battery mode option is missing

Run a action that changes battery mode:
+ it ends with error.

### What is the behavior that you expected?

Battery mode option in home page and battery page should always there.

The conservation mode should be in place.

The actions with battery mode changing should be effective.

### Logs

[log_2023_08_31_04_32_18.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12482253/log_2023_08_31_04_32_18.txt)

**Comment by BartoszCichecki** [comment]
Unsupported device.

**Comment by github-0-searcher** [comment]
I do understand there is quite a gap among Lenovo devices. There is something called [ThinkToolkit](https://github.com/Flicker372/ThinkToolkit) that provides power mode and battery mode changing on Github. But its GUI is not as good as LenovoLegionToolkit and it does not provides actions and anything other than power mode and battery mode. In comparison, LenovoLegionToolkit is much better. Too bad it does not work for thinkbook. 

Both LenovoLegionToolkit and ThinkToolkit are written in C#, I don't anything about C# unfortunately. I put the link here if the maintainer(please!!! if there is any chance) or some thinkbook & c# user decides to add support someday in future.
