### ISSUE TITLE
Roblox's anticheat detects LenovoLegionToolkit as a cheat and crashes game

### ISSUE THREAD

**Issue by RealMamitler** [BartoszCichecki/LenovoLegionToolkit#948]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.1

### OS

Windows 11 22H2 22621.2134

### Device

Legion 7 16IAX7

### BIOS version

K1CN38WW

### What's wrong?

Online videogame roblox (https://www.roblox.com)'s anticheat flags Lenovo Legion Toolkit as a cheat and crashes game 1 minute in or on startup.

### How to reproduce the bug?

1. Download Roblox and Lenovo Legion Toolkit
2. Play a game on roblox while Lenovo Legion Toolkit is running in the background
3. Game should crash in 1 minute to on app startup

### What is the behavior that you expected?

Roblox should not crash after 1 minute or so and should function properly alongside Lenovo Legion Toolkit

### Logs

[log_2023_09_02_15_27_00.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12504235/log_2023_09_02_15_27_00.txt)

### Additional information

Roblox usually either crashes or gives a message saying: "Unexpected error, we are sorry!" with a prompt to quit the application, or just straight up crashes.

**Comment by BartoszCichecki** [comment]
It looks like this more a ticket for the Roblox team, not me. I don't know what triggers the anti cheat.
