### ISSUE TITLE
please add the dynamic option of the refresh rate that is in the windows settings

### ISSUE THREAD

**Issue by samy02** [BartoszCichecki/LenovoLegionToolkit#949]
### Rules

- [ ] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

win 11 23H2 build

### Device

legion 5 pro 16ACH6H

### Is your feature request related to a problem?

nope not a problem but i would like you to add this feature

### How would you like the problem to be solved?

to add it among the other desplay refresh rate options like the in the settings app

### What alternatives have you considered?

my alternative now is when i replug my laptop in the charger i have to manually go to the settings in windows and change it to dynamic 
i would like it to be added so that i can add it in the actions when i replug my laptop

### Additional information

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/77360133/93f4ec3e-26f4-4994-920f-cbf6bc28bae4)

**Comment by BartoszCichecki** [comment]
Unfortunately Microsoft did not expose an API for 3rd part apps for this feature, so it's not possible to add.

**Comment by samy02** [comment]
i see what a shame. 
thanks alot for your efforts and this wonderful tool.
