### ISSUE TITLE
Partial support of IdeaPad Pro 5 Gen 8 16APH8

### ISSUE THREAD

**Issue by mooms06** [BartoszCichecki/LenovoLegionToolkit#953]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.16.2

### OS

Windows 11 22H2 22621.2134

### Device

IdeaPad Pro 5 16APH8 (type 83AR)

### BIOS version

MDCN27WW

### Which features of the application did you test?

All functions listed are working (see capture)

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/25405517/4097a57b-571d-4a21-b56e-a5818b40df13)

### Which features of the application do not work as expected?

It missses the Power mode toggle (the most important feature).

### Logs

[log_2023_09_08_12_19_25.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12559822/log_2023_09_08_12_19_25.zip)

**Comment by BartoszCichecki** [comment]
As written in the readme: "If your laptop is not part of Legion series, this software is not for you. Please do NOT open compatibility requests for other devices."

**Comment by mooms06** [comment]
Ideapad Gaming are listed though.

**Comment by mooms06** [comment]
Can't you at least check if the support could be added easily ? I would be very glad to get rid of Vantage...Or point me to an equivalent of LLT for IdeaPad ?

**Comment by BartoszCichecki** [comment]
No I'cant:
1. I don't have time for it
2. I don't have a device to reverse engineer


Project is open source, so if someone wants to reverse engineer this and add support they are free to do so.
