### ISSUE TITLE
Allow changing Battery Mode from the Battery page 

### ISSUE THREAD

**Issue by chitza** [BartoszCichecki/LenovoLegionToolkit#956]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 10 Pro 22H2

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

I often find myself navigating to the "Battery" page to change the charging mode (Rapid/Normal).
And every time I discover the feature is in the "Dashboard" page 😄 

### How would you like the problem to be solved?

Place a copy of the "Battery Mode" widget at the top of the "Battery" page

### What alternatives have you considered?

-

**Comment by BartoszCichecki** [comment]
You can never really satisfy everyone, so I am putting this one on hold for now. Let's see if the idea becomes popular.

**Comment by russellmm** [comment]
lol... When I read this I thought it was a request to allow you to disconnect the Battery and shutdown (the thing we have to do in BIOS). now that would be interesting. 

But moving the battery mode to a separate page.... please no.

**Comment by cristi-paraschiv** [comment]
> 
> 
> But moving the battery mode to a separate page.... please no.

I'm not proposing a move, merely a copy/clone.

**Comment by BartoszCichecki** [comment]
Closing the issue due to lack of support (and some opposition).
