### ISSUE TITLE
Installation Process is Broken with .NET Installed

### ISSUE THREAD

**Issue by OttCS** [BartoszCichecki/LenovoLegionToolkit#96]
Just recently wiped my Legion 5, and when trying to reinstall LLT it requires .NET 5.0, and the provided link correctly opens the download page. However, even after downloading the linked version 5.0.16 it just keeps thinking that .NET isn't installed. Is there a fix I can do or is it something in LLT's code?

**Comment by OttCS** [comment]
Note: Neither the x86 or x64 runtimes work for 5.0.16, same thing with .NET 6.0.202

**Comment by BartoszCichecki** [comment]
Same here, working fine with 5.0.16, so probably some sort of issue on your machine.
