### ISSUE TITLE
Add an option to switch between degree Celcius and Fahrenheit

### ISSUE THREAD

**Issue by AnoTherK-ATK** [BartoszCichecki/LenovoLegionToolkit#960]
### Rules

- [x] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2 Build 22621.2134

### Device

Legion Y9000X IAH7

### Is your feature request related to a problem?

I want to know the temperature in Celcius but I don't know how to change

### How would you like the problem to be solved?

Please add an option to switch between them

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment]
Click the temperature.
