### ISSUE TITLE
Discrete GPU

### ISSUE THREAD

**Issue by Henok7777** [BartoszCichecki/LenovoLegionToolkit#964]
### Rules

- [ ] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 Home 22H2  22621.2215

### Device

Legion 5 15ARH7H

### BIOS version

JUCN58WW

### What's wrong?

I cannot deactivate the GPU on all GPU working mode even if it says inactive. 

### How to reproduce the bug?

1. Go to the home page .
2. scroll to the Graphics section.
3. select any GPU mode except " dGPU" mode.
4. then go to the Discrete GPU part it say " inactive" , select the Deactivate dropdown menu and select Restart GPU.
5. it doesn't restart the GPU for me, but used to work .  

### What is the behavior that you expected?

it should deactivate the gpu.

### Logs

hb

**Comment by BartoszCichecki** [comment]
I don't get it. If it says inactive then it isn't active. What more do you want to deactivate?
