### ISSUE TITLE
System.IO.FileNotFoundException on boot

### ISSUE THREAD

**Issue by eldendiss** [BartoszCichecki/LenovoLegionToolkit#965]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Win 11 22H2 build 22621

### Device

IdeaPad Gaming 3 15ACH6

### BIOS version

H3CN39WW(V2.09)

### What's wrong?

Sometimes when PC boots up Legion Toolkit crashes with unexpected exception IO.FileNotFoundException. This issue is not 100% reproducible on every boot, most of the time everything works as it should. Program can be started manually without any issues.

### How to reproduce the bug?

My settings: 

- Autorun enabled
- Minimize on close enabled
- Disable Lenovo Vantage and ImController enabled (Lenovo Vantage not installed)
- Disable Lenovo Hotkeys enabled

Then just shutdown and boot up computer.

### What is the behavior that you expected?

Not throwing the exception? :D

### Logs

[error_2023_09_13_12_26_57.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12597369/error_2023_09_13_12_26_57.txt)

**Comment by BartoszCichecki** [comment]
> Could not load file or assembly 'System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

It looks like you have some issues with your .NET installation. You can follow the steps in the README and reinstall it, but if that doesn't help I can't help with fixing this issue, since it indicates it's a problem with your Windows install.
