### ISSUE TITLE
Lenovo Legion Slim 5 14APH8

### ISSUE THREAD

**Issue by FabianFinke** [BartoszCichecki/LenovoLegionToolkit#969]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.16.2

### OS

Windows 11 Home 22H2

### Device

Legion Slim 5 14APH8 (82Y5)

### BIOS version

MACN22WW

### Which features of the application did you test?

Almost everything works out of the box.

**Tested and working**

- Switching performance mode
- Battery mode
- Always on USB
- Flip to start
- GPU mode
- GPU overclock
- HDR
- Mic switch
- Keyboard brightness
- Custom mode TGP/TDP
- Dashboard stats

### Which features of the application do not work as expected?

Setting the fan curve seems to work partially but the fans won't go lower than 4800rpm at max TGP. Possibly a hardware limitation? If so it would be nice if the UI could reflect the fan speed limits.

### Logs

[log_2023_09_15_07_57_31.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12618142/log_2023_09_15_07_57_31.txt)

### Additional information

Thank you!

**Comment by BartoszCichecki** [comment]
From the log, I can see that the curve is applied correctly. Lenovo's fan control is known to be weird and I am already showing all the data that are available to the user. If despite applying the curve, fans do something else, the only option is that it will be fixed with a BIOS update.

**Comment by BartoszCichecki** [comment]
Yes, absolutely it will go in the next release.

**Comment by Natriumpikant** [comment]
Damn, we really need a BIOS Update for this. Beside the fans, this hardware is a really nice piece.
