### ISSUE TITLE
Cant run

### ISSUE THREAD

**Issue by jookk** [BartoszCichecki/LenovoLegionToolkit#97]
Can you help me to run your Vantage utility?
OS: Windows 11 64bit
installed Windows Desktop Runtime 5.0.15

After running Im gettin this error:
<img width="415" alt="error" src="https://user-images.githubusercontent.com/11217085/168213052-3a061c6e-1dd7-468e-b700-6c4e66baa567.png">

**Comment by BartoszCichecki** [comment]
Do you have .NET 4 installed? I think I might have wrongly assumed that all machines have it. I would suggest installing .NET 4 if you don't have it, but I will try to get around this so there is nor dependency on .NET 4 in the future.

**Comment by jookk** [comment]
I enabled net 3.5 and older and app is "probably" starting.
But I got another error:
![after run](https://user-images.githubusercontent.com/11217085/168414939-41edc353-bbcd-4db2-a5fa-ed7a5620abc9.jpg)

**Comment by BartoszCichecki** [comment]
Oh, these two models are not supported and to be honest they probably will not be.
