### ISSUE TITLE
希望优化软件流畅度，有些卡顿不够顺滑

### ISSUE THREAD

**Issue by RinSky123** [BartoszCichecki/LenovoLegionToolkit#972]
### Rules

- [X] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

windows11 22h2

### Device

Legion r70002021

### Is your feature request related to a problem?

操作不够流畅

### How would you like the problem to be solved?

优化流畅度

### What alternatives have you considered?

优化操作流畅度

**Comment by BartoszCichecki** [comment]
I have no idea what are you saying. Issues should be reported in English.
