### ISSUE TITLE
I hope to optimize the software's fluency and make the operation smoother.

### ISSUE THREAD

**Issue by RinSky123** [BartoszCichecki/LenovoLegionToolkit#973]
### Rules

- [X] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [ ] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

windows11 22h2

### Device

Legion r70002021

### Is your feature request related to a problem?

The operation is not smooth enough and lacks fluency.

### How would you like the problem to be solved?

I hope to optimize the software's fluency and make the operation smoother.

### What alternatives have you considered?

I hope to optimize the software's fluency and make the operation smoother.

**Comment by BartoszCichecki** [comment]
I don't know what kind of fluency you are talking about. You provided almost no information. Closing this one too, because of rule number 3: " I understand that, if insufficient information was provided, my issue will be closed without an answer."
