### ISSUE TITLE
[COMPATIBILITY] Thinkbook 16p G4 IRH

### ISSUE THREAD

**Issue by hzdz9596** [BartoszCichecki/LenovoLegionToolkit#974]
### Rules

- [X] I made myself familiar with the README.
- [X] I understand that requests should not be placed for devices that are not part of Legion, Ideapad Gaming and LOQ line ups.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Thinkbook 16p G4 IRH

### BIOS version

LRCN37WW

### Which features of the application did you test?

These works: battery mode, always on USB, flip to start settings, gpu working mode (all modes), microphone & fn lock, resolution, refresh rate, dpi, turn off displays

### Which features of the application do not work as expected?

Power mode, keyboard light control

### Logs

[log_2023_09_18_10_54_21.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12647059/log_2023_09_18_10_54_21.txt)

### Additional information

I **do understand** that this is not a legion device, but this device's spec is really similar to that of Legion Y9000X 2023, which is supported by this project. This device even support Legion's proprietary C135W and C140W GaN adapter!

Most errors in the log look like unsupported hardware features (e.g. logo backlight which this device doesn't have) which is easily to solve. And since I have the hardware, I can help with testing (or even make the PR myself) if it's okay.

**Comment by BartoszCichecki** [comment]
"If your laptop is not part of Legion, IdeaPad Gaming or LOQ series, this software is not for you. Please do NOT open compatibility requests for other devices."
