### ISSUE TITLE
Advanced thermal optimization

### ISSUE THREAD

**Issue by RunningDead89** [BartoszCichecki/LenovoLegionToolkit#975]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0 BETA 3

### OS

Windows 11 22H2 Dev Build 23545.1000

### Device

Legion 5 Pro 16ACH6H

### Is your feature request related to a problem?

I would find it very useful if I could change the advanced thermal optimization in LLT instead of having to manually change the setting in BIOS every time after a BIOS update. Is it possible to add this in LLT for laptops that support it?

### How would you like the problem to be solved?

An option to change advanced thermal optimization in LLT

### What alternatives have you considered?

---

**Comment by BartoszCichecki** [comment]
From what I know that setting isn't exposed as UEFI variable. 

If anything changes I will reopen the issue.
