### ISSUE TITLE
[REQ] Add 'GPU Working Mode' Action/Step

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#979]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

W 11

### Device

Legion 5 Pro 16ARH7H

### Is your feature request related to a problem?

Ability to change GPU Working Mode automatically on a game start/close or on a quick action

### How would you like the problem to be solved?

.

### What alternatives have you considered?

.

**Comment by BartoszCichecki** [comment]
"I made myself familiar with the README."

I don't think so.

**Comment by Oblivious02** [comment]
> "I made myself familiar with the README."
> 
> I don't think so.

I don't really know what I missed but okay
