### ISSUE TITLE
CPU Boost Mode not available

### ISSUE THREAD

**Issue by alantoblooddy** [BartoszCichecki/LenovoLegionToolkit#98]
Hi, 

I've got an issue with CPU Boost Mode setting. Every time I click on it or just draw my mouse to the setting, I've got the following error, and the app crashes.

The app is run under the administrator.

My laptop: Lenovo Legion 5 15ARH05H - Type 82B1

![Снимок экрана 2022-05-14 093813](https://user-images.githubusercontent.com/22687186/168414142-60aff39c-162a-4727-8b51-9e80ff73b8a3.png)

**Comment by hacker-biba** [comment]
I've encountered the same issue. My laptop is Lenovo Legion 5 15ACH6H 82JU

**Comment by BartoszCichecki** [comment]
Hey, which version of Windows are you using?

**Comment by mind12** [comment]
Hello,

Afaik 2020 Legion models doesnt have the Legion power plans so if your app is looking for those guids that could cause the crashes.

**Comment by BartoszCichecki** [comment]
Hey, no i am not looking for specific GUIDs here. I am listing all power plans here regardless of GUIDS. It still shouldn't crash tho, so I'll push a hot fix asap.

**Comment by alantoblooddy** [comment]
> Hey, which version of Windows are you using?

Windows 10 21H2. I’ve got two power plans:

1. Balance (from the factory).
2. Maximum performance (custom made).

Sorry for off top. Is there a way to make a donation ?

**Comment by hacker-biba** [comment]
> which version of Windows are you using?

I have Windows 10 21H2 19044.1200 installed
I'm using Legion power plans

**Comment by BartoszCichecki** [comment]
So, I made a fix and update will be out soon. However, if you got this error there is probably one more issue that I cannot track down now. Once 1.7.1 is out and this option still doesn't work, please reopen this ticket and attach [trace logs](https://github.com/BartoszCichecki/LenovoLegionToolkit#bugs).

**Comment by BartoszCichecki** [comment]
@alantoblooddy regarding donations, not at the moment, but thanks! I am in process of enabling GitHub Sponsor profile so maybe one day you will be able to get me a coffee or beer ;)
