### ISSUE TITLE
When adding a tile to the dashboard, if the "tile selection" popup doesn't have enough room, it gets cut off

### ISSUE THREAD

**Issue by zwresn453** [BartoszCichecki/LenovoLegionToolkit#988]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Legion 7-16ACHg6

### BIOS version

GKCN60WW

### What's wrong?

Difficult to describe. Please see "how to reproduce".

### How to reproduce the bug?

1) Go to Dashboard
2) Press on Customize... button
3) In any of the categories, press the Add... button. (continue reading for the problem)

If the Customize Dashboard window is close enough to the top of the screen, the popup will be cut off at the top (if it opens above the Add... button). If the window is very close the top of the screen, the popup will appear _below_ the Add... button instead of above, but now it goes off the bottom of the screen. 

### What is the behavior that you expected?

This is can cause confusion because if a user is trying to add a tile that is off the edge of the screen, they will probably scroll the popup but nothing will happen, telling them that the entire list is already shown when it is actually not.

I would expect that the entire list shows reliably. 

I would suggest making the popup able to be scrolled. If this is not possible, maybe the popup could appear to the side of the Add... button (instead of above or below), or be a separate window instead of a popup.

### Logs

[log_2023_10_03_02_33_10.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12787933/log_2023_10_03_02_33_10.txt)

**Comment by BartoszCichecki** [comment]
Can you paste some screenshots of the issue?

**Comment by zwresn453** [comment]
I have attached screenshots below.
Picture of the menu cut off because it is too close to the top of the screen:
![Picture of the menu cut off because it is too close to the top of the screen](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/121317613/19e781df-c777-4466-83be-2701b0b2c79d)


Menu showing properly:
![Menu showing properly](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/121317613/8b4b2e87-3ad2-4bf6-8ecd-c46ce14dadc1)
