### ISSUE TITLE
When the system runs continuously for a long period of time, LTT cannot detect the process properly.

### ISSUE THREAD

**Issue by xxhhlk** [BartoszCichecki/LenovoLegionToolkit#989]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 10 Pro 22H2 19045.3516

### Device

Legion Y9000P IAH7H

### BIOS version

J2CN54WW

### What's wrong?

I found that after the system has been running continuously for a long time, usually 24~48 hours, the "when app starts" in actions doesn't take effect. So it may not be able to detect the process? I guess.

### How to reproduce the bug?

1、Turn on the computer, the function of "when the app starts" can run normally.
2. Use the computer normally for 1-2 days.
3、Run the program that needs to be detected in the "When App Starts" setting, and the corresponding operation does not happen.

### What is the behavior that you expected?

I expect "when the app starts" function to work even if the system is running for a long time.

### Logs

[LTT_log_20231004.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12801914/LTT_log_20231004.zip)

### Additional information

After restarting the system, it works fine. Sometimes restarting Lenovo Legion Toolkit a few more times brings it back to normal, sometimes not. But after running it again for a while, it still does not work properly again.

I have configured several "when app starts" actions that detect different programs and do different steps. They are used to switch power modes, or to switch custom mode presets, but none of them work when the problem occurs. Sometimes after restarting the Lenovo Legion Toolkit software, it responds successfully once more, but not after that.

Attachments include logs that work and those that don't. Thank you!

**Comment by zwresn453** [comment]
Although it may not be convenient, I would recommend getting into the habit of restarting your system every 24 hours in order to keep the system stable. 

I am guessing that this problem will take a lot of work for the developer to fix, and if restarting your system on a normal cadence fixes it (in addition to generally increasing system stability), I think that this might be the best solution. Unless other people are having this same problem?

**Comment by BartoszCichecki** [comment]
@xxhhlk  I can see you have several "when app starts" actions defined, but there aren't any obvious errors. What was the process name that LLT doesn't respond to?

**Comment by xxhhlk** [comment]
> @xxhhlk I can see you have several "when app starts" actions defined, but there aren't any obvious errors. What was the process name that LLT doesn't respond to?

Hi, in the log, I tried a couple of processes whose names start with "ChangeMode". (ChangeModeLow.exe, ChangeModeHigh.exe, ChangeMode_Custom.exe, ChangeMode_Silent.exe)
There are rules for a few other processes as well, but I haven't tried them yet when the problem occurs. I can test it next time if needed.

**Comment by BartoszCichecki** [comment]
I don't understand so what am I supposed to look for in the log? Which process was not recognized properly?

**Comment by xxhhlk** [comment]
Hi, I'm sorry, I can't remember exactly which process was tried when logging was enabled, but it must have belonged to one or more of these processes: 
- ChangeModeLow.exe
- ChangeModeHigh.exe
- ChangeMode_Custom.exe
- ChangeMode_Silent.exe

**Comment by BartoszCichecki** [comment]
Ok, I can't seem to track anything wrong in from the logs you sent. In all the logs, LLT is correctly listening to processes that are started, so unless you can come up with a more reproducible scenario for this, I can't do much. For now I am closing the issue, but if you get more precise information on how to reproduce this, feel free to re-open this issue.
