### ISSUE TITLE
I hope I can customize the maintenance mode battery threshold

### ISSUE THREAD

**Issue by tumibloom** [BartoszCichecki/LenovoLegionToolkit#991]
### Rules

- [X] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

windows11 22H

### Device

R9000P2021H

### Is your feature request related to a problem?

I hope I can customize the maintenance mode battery threshold like 70%

### How would you like the problem to be solved?

I hope I can customize the maintenance mode battery threshold like 70%

### What alternatives have you considered?

no

**Comment by BartoszCichecki** [comment]
"I checked closed issues for similar ones and did not find a similar feature request mentioned before."

Check closed issues next time.
