### ISSUE TITLE
LLT could not show the CPU temperature

### ISSUE THREAD

**Issue by MuSir0216** [BartoszCichecki/LenovoLegionToolkit#994]
### Rules

- [X] I made myself familiar with the README.
- [x] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [x] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Legion Y9000P 2021H (China)

### BIOS version

H1CN53WW

### What's wrong?

Sir, the LLT could not show the CPU temperature(just like "-") while other sensor statistics is correct.

### How to reproduce the bug?

Just run the LLT, then the sensors table "CPU-temperature" is none(like "_").

### What is the behavior that you expected?

I just want to know my CPU temperature, i can guarantee that my sensors are working well. I tried some other softwares to get the CPU temperatures and they all worked out. So i mean that the LLT may get wrong? could you please help to debug?

### Logs

[log_2023_10_09_10_33_35.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/12844993/log_2023_10_09_10_33_35.txt)

### Additional information

I join in the Chinese QQ channel and wanted to find someone to help me, but they played jokes on me and made me terrible.
So i come here to find help. 
My English is not good,please do not get mad.
Thanks!

**Comment by MuSir0216** [comment]
the Screenshot:
<img width="778" alt="image" src="https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/147392536/d2f1df5e-a9dd-4c47-b4a3-8a700f838e86">

**Comment by BartoszCichecki** [comment]
I don't know the reason why it's not showing. Your laptop doesn't report CPU temperature. It could be a bug in BIOS/EC or a missing driver - I don't know, but I don't see any issues related to LLT in the log you sent.

The reason why other programs show CPU temperature is that they read it directly from CPU while LLT reads the temperature using Lenovo provided functions.

**Comment by MuSir0216** [comment]
> I don't know the reason why it's not showing. Your laptop doesn't report CPU temperature. It could be a bug in BIOS/EC or a missing driver - I don't know, but I don't see any issues related to LLT in the log you sent.
> 
> The reason why other programs show CPU temperature is that they read it directly from CPU while LLT reads the temperature using Lenovo provided functions.

OK.Thanks.

**Comment by MuSir0216** [comment]
> I don't know the reason why it's not showing. Your laptop doesn't report CPU temperature. It could be a bug in BIOS/EC or a missing driver - I don't know, but I don't see any issues related to LLT in the log you sent.
> 
> The reason why other programs show CPU temperature is that they read it directly from CPU while LLT reads the temperature using Lenovo provided functions.

Could you please show me a way to solve it？
