### ISSUE TITLE
Add actions trigger on custom power mode preset

### ISSUE THREAD

**Issue by rickygjun** [BartoszCichecki/LenovoLegionToolkit#998]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

Is it possible to add custom power mode presets as the action trigger? currently only custom mode can detected as the trigger, can we just go further to make the preset as the trigger.

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/125786452/2112b778-f2fd-43de-ad2d-341d9cffeb86)

This will enable user to assign actions based on preset change.

### How would you like the problem to be solved?

Add new feature

### What alternatives have you considered?

None

**Comment by BartoszCichecki** [comment]
What is the use case for this?

**Comment by rickygjun** [comment]
My use case is when game preset in custom power mode detected, example was on quiet preset, now game preset is detected, pop up a notification in bottom right coner saying "game mode is on"

**Comment by rickygjun** [comment]
Let me explain further, sometimes I do manual power mode change, but all my power modes are presets in custom power mode. So I would like to trigger some action when I manually switch from my "quiet" preset to "full fan" preset, like run some scripts
