### ISSUE TITLE
Power mode change (including preset change) notification support

### ISSUE THREAD

**Issue by rickygjun** [BartoszCichecki/LenovoLegionToolkit#999]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar feature request mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.16.2

### OS

Windows 11 22H2

### Device

Legion 7 16IAX7

### Is your feature request related to a problem?

Is it possible to add notification support in actions?

My use case: My use case is when power mode changed as a trigger, pop up a notification in bottom right corner saying "game mode is on"

### How would you like the problem to be solved?

The notification ideally can be the same style like the bottom right notification in settings (caps lock and num lock etc.)

### What alternatives have you considered?

None

### Additional information

The notification ideally can be the same style like the buttom right notification in settings (caps lock and num lock etc.)

**Comment by BartoszCichecki** [comment]
Added a new step to Actions called "Show notification" where you can enter custom text to display inside a notification.
